access_bcTurbVisc_forElement – Musubi
access_bcTurbVisc_forElement Subroutine
30 statements
Source File
private recursive subroutine access_bcTurbVisc_forElement(fun, varSys, elempos, time, tree, nElems, nDofs, res)
This routine returns turbulent viscosity computed in turbulent_wall bc according to RANS formulation and stored in mus_turb_wallFunc_data_type routine.
The interface has to comply to the abstract interface tem_varSys_proc_element.
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
integer, intent(in) :: elempos(:)
Position of the TreeID of the element to get the variable for in the global treeID list.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nElems
Number of values to obtain for this variable (vectorized access).
integer, intent(in) :: nDofs
Number of degrees of freedom within an element.
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Linearized array dimension: (n requested entries) x (nComponents of this variable) x (nDegrees of freedom) Access: (iElem-1)fun%nComponentsnDofs + (iDof-1)*fun%nComponents + iComp
Calls
Call graph
access_bcturbvisc_forelement calls bc, bclevelpointer, field, minbcid, posinbndid, tem_LevelOf, tvisc