add_Momentum_Increment_to_Auxfield – Musubi
add_Momentum_Increment_to_Auxfield Subroutine
17 statements
Source File
public subroutine add_Momentum_Increment_to_Auxfield(posInTotal, scheme, auxField, iLevel, varSys, derVarPos, momentumIncrement)
Add a momentum increment to element with PosInTotal in total list
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: posInTotal
Position of element to modify in total list
type(mus_scheme_type), intent(inout) :: scheme
Scheme
real(kind=rk), intent(inout) :: auxField(:)
output auxField array
integer, intent(in) :: iLevel
current level
type(tem_varSys_type), intent(in) :: varSys
variable system definition
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
position of derived quantities in varsys
real(kind=rk), intent(in) :: momentumIncrement(3)
Momentum increment to apply, in lattice units
Calls
Called by
Call graph
add_momentum_increment_to_auxfield calls auxfield_varpos
incrementauxfield_dps calls add_momentum_increment_to_auxfield
recalculate_auxfield_dps calls add_momentum_increment_to_auxfield
demsubcycles_dps calls incrementauxfield_dps, recalculate_auxfield_dps
mus_particles_move_dps calls demsubcycles_dps