addCollisionForceToBuffer – Musubi
addCollisionForceToBuffer Subroutine
15 statements
Source File
public subroutine addCollisionForceToBuffer(particleGroup, recvRankIndex, Fcoll, particleID)
addCollisionForceToBuffer adds DEM collision force Fcoll to the force buffer sent to particle with id particleID on rank recvRankIndex.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
particleGroup of this process
integer :: recvRankIndex
Index of receiving rank in particleGroup%send%buf_force(recvRankIndex)
real(kind=rk), intent(in) :: Fcoll(3)
Collision force to add to buffer
integer, intent(in) :: particleID
ID of particle to which collision force should be applied
Calls
Called by
Call graph
addcollisionforcetobuffer calls tem_abort
dem_computeremotecollisionforces calls addcollisionforcetobuffer
dem_computeremotecollisionforces_dps calls addcollisionforcetobuffer
demsubcycles_mem calls dem_computeremotecollisionforces
updateparticleforces calls dem_computeremotecollisionforces_dps
demsubcycles_dps calls updateparticleforces
demsubcycles_dps_onewaycoupled calls updateparticleforces
mus_particles_move calls demsubcycles_mem
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled