applySrc_forceMSLiquid_1stOrd_WTDF – Musubi
applySrc_forceMSLiquid_1stOrd_WTDF Subroutine
64 statements
Source File
public subroutine applySrc_forceMSLiquid_1stOrd_WTDF(fun, inState, outState, neigh, auxField, nPdfSize, iLevel, varSys, time, phyConvFac, derVarPos)
Update state with source variable "force" with thermodynamic factor Simuilar to derive routine but it updates the state whereas derive is used for tracking Refer to Appendix in PhD Thesis of K. Masilamani "Coupled Simulation Framework to Simulate Electrodialysis Process for Seawater Desalination"
This subroutine's interface must match the abstract interface definition proc_apply_source in derived/mus_source_type_module.f90 in order to be callable via applySrc function pointer.
Arguments
Type Intent Optional Attributes Name
class(mus_source_op_type), intent(in) :: fun
Description of method to apply source terms
real(kind=rk), intent(in) :: inState(:)
input pdf vector
real(kind=rk), intent(inout) :: outState(:)
output pdf vector
integer, intent(in) :: neigh(:)
connectivity Array corresponding to state vector
real(kind=rk), intent(in) :: auxField(:)
auxField array
integer, intent(in) :: nPdfSize
number of elements in state Array
integer, intent(in) :: iLevel
current level
type(tem_varSys_type), intent(in) :: varSys
variable system
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(mus_convertFac_type), intent(in) :: phyConvFac
Physics conversion factor for current level
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
position of derived quantities in varsys
Calls
Call graph
applysrc_forcemsliquid_1stord_wtdf calls auxfield_varpos, cxdirrk, get_valofindex, input_varpos, mus_calc_thermfactor, invert_matrix, val
mus_calc_thermfactor calls mus_calc_thermfactor_single