applySrc_force_GNS – Musubi
applySrc_force_GNS Subroutine
49 statements
Source File
public subroutine applySrc_force_GNS(fun, inState, outState, neigh, auxField, nPdfSize, iLevel, varSys, time, phyConvFac, derVarPos)
Update state with source variable "force" for Generalized Navier-Stokes equations. The implementation is taken from "Lattice Boltzmann model for incompressible flows through porous media" by Z. Guo and T.S. Zhao (2002) Physical Review E.
This subroutine's interface must match the abstract interface definition proc_apply_source in derived/mus_source_var_module.f90 in order to be callable via applySrc function pointer.
Arguments
Type Intent Optional Attributes Name
class(mus_source_op_type), intent(in) :: fun
Description of method to apply source terms
real(kind=rk), intent(in) :: inState(:)
input pdf vector
real(kind=rk), intent(inout) :: outState(:)
output pdf vector
integer, intent(in) :: neigh(:)
connectivity Array corresponding to state vector
real(kind=rk), intent(in) :: auxField(:)
auxField array
integer, intent(in) :: nPdfSize
number of elements in state Array
integer, intent(in) :: iLevel
current level
type(tem_varSys_type), intent(in) :: varSys
variable system
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(mus_convertFac_type), intent(in) :: phyConvFac
Physics conversion factor for current level
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
position of derived quantities in varsys
Calls
Call graph
applysrc_force_gns calls auxfield_varpos, cxdirrk, get_valofindex, val