applyVelocityBounceback – Musubi
applyVelocityBounceback Subroutine
57 statements
Source File
public subroutine applyVelocityBounceback(this, scheme, stencil, params)
ApplyVelocityBounceback adds the momentum exchange term to the distribution function at the particle neighboring fluid nodes this term accounts for the moving boundary of the particle.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_MEM_type), intent(inout) :: this
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to level descriptor
type(tem_stencilHeader_type), intent(in) :: stencil
fluid stencil
type(mus_param_type), intent(in) :: params
Parameters for access to dt, dx, conversion factors between units
Calls
Called by
Call graph
applyvelocitybounceback calls baryoftotal, cxdirinv, nghelems, calcperiodicrsurface, cross_product, property, state_varpos, val
calcperiodicrsurface calls calcperiodicdistancetosurface
mus_particles_transfermomentumtofluid_mem calls applyvelocitybounceback