assignBCList – Musubi
assignBCList Subroutine
90 statements
Source File
private subroutine assignBCList(tree, bc_prop, stencil, globBC)
This routine assigns the BC lists Run over all the elements with the property boundary and check each direction. Assign all common boundaries to the level-wise representation 3rd step in build_BCLists
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
fluid tree from mesh
type(tem_BC_prop_type), intent(in) :: bc_prop
boundary information from mesh
type(tem_stencilHeader_type), intent(in) :: stencil
stencil
type(glob_boundary_type), intent(inout) :: globBC(:)
boundaries for the elements with bnd property set
Calls
Called by
Call graph
assignbclist calls append, elemid, tem_LevelOf, val
build_bclists calls assignbclist
mus_construct calls build_bclists
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize