bgk_ProjectedRecursiveRegularized_d3q19 – Musubi
bgk_ProjectedRecursiveRegularized_d3q19 Subroutine
58 statements
Source File
public subroutine bgk_ProjectedRecursiveRegularized_d3q19(fieldProp, inState, outState, auxField, neigh, nElems, nSolve, level, layout, params, varSys, derVarPos)
Projected Recursive Regularized relaxation routine for the D3Q19 This subroutine interface must match the abstract interface definition kernel in scheme/mus_scheme_type_module.f90 in order to be callable via compute function pointer. works for both d3q19 and d3q27
TODO:tr_SR = div2_3 * (gradU(1, 1, 1) + gradU(2, 2, 1) + gradU(3, 3, 1))
Arguments
Type Intent Optional Attributes Name
type(mus_field_prop_type), intent(in) :: fieldProp(:)
Array of field properties (fluid or species)
real(kind=rk), intent(in) :: inState(nElems*varSys%nScalars)
input pdf vector
real(kind=rk), intent(out) :: outState(nElems*varSys%nScalars)
output pdf vector
real(kind=rk), intent(inout) :: auxField(nElems*varSys%nAuxScalars)
Auxiliary field computed from pre-collision state Is updated with correct velocity field for multicomponent models
integer, intent(in) :: neigh(nElems*layout%fStencil%QQ)
connectivity vector
integer, intent(in) :: nElems
number of elements in state Array
integer, intent(in) :: nSolve
number of elements solved in kernel
integer, intent(in) :: level
current level
type(mus_scheme_layout_type), intent(in) :: layout
current layout
type(mus_param_type), intent(in) :: params
global parameters
type(tem_varSys_type), intent(in) :: varSys
variable system definition
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
position of derived quantities in varsys for all fields
Calls
Call graph
bgk_projectedrecursiveregularized_d3q19 calls auxfield_varpos, f_f_eq_regularized_4th_ord_d3q19, val
f_f_eq_regularized_4th_ord_d3q19 calls f_f_eq_regularized_2nd_ord_d3q19