bgk_HybridRecursiveRegularizedCorr_d2q9 – Musubi
bgk_HybridRecursiveRegularizedCorr_d2q9 Subroutine
71 statements
Source File
public subroutine bgk_HybridRecursiveRegularizedCorr_d2q9(fieldProp, inState, outState, auxField, neigh, nElems, nSolve, level, layout, params, varSys, derVarPos)
Hybrid recursive regularization relaxation routine for the BGK model. based on: Feng et al., JCP 2019, "Hybrid recursive regularized thermal lattice Boltzmann model for high subsonic compressible flows"
This subroutine interface must match the abstract interface definition kernel in scheme/mus_scheme_type_module.f90 in order to be callable via compute function pointer.
Generic fetching step: Streaming for pull Local copy for push
Arguments
Type Intent Optional Attributes Name
type(mus_field_prop_type), intent(in) :: fieldProp(:)
Array of field properties (fluid or species)
real(kind=rk), intent(in) :: inState(nElems*varSys%nScalars)
Input pdf vector
real(kind=rk), intent(out) :: outState(nElems*varSys%nScalars)
Output pdf vector
real(kind=rk), intent(inout) :: auxField(nElems*varSys%nAuxScalars)
Auxiliary field computed from pre-collision state is updated with correct velocity field for multicomponent models
integer, intent(in) :: neigh(nElems*layout%fStencil%QQ)
Connectivity vector
integer, intent(in) :: nElems
Number of elements in state Array
integer, intent(in) :: nSolve
Number of elements solved in kernel
integer, intent(in) :: level
Current level
type(mus_scheme_layout_type), intent(in) :: layout
Vurrent layout
type(mus_param_type), intent(in) :: params
Global parameters
type(tem_varSys_type), intent(in) :: varSys
Variable system definition
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
Position of derived quantities in varsys for all fields
Calls
Call graph
bgk_hybridrecursiveregularizedcorr_d2q9 calls auxfield_varpos, f_f_eq_regularized_4th_ord_d2q9, hrr_correction_d2q9, secondmom_2d, val
f_f_eq_regularized_4th_ord_d2q9 calls f_f_eq_regularized_2nd_ord_d2q9