bgk_advRel_MSLiquid_generic_WTDF – Musubi
bgk_advRel_MSLiquid_generic_WTDF Subroutine
138 statements
Source File
public subroutine bgk_advRel_MSLiquid_generic_WTDF(fieldProp, inState, outState, auxField, neigh, nElems, nSolve, level, layout, params, varSys, derVarPos)
Unoptimized Advection relaxation routine for the multispecies BGK model with thermodynamic factors in Maxwell-Stefan formulation
This routine contains the implementation based on the paper "A Lattice Boltzmann Scheme for liquid mixtures - Part II: Discretization and Numerics, Jens Zudrop, Sabine Roller, Pietro Asinari. "\n
This subroutine interface must match the abstract interface definition kernel in scheme/mus_scheme_type_module.f90 in order to be callable via compute function pointer.
Arguments
Type Intent Optional Attributes Name
type(mus_field_prop_type), intent(in) :: fieldProp(:)
Array of field properties (fluid or species)
real(kind=rk), intent(in) :: inState(nElems*varSys%nScalars)
input pdf vector
real(kind=rk), intent(out) :: outState(nElems*varSys%nScalars)
output pdf vector
real(kind=rk), intent(inout) :: auxField(nElems*varSys%nAuxScalars)
Auxiliary field computed from pre-collision state Is updated with correct velocity field for multicomponent models
integer, intent(in) :: neigh(nElems*layout%fStencil%QQ)
connectivity vector
integer, intent(in) :: nElems
number of elements in state Array
integer, intent(in) :: nSolve
number of elements solved in kernel
integer, intent(in) :: level
current level
type(mus_scheme_layout_type), intent(in) :: layout
current layout
type(mus_param_type), intent(in) :: params
global parameters
type(tem_varSys_type), intent(in) :: varSys
variable system definition
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
position of derived quantities in varsys for all fields
Calls
Call graph
bgk_advrel_msliquid_generic_wtdf calls auxfield_varpos, cxdir, mus_calc_ms_diffmatrix, mus_calc_thermfactor, invert_matrix, val
mus_calc_ms_diffmatrix calls mus_calc_ms_diffmatrix_single
mus_calc_thermfactor calls mus_calc_thermfactor_single