build_BClists – Musubi
build_BClists Subroutine
39 statements
Source File
private subroutine build_BClists(globBC, tree, bc_prop, minLevel, maxLevel, layout, field, comm)
Assemble the level-wise list of elements which adhere to the boundary conditions.
The boundaries will then be treated for each level one by one, running over the list of elements. The bitmasks are set for the directions pointing into the domain. In the LBM, the incoming densities have to be updated. As boundaries are being set before the kernel, the state arrays have to be stored to the FETCH position
Arguments
Type Intent Optional Attributes Name
type(glob_boundary_type), intent(out), allocatable :: globBC(:)
boundaries for the elements with bnd property set
type(treelmesh_type), intent(in) :: tree
fluid tree from mesh
type(tem_BC_prop_type), intent(in) :: bc_prop
boundary information from mesh
integer, intent(in) :: minLevel
contains pdf global information
integer, intent(in) :: maxLevel
contains pdf global information
type(mus_scheme_layout_type), intent(in) :: layout
scheme layout
type(mus_field_type), intent(in) :: field(:)
field type
integer, intent(in) :: comm
mpi communication enviroment with mpi communicator
Calls
Called by
Call graph
build_bclists calls allocatebclist, assignbclist, countnbnds, mus_check_allwall, normalizebc
allocatebclist calls mus_init_bc_elems, val
assignbclist calls append, elemid, tem_LevelOf, val
countnbnds calls elemid, mpi_allreduce, tem_LevelOf, tem_horizontalSpacer
normalizebc calls append, cxdir, mpi_allreduce, tem_determine_discreteVector, val
mus_init_bc_elems calls destroy, init
mus_construct calls build_bclists
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve