build_bcLevelPointer – Musubi
build_bcLevelPointer Subroutine
18 statements
Source File
private subroutine build_bcLevelPointer(bcLevelPointer, posInBndID, minBCID, levelPointer, bc_prop, tree, globBC)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), allocatable :: bcLevelPointer(:)
levelPointer from posInBndID to globBC%elemLVl(:)%elem
integer, intent(in) :: posInBndID(:)
tree element position in boundaryID
integer, intent(in) :: minBCID(:)
minBCID for each element
integer, intent(in) :: levelPointer(:)
tree element position in levelDesc total list
type(tem_BC_prop_type), intent(in) :: bc_prop
boundary information from mesh
type(treelmesh_type), intent(in) :: tree
fluid tree from mesh
type(glob_boundary_type), intent(in) :: globBC(bc_prop%nBCtypes)
global boundary information
Calls
Called by
Call graph
build_bclevelpointer calls elemid, positionofval, tem_LevelOf
mus_construct calls build_bclevelpointer
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve