calcVelocityAndPressureGradient_onewaycoupled_old – Musubi
calcVelocityAndPressureGradient_onewaycoupled_old Subroutine
58 statements
Source File
public subroutine calcVelocityAndPressureGradient_onewaycoupled_old(coord, scheme, grad_p, curl_u, err)
calcVelocityAndPressureGradient calculates the gradient of pressure and curl of the velocity field (in lattice units) at coordinate coord Coord must be a local element on this process!
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: coord(4)
Integer coordinate to calculate grad(p) and curl(u) at
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to total list
real(kind=rk), intent(out) :: grad_p(3)
Output pressure gradient at coord
real(kind=rk), intent(out) :: curl_u(3)
Output velocity curl at coord
logical, intent(out) :: err
Error code: set to TRUE if we could not find ldPos of coord we are trying to grab value at (for example because it is outside domain and not a halo.
Calls
Called by
Call graph
calcvelocityandpressuregradient_onewaycoupled_old calls auxfield_varpos, cxdir, cxdirinv, grabvalueatcoord, cross_product, getindexofcoordintotal, getneighborcoord, tem_abort
grabvalueatcoord calls grabvalueatcoord_onewaycoupled, grabvalueatcoord_twowaycoupled
getindexofcoordintotal calls tem_IdOfCoord, tem_PosOfId
grabvalueatcoord_onewaycoupled calls tem_IdOfCoord, tem_PosOfId
grabvalueatcoord_twowaycoupled calls tem_IdOfCoord, tem_PosOfId
mus_particles_dps_interpolatefluidproperties_onewaycoupled calls calcvelocityandpressuregradient_onewaycoupled_old
mus_particles_applyhydrodynamicforces_dps_onewaycoupled calls mus_particles_dps_interpolatefluidproperties_onewaycoupled