calcTurbWallBndForceAndMoment – Musubi
calcTurbWallBndForceAndMoment Subroutine
38 statements
Source File
private subroutine calcTurbWallBndForceAndMoment(bndForce, bndMoment, momRefPnt, globBC, baryOfTotal, bcBuffer, state, nSize, neigh, layout, physics, nScalars, varPos, iLevel, iField)
This routine computes bndForce on boundary elements using momentum exchange method.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(out) :: bndForce(:,:)
Boundary force
real(kind=rk), intent(out) :: bndMoment(:,:)
Boundary moment
real(kind=rk), intent(in) :: momRefPnt(:)
Reference point for moment calculation
type(glob_boundary_type), intent(in) :: globBC
scheme global boundary type
real(kind=rk), intent(in) :: baryOfTotal(:,:)
barycenter of elements in total list Size: nElemsTotal, 3
real(kind=rk), intent(in) :: bcBuffer(:)
state values of boundary elements of all fields of iLevel
real(kind=rk), intent(inout) :: state(:)
Current state vector of iLevel
integer, intent(in) :: nSize
size of state array (in terms of elements)
integer, intent(in) :: neigh(:)
connectivity array corresponding to state vector
type(mus_scheme_layout_type), intent(in) :: layout
stencil layout information
type(mus_physics_type), intent(in) :: physics
contains physics conversion factors
integer, intent(in) :: nScalars
number of Scalars in the scheme var system
integer, intent(in) :: varPos(:)
pointer to field variable in the state vector
integer, intent(in) :: iLevel
the level On which this boundary was invoked
integer, intent(in) :: iField
current field
Calls
Called by
Call graph
calcturbwallbndforceandmoment calls cross_product3D, cxdirinv, cxdirrk, val
turbulent_wall calls calcturbwallbndforceandmoment
turbulent_wall_eq calls calcturbwallbndforceandmoment
turbulent_wall_eq_curved calls calcturbwallbndforceandmoment
turbulent_wall_libb calls calcturbwallbndforceandmoment
turbulent_wall_noneq_expol calls calcturbwallbndforceandmoment
turbulent_wall_noneq_expol_curved calls calcturbwallbndforceandmoment