calcVelocityAndPressureGradient – Musubi
calcVelocityAndPressureGradient Subroutine
72 statements
Source File
public subroutine calcVelocityAndPressureGradient(coord, scheme, grad_p, curl_u, err, posOfCoord)
calcVelocityAndPressureGradient calculates the gradient of pressure and curl of the velocity field (in lattice units) at coordinate coord Coord must be a local element on this process!
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: coord(4)
Integer coordinate to calculate grad(p) and curl(u) at
type(mus_scheme_type), intent(in) :: scheme
Scheme for access to total list
real(kind=rk), intent(out) :: grad_p(3)
Output pressure gradient at coord
real(kind=rk), intent(out) :: curl_u(3)
Output velocity curl at coord
logical, intent(out) :: err
Error code: set to TRUE if we could not find ldPos of coord we are trying to grab value at (for example because it is outside domain and not a halo.
integer, intent(in), optional :: posOfCoord
of this routine if this is known.
Calls
Called by
Call graph
calcvelocityandpressuregradient calls auxfield_varpos, cxdir, cxdirinv, nghelems, cross_product, getindexofcoordintotal
getindexofcoordintotal calls tem_IdOfCoord, tem_PosOfId
test_calcvelocityandpressuregradient_dps calls calcvelocityandpressuregradient