calc_surface_vel – Musubi
calc_surface_vel Function
9 statements
Source File
public function calc_surface_vel(om, particle_radius, n) result(usurf)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: om(3)
real(kind=rk), intent(in) :: particle_radius
real(kind=rk), intent(in) :: n(3)
Return Value real(kind=rk), (3)
Calls
Called by
Call graph
calc_surface_vel calls cross_product
checkandcollidedem_dps calls calc_surface_vel
checkandcollidedem_mem calls calc_surface_vel
checkandcollidedem calls checkandcollidedem_dps, checkandcollidedem_mem
dem_computelocalcollisionforces calls checkandcollidedem
dem_computelocalcollisionforces_dps calls checkandcollidedem
dem_computeremotecollisionforces calls checkandcollidedem
dem_computeremotecollisionforces_dps calls checkandcollidedem
demsubcycles_mem calls dem_computelocalcollisionforces, dem_computeremotecollisionforces
updateparticleforces calls dem_computelocalcollisionforces_dps, dem_computeremotecollisionforces_dps