check_flow_status – Musubi
check_flow_status Subroutine
22 statements
Source File
public subroutine check_flow_status(scheme, geometry, general, physics, mus_aborts, restart_triggered)
This routine performs several tasks: geometry increment, time updating, tracking, density checking, restart
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout), target :: scheme
containers for the different schemes
type(mus_geom_type), intent(inout) :: geometry
geometry infomation
type(tem_general_type), intent(inout) :: general
Global parameters
type(mus_physics_type), intent(in) :: physics
physics conversion tyoe
type(mus_abortCriteria_type), intent(in) :: mus_aborts
logical, intent(inout) :: restart_triggered
Indication whether a restart output was triggered
Calls
Call graph
check_flow_status calls mus_calcbndforce, mus_geomincr, mus_dumpdata, perform_checks, tem_convergence_check, tem_opVar_reduction_transient_update, tem_simControl_syncUpdate, val
mus_dumpdata calls mus_writerestart, tem_timeControl_check, tem_time_dump, tem_tracker
perform_checks calls check_density, check_potential, check_velocityfluid, check_velocityms, mus_check_omegakine, tem_abort, tem_timeControl_globalTriggered
check_density calls tem_time_dump, auxfield_varpos, bits, mpi_reduce, tem_isNaN, total
check_potential calls tem_time_dump, bits, mpi_reduce, tem_isNaN
check_velocityfluid calls auxfield_varpos, bits, mpi_reduce, tem_isNaN
check_velocityms calls auxfield_varpos, bits, mpi_reduce, tem_isNaN
mus_check_omegakine calls tem_abort, bits, mpi_reduce
mus_writerestart calls mus_pdf_serialize, tem_restart_closeWrite, tem_restart_openWrite, tem_restart_writeData, tem_startTimer, tem_stopTimer