check_density – Musubi
check_density Subroutine
58 statements
Source File
public subroutine check_density(scheme, minLevel, maxLevel, general, total_density)
Check the total density for a selected scheme and write to unit
The output might be delayed by using arrays which are then dumped to keep disc access more restricted
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
scheme type
integer, intent(in) :: minLevel
global scheme independent information
integer, intent(in) :: maxLevel
global scheme independent information
type(tem_general_type), intent(inout) :: general
real(kind=rk), intent(out), optional :: total_density
Calls
Called by
Call graph
check_density calls auxfield_varpos, bits, mpi_reduce, tem_isNaN, tem_time_dump, total
perform_checks calls check_density
check_flow_status calls perform_checks