checkAndCollideDEM_DPS – Musubi
checkAndCollideDEM_DPS Subroutine
55 statements
Source File
public subroutine checkAndCollideDEM_DPS(particleA, particleB, hasCollided, eps, Tc, mu)
checkAndCollideDEM checks if two particles A and B collide This is the case if the continuous representations overlap If there is a collision, a collision force is applied to each particle
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: particleA
First particle to collide
type(mus_particle_DPS_type), intent(inout) :: particleB
Second particle to collide
logical, intent(out) :: hasCollided
Logical which indicates whether particles have indeed collided
real(kind=rk), intent(in) :: eps
Threshold gap at which to call it a collision
real(kind=rk), intent(in) :: Tc
Collision time, used to compute DEM spring and damper constant
real(kind=rk), intent(in) :: mu
Dynamic viscosity, in physical units
Calls
Called by
Call graph
checkandcollidedem_dps calls calc_surface_vel, computedisplacement, computelubforce_normal, computelubforce_tangential
calc_surface_vel calls cross_product
checkandcollidedem calls checkandcollidedem_dps
dem_computelocalcollisionforces calls checkandcollidedem
dem_computelocalcollisionforces_dps calls checkandcollidedem
dem_computeremotecollisionforces calls checkandcollidedem
dem_computeremotecollisionforces_dps calls checkandcollidedem
demsubcycles_mem calls dem_computelocalcollisionforces, dem_computeremotecollisionforces
updateparticleforces calls dem_computelocalcollisionforces_dps, dem_computeremotecollisionforces_dps
demsubcycles_dps calls updateparticleforces
demsubcycles_dps_onewaycoupled calls updateparticleforces
mus_particles_move calls demsubcycles_mem