check_and_create_new_particles_MEM – Musubi
check_and_create_new_particles_MEM Subroutine
45 statements
Source File
public subroutine check_and_create_new_particles_MEM(particle_creator, iter, particleGroup, scheme, geometry, params, myRank)
Routine that checks if new particles should be created and creates them if so.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_creator_type), intent(inout) :: particle_creator
Particle creator object
integer, intent(in) :: iter
Current LBM iteration
type(mus_particle_group_type), intent(inout) :: particleGroup
particleGroup to add particles to
type(mus_scheme_type), intent(inout) :: scheme
Scheme to initialize particles on the lattice
type(mus_geom_type), intent(in) :: geometry
Geometry to initialize particles on the lattice
type(mus_param_type), intent(in) :: params
Params
integer, intent(in) :: myRank
This process rank
Calls
Called by
Call graph
check_and_create_new_particles_mem calls allocateprocessmasks, create_particles_mem, exchangenewparticles_mem, initparticle_mem, must_create_new_particles, printparticlegroup2_mem, remove_particle_from_da_particle_mem, updatecoordoforigin, tem_CoordOfReal
allocateprocessmasks calls allocateprocessmasks_dps
create_particles_mem calls createnewparticle_mem, getnewparticleid, tem_abort, val
exchangenewparticles_mem calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, append_da_particle_mem, tem_abort
initparticle_mem calls init, make_pdf_tiny, updateexclusionlist, updatefluidneighbors, updatesolidnodes
remove_particle_from_da_particle_mem calls swap_da_particle_mem
updatecoordoforigin calls tem_CoordOfReal
check_particles_mem calls check_and_create_new_particles_mem