checkForParticleOverlap – Musubi
checkForParticleOverlap Subroutine
31 statements
Source File
public subroutine checkForParticleOverlap(this, particleGroup, scheme, overlapsOtherParticle)
handleParticleOverlap checks for overlap with discrete representations of other particles. Returns overlapsOtherParticle = TRUE if there is overlap. This does not require communication with other processes.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_MEM_type), intent(inout) :: this
Particle we are currently checking overlap for
type(mus_particle_group_type), intent(inout) :: particleGroup
particleGroup to search for overlapping particles in
type(mus_scheme_type), intent(in) :: scheme
Scheme for access to level descriptor
logical, intent(out) :: overlapsOtherParticle
logical indicating if a overlap has been detected (1) or not (0)
Calls
Called by
Call graph
checkforparticleoverlap calls findparticlefromelem, property, tem_abort, val
maptolattice calls checkforparticleoverlap
mus_particles_mapping_mem calls maptolattice