check_velocityMS – Musubi
check_velocityMS Subroutine
44 statements
Source File
private subroutine check_velocityMS(scheme, minLevel, maxLevel, general, mus_aborts)
Check the maximum velocity whether it is above Ma>0.1
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
scheme type
integer, intent(in) :: minLevel
global scheme independent information
integer, intent(in) :: maxLevel
global scheme independent information
type(tem_general_type), intent(inout) :: general
type(mus_abortCriteria_type), intent(in) :: mus_aborts
Calls
Called by
Call graph
check_velocityms calls auxfield_varpos, bits, mpi_reduce, tem_isNaN
perform_checks calls check_velocityms
check_flow_status calls perform_checks
mus_solve calls check_flow_status
musubi calls mus_solve