check_solid_in_bc – Musubi
check_solid_in_bc Subroutine
33 statements
Source File
public subroutine check_solid_in_bc(minLevel, maxLevel, levelPointer, levelDesc, nElems, elemLvl, nValid, posInBCElem)
It count valid (non-solid) elements in BC elements list. Input: minLevel, maxLevel LevelPointer LevelDesc nElems - number of BC elements elems - positions of BC elements in tree or levelPointer Output: nValid - number of valid BC elements posInBCElem - positions of valid elements in BC elements list
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
integer, intent(in) :: levelPointer(:)
Level Pointer (position of a element in level desc)
type(tem_levelDesc_type), intent(in) :: levelDesc(minLevel:maxLevel)
Level Descriptor
integer, intent(in) :: nElems(minLevel:maxLevel)
number of BC elements
type(bc_elems_type), intent(in) :: elemLvl(minLevel:maxLevel)
BC elements list that contains their position in levelPointer
integer, intent(out) :: nValid(minLevel:maxLevel)
number of valid (non-solid) elements
integer, intent(out) :: posInBCElem(maxval(nElems),minLevel:maxLevel)
positions of valid elements in globBC elements list
Calls
Called by
Call graph
check_solid_in_bc calls val
remove_solid_in_bc calls check_solid_in_bc
update_bclists calls remove_solid_in_bc
mus_construct calls update_bclists
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct