check_and_create_new_particles_DPS – Musubi
check_and_create_new_particles_DPS Subroutine
36 statements
Source File
public subroutine check_and_create_new_particles_DPS(particle_creator, iter, particleGroup, scheme, geometry, params, myRank)
Routine that checks if new particles should be created and creates them if so.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_creator_type), intent(inout) :: particle_creator
Particle creator object
integer, intent(in) :: iter
Current LBM iteration
type(mus_particle_group_type), intent(inout) :: particleGroup
particleGroup to add particles to
type(mus_scheme_type), intent(inout) :: scheme
Scheme to initialize particles on the lattice
type(mus_geom_type), intent(in) :: geometry
Geometry to initialize particles on the lattice
type(mus_param_type), intent(in) :: params
Params
integer, intent(in) :: myRank
This process rank
Calls
Called by
Call graph
check_and_create_new_particles_dps calls allocateprocessmasks, create_particles_dps, exchangenewparticles_dps, initparticle_dps, must_create_new_particles, printparticlegroup2_dps
allocateprocessmasks calls allocateprocessmasks_dps
create_particles_dps calls createnewparticle_dps, getnewparticleid, tem_CoordOfReal, val
exchangenewparticles_dps calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, append_da_particle_dps, tem_abort
initparticle_dps calls getposofcoord, updatecoordoforigin_dps, updateexistsonproc_dps, updateparticleowner, tem_CoordOfReal
printparticlegroup2_dps calls tem_IdOfCoord
check_particles_dps calls check_and_create_new_particles_dps