check_varSys_forPdfVar – Musubi
check_varSys_forPdfVar Subroutine
21 statements
Source File
private subroutine check_varSys_forPdfVar(readVarIsPdf, varSys, nFields, fldLabel)
This function runs over all variable loaded from restart file check if variables loaded are pdf variable or derive variable
Variable read from restart file can have variables other than pdf but pdf must be the 1st variable if not stateVarIsPdf will be false
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: readVarIsPdf
return true if variable read from restart file has pdf
type(tem_varSys_type), intent(in) :: varSys
variable system loaded from restart file
integer, intent(in) :: nFields
number of fields
character(len=*), intent(in) :: fldLabel(:)
array of field label prefix. Size=nFields
Calls
Called by
Call graph
check_varsys_forpdfvar calls val
mus_append_readvarasstatevar calls check_varsys_forpdfvar
mus_load_scheme calls mus_append_readvarasstatevar
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config