check_streaming_layout – Musubi
check_streaming_layout Subroutine
15 statements
Source File
public subroutine check_streaming_layout(minLevel, maxLevel)
Check for the streaming layout.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
Called by
Call graph
mus_hvs_init_aux calls check_streaming_layout
mus_init_aux calls check_streaming_layout
mus_initialize calls mus_init_aux
mus_harvesting calls mus_hvs_init_aux
musubi calls mus_initialize