check_particles_MEM – Musubi
check_particles_MEM Subroutine
4 statements
Source File
private subroutine check_particles_MEM(me)
Arguments
Type Intent Optional Attributes Name
class(mus_control_type) :: me
self control type
Calls
Call graph
check_particles_mem calls check_and_create_new_particles_mem
check_and_create_new_particles_mem calls allocateprocessmasks, create_particles_mem, exchangenewparticles_mem, initparticle_mem, must_create_new_particles, printparticlegroup2_mem, remove_particle_from_da_particle_mem, updatecoordoforigin, tem_CoordOfReal
allocateprocessmasks calls allocateprocessmasks_dps
create_particles_mem calls createnewparticle_mem, getnewparticleid, tem_abort, val
exchangenewparticles_mem calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, append_da_particle_mem, tem_abort
initparticle_mem calls init, make_pdf_tiny, updateexclusionlist, updatefluidneighbors, updatesolidnodes
remove_particle_from_da_particle_mem calls swap_da_particle_mem
updatecoordoforigin calls tem_CoordOfReal