check_BCs_preRequisite_MS – Musubi
check_BCs_preRequisite_MS Subroutine
26 statements
Source File
private subroutine check_BCs_preRequisite_MS(field, nBCs)
Check prerequisite for some boundary conditions
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(inout) :: field(:)
fluid parameters and properties
integer, intent(in) :: nBCs
Number of boundary types
Calls
Called by
Call graph
check_bcs_prerequisite_ms calls tem_abort
mus_init_boundary calls check_bcs_prerequisite_ms
mus_initialize calls mus_init_boundary
mus_reset_aux calls mus_init_boundary
mus_perform_dynloadbal calls mus_reset_aux
musubi calls mus_initialize
mus_solve calls mus_perform_dynloadbal