check_potential – Musubi
check_potential Subroutine
27 statements
Source File
public subroutine check_potential(scheme, minLevel, maxLevel, general, total_potential)
Check the total potential for poisson scheme
The output might be delayed by using arrays which are then dumped to keep disc access more restricted
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
scheme type
integer, intent(in) :: minLevel
global scheme independent information
integer, intent(in) :: maxLevel
global scheme independent information
type(tem_general_type), intent(inout) :: general
real(kind=rk), intent(out), optional :: total_potential
Calls
Called by
Call graph
check_potential calls bits, mpi_reduce, tem_isNaN, tem_time_dump
mus_finalize calls check_potential
mus_solve calls check_potential, check_flow_status
perform_checks calls check_potential
check_flow_status calls perform_checks
musubi calls mus_finalize, mus_solve