compute_fluid_momentum – Musubi
compute_fluid_momentum Subroutine
41 statements
Source File
public subroutine compute_fluid_momentum(scheme, lev, params, totalMomentum, comm, myRank, nProcs)
compute_fluid_momentum calculates the total momentum of the fluid for all fluid elements in the global domain. The result "totalMomentum" is returned in physical units.
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
scheme for access to auxfield
integer, intent(in) :: lev
level in the octree to compute total momentum on
type(mus_param_type), intent(in) :: params
params for access to dt, dx, etc.
real(kind=rk), intent(out) :: totalMomentum(3)
output: total momentum on ENTIRE fluid domain (across all procs)
integer :: comm
MPI communicator
integer :: myRank
My MPI rank
integer :: nProcs
Number of MPI processes in communicator
Calls
Called by
Call graph
compute_fluid_momentum calls auxfield_varpos, mpi_reduce, property
mus_log_fluid_momentum calls compute_fluid_momentum
mus_particles_log_total_momentum calls compute_fluid_momentum
test_compute_fluid_momentum calls compute_fluid_momentum