computeLubForce_normal – Musubi
computeLubForce_normal Function
14 statements
Source File
public function computeLubForce_normal(h, hc, mu, R, un, norm_rab) result(Flub)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: h
Gap between particles (physical units)
real(kind=rk), intent(in) :: hc
Critical gap (physical units) If h < hc we use hc to compute the lubrication forces to prevent them from diverging as h -> 0.
real(kind=rk), intent(in) :: mu
Dynamic viscosity (physical units)
real(kind=rk), intent(in) :: R
Radius of the particles
real(kind=rk), intent(in) :: un
Relative velocity in normal direction between the two particles
real(kind=rk), intent(in) :: norm_rab(3)
Unit vector pointing in the direction from particle A to particle B
Return Value real(kind=rk), (3)
Called by
Call graph
checkandcollidedem_dps calls computelubforce_normal
checkandcollidedem_mem calls computelubforce_normal
checkandcollidedem calls checkandcollidedem_dps, checkandcollidedem_mem
dem_computelocalcollisionforces calls checkandcollidedem
dem_computelocalcollisionforces_dps calls checkandcollidedem
dem_computeremotecollisionforces calls checkandcollidedem
dem_computeremotecollisionforces_dps calls checkandcollidedem
demsubcycles_mem calls dem_computelocalcollisionforces, dem_computeremotecollisionforces
updateparticleforces calls dem_computelocalcollisionforces_dps, dem_computeremotecollisionforces_dps