computeWallPosSum_DPS – Musubi
computeWallPosSum_DPS Subroutine
80 statements
Source File
public subroutine computeWallPosSum_DPS(this, BCinteraction, scheme, stencil, geometry, params, rmflag, foundWall, wallPosSum, nWallPos)
computeWallPosSum computes the sum of the locations of wall boundaries in the area surrounding the particle. It also sets rmflag to true if an open boundary is detected, indicating that this particle should be removed from the global domain (in a different routine)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: this
integer, intent(in) :: BCinteraction(:)
Array of length nBCs which tells us how particles should interact with each boundary. Indexed using boundary ID!
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to level descriptor
type(tem_stencilHeader_type), intent(in) :: stencil
Stencil for access to cq
type(mus_geom_type), intent(in) :: geometry
Geometry information to determine TreeIDs of elements 'covered' by particle
type(mus_param_type), intent(in) :: params
Parameters for access to conversion factors between units
logical, intent(out) :: rmflag
Flag to indicate whether particle should be removed because it just hit a non-wall BC
logical, intent(out) :: foundWall
Flag to indicate whether we found a wall or not
real(kind=rk), intent(out) :: wallPosSum(3)
Sum of locations (x,y,z) of the detected walls
integer, intent(out) :: nWallPos
Number of elements in wallPosSum
Calls
Called by
Call graph
computewallpossum_dps calls baryoftotal, boundary_id, nghelems, property, tem_IdOfCoord, tem_PosOfId
computewallpossum calls computewallpossum_dps
dem_storewallpositions_mem calls computewallpossum
demsubcycles_mem calls dem_storewallpositions_mem
mus_particles_move calls demsubcycles_mem