computeWallForce_1D – Musubi
computeWallForce_1D Function
21 statements
Source File
public function computeWallForce_1D(xp, up, Rp, xwall, kn, dn, eps) result(Fwall)
computeWallForce_1D computes the 1D DEM force between a particle at position xp with velocity un to a wall at position xwall.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: xp
Particle position
real(kind=rk), intent(in) :: up
Particle velocity
real(kind=rk), intent(in) :: Rp
Particle radius
real(kind=rk), intent(in) :: xwall
Wall position
real(kind=rk), intent(in) :: kn
Spring constant
real(kind=rk), intent(in) :: dn
Damping coefficient
real(kind=rk), intent(in) :: eps
Threshold distance at which to execute a collision
Return Value real(kind=rk)
Called by
Call graph
computewallforce_dps calls computewallforce_1d
dem_computewallforces_dps calls computewallforce_dps
test_computewallforces calls computewallforce_dps
updateparticleforces calls dem_computewallforces_dps
demsubcycles_dps calls updateparticleforces
demsubcycles_dps_onewaycoupled calls updateparticleforces