computeDisplacement – Musubi
computeDisplacement Function
20 statements
Source File
public function computeDisplacement(x1, x2, boundaryData) result(r12)
computeDistance computes the shortest distance between points x1 and x2 In doing so it takes possible periodic boundaries into account.
Arguments
Type Intent Optional Attributes Name
real(kind=rk) :: x1(3)
xyz coordinates of point 1
real(kind=rk) :: x2(3)
xyz coordinates of point 2
type(mus_particle_boundarydata_type), intent(in) :: boundaryData
Boundary data tells us the domain bounds and if we have periodic bounds
Return Value real(kind=rk), (3)
Called by
Call graph
checkandcollidedem_dps calls computedisplacement
checkandcollidedem_mem calls computedisplacement
dem_fillneighborlist calls computedisplacement
destroyparticle_mem calls computedisplacement
maptolattice calls computedisplacement
test_computedisplacement calls computedisplacement
checkandcollidedem calls checkandcollidedem_dps, checkandcollidedem_mem
demsubcycles_dps calls dem_fillneighborlist
demsubcycles_dps_onewaycoupled calls dem_fillneighborlist
mus_particles_applyhydrodynamicforces_mem calls destroyparticle_mem
mus_particles_mapping_mem calls maptolattice
test_dem_fillneighborlist calls dem_fillneighborlist
dem_computelocalcollisionforces calls checkandcollidedem
dem_computelocalcollisionforces_dps calls checkandcollidedem
dem_computeremotecollisionforces calls checkandcollidedem
dem_computeremotecollisionforces_dps calls checkandcollidedem
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled
demsubcycles_mem calls dem_computelocalcollisionforces, dem_computeremotecollisionforces
updateparticleforces calls dem_computelocalcollisionforces_dps, dem_computeremotecollisionforces_dps