computeWallForce_DPS – Musubi
computeWallForce_DPS Function
24 statements
Source File
public function computeWallForce_DPS(this, boundaryData, eps, kn, dn) result(Fwall)
Routine for computing the collision force between particles and walls for the case of a simple prismatic domain with walls aligned with the Cartesian axes.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: this
Particle to collide
type(mus_particle_boundarydata_type) :: boundaryData
Boundary data containing information on wall location
real(kind=rk), intent(in) :: eps
Threshold gap at which to call it a collision
real(kind=rk), intent(in) :: kn
Spring coefficient
real(kind=rk), intent(in) :: dn
Damping coefficient
Return Value real(kind=rk), (3)
Calls
Called by
Call graph
computewallforce_dps calls computewallforce_1d
dem_computewallforces_dps calls computewallforce_dps
test_computewallforces calls computewallforce_dps
updateparticleforces calls dem_computewallforces_dps
demsubcycles_dps calls updateparticleforces
demsubcycles_dps_onewaycoupled calls updateparticleforces
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled