coordLocalOnMyRank – Musubi
coordLocalOnMyRank Function
17 statements
Source File
public function coordLocalOnMyRank(coord, scheme, myRank)
Routine which checks whether integer coordinate is local on the current rank
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: coord(4)
integer coordinate (x,y,z,level)
type(mus_scheme_type), intent(in) :: scheme
Scheme for access to level descriptor
integer, intent(in) :: myRank
This process rank
Return Value logical
Calls
Called by
Call graph
coordlocalonmyrank calls tem_IdOfCoord, tem_PosOfId
getsearchboxlimits calls coordlocalonmyrank
positionlocalonmyrank calls coordlocalonmyrank
find_particle_comm_procs4 calls getsearchboxlimits
init_particle_creator_from_blob calls positionlocalonmyrank
init_particle_creator_from_blob_prism calls positionlocalonmyrank
load_particle_dps_creator_data calls positionlocalonmyrank
load_particle_mem_creator_data calls positionlocalonmyrank
mus_load_particles calls init_particle_creator_from_blob, init_particle_creator_from_blob_prism, load_particle_dps_creator_data, load_particle_mem_creator_data
mus_particles_initialize_communication calls find_particle_comm_procs4
mus_initialize calls mus_load_particles
mus_particles_initialize calls mus_particles_initialize_communication