createNewParticle_MEM – Musubi
createNewParticle_MEM Subroutine
37 statements
Source File
public subroutine createNewParticle_MEM(pos, vel, F, radius, mass, particleID, particleGroup, geometry, scheme, myRank)
Routine to create a new particle using the information in the particleCreator object
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: pos(6)
Create particle at this position
real(kind=rk), intent(in) :: vel(6)
Initial velocity of particle
real(kind=rk), intent(in) :: F(6)
External forces on particle
real(kind=rk), intent(in) :: radius
Particle radius
real(kind=rk), intent(in) :: mass
Particle mass
integer, intent(in) :: particleID
ID that should be assigned to this particle
type(mus_particle_group_type), intent(inout) :: particleGroup
ParticleGroup to add this particle to
type(mus_geom_type), intent(in) :: geometry
Geometry to initialize particles on the lattice
type(mus_scheme_type), intent(inout) :: scheme
Scheme to initialize particles on the lattice
integer, intent(in) :: myRank
Params for access to dt, dx, etc. This process rank
Calls
Called by
Call graph
createnewparticle_mem calls allocateprocessmasks, append_da_particle_mem, initparticle_mem, remove_particle_from_da_particle_mem, updatecoordoforigin, tem_CoordOfReal
allocateprocessmasks calls allocateprocessmasks_dps
append_da_particle_mem calls expand_da_particle_mem, sortposofval_particle_mem
initparticle_mem calls init, make_pdf_tiny, updateexclusionlist, updatefluidneighbors, updatesolidnodes
remove_particle_from_da_particle_mem calls swap_da_particle_mem
updatecoordoforigin calls tem_CoordOfReal
make_pdf_tiny calls state_varpos, val
updateexclusionlist calls append, empty, getbaryofcoord, getneighborcoord, updateexistsonproc, updateparticleowner, tem_IdOfCoord, tem_PosOfId
updatefluidneighbors calls cxdirinv, nghelems, property, state_varpos, val
updatesolidnodes calls property, state_varpos, val
create_particles_mem calls createnewparticle_mem
check_and_create_new_particles_mem calls create_particles_mem
check_particles_mem calls check_and_create_new_particles_mem