createNewParticle_DPS – Musubi
createNewParticle_DPS Subroutine
32 statements
Source File
public subroutine createNewParticle_DPS(pos, vel, F, radius, mass, particleID, particleGroup, geometry, scheme, myRank)
Routine to create a new particle using the information in the particleCreator object
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: pos(6)
Create particle at this position
real(kind=rk), intent(in) :: vel(6)
Initial velocity of particle
real(kind=rk), intent(in) :: F(6)
External forces on particle
real(kind=rk), intent(in) :: radius
Particle radius
real(kind=rk), intent(in) :: mass
Particle mass
integer, intent(in) :: particleID
ID that should be assigned to this particle
type(mus_particle_group_type), intent(inout) :: particleGroup
ParticleGroup to add this particle to
type(mus_geom_type), intent(in) :: geometry
Geometry to initialize particles on the lattice
type(mus_scheme_type), intent(inout) :: scheme
Scheme to initialize particles on the lattice
integer, intent(in) :: myRank
Params for access to dt, dx, etc. This process rank
Calls
Called by
Call graph
createnewparticle_dps calls allocateprocessmasks, append_da_particle_dps, initparticle_dps, remove_particle_from_da_particle_dps
allocateprocessmasks calls allocateprocessmasks_dps
append_da_particle_dps calls expand_da_particle_dps, sortposofval_particle_dps
initparticle_dps calls getposofcoord, updatecoordoforigin_dps, updateexistsonproc_dps, updateparticleowner, tem_CoordOfReal
remove_particle_from_da_particle_dps calls swap_da_particle_dps
getposofcoord calls tem_IdOfCoord, tem_PosOfId
updatecoordoforigin_dps calls getposofcoord, tem_CoordOfReal
updateexistsonproc_dps calls neigh, part_first, part_last, findpartitionoftreeid, followneighpath, wrapperiodiccoord, tem_IdOfCoord, tem_PosOfId, total
updateparticleowner calls part_first, part_last, findpartitionoftreeid, tem_IdOfCoord, tem_PosOfId
findpartitionoftreeid calls part_first, part_last
create_particles_dps calls createnewparticle_dps
check_and_create_new_particles_dps calls create_particles_dps
check_particles_dps calls check_and_create_new_particles_dps