create_particles_DPS – Musubi
create_particles_DPS Subroutine
32 statements
Source File
public subroutine create_particles_DPS(particle_creator, particleGroup, scheme, geometry, params, myRank)
Routine to create new unresolved DPS particles
Arguments
Type Intent Optional Attributes Name
type(mus_particle_creator_type), intent(inout) :: particle_creator
Particle creator object
type(mus_particle_group_type), intent(inout) :: particleGroup
ParticleGroup to add this particle to
type(mus_scheme_type), intent(inout) :: scheme
Scheme to initialize particles on the lattice
type(mus_geom_type), intent(in) :: geometry
Geometry to initialize particles on the lattice
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
integer, intent(in) :: myRank
This process rank
Calls
Called by
Call graph
create_particles_dps calls createnewparticle_dps, getnewparticleid, tem_CoordOfReal, val
createnewparticle_dps calls allocateprocessmasks, append_da_particle_dps, initparticle_dps, remove_particle_from_da_particle_dps
getnewparticleid calls val
allocateprocessmasks calls allocateprocessmasks_dps
append_da_particle_dps calls expand_da_particle_dps, sortposofval_particle_dps
initparticle_dps calls tem_CoordOfReal, getposofcoord, updatecoordoforigin_dps, updateexistsonproc_dps, updateparticleowner
remove_particle_from_da_particle_dps calls swap_da_particle_dps
getposofcoord calls tem_IdOfCoord, tem_PosOfId
updatecoordoforigin_dps calls tem_CoordOfReal, getposofcoord
updateexistsonproc_dps calls neigh, part_first, part_last, findpartitionoftreeid, followneighpath, wrapperiodiccoord, tem_IdOfCoord, tem_PosOfId, total
updateparticleowner calls part_first, part_last, findpartitionoftreeid, tem_IdOfCoord, tem_PosOfId
check_and_create_new_particles_dps calls create_particles_dps
check_particles_dps calls check_and_create_new_particles_dps