create_particles_MEM – Musubi
create_particles_MEM Subroutine
28 statements
Source File
public subroutine create_particles_MEM(particle_creator, particleGroup, scheme, geometry, params, myRank)
Routine to create new fully resolved MEM particles
Arguments
Type Intent Optional Attributes Name
type(mus_particle_creator_type), intent(inout) :: particle_creator
Particle creator object
type(mus_particle_group_type), intent(inout) :: particleGroup
ParticleGroup to add this particle to
type(mus_scheme_type), intent(inout) :: scheme
Scheme to initialize particles on the lattice
type(mus_geom_type), intent(in) :: geometry
Geometry to initialize particles on the lattice
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
integer, intent(in) :: myRank
This process rank
Calls
Called by
Call graph
create_particles_mem calls createnewparticle_mem, getnewparticleid, tem_abort, val
createnewparticle_mem calls allocateprocessmasks, append_da_particle_mem, initparticle_mem, remove_particle_from_da_particle_mem, updatecoordoforigin, tem_CoordOfReal
getnewparticleid calls val
allocateprocessmasks calls allocateprocessmasks_dps
append_da_particle_mem calls expand_da_particle_mem, sortposofval_particle_mem
initparticle_mem calls init, make_pdf_tiny, updateexclusionlist, updatefluidneighbors, updatesolidnodes
remove_particle_from_da_particle_mem calls swap_da_particle_mem
updatecoordoforigin calls tem_CoordOfReal
make_pdf_tiny calls val, state_varpos
updateexclusionlist calls append, empty, getbaryofcoord, getneighborcoord, updateexistsonproc, updateparticleowner, tem_IdOfCoord, tem_PosOfId
updatefluidneighbors calls val, cxdirinv, nghelems, property, state_varpos
updatesolidnodes calls val, property, state_varpos
check_and_create_new_particles_mem calls create_particles_mem
check_particles_mem calls check_and_create_new_particles_mem