cross_product – Musubi
cross_product Subroutine
8 statements
Source File
public subroutine cross_product(a, b, res)
computes cross-product a x b = res
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: a(3)
real(kind=rk), intent(in) :: b(3)
real(kind=rk), intent(out) :: res(3)
Called by
Call graph
applyhydrodynamicforces calls cross_product
applyliftforce_dps calls cross_product
applyvelocitybounceback calls cross_product
calc_surface_vel calls cross_product
calcvelocityandpressuregradient calls cross_product
calcvelocityandpressuregradient_onewaycoupled calls cross_product
calcvelocityandpressuregradient_onewaycoupled_old calls cross_product
destroyparticle_mem calls cross_product
maptolattice calls cross_product
rodriguez_rotation calls cross_product
checkandcollidedem_dps calls calc_surface_vel
checkandcollidedem_mem calls calc_surface_vel
dem_computeexternalforces_dps_oneway calls applyliftforce_dps
mus_particles_applyhydrodynamicforces_mem calls applyhydrodynamicforces, destroyparticle_mem
mus_particles_dps_interpolatefluidproperties_onewaycoupled calls calcvelocityandpressuregradient_onewaycoupled_old
mus_particles_mapping_mem calls maptolattice
mus_particles_transfermomentumtofluid_mem calls applyvelocitybounceback
rotate_positions calls rodriguez_rotation
test_calcvelocityandpressuregradient_dps calls calcvelocityandpressuregradient
checkandcollidedem calls checkandcollidedem_dps, checkandcollidedem_mem
fill_blob_positions_gauss calls rotate_positions
fill_blob_positions_gauss_prism calls rotate_positions
init_particle_creator_from_blob calls rotate_positions, fill_blob_positions_gauss
mus_particles_applyhydrodynamicforces_dps_onewaycoupled calls mus_particles_dps_interpolatefluidproperties_onewaycoupled
dem_computelocalcollisionforces calls checkandcollidedem
dem_computelocalcollisionforces_dps calls checkandcollidedem
dem_computeremotecollisionforces calls checkandcollidedem
dem_computeremotecollisionforces_dps calls checkandcollidedem
init_particle_creator_from_blob_prism calls fill_blob_positions_gauss_prism
mus_load_particles calls init_particle_creator_from_blob