cumnor – Musubi
cumnor Subroutine
84 statements
Source File
public subroutine cumnor(arg, cum, ccum)
************80
CUMNOR computes the cumulative normal distribution.
Arguments
Type Intent Optional Attributes Name
real(kind=rk) :: arg
real(kind=rk) :: cum
real(kind=rk) :: ccum
Calls
Called by
Call graph
cumnor calls r8_swap
normcdf calls cumnor
init_particle_blob_prob_circle calls normcdf
init_particle_blob_prob_square calls normcdf
init_particle_blob_prob calls init_particle_blob_prob_circle, init_particle_blob_prob_square
fill_blob_positions_gauss calls init_particle_blob_prob
fill_blob_positions_gauss_prism calls init_particle_blob_prob