cumulant_d3q27_extended_generic – Musubi
cumulant_d3q27_extended_generic Subroutine
275 statements
Source File
public subroutine cumulant_d3q27_extended_generic(fieldProp, inState, outState, auxField, neigh, nElems, nSolve, level, layout, params, varSys, derVarPos)
Cumulant based on Geier2017 paper. With all modifications and limiters. All omegas are given in input. When omega(N) = -1 means adjusted in this routine. omega(2)=-1 means omega2=omegaBulk. Limiters read from input. lim(N)=10^10 means unlimited. lim(N) is for omega(N+2). Just omega(3:5) are limited as in the paper.
This subroutine interface must match the abstract interface definition kernel in scheme/mus_scheme_type_module.f90 in order to be callable via compute function pointer.
Arguments
Type Intent Optional Attributes Name
type(mus_field_prop_type), intent(in) :: fieldProp(:)
Array of field properties (fluid or species)
real(kind=rk), intent(in) :: inState(nElems*varSys%nScalars)
input pdf vector
real(kind=rk), intent(out) :: outState(nElems*varSys%nScalars)
output pdf vector
real(kind=rk), intent(inout) :: auxField(nElems*varSys%nAuxScalars)
Auxiliary field computed from pre-collision state Is updated with correct velocity field for multicomponent models
integer, intent(in) :: neigh(nElems*layout%fStencil%QQ)
connectivity vector
integer, intent(in) :: nElems
number of elements in state Array
integer, intent(in) :: nSolve
number of elements solved in kernel
integer, intent(in) :: level
current level
type(mus_scheme_layout_type), intent(in) :: layout
current layout
type(mus_param_type), intent(in) :: params
global parameters
type(tem_varSys_type), intent(in) :: varSys
variable system definition
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
position of derived quantities in varsys for all fields
Calls
Call graph
cumulant_d3q27_extended_generic calls auxfield_varpos, kpc_i_bg, kpc_ij_g, kpc_ijk, kum_abg, kum_i_bg, kum_ij_g, weights_abg, weights_from_layout, weights_ibg, weights_ijg, val