cumulant_omega_check – Musubi
cumulant_omega_check Subroutine
65 statements
Source File
public subroutine cumulant_omega_check(omegaVisc, omegaBulk, omegaIn, nSolve, level)
Checking the stability regions of omegas for the parametrized Cumulant Just omega(2) is given in input. omega(2)=-1 means omega2=omegaBulk. Limiters read from input. lim(N)=10^10 means unlimited. lim(N) is for omega(N+2). Just omega(3:5) are limited as in the paper. omega(6:10) = 1._rk
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: omegaVisc(:)
vector of omegas in the level
real(kind=rk), intent(in) :: omegaBulk
omega bulk value in the level
real(kind=rk), intent(in) :: omegaIn(:)
vector of omegas as given in musubi.lua
integer, intent(in) :: nSolve
number of elements solved in kernel
integer, intent(in) :: level
current level
Calls
Called by
Call graph
cumulant_omega_check calls tem_abort
mus_fluid_dump calls cumulant_omega_check
mus_init_fluid calls mus_fluid_dump
mus_hvs_init_aux calls mus_init_fluid
mus_init_aux calls mus_init_fluid
mus_reset_aux calls mus_init_fluid
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_hvs_init_aux