debug_dependencies – Musubi
debug_dependencies Subroutine
32 statements
Source File
public subroutine debug_dependencies(intp, levelDesc, tree, rank)
check the dependencies from Finer
Arguments
Type Intent Optional Attributes Name
type(mus_interpolation_type), intent(in) :: intp
interpolation method info
type(tem_levelDesc_type), intent(in) :: levelDesc(:)
state properties
type(treelmesh_type), intent(in) :: tree
global tree information
integer, intent(in) :: rank
musubi mpi communicator environment
Calls
Called by
Call graph
debug_dependencies calls newunit, dump_finerghostsfromme, dump_finerghostsfrommebuffer, dump_myghostsfromfiner
dump_finerghostsfromme calls nelems, dump_elemdep, tem_BaryOfId, val, weight
dump_finerghostsfrommebuffer calls nelems, dump_elemdep, tem_BaryOfId, val, weight
dump_myghostsfromfiner calls nelems, dump_elemdep, tem_BaryOfId, val
dump_elemdep calls tem_BaryOfId, tem_ElemSize
mus_hvs_init_aux calls debug_dependencies
mus_init_aux calls debug_dependencies
mus_initialize calls mus_init_aux
mus_harvesting calls mus_hvs_init_aux
musubi calls mus_initialize