debug_dependenciesFromFiner – Musubi
debug_dependenciesFromFiner Subroutine
30 statements
Source File
public subroutine debug_dependenciesFromFiner(levelDesc, minLevel, maxLevel)
Debug the dependencies for the ghostFromFiner elements
Arguments
Type Intent Optional Attributes Name
type(tem_levelDesc_type), intent(in) :: levelDesc(minLevel:maxLevel)
integer, intent(in) :: minLevel
Level range
integer, intent(in) :: maxLevel
Calls
Called by
Call graph
debug_dependenciesfromfiner calls nelems, tem_horizontalSpacer, tem_toStr, val
mus_construct calls debug_dependenciesfromfiner
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve