debug_connectivity – Musubi
debug_connectivity Subroutine
51 statements
Source File
public subroutine debug_connectivity(scheme, minLevel, maxLevel)
Detailed Debug output to the PDF neighbor (connectivity) list
currently the dubug connectivity is done only for 1st field
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
Calls
Called by
Call graph
debug_connectivity calls tem_CoordOfId, tem_horizontalSpacer, total, val
mus_construct calls debug_connectivity
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve