debug_normals – Musubi
debug_normals Subroutine
28 statements
Source File
public subroutine debug_normals(tree, scheme, nBCs)
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
type(mus_scheme_type), intent(in) :: scheme
integer, intent(in) :: nBCs
Calls
Called by
Call graph
debug_normals calls tem_BaryOfId, total, val
mus_construct calls debug_normals
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve