DEM_computeRemoteCollisionForces_DPS – Musubi
DEM_computeRemoteCollisionForces_DPS Subroutine
47 statements
Source File
public subroutine DEM_computeRemoteCollisionForces_DPS(particleGroup, myRank, eps, Tc, mu)
Compute collision forces using Discrete Element Method between particle pairs where particles belong to different processes.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
particleGroup to search for collisions in
integer, intent(in) :: myRank
This proc's rank
real(kind=rk), intent(in) :: eps
Threshold gap at which to call it a collision
real(kind=rk), intent(in) :: Tc
DEM collision time, used for calculating spring and damper coefficients
real(kind=rk), intent(in) :: mu
Fluid dynamic viscosity, physical units
Calls
Called by
Call graph
dem_computeremotecollisionforces_dps calls checkandcollidedem, dem_isremotecollision, addcollisionforcetobuffer, tem_abort
checkandcollidedem calls checkandcollidedem_dps, checkandcollidedem_mem
dem_isremotecollision calls dem_isremotecollision_dps, dem_isremotecollision_mem
addcollisionforcetobuffer calls tem_abort
checkandcollidedem_dps calls calc_surface_vel, computedisplacement, computelubforce_normal, computelubforce_tangential
checkandcollidedem_mem calls calc_surface_vel, computedisplacement, computelubforce_normal, computelubforce_tangential
dem_isremotecollision_dps calls tem_abort
dem_isremotecollision_mem calls tem_abort
calc_surface_vel calls cross_product
updateparticleforces calls dem_computeremotecollisionforces_dps
demsubcycles_dps calls updateparticleforces
demsubcycles_dps_onewaycoupled calls updateparticleforces
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled