DEM_computeLocalCollisionForces_DPS – Musubi
DEM_computeLocalCollisionForces_DPS Subroutine
28 statements
Source File
public subroutine DEM_computeLocalCollisionForces_DPS(particleGroup, myRank, eps, Tc, mu)
Compute collision forces using Discrete Element Method between particles local to this process i.e. both particles are owned by this process.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
particleGroup to search for collisions in
integer, intent(in) :: myRank
This proc's rank
real(kind=rk), intent(in) :: eps
Threshold gap at which to call it a collision
real(kind=rk), intent(in) :: Tc
DEM collision time, used for calculating spring and damper coefficients
real(kind=rk), intent(in) :: mu
Fluid dynamic viscosity, in physical units
Calls
Called by
Call graph
dem_computelocalcollisionforces_dps calls checkandcollidedem, islocalcollision
checkandcollidedem calls checkandcollidedem_dps, checkandcollidedem_mem
islocalcollision calls islocalcollision_dps, islocalcollision_mem
checkandcollidedem_dps calls calc_surface_vel, computedisplacement, computelubforce_normal, computelubforce_tangential
checkandcollidedem_mem calls calc_surface_vel, computedisplacement, computelubforce_normal, computelubforce_tangential
calc_surface_vel calls cross_product
updateparticleforces calls dem_computelocalcollisionforces_dps
demsubcycles_dps calls updateparticleforces
demsubcycles_dps_onewaycoupled calls updateparticleforces
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled