DEM_storeWallPositions_MEM – Musubi
DEM_storeWallPositions_MEM Subroutine
54 statements
Source File
public subroutine DEM_storeWallPositions_MEM(particleGroup, scheme, geometry, params, Tc, eps)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
particleGroup
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
real(kind=rk) :: Tc
Collision time
real(kind=rk) :: eps
Threshold gap for DEM collisions
Calls
Called by
Call graph
dem_storewallpositions_mem calls computewallpossum, dem_exchangewallpositions, tem_abort
computewallpossum calls computewallpossum_dps, computewallpossum_mem
dem_exchangewallpositions calls tem_abort, mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, print_particles_comm, printparticlegroup, printpidlist, sortposofval_particle_mem
computewallpossum_dps calls baryoftotal, boundary_id, nghelems, property, tem_IdOfCoord, tem_PosOfId
computewallpossum_mem calls baryoftotal, boundary_id, nghelems, property, tem_IdOfCoord, tem_PosOfId
print_particles_comm calls print_particles_pidvectorbuffer, print_particles_statebuffer
demsubcycles_mem calls dem_storewallpositions_mem
mus_particles_move calls demsubcycles_mem