DEM_swapFnowFnext_DPS – Musubi
DEM_swapFnowFnext_DPS Subroutine
10 statements
Source File
public subroutine DEM_swapFnowFnext_DPS(this)
Swap the indices of Fnow and Fnext pointing to the force at the current and next time step respectively
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: this
Called by
Call graph
dem_swapfnowfnext calls dem_swapfnowfnext_dps
demsubcycles_dps calls dem_swapfnowfnext
demsubcycles_dps_onewaycoupled calls dem_swapfnowfnext
demsubcycles_mem calls dem_swapfnowfnext
mus_particles_move calls demsubcycles_mem
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled