DEM_exchangeWallPositions – Musubi
DEM_exchangeWallPositions Subroutine
64 statements
Source File
public subroutine DEM_exchangeWallPositions(this, send, recv, comm, myRank, message_flag)
DEM_exchangeWallPositions sends wall position sums close to a particle as detected on each process to the particle owner, which averages the results to get one average wall position Upon termination of this routine particle%rwall for all particles which I own should be set correctly.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: this
particleGroup of this process
type(mus_particles_communication_type), intent(inout) :: send
Communication type for sending force contributions
type(mus_particles_communication_type), intent(inout) :: recv
Communication type for receiving force contributions
integer, intent(in) :: comm
MPI communicator
integer, intent(in) :: myRank
Rank of this process
integer, intent(in) :: message_flag
Flag for message (in Musubi this is just iLevel, don't think we really need this here)
Calls
Called by
Call graph
dem_exchangewallpositions calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, print_particles_comm, printparticlegroup, printpidlist, sortposofval_particle_mem, tem_abort
print_particles_comm calls print_particles_pidvectorbuffer, print_particles_statebuffer
dem_storewallpositions_mem calls dem_exchangewallpositions
demsubcycles_mem calls dem_storewallpositions_mem
mus_particles_move calls demsubcycles_mem