DEM_computeExternalForces_DPS_oneway – Musubi
DEM_computeExternalForces_DPS_oneway Subroutine
18 statements
Source File
public subroutine DEM_computeExternalForces_DPS_oneway(particleGroup, nu, myRank)
DEM_computeExternalForces adds the non-DEM forces (including hydrodynamic force from the LBM) to F_DEM which is used to update velocity within the DEM subcycle.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
particleGroup to search for collisions in
real(kind=rk), intent(in) :: nu
Fluid dynamic viscosity (physical units) for computing hydro forces
integer, intent(in) :: myRank
This process rank
Calls
Call graph
dem_computeexternalforces_dps_oneway calls applydragforce_dps, applyliftforce_dps, applypressureforce_dps
applyliftforce_dps calls cross_product