DEM_exchangeForces – Musubi
DEM_exchangeForces Subroutine
55 statements
Source File
public subroutine DEM_exchangeForces(this, send, recv, comm, myRank, message_flag)
DEM_exchangeForces sends DEM collision force contributions from collisions that cannot be resolved by the receiving process. The send force buffers in this case must already be filled in the DEM collision-handling routines!
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: this
particleGroup of this process
type(mus_particles_communication_type), intent(inout) :: send
Communication type for sending force contributions
type(mus_particles_communication_type), intent(inout) :: recv
Communication type for receiving force contributions
integer, intent(in) :: comm
MPI communicator
integer, intent(in) :: myRank
Rank of this process
integer, intent(in) :: message_flag
Flag for message (in Musubi this is just iLevel, don't think we really need this here)
Calls
Called by
Call graph
dem_exchangeforces calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, print_particles_comm, printparticlegroup, printpidlist, sortposofval_particle_mem, tem_abort
print_particles_comm calls print_particles_pidvectorbuffer, print_particles_statebuffer
demsubcycles_mem calls dem_exchangeforces
mus_particles_move calls demsubcycles_mem