DEM_isRemoteCollision_MEM – Musubi
DEM_isRemoteCollision_MEM Subroutine
53 statements
Source File
public subroutine DEM_isRemoteCollision_MEM(particleA, particleB, myRank, send, isRemoteCollision, otherRank, otherRankIndex)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_MEM_type), intent(in) :: particleA
First particle to collide
type(mus_particle_MEM_type), intent(in) :: particleB
Second particle to collide
integer, intent(in) :: myRank
This process's rank
type(mus_particles_communication_type), intent(in) :: send
Communication type for sending
logical, intent(out) :: isRemoteCollision
logical indicating if this is a remote collision that needs to be resolved on this process
integer, intent(out) :: otherRank
Other particle's rank as an output
integer, intent(out) :: otherRankIndex
Position of other particle's rank in send%proc
Calls
Called by
Call graph
dem_isremotecollision_mem calls tem_abort
dem_isremotecollision calls dem_isremotecollision_mem
dem_computeremotecollisionforces calls dem_isremotecollision
dem_computeremotecollisionforces_dps calls dem_isremotecollision
demsubcycles_mem calls dem_computeremotecollisionforces
updateparticleforces calls dem_computeremotecollisionforces_dps
demsubcycles_dps calls updateparticleforces
demsubcycles_dps_onewaycoupled calls updateparticleforces
mus_particles_move calls demsubcycles_mem