DEM_resetFnext_DPS – Musubi
DEM_resetFnext_DPS Subroutine
9 statements
Source File
public subroutine DEM_resetFnext_DPS(particleGroup)
Reset the force at the next time step to 0
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
particleGroup to reset F_DEM(F_DEM_next,:) for
Called by
Call graph
updateparticleforces calls dem_resetfnext_dps
demsubcycles_dps calls updateparticleforces
demsubcycles_dps_onewaycoupled calls updateparticleforces
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled