DEMSubcycles_MEM – Musubi
DEMSubcycles_MEM Subroutine
60 statements
Source File
public subroutine DEMSubcycles_MEM(particleGroup, scheme, geometry, params, Nsubcycles)
DEMsubcycles runs Nsubcycles time integration steps per LBM time step In this routine simple Forward Euler integration of particle position and velocity is used.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
integer, intent(in) :: Nsubcycles
Number of subcycles
Calls
Called by
Call graph
demsubcycles_mem calls dem_swapfnowfnext, updatepositionverlet, updatevelocityverlet, dem_computeexternalforces, dem_computelocalcollisionforces, dem_computeremotecollisionforces, dem_computewallforces_mem, dem_exchangeforces, dem_resetfnext_mem, dem_storewallpositions_mem, exchangepositions, exchangevelocities, resetforcebuffers, updatecoordoforigin, wrapperiodicpos, val
mus_particles_move calls demsubcycles_mem