DEMSubcycles_DPS_onewaycoupled – Musubi
DEMSubcycles_DPS_onewaycoupled Subroutine
50 statements
Source File
public subroutine DEMSubcycles_DPS_onewaycoupled(particleGroup, scheme, geometry, params, Nsubcycles)
DEMsubcycles runs Nsubcycles time integration steps per LBM time step In this routine velocity verlet integration of particle position and velocity is used. This routine is for one-way coupled DPS particles.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
integer, intent(in) :: Nsubcycles
Number of subcycles
Calls
Called by
Call graph
demsubcycles_dps_onewaycoupled calls dem_swapfnowfnext, updatepositionverlet, updatevelocityverlet, dem_fillneighborlist, exchangepositions_dps, exchangevelocities_dps, mapparticlestolattice_dps, updateparticleforces, wrapperiodicpos, val
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled