derive_HRRCorrection_d3q27 – Musubi
derive_HRRCorrection_d3q27 Subroutine
39 statements
Source File
public recursive subroutine derive_HRRCorrection_d3q27(fun, varSys, elempos, time, tree, nElems, nDofs, res)
Derive external force variable defined as a source term. It evaluates spacetime function defined in lua file for force variable and convert it to state value which is to be added to the state
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
integer, intent(in) :: elempos(:)
Position of the TreeID of the element to get the variable for in the global treeID list.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nElems
Number of values to obtain for this variable (vectorized access).
integer, intent(in) :: nDofs
Number of degrees of freedom within an element.
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Linearized array dimension: (n requested entries) x (nComponents of this variable) x (nDegrees of freedom) Access: (iElem-1)fun%nComponentsnDofs + (iDof-1)*fun%nComponents + iComp
Calls
Call graph
derive_hrrcorrection_d3q27 calls auxfield_varpos, hrr_correction_d3q27, tem_LevelOf, tem_abort, val