deriveAuxMSLiquid_fromState_WTDF – Musubi
deriveAuxMSLiquid_fromState_WTDF Subroutine
64 statements
Source File
public subroutine deriveAuxMSLiquid_fromState_WTDF(derVarPos, state, neigh, iField, nElems, nSize, iLevel, stencil, varSys, auxField, quantities)
This routine computes auxField 'density and velocity' of given field from state array with thermodynamic factot. velocity of original PDF is computed in this routine by solving LSE.
This subroutine's interface must match the abstract interface definition derive_auxFromState in derived/mus_derVarPos_module.f90 in order to be callable via auxFieldFromState function pointer.
Arguments
Type Intent Optional Attributes Name
class(mus_derVarPos_type), intent(in) :: derVarPos
Position of derive variable in variable system
real(kind=rk), intent(in) :: state(:)
Array of state n * layout%stencil(1)%QQ * nFields
integer, intent(in) :: neigh(:)
connectivity vector
integer, intent(in) :: iField
Current field
integer, intent(in) :: nElems
number of elements
integer, intent(in) :: nSize
number of elements in state array
integer, intent(in) :: iLevel
current level
type(tem_stencilHeader_type), intent(in) :: stencil
stencil header contains discrete velocity vectors
type(tem_varSys_type), intent(in) :: varSys
variable system which is required to access fieldProp information via variable method data c_ptr
real(kind=rk), intent(inout) :: auxField(:)
Output of this routine Size: nElems*nAuxScalars
type(mus_scheme_derived_quantities_type), intent(in) :: quantities
Class that contains pointers to the proper derived quantities functions
Calls
Call graph
deriveauxmsliquid_fromstate_wtdf calls auxfield_varpos, mus_calc_ms_diffmatrix, mus_calc_thermfactor, invert_matrix, momentumfrommacrolse_wtdf, val
mus_calc_ms_diffmatrix calls mus_calc_ms_diffmatrix_single
mus_calc_thermfactor calls mus_calc_thermfactor_single
momentumfrommacrolse_wtdf calls invert_matrix