deriveEqMSLiquid_FromState – Musubi
deriveEqMSLiquid_FromState Subroutine
59 statements
Source File
public subroutine deriveEqMSLiquid_FromState(state, iField, nElems, varSys, layout, res)
This routine computes equilibrium from state array
This subroutine's interface must match the abstract interface definition derive_FromState in derived/mus_derVarPos_module.f90 in order to be callable via velFromState, equilFromState, momFromState, velocitiesFromState, and momentaFromState function pointers.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:)
Array of state n * layout%fStencil%QQ * nFields
integer, intent(in) :: iField
Current field
integer, intent(in) :: nElems
number of elements
type(tem_varSys_type), intent(in) :: varSys
variable system which is required to access fieldProp information via variable method data c_ptr
type(mus_scheme_layout_type), intent(in) :: layout
scheme layout contains stencil definition and lattice weights
real(kind=rk), intent(out) :: res(:)
Output of this routine Dimension: n * nComponents of res
Calls
Call graph
deriveeqmsliquid_fromstate calls cxdirrk, equilfrommacro, momentumfrommacrolse, state_varpos, val
equilfrommacro calls cxdirrk, equilvelfrommacro
momentumfrommacrolse calls invert_matrix