do_fast_singleLevel – Musubi
do_fast_singleLevel Subroutine
38 statements
Source File
private subroutine do_fast_singleLevel(me, scheme, geometry, params, iLevel)
Control routine for an optimized workflow with reduced functionality.
No sources, no multilevel, no multiLevel. Use for benchmarking
Arguments
Type Intent Optional Attributes Name
class(mus_control_type) :: me
self control type dummy variable in this routine, required by interface
type(mus_scheme_type), intent(inout) :: scheme
container for the scheme
type(mus_geom_type), intent(inout) :: geometry
geometry infomation
type(mus_param_type), intent(inout) :: params
global parameters
integer, intent(in) :: iLevel
Level counter variable
Calls
Call graph
do_fast_singlelevel calls exchange_real, mus_buildbuffibm, mus_inamuro_ibm, mus_apply_sourceterms, mus_calcauxfieldandexchange, mus_swap_now_next, mus_update_relaxparams, mus_update_sourcevars, set_boundary, tem_startTimer, tem_stopTimer, tem_time_advance
mus_apply_sourceterms calls tem_startTimer, tem_stopTimer
mus_calcauxfieldandexchange calls exchange_real
mus_update_relaxparams calls nelems, mus_turb_updateviscofturbwall, mus_update_relaxparamkine, mus_update_visckine, setparameters_multispecies, tvisc
mus_update_sourcevars calls tem_startTimer, tem_stopTimer
mus_update_relaxparamkine calls val
mus_update_visckine calls auxfield_varpos, calcvisc, mus_turb_calcvisc, tem_spacetime_for, val
setparameters_multispecies calls invert_matrix, tem_temporal_for