do_intpCoarserAndExchange – Musubi
do_intpCoarserAndExchange Subroutine
26 statements
Source File
private subroutine do_intpCoarserAndExchange(scheme, params, iLevel)
This routine utilizes fluid elements on my level (L) to fill finer ghost elements on next level (L+1). Then it exchanges the datas of finer ghost elements (L+1) between process.
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout), target :: scheme
containers for the different schemes
type(mus_param_type), intent(in) :: params
global parameters
integer, intent(in) :: iLevel
Level counter variable
Calls
Called by
Call graph
do_intpcoarserandexchange calls exchange_real, start_stagetimer, stop_stagetimer, tem_startTimer, tem_stopTimer
start_stagetimer calls tem_startTimer
stop_stagetimer calls tem_stopTimer
do_recursive_multilevel calls do_intpcoarserandexchange