do_intpFinerAndExchange – Musubi
do_intpFinerAndExchange Subroutine
23 statements
Source File
private subroutine do_intpFinerAndExchange(scheme, params, iLevel)
This routine does: 1. interpolate my coarse ghost element (iLevel) from finer level (iLevel+1) 2. exchange the data of my coarse ghost elements between process
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout), target :: scheme
containers for the different schemes
type(mus_param_type), intent(inout) :: params
global parameters
integer, intent(in) :: iLevel
Calls
Called by
Call graph
do_intpfinerandexchange calls exchange_real, start_stagetimer, stop_stagetimer, tem_startTimer, tem_stopTimer
start_stagetimer calls tem_startTimer
stop_stagetimer calls tem_stopTimer
do_recursive_multilevel calls do_intpfinerandexchange