do_recursive_multiLevel – Musubi
do_recursive_multiLevel Subroutine
76 statements
Source File
private recursive subroutine do_recursive_multiLevel(me, scheme, geometry, params, iLevel)
Main control routine: Update the time step for all levels. Main steps: * if iLevel < maxLevel do recursive at iLevel+1 * do BC at iLevel * do auxField calculation at iLevel * do compute kernel at iLevel * do apply source at iLevel * do do_IntpFinerAndExchange at iLevel if iLevel < maxLevel * intp My Coarser ghost (iLevel) from Finer (iLevel+1) * do exchange bufferFromFiner at iLevel * exchange buffer at iLevel * exchange bufferFromCoarser at iLevel if iLevel > minLevel * do do_intpCoarserAndExchange at iLevel if iLevel < maxLevel * intp Finer Ghost (iLevel+1) from my coarser (iLevel) * exchange bufferFromCoarser at iLevel+1
Arguments
Type Intent Optional Attributes Name
class(mus_control_type) :: me
self control type
type(mus_scheme_type), intent(inout) :: scheme
container for the scheme
type(mus_geom_type), intent(inout) :: geometry
geometry infomation
type(mus_param_type), intent(inout) :: params
global parameters
integer, intent(in) :: iLevel
the current level
Calls
Call graph
do_recursive_multilevel calls exchange_real, do_intpcoarserandexchange, do_intpfinerandexchange, mus_apply_sourceterms, mus_calcauxfieldandexchange, mus_intpauxfieldcoarserandexchange, mus_swap_now_next, mus_update_relaxparams, mus_update_sourcevars, start_stagetimer, stop_stagetimer, set_boundary, tem_startTimer, tem_stopTimer, tem_time_advance
do_intpcoarserandexchange calls exchange_real, start_stagetimer, stop_stagetimer, tem_startTimer, tem_stopTimer
do_intpfinerandexchange calls exchange_real, start_stagetimer, stop_stagetimer, tem_startTimer, tem_stopTimer
mus_apply_sourceterms calls tem_startTimer, tem_stopTimer
mus_calcauxfieldandexchange calls exchange_real
mus_intpauxfieldcoarserandexchange calls exchange_real
mus_update_relaxparams calls nelems, mus_turb_updateviscofturbwall, mus_update_relaxparamkine, mus_update_visckine, setparameters_multispecies, tvisc
mus_update_sourcevars calls tem_startTimer, tem_stopTimer
start_stagetimer calls tem_startTimer
stop_stagetimer calls tem_stopTimer
mus_update_relaxparamkine calls val
mus_update_visckine calls auxfield_varpos, calcvisc, mus_turb_calcvisc, tem_spacetime_for, val
setparameters_multispecies calls invert_matrix, tem_temporal_for