dumpdata – Musubi
dumpdata Subroutine
53 statements
Source File
public subroutine dumpdata(tracker, t, scheme, geometry, params)
Debugging routine to dump debug tracking data
Arguments
Type Intent Optional Attributes Name
type(mus_particle_debugtracking_type), intent(inout) :: tracker
Tracker containing file name and elemList
real(kind=rk), intent(in) :: t
Current simulation time
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to fluid data
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params
Calls
Call graph
dumpdata calls auxfield_varpos, getbaryofcoord, openlogfile, tem_CoordOfId, tem_FirstIdAtLevel, total, val
openlogfile calls newunit