dump_MyGhostsFromFiner – Musubi
dump_MyGhostsFromFiner Subroutine
31 statements
Source File
private subroutine dump_MyGhostsFromFiner(intp, leveldesc, nUnit, tree)
check the dependencies from Finer and write them out so we can compare
Arguments
Type Intent Optional Attributes Name
type(mus_interpolation_type), intent(in) :: intp
interpolation method info
type(tem_levelDesc_type), intent(in) :: leveldesc(:)
state properties
integer, intent(in) :: nUnit
unit to write to
type(treelmesh_type), intent(in) :: tree
global tree information
Calls
Called by
Call graph
dump_myghostsfromfiner calls nelems, dump_elemdep, tem_BaryOfId, val
dump_elemdep calls tem_BaryOfId, tem_ElemSize
debug_dependencies calls dump_myghostsfromfiner
mus_hvs_init_aux calls debug_dependencies
mus_init_aux calls debug_dependencies
mus_initialize calls mus_init_aux
mus_harvesting calls mus_hvs_init_aux
musubi calls mus_initialize