dump_linear_partition – Musubi
dump_linear_partition Subroutine
41 statements
Source File
public subroutine dump_linear_partition(treeID, nElems, offset, myRank, iter)
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: treeID(1:nElems)
integer, intent(in) :: nElems
integer(kind=long_k), intent(in) :: offset
integer, intent(in) :: myRank
integer, intent(in) :: iter
Calls
Called by
Call graph
dump_linear_partition calls newunit, tem_LevelOf
mus_load_config calls dump_linear_partition
mus_perform_dynloadbal calls dump_linear_partition
mus_solve calls mus_perform_dynloadbal
musubi calls mus_load_config, mus_solve