dump_elemDep – Musubi
dump_elemDep Subroutine
19 statements
Source File
private subroutine dump_elemDep(targetElem, sourceElem, nUnit, tree, weight)
dump dependencies for one element
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: targetElem
integer(kind=long_k), intent(in) :: sourceElem
integer, intent(in) :: nUnit
type(treelmesh_type), intent(in) :: tree
real(kind=rk), optional :: weight
Calls
Called by
Call graph
dump_elemdep calls tem_BaryOfId, tem_ElemSize
dump_finerghostsfromme calls dump_elemdep
dump_finerghostsfrommebuffer calls dump_elemdep
dump_myghostsfromfiner calls dump_elemdep
debug_dependencies calls dump_finerghostsfromme, dump_finerghostsfrommebuffer, dump_myghostsfromfiner
mus_hvs_init_aux calls debug_dependencies
mus_init_aux calls debug_dependencies
mus_initialize calls mus_init_aux
mus_harvesting calls mus_hvs_init_aux