dump_timing – Musubi
dump_timing Subroutine
64 statements
Source File
private subroutine dump_timing(totalDens, DomSize, MLUPS, MLUPS_kernel, timerVal, imbalance, general)
Performance results (MLUPs) are written to a file for statistical review The file-format is simple can be evaluated with gnuplot
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: totalDens
integer(kind=long_k), intent(in) :: DomSize
real(kind=rk), intent(in) :: MLUPS
real(kind=rk), intent(in) :: MLUPS_kernel
real(kind=rk), intent(in) :: timerVal(:)
Max. timers of all process
real(kind=rk), intent(in) :: imbalance
type(tem_general_type), intent(in) :: general
Calls
Called by
Call graph
dump_timing calls get_auxtime, get_bcbufferratio, get_computeratio, get_relaxtime, newunit, get_boundaryratio, get_communicateratio, get_intpratio, tem_getTimerName, tem_getTimerVal
get_auxtime calls get_auxtime_atlevel, get_auxtime_total
get_bcbufferratio calls get_bcbufferratio_atlevel, get_bcbufferratio_total
get_computeratio calls get_computeratio_atlevel, get_computeratio_total
get_relaxtime calls get_relaxtime_atlevel, get_relaxtime_total
get_boundaryratio calls get_boundarytime, get_mainlooptime
get_communicateratio calls get_communicatetime, get_mainlooptime
get_intpratio calls get_intptime, get_mainlooptime
get_boundarytime calls get_boundarytime_byid, get_boundarytime_total
get_auxtime_atlevel calls tem_getTimerVal
get_auxtime_total calls get_auxtime
get_bcbufferratio_atlevel calls get_mainlooptime, get_bcbuffertime
get_bcbufferratio_total calls get_mainlooptime, get_bcbuffertime
get_communicatetime calls tem_getTimerVal
get_computeratio_atlevel calls get_mainlooptime, get_computetime
get_computeratio_total calls get_mainlooptime, get_computetime
get_intptime calls get_intpfromcoarsertime, get_intpfromfinertime
get_mainlooptime calls tem_getTimerVal
get_relaxtime_atlevel calls tem_getTimerVal
get_relaxtime_total calls get_relaxtime
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure
musubi calls mus_finalize, mus_solve