dump_intpLists – Musubi
dump_intpLists Subroutine
31 statements
Source File
public subroutine dump_intpLists(minLevel, maxLevel, order, levelDesc, rank)
check the dependencies from Finer
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
global pdf information
integer, intent(in) :: maxLevel
global pdf information
integer, intent(in) :: order
type(tem_levelDesc_type), intent(in) :: levelDesc(minLevel:maxLevel)
state properties
integer, intent(in) :: rank
musubi mpi communicator environment
Calls
Called by
Call graph
dump_intplists calls newunit, dump_intplist
mus_hvs_init_aux calls dump_intplists
mus_init_aux calls dump_intplists
mus_initialize calls mus_init_aux
mus_harvesting calls mus_hvs_init_aux
musubi calls mus_initialize