dump_FinerGhostsFromMe – Musubi
dump_FinerGhostsFromMe Subroutine
44 statements
Source File
private subroutine dump_FinerGhostsFromMe(intp, levelDesc, nUnit, tree)
check the dependencies from Coarser
Arguments
Type Intent Optional Attributes Name
type(mus_interpolation_type), intent(in) :: intp
interpolation method info
type(tem_levelDesc_type), intent(in) :: levelDesc(:)
state properties
integer, intent(in) :: nUnit
unit to write to
type(treelmesh_type), intent(in) :: tree
global tree information
Calls
Called by
Call graph
dump_finerghostsfromme calls nelems, dump_elemdep, tem_BaryOfId, val, weight
dump_elemdep calls tem_BaryOfId, tem_ElemSize
debug_dependencies calls dump_finerghostsfromme
mus_hvs_init_aux calls debug_dependencies
mus_init_aux calls debug_dependencies
mus_initialize calls mus_init_aux
mus_harvesting calls mus_hvs_init_aux
musubi calls mus_initialize