dump_bc_timing – Musubi
dump_bc_timing Subroutine
61 statements
Source File
public subroutine dump_bc_timing(proc, nFluids, nBCElems, DomSize, iter, send)
This routine dump compute and BC timing for all ranks rank nFluids tCompute nBCElems tBC tCPU tMainLoop
Arguments
Type Intent Optional Attributes Name
type(tem_comm_env_type), intent(in) :: proc
integer, intent(in) :: nFluids
integer, intent(in) :: nBCElems
integer(kind=long_k), intent(in) :: DomSize
integer, intent(in) :: iter
type(tem_communication_type), intent(in) :: send
Calls
Call graph
dump_bc_timing calls check_mpi_error, get_bcbuffertime, get_boundarytime, get_computetime, mpi_barrier, mpi_file_close, mpi_file_open, mpi_file_write_ordered, mpi_reduce, newunit, get_communicatetime, get_mainlooptime
get_bcbuffertime calls get_bcbuffertime_atlevel, get_bcbuffertime_total
get_boundarytime calls get_boundarytime_byid, get_boundarytime_total
get_computetime calls get_computetime_atlevel, get_computetime_total
get_communicatetime calls tem_getTimerVal
get_mainlooptime calls tem_getTimerVal
get_bcbuffertime_atlevel calls tem_getTimerVal
get_bcbuffertime_total calls get_bcbuffertime
get_boundarytime_byid calls tem_getTimerVal
get_boundarytime_total calls get_boundarytime
get_computetime_atlevel calls tem_getTimerVal
get_computetime_total calls get_computetime