equilVelFromMacro – Musubi
equilVelFromMacro Function
15 statements
Source File
private pure function equilVelFromMacro(iField, moleFraction, velocity, nFields, paramBInv, phi, resi_coeff) result(eqVel)
Equlibrium velocity from macro
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iField
current field
real(kind=rk), intent(in) :: moleFraction(nFields)
mole fraction of all species
real(kind=rk), intent(in) :: velocity(3,nFields)
velocity of all species
integer, intent(in) :: nFields
number of species
real(kind=rk), intent(in) :: paramBInv
free parameter B
real(kind=rk), intent(in) :: phi
molecular weight ratio of iField
real(kind=rk), intent(in) :: resi_coeff(nFields)
resistivity coefficients of iField
Return Value real(kind=rk), (3)
return equilibrium velocity
Called by
Call graph
deriveequilvelmsliquid calls equilvelfrommacro
equilfrommacro calls equilvelfrommacro
deriveeqmsliquid_fromstate calls equilfrommacro
deriveequilmsliquid calls equilfrommacro
deriveequilmsliquid_fromaux calls equilfrommacro
deriveequilmsliquid_frommacro calls equilfrommacro