exchangeForces – Musubi
exchangeForces Subroutine
85 statements
Source File
public subroutine exchangeForces(this, send, recv, comm, myRank, message_flag)
exchangeForces send force contributions from each process on which a particle exists to the particle owner. The total hydrodynamic force is then computed by the particle owner as the sum of all the force contributions (which physically are the surface forces from the part of the particle surface handled by each process). The owner then updates particle velocity in a subsequent call to a different routine. For momentum-exchange method only!
Arguments
Type Intent Optional Attributes Name
class(mus_particle_group_type), intent(inout) :: this
particleGroup of this process
type(mus_particles_communication_type), intent(inout) :: send
Communication type for sending force contributions
type(mus_particles_communication_type), intent(inout) :: recv
Communication type for receiving force contributions
integer, intent(in) :: comm
MPI communicator
integer, intent(in) :: myRank
Rank of this process
integer, intent(in) :: message_flag
Flag for message (in Musubi this is just iLevel, don't think we really need this here)
Calls
Call graph
exchangeforces calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, print_particles_comm, printparticlegroup, printpidlist, sortposofval_particle_mem, tem_abort
print_particles_comm calls print_particles_pidvectorbuffer, print_particles_statebuffer