exchange_tree_bc – Musubi
exchange_tree_bc Subroutine
28 statements
Source File
private subroutine exchange_tree_bc(sparta, geometry, comm, comm_size)
Arguments
Type Intent Optional Attributes Name
type(tem_sparta_type), intent(in) :: sparta
type(mus_geom_type), intent(inout) :: geometry
integer, intent(in) :: comm
integer, intent(in) :: comm_size
Calls
Called by
Call graph
exchange_tree_bc calls exchange_elements, mus_build_posinprop, tem_derive_sparta, tem_destroy_sparta, tem_exchange_sparta, tem_init_sparta
mus_build_posinprop calls mus_build_minbcid, property, tem_build_treeToProp_pointer
mus_perform_dynloadbal calls exchange_tree_bc