exchangeMomInc_DPS – Musubi
exchangeMomInc_DPS Subroutine
66 statements
Source File
public subroutine exchangeMomInc_DPS(this, send, recv, comm, myRank, message_flag)
exchangeMomInc_DPS send the accumulated momentum transfer FROM particles TO fluid from a particle's previous owner to its new owner.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: this
particleGroup of this process
type(mus_particles_communication_type), intent(inout) :: send
Communication type for sending force contributions
type(mus_particles_communication_type), intent(inout) :: recv
Communication type for receiving force contributions
integer, intent(in) :: comm
MPI communicator
integer, intent(in) :: myRank
Rank of this process
integer, intent(in) :: message_flag
Flag for message (in Musubi this is just iLevel, don't think we really need this here)
Calls
Called by
Call graph
exchangemominc_dps calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, sortposofval_particle_dps, tem_abort, tem_startTimer, tem_stopTimer
demsubcycles_dps calls exchangemominc_dps
mus_particles_move_dps calls demsubcycles_dps