exchangeHydroForces_DPS – Musubi
exchangeHydroForces_DPS Subroutine
62 statements
Source File
public subroutine exchangeHydroForces_DPS(this, send, recv, comm, myRank, message_flag)
exchangeHydroForces_DPS exchanges particles hydrodynamic forces after they have been updated by the particle owner. Each process sends force updates for particles they own and receives updates for particles which they do not own, but that do exist in their particleGroup.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: this
particleGroup of this process
type(mus_particles_communication_type), intent(inout) :: send
Communication type for sending force contributions
type(mus_particles_communication_type), intent(inout) :: recv
Communication type for receiving force contributions
integer, intent(in) :: comm
MPI communicator
integer, intent(in) :: myRank
Rank of this process
integer, intent(in) :: message_flag
Flag for message (in Musubi this is just iLevel, don't think we really need this here)
Calls
Called by
Call graph
exchangehydroforces_dps calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, sortposofval_particle_dps, tem_abort, tem_startTimer, tem_stopTimer
mus_particles_transfermomentumtofluid_dps calls exchangehydroforces_dps
updateparticleforces calls exchangehydroforces_dps
demsubcycles_dps calls updateparticleforces
demsubcycles_dps_onewaycoupled calls updateparticleforces
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled