exchangePositions – Musubi
exchangePositions Subroutine
71 statements
Source File
public subroutine exchangePositions(this, send, recv, comm, myRank, message_flag)
exchangePositions exchanges particles continuous positions after they have been updated by the particle owner. Each process sends position updates for particles they own and receives updates for particles which they do not own, but that do exist in their particleGroup.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: this
particleGroup of this process
type(mus_particles_communication_type), intent(inout) :: send
Communication type for sending force contributions
type(mus_particles_communication_type), intent(inout) :: recv
Communication type for receiving force contributions
integer, intent(in) :: comm
MPI communicator
integer, intent(in) :: myRank
Rank of this process
integer, intent(in) :: message_flag
Flag for message (in Musubi this is just iLevel, don't think we really need this here)
Calls
Called by
Call graph
exchangepositions calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, print_particles_comm, printparticlegroup, printpidlist, sortposofval_particle_mem, tem_abort
print_particles_comm calls print_particles_pidvectorbuffer, print_particles_statebuffer
demsubcycles_mem calls exchangepositions
mus_particles_move calls demsubcycles_mem