f_f_eq_regularized_2nd_ord_d2q9 – Musubi
f_f_eq_regularized_2nd_ord_d2q9 Subroutine
50 statements
Source File
private pure subroutine f_f_eq_regularized_2nd_ord_d2q9(weight, rho, u_x, u_y, feq, f1, a12xx, a12yy, a12xy)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: weight(QQ)
Weights of the stencil
real(kind=rk), intent(in) :: rho
Density, velocity components
real(kind=rk), intent(in) :: u_x
real(kind=rk), intent(in) :: u_y
real(kind=rk), intent(out) :: feq(QQ)
Equilibrium pdf and full pdf
real(kind=rk), intent(out) :: f1(QQ)
real(kind=rk), intent(in) :: a12xx
Coefficients of f1: a12xx, a12yy, a12xy
real(kind=rk), intent(in) :: a12yy
Coefficients of f1: a12xx, a12yy, a12xy
real(kind=rk), intent(in) :: a12xy
Coefficients of f1: a12xx, a12yy, a12xy
Called by
Call graph
bgk_dualrelaxationtime_rr_d2q9 calls f_f_eq_regularized_2nd_ord_d2q9
bgk_regularized_d2q9 calls f_f_eq_regularized_2nd_ord_d2q9
f_f_eq_regularized_4th_ord_d2q9 calls f_f_eq_regularized_2nd_ord_d2q9
bgk_hybridrecursiveregularized_d2q9 calls f_f_eq_regularized_4th_ord_d2q9
bgk_hybridrecursiveregularizedcorr_d2q9 calls f_f_eq_regularized_4th_ord_d2q9
bgk_projectedrecursiveregularized_d2q9 calls f_f_eq_regularized_4th_ord_d2q9
bgk_recursiveregularized_d2q9 calls f_f_eq_regularized_4th_ord_d2q9