f_f_eq_regularized_2nd_ord_d3q19 – Musubi
f_f_eq_regularized_2nd_ord_d3q19 Subroutine
95 statements
Source File
private pure subroutine f_f_eq_regularized_2nd_ord_d3q19(weight, rho, u_x, u_y, u_z, feq, f1, a12xx, a12yy, a12zz, a12xy, a12xz, a12yz)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: weight(QQ)
weights of the stencil
real(kind=rk), intent(in) :: rho
density, velocity components
real(kind=rk), intent(in) :: u_x
real(kind=rk), intent(in) :: u_y
real(kind=rk), intent(in) :: u_z
real(kind=rk), intent(out) :: feq(QQ)
equilibrium pdf and full pdf
real(kind=rk), intent(out) :: f1(QQ)
real(kind=rk), intent(in) :: a12xx
coefficients of f1: a12xx, a12yy, a12xy, etc ...
real(kind=rk), intent(in) :: a12yy
coefficients of f1: a12xx, a12yy, a12xy, etc ...
real(kind=rk), intent(in) :: a12zz
coefficients of f1: a12xx, a12yy, a12xy, etc ...
real(kind=rk), intent(in) :: a12xy
coefficients of f1: a12xx, a12yy, a12xy, etc ...
real(kind=rk), intent(in) :: a12xz
coefficients of f1: a12xx, a12yy, a12xy, etc ...
real(kind=rk), intent(in) :: a12yz
coefficients of f1: a12xx, a12yy, a12xy, etc ...
Called by
Call graph
bgk_dualrelaxationtime_rr_d3q19 calls f_f_eq_regularized_2nd_ord_d3q19
bgk_regularized_d3q19 calls f_f_eq_regularized_2nd_ord_d3q19
f_f_eq_regularized_4th_ord_d3q19 calls f_f_eq_regularized_2nd_ord_d3q19
bgk_hybridrecursiveregularized_d3q19 calls f_f_eq_regularized_4th_ord_d3q19
bgk_hybridrecursiveregularizedcorr_d3q19 calls f_f_eq_regularized_4th_ord_d3q19
bgk_projectedrecursiveregularized_d3q19 calls f_f_eq_regularized_4th_ord_d3q19
bgk_recursiveregularized_d3q19 calls f_f_eq_regularized_4th_ord_d3q19