fillHelperElementsCoarseToFine – Musubi
fillHelperElementsCoarseToFine Subroutine
27 statements
Source File
public recursive subroutine fillHelperElementsCoarseToFine(scheme, general, physics, iLevel, minLevel, maxLevel)
Recursively fill all the helper elements (i.e. ghost, halo) with valid information from the fluid elements.
This step is required before each run of the simulation. It would be possible to fill also the helper elements with the initial conditions. However, we are only able to fill the fluid elements with valid data (restart files have no information about the helper elements)
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
containers for the scheme contains interpolation type
type(tem_general_type), intent(in) :: general
global parameters
type(mus_physics_type), intent(in) :: physics
integer, intent(in) :: iLevel
Level counter variable
integer, intent(in) :: minLevel
level range
integer, intent(in) :: maxLevel
level range
Calls
Called by
Call graph
fillhelperelementscoarsetofine calls fillhelperelementscoarsetofine, exchange_real, intpfromcoarser
mus_init_flow calls fillhelperelementscoarsetofine
mus_reset_aux calls fillhelperelementscoarsetofine
mus_harvesting calls fillhelperelementscoarsetofine
mus_initialize calls mus_init_flow
mus_perform_dynloadbal calls mus_reset_aux
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve