fill_blob_positions_gauss_prism – Musubi
fill_blob_positions_gauss_prism Subroutine
40 statements
Source File
public subroutine fill_blob_positions_gauss_prism(particleblob, positions, Nparticles)
Routine to initialize particle creator object with random positions inside a prism described by blob_prism type
Arguments
Type Intent Optional Attributes Name
type(mus_particle_blob_prism_type), intent(inout) :: particleblob
Particleblob type
type(grw_real2darray_type), intent(inout) :: positions
Positions array to append randomly created values to
integer, intent(in) :: Nparticles
Desired number of particles
Calls
Called by
Call graph
fill_blob_positions_gauss_prism calls append, init_particle_blob_prob, pick_random_position, rotate_positions, set_random_seed, translate_positions, val
init_particle_blob_prob calls init_particle_blob_prob_circle, init_particle_blob_prob_square
pick_random_position calls append, val, fill_bins, map_to_bin, normalize_probabilities, remove_elem_grw_real2darray, remove_elem_grw_realarray, tem_abort
rotate_positions calls rodriguez_rotation
fill_bins calls append, val
init_particle_blob_prob_circle calls append, fill_bins, normalize_probabilities, init, normcdf
init_particle_blob_prob_square calls append, fill_bins, normalize_probabilities, init, normcdf
normalize_probabilities calls val
remove_elem_grw_real2darray calls swap_grw_real2darray
remove_elem_grw_realarray calls swap_grw_realarray
rodriguez_rotation calls cross_product
normcdf calls cumnor
init_particle_creator_from_blob_prism calls fill_blob_positions_gauss_prism
mus_load_particles calls init_particle_creator_from_blob_prism
mus_initialize calls mus_load_particles
musubi calls mus_initialize