fill_cylinder – Musubi
fill_cylinder Subroutine
34 statements
Source File
public subroutine fill_cylinder(R, L, d, positions)
Fill_cylinder fills the dynamic array positions with coordinates of particles spaced a distance d apart inside a cylinder with faces z = 0 and z = L and radius R. For cylinders of different position and orientation, these coordinates can be transformed.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: R
Radius of the cylinder
real(kind=rk), intent(in) :: L
Length of the cylinder
real(kind=rk) :: d
Distance between particles
type(grw_real2darray_type), intent(inout) :: positions
Calls
Called by
Call graph
fill_cylinder calls append, init
init_particle_creator_from_blob calls fill_cylinder
mus_load_particles calls init_particle_creator_from_blob
mus_initialize calls mus_load_particles
musubi calls mus_initialize