finalize_BClist – Musubi
finalize_BClist Subroutine
67 statements
Source File
private subroutine finalize_BClist(scheme, proc, minLevel, maxLevel, nBCs)
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme information including fluid, boundary and flow information
type(tem_comm_env_type), intent(in) :: proc
mpi communication enviroment with mpi communicator
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
integer, intent(in) :: nBCs
Calls
Called by
Call graph
finalize_bclist calls mpi_allreduce, nghelems, offset, setfieldbcneigh, tem_abort
setfieldbcneigh calls nghelems, tem_CoordOfId, tem_FirstIdAtLevel, tem_IdOfCoord, tem_treeIDinTotal, val
mus_construct calls finalize_bclist
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve