find_particle_comm_procs4 – Musubi
find_particle_comm_procs4 Subroutine
97 statements
Source File
public subroutine find_particle_comm_procs4(prunedProcs, scheme, geometry, myRank, dpad)
find_particle_comm_procs generates a list of all processes we may need to communicate particle data with over the duration of the simulation. We only need to communicate this data for particles on our rank which also exist on other processes. This means we will never communicate with processes whose domains are not within one particle diameter of our domain. This is the key assumption used to generate the list of procs Hence the padding distance dpad should be set to the largest particle diameter in the simulation
Arguments
Type Intent Optional Attributes Name
type(dyn_intarray_type) :: prunedProcs
Dynamic array of procs which we will store the found procs in
type(mus_scheme_type), intent(in) :: scheme
Scheme for access to level descriptor
type(mus_geom_type), intent(in) :: geometry
Geometry information to determine TreeIDs of elements 'covered' by particle
integer, intent(in) :: myRank
This process's rank
real(kind=rk) :: dpad
Padding distance
Calls
Called by
Call graph
find_particle_comm_procs4 calls append, findpartitionoftreeid, getbaryofcoord, getcartesianstencilindices, getneighborcoord, getsearchboxlimits, pruneparticlecommprocs, property, tem_CoordOfId, tem_FirstIdAtLevel, tem_IdOfCoord, total
findpartitionoftreeid calls part_first, part_last
getcartesianstencilindices calls tem_stencil_findIndexOfDir
getsearchboxlimits calls boundary_id, coordlocalonmyrank
pruneparticlecommprocs calls append, mpi_irecv, mpi_isend, mpi_waitall
coordlocalonmyrank calls tem_IdOfCoord, tem_PosOfId
mus_particles_initialize_communication calls find_particle_comm_procs4
mus_particles_initialize calls mus_particles_initialize_communication
mus_initialize calls mus_particles_initialize
musubi calls mus_initialize