findPartitionOfTreeID – Musubi
findPartitionOfTreeID Subroutine
25 statements
Source File
public subroutine findPartitionOfTreeID(sTreeID, geometry, procs, nProcs, outProc, procIndex)
Routine to find the process a certain treeID is on. Looks in the ranks in the array of argument procs Returns the INDEX of the found proc in this array Example: procs = [4 8 7] and we find our treeID on rank 8 will return procIndex = 2
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: sTreeID
TreeID to look for
type(mus_geom_type), intent(in) :: geometry
Geometry to look in
integer, intent(in), optional :: procs(:)
Only look on these ranks (look in all ranks if omitted)
integer, intent(in) :: nProcs
Number of elements in procs
integer, intent(out) :: outProc
Process which the treeID is on
integer, intent(out) :: procIndex
Index of that process
Calls
Called by
Call graph
findpartitionoftreeid calls part_first, part_last
find_particle_comm_procs4 calls findpartitionoftreeid
updateexistsonproc calls findpartitionoftreeid
updateexistsonproc_dps calls findpartitionoftreeid
updateparticleowner calls findpartitionoftreeid
initparticle_dps calls updateexistsonproc_dps, updateparticleowner
maptolattice_dps calls updateexistsonproc_dps, updateparticleowner
mus_particles_initialize_communication calls find_particle_comm_procs4
updateexclusionlist calls updateexistsonproc, updateparticleowner
check_and_create_new_particles_dps calls initparticle_dps
createnewparticle_dps calls initparticle_dps
initparticle_mem calls updateexclusionlist
mapparticlestolattice_dps calls initparticle_dps, maptolattice_dps
maptolattice calls updateexclusionlist
mus_particles_initialize calls mus_particles_initialize_communication
mus_particles_mapping_dps calls initparticle_dps, maptolattice_dps
check_and_create_new_particles_mem calls initparticle_mem
check_particles_dps calls check_and_create_new_particles_dps
create_particles_dps calls createnewparticle_dps
createnewparticle_mem calls initparticle_mem
demsubcycles_dps calls mapparticlestolattice_dps
demsubcycles_dps_onewaycoupled calls mapparticlestolattice_dps
mus_initialize calls mus_particles_initialize
mus_particles_applyhydrodynamicforces_mem calls initparticle_mem
mus_particles_mapping_mem calls maptolattice