generateElemListLine – Musubi
generateElemListLine Subroutine
27 statements
Source File
public subroutine generateElemListLine(dir, xstart, length, scheme, geometry, elemList)
Debugging routine to create a list of elements along a line so that the properties of these elements can be printed
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: dir(3)
real(kind=rk), intent(in) :: xstart(3)
real(kind=rk), intent(in) :: length
type(mus_scheme_type), intent(in) :: scheme
scheme
type(mus_geom_type), intent(in) :: geometry
geometry
type(dyn_intarray_type), intent(inout) :: elemList
Calls
Called by
Call graph
generateelemlistline calls append, empty, tem_CoordOfReal, tem_IdOfCoord, tem_PosOfId
test_generateelemlistline calls generateelemlistline