get_boundaryRatio – Musubi
get_boundaryRatio Function
4 statements
Source File
public function get_boundaryRatio() result(ratio)
Arguments
None
Return Value real(kind=rk)
Calls
Called by
Call graph
get_boundaryratio calls get_boundarytime, get_mainlooptime
get_boundarytime calls get_boundarytime_byid, get_boundarytime_total
get_mainlooptime calls tem_getTimerVal
get_boundarytime_byid calls tem_getTimerVal
get_boundarytime_total calls get_boundarytime
dump_timing calls get_boundaryratio
mus_perf_measure calls dump_timing