get_intpFromFinerRatio_total – Musubi
get_intpFromFinerRatio_total Function
4 statements
Source File
private function get_intpFromFinerRatio_total() result(ratio)
Arguments
None
Return Value real(kind=rk)
Calls
Called by
Call graph
get_intpfromfinerratio_total calls get_intpfromfinertime, get_mainlooptime
get_intpfromfinertime calls get_intpfromfinertime_atlevel, get_intpfromfinertime_total
get_mainlooptime calls tem_getTimerVal
get_intpfromfinertime_atlevel calls tem_getTimerVal
get_intpfromfinertime_total calls tem_getTimerVal
get_intpfromfinerratio calls get_intpfromfinerratio_total