get_intpRatio – Musubi
get_intpRatio Function
4 statements
Source File
public function get_intpRatio() result(ratio)
Arguments
None
Return Value real(kind=rk)
Calls
Called by
Call graph
get_intpratio calls get_intptime, get_mainlooptime
get_intptime calls get_intpfromcoarsertime, get_intpfromfinertime
get_mainlooptime calls tem_getTimerVal
get_intpfromcoarsertime calls get_intpfromcoarsertime_atlevel, get_intpfromcoarsertime_total
get_intpfromfinertime calls get_intpfromfinertime_atlevel, get_intpfromfinertime_total
get_intpfromcoarsertime_atlevel calls tem_getTimerVal
get_intpfromcoarsertime_total calls get_intpfromcoarsertime
get_intpfromfinertime_atlevel calls tem_getTimerVal
get_intpfromfinertime_total calls tem_getTimerVal
dump_timing calls get_intpratio
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure
musubi calls mus_finalize, mus_solve