get_computeTime_atLevel – Musubi
get_computeTime_atLevel Function
5 statements
Source File
private function get_computeTime_atLevel(level) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Calls
Called by
Call graph
get_computetime_atlevel calls tem_getTimerVal
get_computetime calls get_computetime_atlevel, get_computetime_total
dump_bc_timing calls get_computetime
get_computeratio_atlevel calls get_computetime
get_computeratio_total calls get_computetime
get_computetime_total calls get_computetime
mus_getweights calls get_computetime
mus_perf_measure calls get_computetime
get_computeratio calls get_computeratio_atlevel, get_computeratio_total
mus_balance calls mus_getweights
mus_finalize calls mus_getweights, mus_perf_measure
mus_solve calls mus_perf_measure
dump_timing calls get_computeratio
mus_perform_dynloadbal calls mus_balance
musubi calls mus_finalize, mus_solve