get_computeRatio_total – Musubi
get_computeRatio_total Function
4 statements
Source File
private function get_computeRatio_total() result(ratio)
Arguments
None
Return Value real(kind=rk)
Calls
Called by
Call graph
get_computeratio_total calls get_computetime, get_mainlooptime
get_computetime calls get_computetime_atlevel, get_computetime_total
get_mainlooptime calls tem_getTimerVal
get_computetime_atlevel calls tem_getTimerVal
get_computetime_total calls get_computetime
get_computeratio calls get_computeratio_total
dump_timing calls get_computeratio
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure