get_stageTime – Musubi
get_stageTime Function
9 statements
Source File
public function get_stageTime(ii) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ii
Return Value real(kind=rk)
Calls
Called by
Call graph
get_stagetime calls get_mainlooptime, tem_getTimerVal
get_mainlooptime calls tem_getTimerVal
get_stageratio calls get_stagetime
dump_level_timing calls get_stageratio
mus_finalize calls dump_level_timing
mus_solve calls dump_level_timing
musubi calls mus_finalize, mus_solve