get_stageRatio – Musubi
get_stageRatio Function
5 statements
Source File
public function get_stageRatio(ii) result(ratio)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ii
Return Value real(kind=rk)
Calls
Called by
Call graph
get_stageratio calls get_mainlooptime, get_stagetime
get_mainlooptime calls tem_getTimerVal
get_stagetime calls get_mainlooptime, tem_getTimerVal
dump_level_timing calls get_stageratio
mus_finalize calls dump_level_timing
mus_solve calls dump_level_timing
musubi calls mus_finalize, mus_solve