get_communicateTime – Musubi
get_communicateTime Function
10 statements
Source File
public function get_communicateTime() result(time)
Arguments
None
Return Value real(kind=rk)
Calls
Called by
Call graph
get_communicatetime calls tem_getTimerVal
dump_bc_timing calls get_communicatetime
get_communicateratio calls get_communicatetime
mus_perf_measure calls get_communicatetime, dump_timing
dump_timing calls get_communicateratio
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure
musubi calls mus_finalize, mus_solve