get_bcBufferRatio_atLevel – Musubi
get_bcBufferRatio_atLevel Function
5 statements
Source File
private function get_bcBufferRatio_atLevel(level) result(ratio)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Calls
Called by
Call graph
get_bcbufferratio_atlevel calls get_bcbuffertime, get_mainlooptime
get_bcbuffertime calls get_bcbuffertime_atlevel, get_bcbuffertime_total
get_mainlooptime calls tem_getTimerVal
get_bcbuffertime_atlevel calls tem_getTimerVal
get_bcbuffertime_total calls get_bcbuffertime
get_bcbufferratio calls get_bcbufferratio_atlevel
dump_timing calls get_bcbufferratio
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure