get_momentVector – Musubi
get_momentVector Function
7 statements
Source File
public pure function get_momentVector(QQ, cxDir, expX) result(mom)
get the moment vector to calculate the moment from the pdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: QQ
integer, intent(in) :: cxDir(3,QQ)
integer, intent(in) :: expX(3)
exponents of the moments
Return Value real(kind=rk), (QQ)
moment vector
Calls
Called by
Call graph
get_momentvector calls mus_imomvector
get_moment calls get_momentvector
init_transformation_matrix_fluid calls get_momentvector
init_transformation_matrix_ms calls get_momentvector
mus_init_moments calls init_transformation_matrix_fluid, init_transformation_matrix_ms
mus_init_scheme calls mus_init_moments
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme