get_auxTime_atLevel – Musubi
get_auxTime_atLevel Function
5 statements
Source File
private function get_auxTime_atLevel(level) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Calls
Called by
Call graph
get_auxtime_atlevel calls tem_getTimerVal
get_auxtime calls get_auxtime_atlevel, get_auxtime_total
dump_timing calls get_auxtime
get_auxtime_total calls get_auxtime
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure