get_communicateRatio – Musubi
get_communicateRatio Function
4 statements
Source File
public function get_communicateRatio() result(ratio)
Arguments
None
Return Value real(kind=rk)
Calls
Called by
Call graph
get_communicateratio calls get_communicatetime, get_mainlooptime
get_communicatetime calls tem_getTimerVal
get_mainlooptime calls tem_getTimerVal
dump_timing calls get_communicateratio
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure
musubi calls mus_finalize, mus_solve