get_computeRatio_atLevel – Musubi
get_computeRatio_atLevel Function
5 statements
Source File
private function get_computeRatio_atLevel(level) result(ratio)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Calls
Called by
Call graph
get_computeratio_atlevel calls get_computetime, get_mainlooptime
get_computetime calls get_computetime_atlevel, get_computetime_total
get_mainlooptime calls tem_getTimerVal
get_computetime_atlevel calls tem_getTimerVal
get_computetime_total calls get_computetime
get_computeratio calls get_computeratio_atlevel
dump_timing calls get_computeratio
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure