get_mainLoopTime – Musubi
get_mainLoopTime Function
4 statements
Source File
public function get_mainLoopTime() result(time)
Arguments
None
Return Value real(kind=rk)
Calls
Called by
Call graph
get_mainlooptime calls tem_getTimerVal
dump_bc_timing calls get_mainlooptime
dump_level_timing calls get_mainlooptime, get_stageratio
get_bcbufferratio_atlevel calls get_mainlooptime
get_bcbufferratio_total calls get_mainlooptime
get_boundaryratio calls get_mainlooptime
get_communicateratio calls get_mainlooptime
get_computeratio_atlevel calls get_mainlooptime
get_computeratio_total calls get_mainlooptime
get_intpfromcoarserratio_atlevel calls get_mainlooptime
get_intpfromcoarserratio_total calls get_mainlooptime
get_intpfromfinerratio_atlevel calls get_mainlooptime
get_intpfromfinerratio_total calls get_mainlooptime
get_intpratio calls get_mainlooptime
get_stageratio calls get_mainlooptime, get_stagetime
get_stagetime calls get_mainlooptime
mus_perf_measure calls get_mainlooptime, dump_timing
get_bcbufferratio calls get_bcbufferratio_atlevel, get_bcbufferratio_total
get_computeratio calls get_computeratio_atlevel, get_computeratio_total
get_intpfromcoarserratio calls get_intpfromcoarserratio_atlevel, get_intpfromcoarserratio_total
get_intpfromfinerratio calls get_intpfromfinerratio_atlevel, get_intpfromfinerratio_total
dump_timing calls get_boundaryratio, get_communicateratio, get_intpratio, get_bcbufferratio, get_computeratio
mus_finalize calls dump_level_timing, mus_perf_measure
mus_solve calls dump_level_timing, mus_perf_measure
musubi calls mus_finalize, mus_solve