get_intpFromCoarserTime_atLevel – Musubi
get_intpFromCoarserTime_atLevel Function
5 statements
Source File
private function get_intpFromCoarserTime_atLevel(level) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Calls
Called by
Call graph
get_intpfromcoarsertime_atlevel calls tem_getTimerVal
get_intpfromcoarsertime calls get_intpfromcoarsertime_atlevel, get_intpfromcoarsertime_total
get_intpfromcoarserratio_atlevel calls get_intpfromcoarsertime
get_intpfromcoarserratio_total calls get_intpfromcoarsertime
get_intpfromcoarsertime_total calls get_intpfromcoarsertime
get_intptime calls get_intpfromcoarsertime
mus_getweights calls get_intpfromcoarsertime
get_intpfromcoarserratio calls get_intpfromcoarserratio_atlevel, get_intpfromcoarserratio_total
get_intpratio calls get_intptime
mus_balance calls mus_getweights
mus_finalize calls mus_getweights
dump_timing calls get_intpratio
mus_perform_dynloadbal calls mus_balance
musubi calls mus_finalize