get_relaxTime_total – Musubi
get_relaxTime_total Function
8 statements
Source File
private function get_relaxTime_total() result(time)
Arguments
None
Return Value real(kind=rk)
Calls
Called by
Call graph
get_relaxtime_total calls get_relaxtime
get_relaxtime calls get_relaxtime_total, get_relaxtime_atlevel
get_relaxtime_atlevel calls tem_getTimerVal
dump_timing calls get_relaxtime
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure