get_boundaryTime_byID – Musubi
get_boundaryTime_byID Function
9 statements
Source File
private function get_boundaryTime_byID(bcID) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: bcID
Return Value real(kind=rk)
Calls
Called by
Call graph
get_boundarytime_byid calls tem_getTimerVal
get_boundarytime calls get_boundarytime_byid, get_boundarytime_total
dump_bc_timing calls get_boundarytime
get_boundaryratio calls get_boundarytime
get_boundarytime_total calls get_boundarytime
mus_bc_timing calls get_boundarytime
mus_getweights calls get_boundarytime
dump_timing calls get_boundaryratio
mus_balance calls mus_getweights
mus_perf_measure calls dump_timing
mus_perform_dynloadbal calls mus_balance