get_relaxTime_atLevel – Musubi
get_relaxTime_atLevel Function
5 statements
Source File
private function get_relaxTime_atLevel(level) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Calls
Called by
Call graph
get_relaxtime_atlevel calls tem_getTimerVal
get_relaxtime calls get_relaxtime_atlevel, get_relaxtime_total
dump_timing calls get_relaxtime
get_relaxtime_total calls get_relaxtime
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure