get_bcBufferTime_atLevel – Musubi
get_bcBufferTime_atLevel Function
5 statements
Source File
private function get_bcBufferTime_atLevel(level) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Calls
Called by
Call graph
get_bcbuffertime_atlevel calls tem_getTimerVal
get_bcbuffertime calls get_bcbuffertime_atlevel, get_bcbuffertime_total
dump_bc_timing calls get_bcbuffertime
get_bcbufferratio_atlevel calls get_bcbuffertime
get_bcbufferratio_total calls get_bcbuffertime
get_bcbuffertime_total calls get_bcbuffertime
mus_getweights calls get_bcbuffertime
get_bcbufferratio calls get_bcbufferratio_atlevel, get_bcbufferratio_total
mus_balance calls mus_getweights
mus_finalize calls mus_getweights
dump_timing calls get_bcbufferratio
mus_perform_dynloadbal calls mus_balance
musubi calls mus_finalize