getBaryOfCoord – Musubi
getBaryOfCoord Function
11 statements
Source File
public pure function getBaryOfCoord(coord, origin, dx) result(bary)
Convenience function to get barycenter of integer coordinate
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: coord(3)
real(kind=rk), intent(in) :: origin(3)
real(kind=rk), intent(in) :: dx
Return Value real(kind=rk), (3)
Called by
Call graph
addparticlesourcetoauxfield_dps calls getbaryofcoord
distributeparticlevolume calls getbaryofcoord
dumpdata calls getbaryofcoord
find_particle_comm_procs4 calls getbaryofcoord
getprocessboundingbox calls getbaryofcoord
incrementauxfield_dps calls getbaryofcoord
interpolatefluidprops calls getbaryofcoord
interpolatefluidprops_onewaycoupled calls getbaryofcoord
interpolatefluidprops_onewaycoupled_old calls getbaryofcoord
recalculate_auxfield_dps calls getbaryofcoord
test_generateelemlistline calls getbaryofcoord
transfermomentumtofluid_dps calls getbaryofcoord
transfermomentumtofluid_dps_twoway calls getbaryofcoord
updateexclusionlist calls getbaryofcoord
demsubcycles_dps calls incrementauxfield_dps, recalculate_auxfield_dps
initparticle_mem calls updateexclusionlist
maptolattice calls updateexclusionlist
mus_particles_dps_interpolatefluidproperties_onewaycoupled calls interpolatefluidprops_onewaycoupled_old
mus_particles_initialize_communication calls find_particle_comm_procs4
mus_particles_updatefluidvolumefraction calls distributeparticlevolume
test_interpolation_delta_dps_d2q9 calls interpolatefluidprops
test_interpolation_delta_dps_d3q19 calls interpolatefluidprops
check_and_create_new_particles_mem calls initparticle_mem
check_particles_dps calls mus_particles_updatefluidvolumefraction
createnewparticle_mem calls initparticle_mem
mus_particles_applyhydrodynamicforces_dps_onewaycoupled calls mus_particles_dps_interpolatefluidproperties_onewaycoupled
mus_particles_applyhydrodynamicforces_mem calls initparticle_mem
mus_particles_initialize calls mus_particles_initialize_communication, mus_particles_updatefluidvolumefraction
mus_particles_mapping_mem calls maptolattice
mus_particles_move_dps calls demsubcycles_dps