getDensity_forPdfSubset – Musubi
getDensity_forPdfSubset Function
11 statements
Source File
private pure function getDensity_forPdfSubset(subset, stencil, varPos) result(res)
Calculate the density of a given subset of pdfs vector (sum up all values)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: subset(:)
type(tem_stencilHeader_type), intent(in) :: stencil
integer, intent(in) :: varPos(:)
Return Value real(kind=rk)
Called by
Call graph
getdensity calls getdensity_forpdfsubset
getequilibrium_forpdfsubset calls getdensity_forpdfsubset
getequilibrium calls getequilibrium_forpdfsubset, getequilibrium_forelemfromstate
getequilibrium_forelemfromstate calls getdensity
mus_applyforce_x calls getdensity
mus_inamuro_ibm calls mus_applyforce_x
mus_turbvisc_smagorinsky_fromprecolpdf_2d calls getequilibrium
mus_turbvisc_smagorinsky_fromprecolpdf_3d calls getequilibrium
do_fast_singlelevel calls mus_inamuro_ibm