getEquilibrium_forElemfromState – Musubi
getEquilibrium_forElemfromState Function
19 statements
Source File
private pure function getEquilibrium_forElemfromState(state, elem, layout, varPos, nScalars, neigh) result(equil)
Calculate the equilibrium distribution function in all directions
The equilibrim distribution function is:\n \n where is the weight in each direction,\n is the macroscopic value of density,\n is the speed of sound,\n is the lattice unit velocity in each direction,\n is the macroscopic value of velocity.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:)
integer, intent(in) :: elem
type(mus_scheme_layout_type), intent(in) :: layout
integer, intent(in) :: varPos(:)
integer, intent(in) :: nScalars
integer, intent(in) :: neigh(:)
Return Value real(kind=rk), (layout%fStencil%QQ)
Calls
Called by
Call graph
getequilibrium_forelemfromstate calls cxdirrk, getdensity, getvelocity
getdensity calls getdensity_forelemfromstate, getdensity_forpdfsubset
getvelocity calls getvelocity_forelemfromstate_noforce, getvelocity_forpdfsubset
getequilibrium calls getequilibrium_forelemfromstate
mus_turbvisc_smagorinsky_fromprecolpdf_2d calls getequilibrium
mus_turbvisc_smagorinsky_fromprecolpdf_3d calls getequilibrium