getEquilibrium_forPdfSubset – Musubi
getEquilibrium_forPdfSubset Function
16 statements
Source File
private pure function getEquilibrium_forPdfSubset(subset, layout, varPos) result(equil)
Calculate the equilibrium distribution function in all directions
The equilibrim distribution function is:\n \n where is the weight in each direction,\n is the macroscopic value of density,\n is the speed of sound,\n is the lattice unit velocity in each direction,\n is the macroscopic value of velocity.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: subset(:)
type(mus_scheme_layout_type), intent(in) :: layout
integer, intent(in) :: varPos(:)
Return Value real(kind=rk), (layout%fStencil%QQ)
Calls
Called by
Call graph
getequilibrium_forpdfsubset calls cxdirrk, getdensity_forpdfsubset, getvelocity_forpdfsubset
getequilibrium calls getequilibrium_forpdfsubset
mus_turbvisc_smagorinsky_fromprecolpdf_2d calls getequilibrium
mus_turbvisc_smagorinsky_fromprecolpdf_3d calls getequilibrium