getEqByDensVel – Musubi
getEqByDensVel Function
13 statements
Source File
public pure function getEqByDensVel(dens, vel, layout) result(equil)
Calculate the equilibrium distribution function in all directions
The equilibrium distribution function is:\n
where is the weight in each direction,\n is the macroscopic value of density,\n is the speed of sound,\n is the lattice unit velocity in each direction,\n is the macroscopic value of velocity.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: dens
real(kind=rk), intent(in) :: vel(3)
type(mus_scheme_layout_type), intent(in) :: layout
Return Value real(kind=rk), (layout%fStencil%QQ)
Calls
Called by
Call graph
geteqbydensvel calls cxdirrk
getequilibrium calls geteqbydensvel
mus_turbvisc_smagorinsky_fromprecolpdf_2d calls getequilibrium
mus_turbvisc_smagorinsky_fromprecolpdf_3d calls getequilibrium