getFieldVariable_scalar – Musubi
getFieldVariable_scalar Function
19 statements
Source File
private function getFieldVariable_scalar(conf, varLabel, varName, fieldVar, fieldProp) result(val)
Get the field variable name for given field type from a given solver specific character handle.
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
handle of the solver specific character
character(len=*), intent(in) :: varLabel
complete variable label (prefix + pure variable name)
character(len=*), intent(in) :: varName
pure variable name (e.g. density)
character(len=*), intent(in) :: fieldVar
required name of the field variable
character(len=*), intent(in) :: fieldProp
Which field type does the field variable belong to. Example: 'fluid'/'species'
Return Value real(kind=rk)
val to be returned
Calls
Called by
Call graph
getfieldvariable_scalar calls aot_get_val, aot_table_close, aot_table_open
getfieldvariable calls getfieldvariable_scalar