getFieldVariable_array – Musubi
getFieldVariable_array Function
22 statements
Source File
private function getFieldVariable_array(conf, varLabel, varName, fieldVar, fieldProp, nVals) result(val)
Get the field variable name for given field type from a given solver specific character handle.
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
handle of the solver specific character
character(len=*), intent(in) :: varLabel
complete variable label (prefix + pure variable name)
character(len=*), intent(in) :: varName
pure variable name (e.g. density)
character(len=*), intent(in) :: fieldVar
required name of the field variable
character(len=*), intent(in) :: fieldProp
Which field type does the field variable belong to. Example: 'fluid'/'species'
integer, intent(in) :: nVals
number of entries in the array to read out
Return Value real(kind=rk), (nVals)
val to be returned
Calls
Called by
Call graph
getfieldvariable_array calls aot_get_val, aot_table_close, aot_table_open
getfieldvariable calls getfieldvariable_array