getIndexOfCoordInTotal – Musubi
getIndexOfCoordInTotal Subroutine
14 statements
Source File
public subroutine getIndexOfCoordInTotal(scheme, coord, ldPos)
Get the index in the total list of a specified integer coordinate
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
integer, intent(in) :: coord(4)
integer, intent(out) :: ldPos
Calls
Called by
Call graph
getindexofcoordintotal calls tem_IdOfCoord, tem_PosOfId
calcvelocityandpressuregradient calls getindexofcoordintotal
calcvelocityandpressuregradient_onewaycoupled calls getindexofcoordintotal
calcvelocityandpressuregradient_onewaycoupled_old calls getindexofcoordintotal
mus_particles_dps_interpolatefluidproperties_onewaycoupled calls calcvelocityandpressuregradient_onewaycoupled_old
test_calcvelocityandpressuregradient_dps calls calcvelocityandpressuregradient
mus_particles_applyhydrodynamicforces_dps_onewaycoupled calls mus_particles_dps_interpolatefluidproperties_onewaycoupled