getNEq_acoustic – Musubi
getNEq_acoustic Function
Jiaxing Qi
23 statements
Source File
public function getNEq_acoustic(layout, omega, Sxx) result(nEq)
Setting the non-equilibrium part based on the acoustic scaling
The non-equilibirium part of pdf is computed from strain rate tensor by \cite Latt:2011vr where is Frobenius inner product. and is the strain rate tensor
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_layout_type), intent(in) :: layout
real(kind=rk), intent(in) :: omega
real(kind=rk), intent(in) :: Sxx(3,3)
strain rate tensor
Return Value real(kind=rk), (layout%fStencil%QQ)
Calls
Called by
Call graph
getneq_acoustic calls cxdirrk, convprepost
mus_init_pdf calls getneq_acoustic
mus_init_byic calls mus_init_pdf
mus_init_flow calls mus_init_byic
mus_initialize calls mus_init_flow