getNEq_diffusive – Musubi
getNEq_diffusive Function
Jiaxing Qi
20 statements
Source File
public function getNEq_diffusive(layout, omega, Sxx) result(nEq)
Calculate the non-equilibrium part of pdf from strain rate tensor based on the diffusive scaling
According to \cite Junk:2005cr \n The non-equilibrium part of pdf is set by \n where is the viscosity, is the strain rate tensor and and is the number of dimension. \n Notice here that strain rate tensor above has to be a traceless tensor, i.e. . In current implementation, the above equation is slightly modified so that the strain rate tensor is not required to be traceless anymore. In this way, calculated by this routine can recover the input strain rate tensor no matter it is traceless or not.\n Specificly the in above equation is modified slightly, i.e. This routine has a unit test program utest/mus_fNeq_diffusive_test
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_layout_type), intent(in) :: layout
real(kind=rk), intent(in) :: omega
real(kind=rk), intent(in) :: Sxx(3,3)
Strain rate tensor. It is a symmetric 3x3 matrix
Return Value real(kind=rk), (layout%fStencil%QQ)
Calls
Called by
Call graph
getneq_diffusive calls cxdirrk, convprepost
mus_init_pdf calls getneq_diffusive
mus_init_byic calls mus_init_pdf
mus_init_flow calls mus_init_byic
mus_initialize calls mus_init_flow