getNeighborCoord – Musubi
getNeighborCoord Function
43 statements
Source File
public function getNeighborCoord(coord, nx, ny, nz, boundaryData) result(neighborCoord)
getNeighborCoord gets the coordinate of the element offset from input coord by (nx,ny,nz) while taking into account periodicity
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: coord(4)
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: nz
type(mus_particle_boundarydata_type), intent(in) :: boundaryData
Return Value integer, (4)
Called by
Call graph
calcvelocityandpressuregradient_onewaycoupled_old calls getneighborcoord
find_particle_comm_procs4 calls getneighborcoord
interpolatefluidprops_onewaycoupled_old calls getneighborcoord
updateexclusionlist calls getneighborcoord, updateexistsonproc
updateexistsonproc calls getneighborcoord
initparticle_mem calls updateexclusionlist
maptolattice calls updateexclusionlist
mus_particles_dps_interpolatefluidproperties_onewaycoupled calls calcvelocityandpressuregradient_onewaycoupled_old, interpolatefluidprops_onewaycoupled_old
mus_particles_initialize_communication calls find_particle_comm_procs4
check_and_create_new_particles_mem calls initparticle_mem
createnewparticle_mem calls initparticle_mem
mus_particles_applyhydrodynamicforces_dps_onewaycoupled calls mus_particles_dps_interpolatefluidproperties_onewaycoupled
mus_particles_applyhydrodynamicforces_mem calls initparticle_mem
mus_particles_initialize calls mus_particles_initialize_communication
mus_particles_mapping_mem calls maptolattice
check_particles_mem calls check_and_create_new_particles_mem
create_particles_mem calls createnewparticle_mem
mus_initialize calls mus_particles_initialize