getNonEqFac_intp_fine_to_coarse – Musubi
getNonEqFac_intp_fine_to_coarse Function
6 statements
Source File
public pure function getNonEqFac_intp_fine_to_coarse(omegaC, omegaF) result(fac)
Calculate the conversion factor to convert nonEq pdfs from fine to coarse.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: omegaC
real(kind=rk), intent(in) :: omegaF
Return Value real(kind=rk)
Calls
Called by
Call graph
getnoneqfac_intp_fine_to_coarse calls getnoneqfac_intp
fillmyghostsfromfiner_avg2d_feq_fneq calls getnoneqfac_intp_fine_to_coarse
fillmyghostsfromfiner_avg_feq_fneq calls getnoneqfac_intp_fine_to_coarse
fillmyghostsfromfiner_avgles_feq_fneq calls getnoneqfac_intp_fine_to_coarse