getProcessBoundingBox – Musubi
getProcessBoundingBox Subroutine
73 statements
Source File
public subroutine getProcessBoundingBox(scheme, geometry, boundingBox)
Routine to find the bounding box of the part of the spatial domain on this process
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
Scheme for access to level descriptor
type(mus_geom_type), intent(in) :: geometry
Geometry information to determine TreeIDs of elements 'covered' by particle
real(kind=rk), intent(out) :: boundingBox(6)
Calls
Call graph
getprocessboundingbox calls origin, getbaryofcoord, property, tem_CoordOfId, tem_FirstIdAtLevel, total