getPosOfCoord – Musubi
getPosOfCoord Function
13 statements
Source File
public function getPosOfCoord(coord, scheme) result(ldPos)
Get the position in the levelDesc%total list of an element with integer coordinate coord. This routine returns ldPos <= 0 if the element could not be found on this process.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: coord(4)
type(mus_scheme_type), intent(in) :: scheme
Return Value integer
Calls
Called by
Call graph
getposofcoord calls tem_IdOfCoord, tem_PosOfId
addparticlesourcetoauxfield_dps calls getposofcoord
distributeparticlevolume calls getposofcoord
incrementauxfield_dps calls getposofcoord
initparticle_dps calls getposofcoord, updatecoordoforigin_dps
interpolatefluidprops calls getposofcoord
interpolatefluidprops_onewaycoupled calls getposofcoord
recalculate_auxfield_dps calls getposofcoord
transfermomentumtofluid_dps calls getposofcoord
transfermomentumtofluid_dps_twoway calls getposofcoord
updatecoordoforigin_dps calls getposofcoord
check_and_create_new_particles_dps calls initparticle_dps, create_particles_dps
createnewparticle_dps calls initparticle_dps
demsubcycles_dps calls incrementauxfield_dps, recalculate_auxfield_dps, mapparticlestolattice_dps
mapparticlestolattice_dps calls initparticle_dps, maptolattice_dps
maptolattice_dps calls updatecoordoforigin_dps
mus_particles_mapping_dps calls initparticle_dps, maptolattice_dps
mus_particles_updatefluidvolumefraction calls distributeparticlevolume
test_interpolation_delta_dps_d2q9 calls interpolatefluidprops
test_interpolation_delta_dps_d3q19 calls interpolatefluidprops
check_particles_dps calls check_and_create_new_particles_dps, mus_particles_updatefluidvolumefraction
create_particles_dps calls createnewparticle_dps
demsubcycles_dps_onewaycoupled calls mapparticlestolattice_dps
mus_particles_initialize calls mus_particles_updatefluidvolumefraction
mus_particles_move_dps calls demsubcycles_dps
mus_initialize calls mus_particles_initialize
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled