getSearchBoxLimits – Musubi
getSearchBoxLimits Subroutine
66 statements
Source File
public subroutine getSearchBoxLimits(elemCoord, elemPos, scheme, geometry, dirs, myRank, ndpad, lims)
getSearchBoxLimits is used in find_particle_comm_procs to determine where the non-local elements we have to check the owner proc of are.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: elemCoord(4)
Coordinate to get search box around
integer, intent(in) :: elemPos
Element position in total list
type(mus_scheme_type), intent(in) :: scheme
Scheme for access to level descriptor
type(mus_geom_type), intent(in) :: geometry
Geometry information to determine whether halo has boundaries
integer, intent(in) :: dirs(6)
indices of cartesian directions [-x +x -y +y -z +z] in stencil
integer, intent(in) :: myRank
This procs rank
integer, intent(in) :: ndpad
Length of the search box in the directions where there are no local elements
integer, intent(out) :: lims(6)
lims = [xmin, xmax, ymin, ymax, zmin, zmax]
Calls
Called by
Call graph
getsearchboxlimits calls boundary_id, coordlocalonmyrank
coordlocalonmyrank calls tem_IdOfCoord, tem_PosOfId
find_particle_comm_procs4 calls getsearchboxlimits
mus_particles_initialize_communication calls find_particle_comm_procs4
mus_particles_initialize calls mus_particles_initialize_communication
mus_initialize calls mus_particles_initialize