getVelocity_forElemFromState_noForce – Musubi
getVelocity_forElemFromState_noForce Function
19 statements
Source File
private pure function getVelocity_forElemFromState_noForce(state, elem, stencil, varPos, nScalars) result(vel)
Calculate the velocity in all 3 directions from the element indicated (elem), reading the pdf (state information) from the state array. state array includes all the pdfs of all elements. The access to the state array has to be done via the generic access macro IDX, as we want to access post-collision values.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:)
integer, intent(in) :: elem
element index, for which to calc velocity
type(tem_stencilHeader_type), intent(in) :: stencil
integer, intent(in) :: varPos(:)
integer, intent(in) :: nScalars
Return Value real(kind=rk), (3)
Called by
Call graph
getvelocity calls getvelocity_forelemfromstate_noforce
getequilibrium_forelemfromstate calls getvelocity
mus_inamuroini calls getvelocity
getequilibrium calls getequilibrium_forelemfromstate
mus_inamuro_ibm calls mus_inamuroini
do_fast_singlelevel calls mus_inamuro_ibm
mus_turbvisc_smagorinsky_fromprecolpdf_2d calls getequilibrium
mus_turbvisc_smagorinsky_fromprecolpdf_3d calls getequilibrium