getVelocity_forPdfSubset – Musubi
getVelocity_forPdfSubset Function
15 statements
Source File
private pure function getVelocity_forPdfSubset(subset, stencil, varPos) result(vel)
Calculate the velocity in all 3 directions from a subset given, ordered according to the stencil
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: subset(:)
type(tem_stencilHeader_type), intent(in) :: stencil
integer, intent(in) :: varPos(:)
Return Value real(kind=rk), (3)
Called by
Call graph
getvelocity calls getvelocity_forpdfsubset
getequilibrium_forpdfsubset calls getvelocity_forpdfsubset
getequilibrium calls getequilibrium_forpdfsubset, getequilibrium_forelemfromstate
getequilibrium_forelemfromstate calls getvelocity
mus_inamuroini calls getvelocity
mus_inamuro_ibm calls mus_inamuroini
mus_turbvisc_smagorinsky_fromprecolpdf_2d calls getequilibrium
mus_turbvisc_smagorinsky_fromprecolpdf_3d calls getequilibrium
do_fast_singlelevel calls mus_inamuro_ibm