incrementAuxField_DPS – Musubi
incrementAuxField_DPS Subroutine
33 statements
Source File
public subroutine incrementAuxField_DPS(particle, interpolator, scheme, geometry, params, dt_DEM_lat)
Add momentum increments due to particles within DEM subcycles to the auxField
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: particle
Particle to interpolate fluid properties to
type(mus_particle_interpolator_type), intent(in) :: interpolator
interpolator object containing stencil and weight function info
type(mus_scheme_type), intent(inout) :: scheme
Scheme
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
real(kind=rk), intent(in) :: dt_DEM_lat
Time step of DEM subcycles, in lattice units
Calls
Called by
Call graph
incrementauxfield_dps calls neigh, add_momentum_increment_to_auxfield, followneighpath, getbaryofcoord, getposofcoord
add_momentum_increment_to_auxfield calls auxfield_varpos
getposofcoord calls tem_IdOfCoord, tem_PosOfId
demsubcycles_dps calls incrementauxfield_dps
mus_particles_move_dps calls demsubcycles_dps