init_intpArraysPerLevel – Musubi
init_intpArraysPerLevel Subroutine
21 statements
Source File
private subroutine init_intpArraysPerLevel(sourceFromCoarser, intpFromCoarser, sourceFromFiner, intpFromFiner, nGhostFromCoarser, nGhostFromFiner, intp_order, nMaxSourcesFromFiner, iLevel)
Arguments
Type Intent Optional Attributes Name
type(dyn_intarray_type), intent(out) :: sourceFromCoarser
dynamic array of source elements from coarser
type(grw_intarray_type), intent(out), allocatable :: intpFromCoarser(:)
growing array of ghost elements from coarser for different intp order
type(dyn_intarray_type), intent(out) :: sourceFromFiner
dynamic array of source elements from finer
type(grw_intarray_type), intent(out) :: intpFromFiner
growing array of ghost elements from finer
integer, intent(in) :: nGhostFromCoarser
Number of ghost from coarser on this level
integer, intent(in) :: nGhostFromFiner
Number of ghost from finer on this level
integer, intent(in) :: intp_order
interpolation order defined by user
integer, intent(in) :: nMaxSourcesFromFiner
nMaxSources for fillMineFromFiner
integer, intent(in) :: iLevel
current level
Calls
Called by
Call graph
init_intparraysperlevel calls init
mus_init_leveldescintparrays calls init_intparraysperlevel
mus_construct calls mus_init_leveldescintparrays
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize