init_particle_creator_from_blob_prism – Musubi
init_particle_creator_from_blob_prism Subroutine
55 statements
Source File
public subroutine init_particle_creator_from_blob_prism(particle_creator, particleblob, Nparticles, scheme, geometry, myRank)
Routine to initialize the particle creator object from a particle blob prism object Check if particles should be initialized to the local fluid velocity.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_creator_type), intent(inout) :: particle_creator
Particle creator object
type(mus_particle_blob_prism_type), intent(inout) :: particleblob
Particle blob object describing the shape of the initial "blob" of particles
integer, intent(in) :: Nparticles
Desired number of particles to fill the ENTIRE blob with (so not just the part of it on this rank, but on all ranks)
type(mus_scheme_type), intent(in) :: scheme
Scheme to initialize particles on the lattice
type(mus_geom_type), intent(in) :: geometry
Geometry to initialize particles on the lattice
integer, intent(in) :: myRank
This process rank
Calls
Called by
Call graph
init_particle_creator_from_blob_prism calls append, destroy, init, fill_prism, fill_blob_positions_gauss_prism, positionlocalonmyrank, tem_abort
fill_prism calls fill_prism_by_distance, fill_prism_by_number
fill_blob_positions_gauss_prism calls append, init_particle_blob_prob, pick_random_position, rotate_positions, set_random_seed, translate_positions, val
positionlocalonmyrank calls coordlocalonmyrank, tem_CoordOfReal
init_particle_blob_prob calls init_particle_blob_prob_circle, init_particle_blob_prob_square
coordlocalonmyrank calls tem_IdOfCoord, tem_PosOfId
fill_prism_by_distance calls append, init
fill_prism_by_number calls append, init
pick_random_position calls append, tem_abort, val, fill_bins, map_to_bin, normalize_probabilities, remove_elem_grw_real2darray, remove_elem_grw_realarray
rotate_positions calls rodriguez_rotation
fill_bins calls append, val
init_particle_blob_prob_circle calls append, init, fill_bins, normalize_probabilities, normcdf
init_particle_blob_prob_square calls append, init, fill_bins, normalize_probabilities, normcdf
normalize_probabilities calls val
remove_elem_grw_real2darray calls swap_grw_real2darray
remove_elem_grw_realarray calls swap_grw_realarray
rodriguez_rotation calls cross_product
mus_load_particles calls init_particle_creator_from_blob_prism
mus_initialize calls mus_load_particles
musubi calls mus_initialize