init_cxDirWeightedAvg – Musubi
init_cxDirWeightedAvg Function
24 statements
Source File
private function init_cxDirWeightedAvg(QQ, nSources) result(me)
Initialize stencil for weighted average interpolation
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: QQ
integer, intent(in) :: nSources
Return Value integer, (nSources,8)
Calls
Called by
Call graph
init_cxdirweightedavg calls tem_abort
mus_set_nsources calls init_cxdirweightedavg
mus_init_scheme calls mus_set_nsources
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize