init_momentsBC – Musubi
init_momentsBC Subroutine
207 statements
Source File
private subroutine init_momentsBC(bc, levelDesc, layout, globBC, minLevel, maxLevel)
Initialize the values required for the moments BC
Arguments
Type Intent Optional Attributes Name
type(boundary_type), intent(inout) :: bc
global array boundary type
type(tem_levelDesc_type), intent(in) :: levelDesc(minLevel:maxLevel)
Level descriptor
type(mus_scheme_layout_type), intent(in) :: layout
Layout
type(glob_boundary_type), intent(inout) :: globBC
scheme global boundary type
integer, intent(in) :: minLevel
Level range
integer, intent(in) :: maxLevel
Level range
Calls
Called by
Call graph
init_momentsbc calls a, invert_matrix, tem_abort, val
init_boundary_single calls init_momentsbc
mus_init_boundary calls init_boundary_single
mus_initialize calls mus_init_boundary
mus_reset_aux calls mus_init_boundary
mus_perform_dynloadbal calls mus_reset_aux
musubi calls mus_initialize