init_particle_creator_from_blob – Musubi
init_particle_creator_from_blob Subroutine
53 statements
Source File
public subroutine init_particle_creator_from_blob(particle_creator, particleblob, Nparticles, scheme, geometry, myRank)
Routine to initialize the particle creator object from a particle blob cylinder object Check if particles should be initialized to the local fluid velocity.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_creator_type), intent(inout) :: particle_creator
Particle creator object
type(mus_particle_blob_cylinder_type), intent(inout) :: particleblob
Particle blob object describing the shape of the initial "blob" of particles
integer, intent(in) :: Nparticles
Desired number of particles to fill the ENTIRE blob with (so not just the part of it on this rank, but on all ranks)
type(mus_scheme_type), intent(in) :: scheme
Scheme to initialize particles on the lattice
type(mus_geom_type), intent(in) :: geometry
Geometry to initialize particles on the lattice
integer, intent(in) :: myRank
This process rank
Calls
Called by
Call graph
init_particle_creator_from_blob calls append, destroy, init, fill_blob_positions_gauss, fill_cylinder, positionlocalonmyrank, rotate_positions, translate_positions, tem_abort
fill_blob_positions_gauss calls append, rotate_positions, translate_positions, init_particle_blob_prob, pick_random_position, set_random_seed, val
fill_cylinder calls append, init
positionlocalonmyrank calls coordlocalonmyrank, tem_CoordOfReal
rotate_positions calls rodriguez_rotation
init_particle_blob_prob calls init_particle_blob_prob_circle, init_particle_blob_prob_square
coordlocalonmyrank calls tem_IdOfCoord, tem_PosOfId
pick_random_position calls append, tem_abort, val, fill_bins, map_to_bin, normalize_probabilities, remove_elem_grw_real2darray, remove_elem_grw_realarray
rodriguez_rotation calls cross_product
fill_bins calls append, val
init_particle_blob_prob_circle calls append, init, fill_bins, normalize_probabilities, normcdf
init_particle_blob_prob_square calls append, init, fill_bins, normalize_probabilities, normcdf
normalize_probabilities calls val
remove_elem_grw_real2darray calls swap_grw_real2darray
remove_elem_grw_realarray calls swap_grw_realarray
mus_load_particles calls init_particle_creator_from_blob
mus_initialize calls mus_load_particles
musubi calls mus_initialize