init_advRel – Musubi
init_advRel Subroutine
33 statements
Source File
private subroutine init_advRel(scheme)
Choose the relaxation model
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type) :: scheme
scheme type
Calls
Called by
Call graph
init_advrel calls mus_init_advrel_fluid, mus_init_advrel_fluid_gns, mus_init_advrel_fluidincomp, mus_init_advrel_fluidincomp_gns, mus_init_advrel_isotherm_aceq, mus_init_advrel_lbm_ps, mus_init_advrel_multispecies_gas, mus_init_advrel_multispecies_liquid, mus_init_advrel_nernstplanck, mus_init_advrel_pblinear, mus_init_advrel_pbnonlinear, mus_init_advrel_poisson, tem_abort
mus_init_advrel_fluid calls tem_abort, mus_init_advrel_fluid_bgk, mus_init_advrel_fluid_mrt, mus_init_advrel_fluid_trt
mus_init_advrel_fluid_gns calls tem_abort
mus_init_advrel_fluidincomp calls tem_abort, mus_init_advrel_fluidincomp_bgk, mus_init_advrel_fluidincomp_mrt
mus_init_advrel_fluidincomp_gns calls tem_abort
mus_init_advrel_isotherm_aceq calls tem_abort
mus_init_advrel_lbm_ps calls tem_abort
mus_init_advrel_multispecies_gas calls tem_abort
mus_init_advrel_multispecies_liquid calls tem_abort
mus_init_advrel_nernstplanck calls tem_abort
mus_init_advrel_pblinear calls tem_abort
mus_init_advrel_pbnonlinear calls tem_abort
mus_init_advrel_poisson calls tem_abort
mus_init_advrel_fluid_bgk calls tem_abort
mus_init_advrel_fluid_mrt calls tem_abort
mus_init_advrel_fluid_trt calls tem_abort
mus_init_advrel_fluidincomp_bgk calls tem_abort
mus_init_advrel_fluidincomp_mrt calls tem_abort
mus_init_flow calls init_advrel
mus_initialize calls mus_init_flow
musubi calls mus_initialize