initParticle_MEM – Musubi
initParticle_MEM Subroutine
24 statements
Source File
public subroutine initParticle_MEM(particle, particleID, geometry, scheme, myRank, comm, rmflag)
Routine to initialize a newly created MEM particle
Arguments
Type Intent Optional Attributes Name
type(mus_particle_MEM_type), intent(inout) :: particle
Particle to initialize
integer, intent(in) :: particleID
Number to uniquely identify particle particle
type(mus_geom_type), intent(in) :: geometry
Geometry to determine TreeIDs of elements 'covered' by particle
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to level descriptor
integer, intent(in) :: myRank
MPI rank of this process
type(mus_particles_communication_type) :: comm
Communication data type for particles
logical, intent(out) :: rmflag
flag to indicate whether particle exists on this process or should be removed
Calls
Called by
Call graph
initparticle_mem calls init, make_pdf_tiny, updateexclusionlist, updatefluidneighbors, updatesolidnodes
make_pdf_tiny calls state_varpos, val
updateexclusionlist calls append, empty, getbaryofcoord, getneighborcoord, updateexistsonproc, updateparticleowner, tem_IdOfCoord, tem_PosOfId
updatefluidneighbors calls cxdirinv, nghelems, property, state_varpos, val
updatesolidnodes calls property, state_varpos, val
updateexistsonproc calls getneighborcoord, tem_IdOfCoord, part_first, part_last, findpartitionoftreeid
updateparticleowner calls tem_IdOfCoord, tem_PosOfId, findpartitionoftreeid, tem_abort
findpartitionoftreeid calls part_first, part_last
check_and_create_new_particles_mem calls initparticle_mem, create_particles_mem
createnewparticle_mem calls initparticle_mem
mus_particles_applyhydrodynamicforces_mem calls initparticle_mem
check_particles_mem calls check_and_create_new_particles_mem
create_particles_mem calls createnewparticle_mem