initParticleLog_MEM – Musubi
initParticleLog_MEM Subroutine
31 statements
Source File
public subroutine initParticleLog_MEM(particleID, fileName, plogUnit, fileExists)
Routine to initialize MEM particle log file (e.g. print header)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: particleID
character(len=*), intent(in) :: fileName
integer, intent(in) :: plogUnit
logical, intent(in) :: fileExists
Called by
Call graph
logparticledata_mem calls initparticlelog_mem
logparticledata calls logparticledata_mem
mus_particles_logdata_dps calls logparticledata
mus_particles_logdata_mem calls logparticledata
advance_particles_mem calls mus_particles_logdata_mem
check_particles_dps calls mus_particles_logdata_dps