init_transformation_matrix_MS – Musubi
init_transformation_matrix_MS Subroutine
148 statements
Source File
private subroutine init_transformation_matrix_MS(QQ, cxDir, label, me, toMoment, toPdf)
Intialize the moment transformation matrix for multispecies. This matrix must be consistent with relaxation matrix used for multispecies MRT collision routines
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: QQ
integer, intent(in) :: cxDir(3,QQ)
character(len=labelLen) :: label
type(mus_moment_type), intent(inout) :: me
real(kind=rk), intent(inout) :: toMoment(me%toMoments%nEntries(1),me%toMoments%nEntries(2))
real(kind=rk), intent(inout) :: toPdf(me%toPDF%nEntries(1),me%toPDF%nEntries(2))
Calls
Called by
Call graph
init_transformation_matrix_ms calls invert_matrix, get_momentvector
get_momentvector calls mus_imomvector
mus_init_moments calls init_transformation_matrix_ms
mus_init_scheme calls mus_init_moments
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme