initParticle_DPS – Musubi
initParticle_DPS Subroutine
19 statements
Source File
public subroutine initParticle_DPS(particle, interpolator, particleID, geometry, scheme, myRank, comm)
initParticle_DPS performs the initialization of a DPS particle once it has been created. This consists of determining the coordinates of particle origin and determining which processes this particle exists on.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: particle
Particle to initialize
type(mus_particle_interpolator_type), intent(in) :: interpolator
Interpolation data type. We don't interpolate stuff here but we use it to determine the directions we need to search for local elements in (only x, y for d2q9, x, y, z for d3q19)
integer, intent(in) :: particleID
Number to uniquely identify particle particle
type(mus_geom_type), intent(in) :: geometry
Geometry to determine TreeIDs of elements 'covered' by particle
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to level descriptor
integer, intent(in) :: myRank
MPI rank of this process
type(mus_particles_communication_type) :: comm
Communication data type for particles
Calls
Called by
Call graph
initparticle_dps calls getposofcoord, updatecoordoforigin_dps, updateexistsonproc_dps, updateparticleowner, tem_CoordOfReal
getposofcoord calls tem_IdOfCoord, tem_PosOfId
updatecoordoforigin_dps calls getposofcoord, tem_CoordOfReal
updateexistsonproc_dps calls neigh, part_first, part_last, findpartitionoftreeid, followneighpath, wrapperiodiccoord, tem_IdOfCoord, tem_PosOfId, total
updateparticleowner calls part_first, part_last, findpartitionoftreeid, tem_IdOfCoord, tem_PosOfId
findpartitionoftreeid calls part_first, part_last
check_and_create_new_particles_dps calls initparticle_dps, create_particles_dps
createnewparticle_dps calls initparticle_dps
mapparticlestolattice_dps calls initparticle_dps
mus_particles_mapping_dps calls initparticle_dps
check_particles_dps calls check_and_create_new_particles_dps
create_particles_dps calls createnewparticle_dps
demsubcycles_dps calls mapparticlestolattice_dps
demsubcycles_dps_onewaycoupled calls mapparticlestolattice_dps
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled