init_boundary_single – Musubi
init_boundary_single Subroutine
342 statements
Source File
private subroutine init_boundary_single(bc, pdf, tree, levelDesc, layout, schemeHeader, varPos, varSys, derVarPos, globBC, bc_prop, state, auxField, fieldProp)
This subroutine sets the right boundary conditions for the different boundaries.
The boundary conditions were read in the order of config.lua the order in the boundary condition description file however might be different. We have to match the labels.
Arguments
Type Intent Optional Attributes Name
type(boundary_type) :: bc(:)
global array boundary type
type(pdf_data_type), intent(in) :: pdf(tree%global%minLevel:tree%global%maxLevel)
contains global state vector
type(treelmesh_type), intent(in) :: tree
global treelm mesh
type(tem_levelDesc_type), intent(in) :: levelDesc(tree%global%minLevel:tree%global%maxLevel)
global pdf type
type(mus_scheme_layout_type), intent(in) :: layout
scheme layout type
type(mus_scheme_header_type), intent(in) :: schemeHeader
scheme header info
integer, intent(in) :: varPos(:)
varPos of current field variable
type(tem_varSys_type), intent(in) :: varSys
scheme variable system
type(mus_derVarPos_type), intent(in) :: derVarPos
position of derived quantities in varsys
type(glob_boundary_type), intent(inout) :: globBC(:)
scheme global boundary type
type(tem_BC_prop_type), intent(in) :: bc_prop
boundary property type
type(array2D_type), intent(in) :: state(tree%global%minLevel:tree%global%maxLevel)
contains global state vector
type(mus_auxFieldVar_type), intent(in) :: auxField(tree%global%minLevel:tree%global%maxLevel)
AuxField array
type(mus_field_prop_type), intent(in) :: fieldProp
fluid parameters and properties
Calls
Called by
Call graph
init_boundary_single calls init_momentsbc, init_nrbc, init_qvals, mus_alloc_bouzidi, mus_init_turb_wallfunc, mus_set_bouzidi, mus_set_inletbfl, mus_set_inletubb, mus_set_noneqexpol, mus_set_outletexpol, mus_setupindices_forbc, tem_abort
init_momentsbc calls tem_abort, a, invert_matrix, val
init_qvals calls cxdirinv, init, val
mus_init_turb_wallfunc calls auxfield_varpos, val
mus_set_bouzidi calls set_bouzidi_coeff, val
mus_set_inletbfl calls set_bouzidi_coeff, tem_BaryOfId, tem_ElemSizeLevel, val
mus_set_inletubb calls tem_BaryOfId, tem_ElemSizeLevel, val
mus_set_noneqexpol calls val
mus_set_outletexpol calls val
mus_setupindices_forbc calls tem_abort, append, indexlvl, init, mus_get_points_frombc, set_params, setup_indices, val
mus_get_points_frombc calls tem_BaryOfId, tem_ElemSizeLevel, val
mus_init_boundary calls init_boundary_single
mus_initialize calls mus_init_boundary
mus_reset_aux calls mus_init_boundary
mus_perform_dynloadbal calls mus_reset_aux
musubi calls mus_initialize
mus_solve calls mus_perform_dynloadbal