interpolateFluidProps_onewaycoupled_old – Musubi
interpolateFluidProps_onewaycoupled_old Subroutine
44 statements
Source File
public subroutine interpolateFluidProps_onewaycoupled_old(xp, coord_xp, scheme, geom_origin, dx, interpolator, vel_xp, rho_xp)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: xp(3)
Query point (x,y,z) to interpolate fluid properties to
integer, intent(in) :: coord_xp(4)
Coordinate in the tree (ix,iy,iz,level) of xp
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to fluid data
real(kind=rk), intent(in) :: geom_origin(3)
Origin of bounding cube (geometry%tree%global%origin)
real(kind=rk), intent(in) :: dx
Mesh size
type(mus_particle_interpolator_type), intent(in) :: interpolator
Interpolator object containing stencil and weight function information
real(kind=rk), intent(out) :: vel_xp(3)
Fluid velocity at xp
real(kind=rk), intent(out) :: rho_xp
Fluid density at xp
Calls
Called by
Call graph
interpolatefluidprops_onewaycoupled_old calls auxfield_varpos, grabvalueatcoord, getbaryofcoord, getneighborcoord, tem_abort
grabvalueatcoord calls grabvalueatcoord_onewaycoupled, grabvalueatcoord_twowaycoupled
grabvalueatcoord_onewaycoupled calls tem_IdOfCoord, tem_PosOfId
grabvalueatcoord_twowaycoupled calls tem_IdOfCoord, tem_PosOfId
mus_particles_dps_interpolatefluidproperties_onewaycoupled calls interpolatefluidprops_onewaycoupled_old
mus_particles_applyhydrodynamicforces_dps_onewaycoupled calls mus_particles_dps_interpolatefluidproperties_onewaycoupled