interpolateFluidProps – Musubi
interpolateFluidProps Subroutine
58 statements
Source File
public subroutine interpolateFluidProps(xp, coord_xp, scheme, geom_origin, dx, interpolator, vel_xp, rho_xp, eps_f_xp, posOfCoord)
Interpolate the fluid properties to a point xp
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: xp(3)
Query point (x,y,z) to interpolate fluid properties to
integer, intent(in) :: coord_xp(4)
Coordinate in the tree (ix,iy,iz,level) of xp
type(mus_scheme_type), intent(in) :: scheme
Scheme for access to fluid data
real(kind=rk), intent(in) :: geom_origin(3)
Origin of bounding cube (geometry%tree%global%origin)
real(kind=rk), intent(in) :: dx
Mesh size
type(mus_particle_interpolator_type), intent(in) :: interpolator
Interpolator object containing stencil and weight function information
real(kind=rk), intent(out) :: vel_xp(3)
Fluid velocity at xp
real(kind=rk), intent(out) :: rho_xp
Fluid density at xp
real(kind=rk), intent(out) :: eps_f_xp
Fluid volume fraction at xp
integer, intent(in), optional :: posOfCoord
Position of coord_xp in the total list, if available. Supplying this makes the routine run faster.
Calls
Called by
Call graph
interpolatefluidprops calls auxfield_varpos, neigh, followneighpath, getbaryofcoord, getposofcoord
getposofcoord calls tem_IdOfCoord, tem_PosOfId
test_interpolation_delta_dps_d2q9 calls interpolatefluidprops
test_interpolation_delta_dps_d3q19 calls interpolatefluidprops