load_particle_dps_data – Musubi
load_particle_dps_data Subroutine
30 statements
Source File
public subroutine load_particle_dps_data(conf, parent, particles, nparticles, chunksize)
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
integer, intent(in), optional :: parent
handle to parent table if position, velocity tables etc are inside another table
type(dyn_particle_dps_array_type), intent(inout) :: particles
dynamic particle array to append particles read from file to
integer, intent(in) :: nparticles
total number of particles to read
integer, intent(in) :: chunksize
Calls
Call graph
load_particle_dps_data calls append_da_particle_dps, mus_load_particle_dps_data_chunk
append_da_particle_dps calls expand_da_particle_dps, sortposofval_particle_dps
mus_load_particle_dps_data_chunk calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, tem_abort