load_particle_mem_creator_data – Musubi
load_particle_mem_creator_data Subroutine
49 statements
Source File
public subroutine load_particle_mem_creator_data(conf, parent, particle_creator, nparticles, chunksize, scheme, geometry, myrank)
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
integer, intent(in), optional :: parent
handle to parent table if position, velocity tables etc are inside another table
type(mus_particle_creator_type), intent(inout) :: particle_creator
dynamic particle array to append particles read from file to
integer, intent(in) :: nparticles
total number of particles to read
integer, intent(in) :: chunksize
type(mus_scheme_type), intent(in) :: scheme
scheme
type(mus_geom_type), intent(in) :: geometry
geometry
integer, intent(in) :: myrank
this mpi process rank
Calls
Called by
Call graph
load_particle_mem_creator_data calls append, mus_load_particle_mem_data_chunk, positionlocalonmyrank
mus_load_particle_mem_data_chunk calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, tem_abort
positionlocalonmyrank calls coordlocalonmyrank, tem_CoordOfReal
coordlocalonmyrank calls tem_IdOfCoord, tem_PosOfId
mus_load_particles calls load_particle_mem_creator_data
mus_initialize calls mus_load_particles
musubi calls mus_initialize