load_turbChanForce – Musubi
load_turbChanForce Subroutine
51 statements
Source File
private subroutine load_turbChanForce(me, conf, key, parent)
Load shape, bulk velocity and height for turbulent channel force
Arguments
Type Intent Optional Attributes Name
type(mus_turbChannelForce_type), intent(out) :: me
Turbulent channel force
type(flu_State) :: conf
flu state
character(len=*), intent(in) :: key
Table name to load target states
integer, intent(in) :: parent
parent source handle
Calls
Called by
Call graph
load_turbchanforce calls aot_get_val, aot_table_open, canond, tem_abort, tem_load_shape
mus_load_source_var calls load_turbchanforce
mus_load_field_single calls mus_load_source_var
mus_load_scheme calls mus_load_source_var, mus_load_fields
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_load_fields calls mus_load_field_single
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config