load_relaxation_header – Musubi
load_relaxation_header Subroutine
15 statements
Source File
private subroutine load_relaxation_header(me, conf, thandle)
Load relaxation options from a table
Arguments
Type Intent Optional Attributes Name
type(mus_relaxation_header_type), intent(out) :: me
type(flu_State) :: conf
integer, intent(in) :: thandle
relaxation handle
Calls
Called by
Call graph
load_relaxation_header calls aot_get_val, tem_abort
mus_load_scheme_header calls load_relaxation_header
mus_load_scheme calls mus_load_scheme_header
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config