load_iterativeMethod – Musubi
load_iterativeMethod Subroutine
24 statements
Source File
private subroutine load_iterativeMethod(me, conf, parent)
Load the iterativeMethod to use in the turbulent wall model from the user configuration.
Arguments
Type Intent Optional Attributes Name
type(mus_turb_wallFunc_type), intent(inout) :: me
Turbulent wall model type to fill assign wall model
type(flu_State) :: conf
lua flu state
integer, intent(in) :: parent
bc parent handle
Calls
Called by
Call graph
load_iterativemethod calls aot_get_val, tem_abort
mus_load_turb_wallfunc calls load_iterativemethod
mus_load_bc calls mus_load_turb_wallfunc
mus_load_field_single calls mus_load_bc
mus_load_fields calls mus_load_field_single