logParticleData_MEM – Musubi
logParticleData_MEM Subroutine
46 statements
Source File
public subroutine logParticleData_MEM(particle, plogUnit, myRank, t)
Routine to log MEM particle data
Arguments
Type Intent Optional Attributes Name
type(mus_particle_MEM_type), intent(in) :: particle
integer, intent(in) :: plogUnit
integer, intent(in) :: myRank
real(kind=rk), intent(in) :: t
Calls
Called by
Call graph
logparticledata_mem calls initparticlelog_mem, tem_abort
logparticledata calls logparticledata_mem
mus_particles_logdata_dps calls logparticledata
mus_particles_logdata_mem calls logparticledata
advance_particles_mem calls mus_particles_logdata_mem
check_particles_dps calls mus_particles_logdata_dps