make_pdf_tiny – Musubi
make_pdf_tiny Subroutine
19 statements
Source File
public subroutine make_pdf_tiny(scheme, particle, lev)
make_pdf_tiny sets the state vector (particle distribution function) values to some tiny value. This is done for visualization purposes. It has no effect on the flow as the particle elements do not participate in the stream-and-collide process.
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type) :: scheme
type(mus_particle_MEM_type) :: particle
integer :: lev
Calls
Called by
Call graph
make_pdf_tiny calls state_varpos, val
initparticle_mem calls make_pdf_tiny
maptolattice calls make_pdf_tiny
check_and_create_new_particles_mem calls initparticle_mem, create_particles_mem
createnewparticle_mem calls initparticle_mem
mus_particles_applyhydrodynamicforces_mem calls initparticle_mem
mus_particles_mapping_mem calls maptolattice
check_particles_mem calls check_and_create_new_particles_mem
create_particles_mem calls createnewparticle_mem