map_to_bin – Musubi
map_to_bin Subroutine
28 statements
Source File
public subroutine map_to_bin(x, bins, N, ibin)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: x
Number to map to a bin
real(kind=rk), intent(in) :: bins(:)
Array containing the boundaries of each bin Should be monotonic increasing i.e. bin(0) < bin(1) < ... bin(Nbins)
integer, intent(in) :: N
Number of elements in bins array
integer, intent(out) :: ibin
so that bins(ibin) < x <= bins(ibin+1)
EXAMPLE if bins = [0.0, 0.1, 0.3, 0.7, 1.0] and x = 0.32 then this routine returns ibin = 3 since bins(ibin) = 0.3 < x <= bins(ibin+1)
Called by
Call graph
pick_random_position calls map_to_bin
fill_blob_positions_gauss calls pick_random_position
fill_blob_positions_gauss_prism calls pick_random_position
init_particle_creator_from_blob calls fill_blob_positions_gauss
init_particle_creator_from_blob_prism calls fill_blob_positions_gauss_prism
mus_load_particles calls init_particle_creator_from_blob, init_particle_creator_from_blob_prism