mapParticlesToLattice_DPS – Musubi
mapParticlesToLattice_DPS Subroutine
45 statements
Source File
public subroutine mapParticlesToLattice_DPS(particleGroup, scheme, geometry, params)
Main control routine which maps each DPS particle to the lattice
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Called by
Call graph
mapparticlestolattice_dps calls allocateprocessmasks, exchangenewparticles_dps, exchangeparticlestoremove_dps, initparticle_dps, maptolattice_dps, remove_particle_from_da_particle_dps
allocateprocessmasks calls allocateprocessmasks_dps
exchangenewparticles_dps calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, append_da_particle_dps, tem_abort
exchangeparticlestoremove_dps calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, sortposofval_particle_dps, tem_abort
initparticle_dps calls getposofcoord, updatecoordoforigin_dps, updateexistsonproc_dps, updateparticleowner, tem_CoordOfReal
maptolattice_dps calls updatecoordoforigin_dps, updateexistsonproc_dps, updateparticleowner
remove_particle_from_da_particle_dps calls swap_da_particle_dps
append_da_particle_dps calls sortposofval_particle_dps, expand_da_particle_dps
getposofcoord calls tem_IdOfCoord, tem_PosOfId
updatecoordoforigin_dps calls getposofcoord, tem_CoordOfReal
updateexistsonproc_dps calls neigh, part_first, part_last, findpartitionoftreeid, followneighpath, wrapperiodiccoord, tem_IdOfCoord, tem_PosOfId, total
updateparticleowner calls part_first, part_last, findpartitionoftreeid, tem_IdOfCoord, tem_PosOfId
findpartitionoftreeid calls part_first, part_last
demsubcycles_dps calls mapparticlestolattice_dps
demsubcycles_dps_onewaycoupled calls mapparticlestolattice_dps
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled