mapToLattice – Musubi
mapToLattice Subroutine
77 statements
Source File
public subroutine mapToLattice(this, particleGroup, scheme, stencil, geometry, params, rmflag)
mapToLattice is the high-level routine performs a full re-mapping each time step
Arguments
Type Intent Optional Attributes Name
type(mus_particle_MEM_type), intent(inout) :: this
type(mus_particle_group_type), intent(inout) :: particleGroup
Particle group in which to search for collisions
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to level descriptor
type(tem_stencilHeader_type), intent(in) :: stencil
fluid stencil
type(mus_geom_type), intent(in) :: geometry
Geometry to determine TreeIDs of elements 'covered' by particle
type(mus_param_type), intent(in) :: params
Parameters for access to e.g. time step dt
logical, intent(out) :: rmflag
Flag that tells whether to remove this particle from this process
Calls
Called by
Call graph
maptolattice calls append, baryoftotal, empty, checkforparticleoverlap, computedisplacement, cross_product, make_pdf_tiny, settoequilibrium, updateexclusionlist, updatefluidneighbors, updatenewfluidnodes, updatesolidnodes, property, val
checkforparticleoverlap calls property, val, findparticlefromelem, tem_abort
make_pdf_tiny calls val, state_varpos
settoequilibrium calls val, state_varpos
updateexclusionlist calls append, empty, getbaryofcoord, getneighborcoord, updateexistsonproc, updateparticleowner, tem_IdOfCoord, tem_PosOfId
updatefluidneighbors calls property, val, cxdirinv, nghelems, state_varpos
updatenewfluidnodes calls property, val, cxdirinv, nghelems, state_varpos
updatesolidnodes calls property, val, state_varpos
updateexistsonproc calls getneighborcoord, tem_IdOfCoord, part_first, part_last, findpartitionoftreeid
updateparticleowner calls tem_IdOfCoord, tem_PosOfId, tem_abort, findpartitionoftreeid
findpartitionoftreeid calls part_first, part_last
mus_particles_mapping_mem calls maptolattice