mapToLattice_DPS – Musubi
mapToLattice_DPS Subroutine
13 statements
Source File
public subroutine mapToLattice_DPS(particle, interpolator, scheme, geometry, params, comm, particleLogInterval)
Routine to map particles to the lattice (update coordinate of the origin etc.)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: particle
Array of particles
type(mus_particle_interpolator_type), intent(in) :: interpolator
Interpolation data type. We don't interpolate stuff here but we use it to determine the directions we need to search for local elements in (only x, y for d2q9, x, y, z for d3q19)
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
type(mus_particles_communication_type), intent(inout) :: comm
Communication data type for particles
integer, intent(in) :: particleLogInterval
Log the particle data to file every this many iterations
Calls
Called by
Call graph
maptolattice_dps calls updatecoordoforigin_dps, updateexistsonproc_dps, updateparticleowner
updatecoordoforigin_dps calls getposofcoord, tem_CoordOfReal
updateexistsonproc_dps calls neigh, part_first, part_last, findpartitionoftreeid, followneighpath, wrapperiodiccoord, tem_IdOfCoord, tem_PosOfId, total
updateparticleowner calls part_first, part_last, findpartitionoftreeid, tem_IdOfCoord, tem_PosOfId
findpartitionoftreeid calls part_first, part_last
getposofcoord calls tem_IdOfCoord, tem_PosOfId
mapparticlestolattice_dps calls maptolattice_dps
mus_particles_mapping_dps calls maptolattice_dps
demsubcycles_dps calls mapparticlestolattice_dps
demsubcycles_dps_onewaycoupled calls mapparticlestolattice_dps
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled