momentumFromMacroLSE – Musubi
momentumFromMacroLSE Function
27 statements
Source File
public function momentumFromMacroLSE(moleFraction, first_Moments, nFields, phi, resi_coeff, omega_fac, paramBInv) result(momentum)
derive untransformed pdf velocity of species by solving system of equations of nSpecies
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: moleFraction(nFields)
molefraction of all species
real(kind=rk), intent(in) :: first_Moments(3,nFields)
momentum from transformed pdf of all species
integer, intent(in) :: nFields
number of species
real(kind=rk), intent(in) :: phi(nFields)
molecular weight ratio of all species
real(kind=rk), intent(in) :: resi_coeff(nFields,nFields)
resistivity coefficients
real(kind=rk), intent(in) :: omega_fac
relaxation parameter, omega_diff*0.5_rk
real(kind=rk), intent(in) :: paramBInv
free parameter B
Return Value real(kind=rk), (3,nFields)
return actual momentum
Calls
Called by
Call graph
momentumfrommacrolse calls invert_matrix
calcdensandvelsfrompdf calls momentumfrommacrolse
deriveauxmsliquid_fromstate calls momentumfrommacrolse
deriveeqmsliquid_fromstate calls momentumfrommacrolse
derivemomentamsliquid_fromstate calls momentumfrommacrolse
derivemommsliquid_fromstate calls momentumfrommacrolse
derivevelmsliquid_fromstate calls momentumfrommacrolse
derivevelocitiesmsliquid_fromstate calls momentumfrommacrolse
spc_blackbox_mem_ion calls momentumfrommacrolse
spc_blackbox_mem_solvent calls momentumfrommacrolse
spc_inflow calls momentumfrommacrolse
spc_molediff_flux calls momentumfrommacrolse
spc_mole_fraction_noneq_expol calls calcdensandvelsfrompdf
spc_outflow calls calcdensandvelsfrompdf
spc_solvent_inflow calls calcdensandvelsfrompdf
spc_solvent_outflow calls calcdensandvelsfrompdf
spc_velocity_noneq_expol calls calcdensandvelsfrompdf