mus_init_pdf – Musubi
mus_init_pdf Subroutine
89 statements
Source File
private subroutine mus_init_pdf(me, tree, fac, scaling, field, iField, state, neigh, nElems, nSize, iLevel)
Initialize the flow from pressure, velocity and strain rate.\n First equilibirium pdf (fEq) is calculated from pressure and velocity. Then non-equilibirium (fnEq) is calculated from strain rate. At last set the pdf of each element by sum up these two parts (fEq+fnEq).
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: me
Scheme type
type(treelmesh_type), intent(in) :: tree
tree type
type(mus_convertFac_type), intent(in) :: fac
Global parameters
character(len=*), intent(in) :: scaling
scaling
type(mus_field_type), intent(inout) :: field
Field type
integer, intent(in) :: iField
Field index
real(kind=rk), intent(inout) :: state(:)
PDF
integer, intent(in) :: neigh(:)
Connectivity array
integer, intent(in) :: nElems
Number of local elements
integer, intent(in) :: nSize
number of elements as size
integer, intent(in) :: iLevel
Level index
Calls
Called by
Call graph
mus_init_pdf calls ini_state, getneq_acoustic, getneq_diffusive, tem_BaryOfId, tem_spatial_for, total
getneq_acoustic calls cxdirrk, convprepost
getneq_diffusive calls cxdirrk, convprepost
mus_init_byic calls mus_init_pdf
mus_init_flow calls mus_init_byic
mus_initialize calls mus_init_flow
musubi calls mus_initialize