mus_construct_connectivity – Musubi
mus_construct_connectivity Subroutine
51 statements
Source File
public subroutine mus_construct_connectivity(neigh, nSize, nElems, levelDesc, stencil, varSys, stateVarMap)
Construct the propagation list for each element of 1st field.
the bounce back rules have to be applied here
Create connectivity array for one field such that it points to poisition of 1st Field in state array and use macro NGOFFSET to access other field states.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: neigh(:)
connectivity array
integer, intent(in) :: nSize
number of elements in state array
integer, intent(in) :: nElems
number of elements in local partition
type(tem_levelDesc_type), intent(in) :: levelDesc
current level description
type(tem_stencilHeader_type), intent(in) :: stencil
fluid stencil
type(tem_varSys_type), intent(in) :: varSys
global variable system
type(tem_varMap_type), intent(in) :: stateVarMap
state varMap
Calls
Called by
Call graph
mus_construct_connectivity calls nghelems, state_varpos, val
mus_construct calls mus_construct_connectivity
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve