mus_init_advRel_fluid – Musubi
mus_init_advRel_fluid Subroutine
113 statements
Source File
public subroutine mus_init_advRel_fluid(relaxation, variant, layout, compute)
Assigning compute kernel routine by scheme relaxation type for fluid kind.
Arguments
Type Intent Optional Attributes Name
character(len=labelLen), intent(in) :: relaxation
character(len=labelLen), intent(in) :: variant
character(len=labelLen), intent(in) :: layout
procedure(kernel), intent(out), pointer :: compute
Calls
Call graph
mus_init_advrel_fluid calls mus_init_advrel_fluid_bgk, mus_init_advrel_fluid_mrt, mus_init_advrel_fluid_trt, tem_abort
mus_init_advrel_fluid_bgk calls tem_abort
mus_init_advrel_fluid_mrt calls tem_abort
mus_init_advrel_fluid_trt calls tem_abort