mus_setupIndices_forBC – Musubi
mus_setupIndices_forBC Subroutine
67 statements
Source File
private subroutine mus_setupIndices_forBC(bc, globBC, tree, stencil, levelDesc, varSys, minLevel, maxLevel)
This routine setup indices for boundary variables in bc_State_type pntIndex for the points on which boundaries are treated.
Arguments
Type Intent Optional Attributes Name
type(boundary_type), intent(inout), target :: bc
Field boundary type
type(glob_boundary_type), intent(in) :: globBC
for number of elements in boundary and position in buffer
type(treelmesh_type), intent(in) :: tree
global treelm mesh
type(tem_stencilHeader_type), intent(in) :: stencil
for directions
type(tem_levelDesc_type), intent(in) :: levelDesc(minLevel:maxLevel)
global pdf type
type(tem_varSys_type), intent(in) :: varSys
Global variable system
integer, intent(in) :: minLevel
Min and Max level in mesh
integer, intent(in) :: maxLevel
Min and Max level in mesh
Calls
Called by
Call graph
mus_setupindices_forbc calls append, indexlvl, init, mus_get_points_frombc, set_params, setup_indices, tem_abort, val
mus_get_points_frombc calls val, tem_BaryOfId, tem_ElemSizeLevel
init_boundary_single calls mus_setupindices_forbc
mus_init_boundary calls init_boundary_single
mus_initialize calls mus_init_boundary
mus_reset_aux calls mus_init_boundary
mus_perform_dynloadbal calls mus_reset_aux
musubi calls mus_initialize