mus_intpAuxFieldCoarserAndExchange – Musubi
mus_intpAuxFieldCoarserAndExchange Subroutine
12 statements
Source File
public subroutine mus_intpAuxFieldCoarserAndExchange(intp, tAuxField, sAuxField, tLevelDesc, stencil, iLevel, nAuxScalars, general)
This routine interpolate auxField variable for ghostFromFiner and exchange halos
Arguments
Type Intent Optional Attributes Name
type(mus_interpolation_type), intent(inout) :: intp
Interpolation type
type(mus_auxFieldVar_type), intent(inout) :: tAuxField
target auxilary field array
type(mus_auxFieldVar_type), intent(in) :: sAuxField
source auxilary field array
type(tem_levelDesc_type), intent(in) :: tLevelDesc
level descriptor on target level
type(tem_stencilHeader_type), intent(in) :: stencil
stencil header
integer, intent(in) :: iLevel
current level
integer, intent(in) :: nAuxScalars
number of scalars to interpolate
type(tem_general_type), intent(in) :: general
contains commPattern, MPI communicator and simControl
Calls
Called by
Call graph
mus_intpauxfieldcoarserandexchange calls exchange_real
do_recursive_multilevel calls mus_intpauxfieldcoarserandexchange
mus_initauxfield calls mus_intpauxfieldcoarserandexchange
mus_reset_aux calls mus_intpauxfieldcoarserandexchange
mus_init_flow calls mus_initauxfield
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_initauxfield
mus_initialize calls mus_init_flow
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve