mus_geomIncrHead_load – Musubi
mus_geomIncrHead_load Subroutine
30 statements
Source File
public subroutine mus_geomIncrHead_load(me, conf, parent, dynamicGeom)
Read all the necessary information for the geometry increase from the lua config file. This routine basically provides as a wrapper to the routine which reads single values
Example to geomIncr table:
 variable = {
   { name = 'vel_threshold',
     ncomponents = 1,
     var_type = st_fun,
     st_fun = 0.01
   },
   { name = 'incr_condition',
     ncomponents = 1,
     var_type = 'operation' ,
     operation = {
       kind = '<',
       input_varname = {'vel_mag','vel_threshold'}
     }
   },
 }
 geomIncr = {
  condition = 'incr_condition'
 }
Arguments
Type Intent Optional Attributes Name
type(mus_geomIncrHead_type), intent(inout), allocatable :: me(:)
type(flu_State) :: conf
integer, intent(in), optional :: parent
logical, intent(inout) :: dynamicGeom
Calls
Called by
Call graph
mus_geomincrhead_load calls aot_table_close, aot_table_length, aot_table_open, mus_geomincrhead_load_single
mus_geomincrhead_load_single calls aot_get_val, tem_horizontalSpacer, tem_timeControl_load
mus_load_geom calls mus_geomincrhead_load
mus_load_config calls mus_load_geom
musubi calls mus_load_config