mus_physics_dump2outUnit – Musubi
mus_physics_dump2outUnit Subroutine
44 statements
Source File
public subroutine mus_physics_dump2outUnit(me, outUnit, minLevel, maxLevel)
Arguments
Type Intent Optional Attributes Name
type(mus_physics_type), intent(in) :: me
integer, intent(in) :: outUnit
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
Calls
Called by
Call graph
mus_physics_dump2outunit calls tem_toStr
mus_load_physics calls mus_physics_dump2outunit
mus_hvs_load_solverdata calls mus_load_physics
mus_load_config calls mus_load_physics
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load