mus_particles_logdata_DPS – Musubi
mus_particles_logdata_DPS Subroutine
15 statements
Source File
public subroutine mus_particles_logdata_DPS(particleGroup, params)
Main routine to log particle data for DPS particles
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(in) :: particleGroup
Particle group to log
type(mus_param_type), intent(in) :: params
Params for access to time control
Calls
Called by
Call graph
mus_particles_logdata_dps calls logparticledata, closeparticlelog, getparticlelogunit
logparticledata calls logparticledata_dps, logparticledata_mem
logparticledata_dps calls initparticlelog_dps, tem_abort
logparticledata_mem calls initparticlelog_mem, tem_abort
check_particles_dps calls mus_particles_logdata_dps