mus_init_moments – Musubi
mus_init_moments Subroutine
34 statements
Source File
public subroutine mus_init_moments(me, QQ, cxDir, label, schemeHeader)
Initialize the moment space
Arguments
Type Intent Optional Attributes Name
type(mus_moment_type), intent(inout) :: me
integer, intent(in) :: QQ
integer, intent(in) :: cxDir(3,QQ)
character(len=labelLen) :: label
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
Calls
Called by
Call graph
mus_init_moments calls a, nentries, init_transformation_matrix_fluid, init_transformation_matrix_ms, mus_dump_moments
init_transformation_matrix_fluid calls invert_matrix, get_momentvector
init_transformation_matrix_ms calls invert_matrix, get_momentvector
mus_dump_moments calls tem_matrix_dump
get_momentvector calls mus_imomvector
mus_init_scheme calls mus_init_moments
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve