mus_init_MSLiquid – Musubi
mus_init_MSLiquid Subroutine
156 statements
Source File
private subroutine mus_init_MSLiquid(me, tree, fac, state, neigh, field, mixture, nElems, nSize, iLevel)
Initialize the flow from calculated quantitites like density, velocity etc. for multispecies lbm
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: me
type(treelmesh_type), intent(in) :: tree
type(mus_convertFac_type), intent(in) :: fac
real(kind=rk), intent(inout) :: state(:)
PDF
integer, intent(in) :: neigh(:)
Connectivity array
type(mus_field_type), intent(inout) :: field(:)
type(mus_mixture_type), intent(inout) :: mixture
integer, intent(in) :: nElems
integer, intent(in) :: nSize
integer, intent(in) :: iLevel
Calls
Called by
Call graph
mus_init_msliquid calls cxdir, ini_state, mus_calc_ms_diffmatrix, mus_calc_thermfactor, invert_matrix, tem_BaryOfId, tem_abort, tem_spatial_for, total
mus_calc_ms_diffmatrix calls mus_calc_ms_diffmatrix_single
mus_calc_thermfactor calls mus_calc_thermfactor_single
mus_init_byic calls mus_init_msliquid
mus_init_flow calls mus_init_byic
mus_initialize calls mus_init_flow
musubi calls mus_initialize