mus_particles_log_total_momentum – Musubi
mus_particles_log_total_momentum Subroutine
46 statements
Source File
public subroutine mus_particles_log_total_momentum(particleGroup, scheme, lev, params, comm, t)
perform_particle_checks computes the total momentum of the fluid and particle phases and logs this to a file
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(in) :: particleGroup
Particle group on this process
type(mus_scheme_type), intent(inout) :: scheme
scheme for access to auxfield
integer, intent(in) :: lev
level in the octree to compute total momentum on
type(mus_param_type), intent(in) :: params
params for access to dt, dx, etc.
integer :: comm
MPI communicator
real(kind=rk) :: t
Current (physical) time
Calls
Call graph
mus_particles_log_total_momentum calls compute_fluid_momentum, compute_particle_momentum, openlogfile
compute_fluid_momentum calls auxfield_varpos, mpi_reduce, property
compute_particle_momentum calls mpi_reduce
openlogfile calls newunit