mus_unload_IBM – Musubi
mus_unload_IBM Subroutine
14 statements
Source File
public subroutine mus_unload_IBM(me, proc, minLevel, maxLevel)
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_type), intent(inout) :: me(:)
IBM data type
type(tem_comm_env_type), intent(in) :: proc
Global parameters
integer, intent(in) :: minLevel
Level range
integer, intent(in) :: maxLevel
Level range
Calls
Called by
Call graph
mus_unload_ibm calls tem_dump_stlb, tem_freeSurfData
mus_perform_dynloadbal calls mus_unload_ibm
mus_solve calls mus_perform_dynloadbal
musubi calls mus_solve