mus_define_d3q13 – Musubi
mus_define_d3q13 Subroutine
12 statements
Source File
private subroutine mus_define_d3q13(layout, nElems)
This subroutine sets the parameters for the predefined d3q13 stencil.
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_layout_type), intent(inout) :: layout
scheme layout for pdf state
integer, intent(in) :: nElems
number of elements use this layout
Calls
Called by
Call graph
mus_define_d3q13 calls mus_calculate_speed_of_sound, mus_set_weights_d3q13, tem_create_stencil, tem_identify_prevailDirections, tem_stencil_zeroPos
mus_calculate_speed_of_sound calls cxcx
mus_define_layout calls mus_define_d3q13
mus_load_scheme calls mus_define_layout
mus_perform_dynloadbal calls mus_define_layout
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_solve calls mus_perform_dynloadbal
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config, mus_solve