mus_particles_mapping_MEM – Musubi
mus_particles_mapping_MEM Subroutine
23 statements
Source File
public subroutine mus_particles_mapping_MEM(particleGroup, scheme, geometry, params)
mus_particles_mapping maps the current particle positions to the lattice This means the exclusionLists are updated, connectivity of solid and fluid neighbor particles is modified, new fluid particles are initialized and have their connectivity restored. Also particles that have no more elements on this process (either local or halo) get removed from this process. Should be called once per LBM time step.
Arguments
Type Intent Optional Attributes Name
class(mus_particle_group_type), intent(inout) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Call graph
mus_particles_mapping_mem calls maptolattice, remove_particle_from_da_particle_mem
maptolattice calls append, baryoftotal, empty, checkforparticleoverlap, computedisplacement, cross_product, make_pdf_tiny, settoequilibrium, updateexclusionlist, updatefluidneighbors, updatenewfluidnodes, updatesolidnodes, property, val
remove_particle_from_da_particle_mem calls swap_da_particle_mem
checkforparticleoverlap calls property, val, findparticlefromelem, tem_abort
make_pdf_tiny calls val, state_varpos
settoequilibrium calls val, state_varpos
updateexclusionlist calls append, empty, getbaryofcoord, getneighborcoord, updateexistsonproc, updateparticleowner, tem_IdOfCoord, tem_PosOfId
updatefluidneighbors calls property, val, cxdirinv, nghelems, state_varpos
updatenewfluidnodes calls property, val, cxdirinv, nghelems, state_varpos
updatesolidnodes calls property, val, state_varpos
updateexistsonproc calls getneighborcoord, tem_IdOfCoord, part_first, part_last, findpartitionoftreeid
updateparticleowner calls tem_IdOfCoord, tem_PosOfId, tem_abort, findpartitionoftreeid