mus_IBMFinishBuff – Musubi
mus_IBMFinishBuff Subroutine
171 statements
Source File
private subroutine mus_IBMFinishBuff(me, IBMData, levelDesc, commPattern, globTree, iLevel, comm, stencil)
This routine finishes the buffers for Xk and X_pdf. This is moved to a seperate routine since both buffers depend on a local communication which should be done nearby the global synchronization point (mus_exchange)
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_type), intent(inout) :: me
datatype to store the surface information
type(mus_IBM_tmpData_type), intent(inout) :: IBMData
tmp IBMData type to be filled
type(tem_levelDesc_type), intent(inout) :: levelDesc
the level descriptor incl. the global send and receive buffers
type(tem_commPattern_type), intent(inout) :: commPattern
communication pattern to be used
type(treelmesh_type), intent(inout) :: globTree
global tree information
integer, intent(in) :: iLevel
current level
integer, intent(in) :: comm
MPI communicator
type(tem_stencilHeader_type), intent(in) :: stencil(:)
array of stencils (1 is the fluid stencil)
Calls
Called by
Call graph
mus_ibmfinishbuff calls append, buf_int, buf_long, buf_real, destroy, elempos, empty, init, nelemsproc, tem_init_surfData, tem_startTimer, tem_stopTimer, tem_treeIDinTotal, tem_updateTree_properties, val
mus_inamuro_ibm calls mus_ibmfinishbuff
do_fast_singlelevel calls mus_inamuro_ibm