mus_particles_runtests – Musubi
mus_particles_runtests Subroutine
15 statements
Source File
public subroutine mus_particles_runtests(particleGroup, scheme, geometry, params)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
type(mus_scheme_type), intent(inout) :: scheme
type(mus_geom_type), intent(in) :: geometry
type(mus_param_type), intent(in) :: params
Calls
Call graph
mus_particles_runtests calls openlogfile, test_global_errorcheck
openlogfile calls newunit
test_global_errorcheck calls mus_particles_global_errorcheck
mus_particles_global_errorcheck calls mpi_allreduce