mus_nNwtn_dump2outUnit – Musubi
mus_nNwtn_dump2outUnit Subroutine
19 statements
Source File
public subroutine mus_nNwtn_dump2outUnit(me, outUnit)
Dump nonNewtonian fluid parameters to outUnit
Arguments
Type Intent Optional Attributes Name
type(mus_nNwtn_type), intent(in) :: me
nonNewtonian parameters
integer, intent(in) :: outUnit
Calls
Called by
Call graph
mus_nnwtn_dump2outunit calls mus_nnwtn_cs_dump, mus_nnwtn_cy_dump, mus_nnwtn_pl_dump, tem_horizontalSpacer
mus_fluid_dump calls mus_nnwtn_dump2outunit
mus_init_fluid calls mus_fluid_dump
mus_hvs_init_aux calls mus_init_fluid
mus_init_aux calls mus_init_fluid
mus_reset_aux calls mus_init_fluid
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_hvs_init_aux