mus_deriveVar_forPoint – Musubi
mus_deriveVar_forPoint Subroutine
14 statements
Source File
public recursive subroutine mus_deriveVar_forPoint(fun, varSys, point, time, tree, nPnts, res)
Derive variable for a given set of points using linear interpolation. This is a generic routine for any variable. Limitation: If neighbor is halo element then its not considered for interpolation, only the fluid (non-ghost) elements in the local process are used for interpolation.
The interface has to comply to the abstract interface tem_varSys_proc_point.
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
real(kind=rk), intent(in) :: point(:,:)
Three-dimensional coordinates at which the variable should be evaluated. Only useful for variables provided as space-time functions.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nPnts
Number of values to obtain for this variable (vectorized access).
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Dimension: n requested entries x nComponents of this variable Access: (iElem-1)*fun%nComponents + iComp
Calls
Call graph
mus_derivevar_forpoint calls mus_dervar_intponpoint
mus_dervar_intponpoint calls get_element, mus_intp_getsrcelemposintree, tem_abort, val
mus_intp_getsrcelemposintree calls nghelems, tem_BaryOfId, tem_CoordOfReal, tem_FirstIdAtLevel, tem_IdOfCoord, tem_LevelOf, tem_ParentOf, tem_PosOfId, tem_eligibleChildren