mus_accessVar_setupIndices – Musubi
mus_accessVar_setupIndices Subroutine
49 statements
Source File
public subroutine mus_accessVar_setupIndices(fun, varSys, point, offset_bit, iLevel, tree, nPnts, idx)
This routine takes points coordinates, stores them in the method_data and return indices where points are located in the growing array of points or values (sometimes we do not need to store the points) It is need to setup points for every variable. Points will be provided by boundaries or sources depends on what uses the variable. This points do not change with time . This indices will be stored in corresponding boundary or source to evaluate a value on that point later using tem_varSys_proc_getValOfIndex.
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, for this routine we need the location where to store the points.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
real(kind=rk), intent(in) :: point(:,:)
arrays of points for which the indices are returned
character(len=1), intent(in), optional :: offset_bit(:)
Offset bit encoded as character for every point. If not present default is to center i.e offset_bit = achar(1+4+16)
integer, intent(in) :: iLevel
the point data need to be loaded levelwise, we need the current level
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nPnts
number of points
integer, intent(out) :: idx(:)
Calls
Call graph
mus_accessvar_setupindices calls append, pntlvl, mus_intp_getsrcelemposinleveldesc, tem_CoordOfReal, tem_IdOfCoord, tem_LevelOf, tem_PosOfId, truncate