mus_addElectricToAuxField_MSL_WTDF – Musubi
mus_addElectricToAuxField_MSL_WTDF Subroutine
58 statements
Source File
public subroutine mus_addElectricToAuxField_MSL_WTDF(fun, auxField, iLevel, time, varSys, phyConvFac, derVarPos)
This routine add electric force to momentum in auxField for multispecies liquid model with thermodynamic factor Refer to Appendix in PhD Thesis of K. Masilamani "Coupled Simulation Framework to Simulate Electrodialysis Process for Seawater Desalination"
Arguments
Type Intent Optional Attributes Name
class(mus_source_op_type), intent(inout) :: fun
Description of method to update source
real(kind=rk), intent(inout) :: auxField(:)
output auxField array
integer, intent(in) :: iLevel
current level
type(tem_time_type), intent(in) :: time
current timing information
type(tem_varSys_type), intent(in) :: varSys
variable system definition
type(mus_convertFac_type), intent(in) :: phyConvFac
Physics conversion factor for current level
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
position of derived quantities in varsys
Calls
Call graph
mus_addelectrictoauxfield_msl_wtdf calls auxfield_varpos, get_valofindex, input_varpos, mus_calc_thermfactor, invert_matrix, val
mus_calc_thermfactor calls mus_calc_thermfactor_single