mus_IBM_buildSendRecv_Xk – Musubi
mus_IBM_buildSendRecv_Xk Subroutine
111 statements
Source File
private subroutine mus_IBM_buildSendRecv_Xk(me, IBMData, levelDesc, commPattern, globTree, iLevel, params)
This subroutine builds the communication types for the lagrangian elements Xk.
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_type), intent(inout) :: me
datatype to store the surface information
type(mus_IBM_tmpData_type), intent(inout) :: IBMData
tmp IBMData type to be filled
type(tem_levelDesc_type), intent(inout) :: levelDesc
the level descriptor incl. the global send and receive buffers
type(tem_commPattern_type), intent(inout) :: commPattern
communication pattern to be used
type(treelmesh_type), intent(inout) :: globTree
global tree information
integer, intent(in) :: iLevel
current level
type(mus_param_type), intent(inout) :: params
global parameters
Calls
Called by
Call graph
mus_ibm_buildsendrecv_xk calls append, buf_int, elempos, nelems, nelemsproc, proc, mus_ibm_commnewpos, ptrs, tem_startTimer, tem_stopTimer, val
mus_ibm_commnewpos calls append, buf_int, elempos, nelems, nelemsproc, proc, ptrs, val, buf_real, empty, init, tem_init_surfData
mus_buildbuffibm calls mus_ibm_buildsendrecv_xk
do_fast_singlelevel calls mus_buildbuffibm