mus_get_points_fromBC – Musubi
mus_get_points_fromBC Subroutine
63 statements
Source File
public subroutine mus_get_points_fromBC(bc, globBC, tree, stencil, total, iLevel, nPoints, points, offset_bit)
Get Surface points on boundary elements. For boundary state variable which are evaluated linkwise, extract surface points for each link and for non-link based variables project barycenter on the boundary surface. Return real coordinates on boundary surface and offset bit which encodes direction.
Arguments
Type Intent Optional Attributes Name
type(boundary_type), intent(in) :: bc
Field boundary type
type(glob_boundary_type), intent(in) :: globBC
for number of elements in boundary and position in buffer
type(treelmesh_type), intent(in) :: tree
global treelm mesh
type(tem_stencilHeader_type), intent(in) :: stencil
for directions
integer(kind=long_k), intent(in) :: total(:)
global pdf type
integer, intent(in) :: iLevel
Current level
integer, intent(out) :: nPoints
Number of points
real(kind=rk), intent(out), allocatable :: points(:,:)
3-d real coordinates on which boundary variables are evaluated
character(len=1), intent(out), allocatable :: offset_bit(:)
Offset bit encodes direction of boundary. used by apesmate to translate space coordinate in the offset direction to determine the treeID in remote domain
Calls
Called by
Call graph
mus_get_points_frombc calls tem_BaryOfId, tem_ElemSizeLevel, val
mus_setupindices_forbc calls mus_get_points_frombc
init_boundary_single calls mus_setupindices_forbc
mus_init_boundary calls init_boundary_single
mus_initialize calls mus_init_boundary
mus_reset_aux calls mus_init_boundary