mus_init_advRel_fluidIncomp_bgk – Musubi
mus_init_advRel_fluidIncomp_bgk Subroutine
22 statements
Source File
private subroutine mus_init_advRel_fluidIncomp_bgk(variant, layout, compute)
This routine assigns compute routine for bgk relaxation
Supported variants are: * standard - Optimized routines for specifc layouts. * standard_no_opt - no optimized routines for any layouts.
Arguments
Type Intent Optional Attributes Name
character(len=labelLen), intent(in) :: variant
character(len=labelLen), intent(in) :: layout
procedure(kernel), intent(out), pointer :: compute
Calls
Called by
Call graph
mus_init_advrel_fluidincomp_bgk calls tem_abort
mus_init_advrel_fluidincomp calls mus_init_advrel_fluidincomp_bgk
init_advrel calls mus_init_advrel_fluidincomp
mus_init_flow calls init_advrel
mus_initialize calls mus_init_flow