mus_balance – Musubi
mus_balance Subroutine
24 statements
Source File
private subroutine mus_balance(tree, minLevel, maxLevel, levelDesc, nBCs, globBC, general, sparta)
This routine performs the load balancing for multilevel simulations. The weights are calculated on the basis of levelwise run time, which are then fed to sparta for calculation of splitting positions. Restart files are saved and the simulation is restarted with the newly distributed mesh
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(inout) :: tree
geometry infomation
integer, intent(in) :: minLevel
min level and max level
integer, intent(in) :: maxLevel
min level and max level
type(tem_levelDesc_type), intent(in) :: levelDesc(minLevel:maxLevel)
Level descriptor
integer, intent(in) :: nBCs
global IBM type Number of boundary conditions
type(glob_boundary_type), intent(in) :: globBC(nBCs)
BC elements information
type(tem_general_type), intent(in) :: general
global parameters
type(tem_sparta_type), intent(inout) :: sparta
Sparta data type
Calls
Called by
Call graph
mus_balance calls mus_dumpweights, mus_getweights, tem_balance_sparta, tem_timeformatter_init
mus_dumpweights calls tem_create_EndianSuffix, tem_dump_weights
mus_getweights calls get_bcbuffertime, get_boundarytime, get_computetime, get_intpfromcoarsertime, get_intpfromfinertime, nelems, tem_LevelOf, val
get_bcbuffertime calls get_bcbuffertime_atlevel, get_bcbuffertime_total
get_boundarytime calls get_boundarytime_byid, get_boundarytime_total
get_computetime calls get_computetime_atlevel, get_computetime_total
get_intpfromcoarsertime calls get_intpfromcoarsertime_atlevel, get_intpfromcoarsertime_total
get_intpfromfinertime calls get_intpfromfinertime_atlevel, get_intpfromfinertime_total
get_bcbuffertime_atlevel calls tem_getTimerVal
get_bcbuffertime_total calls get_bcbuffertime
get_boundarytime_byid calls tem_getTimerVal
get_boundarytime_total calls get_boundarytime
get_computetime_atlevel calls tem_getTimerVal
get_computetime_total calls get_computetime
get_intpfromcoarsertime_atlevel calls tem_getTimerVal
get_intpfromcoarsertime_total calls get_intpfromcoarsertime
get_intpfromfinertime_atlevel calls tem_getTimerVal
get_intpfromfinertime_total calls tem_getTimerVal
mus_perform_dynloadbal calls mus_balance
mus_solve calls mus_perform_dynloadbal
musubi calls mus_solve