mus_scheme_cleanup – Musubi
mus_scheme_cleanup Subroutine
34 statements
Source File
public subroutine mus_scheme_cleanup(me, minLevel, maxLevel, nBCs)
This subroutine acts as a destructor for the construct routine
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: me
scheme information including fluid, boundary and flow information
integer, intent(in) :: minLevel
minlevel
integer, intent(in) :: maxLevel
maxlevel
integer, intent(in) :: nBCs
Number of boundary conditions
Calls
Called by
Call graph
mus_scheme_cleanup calls destroy, instance, mus_field_cleanup, mus_source_cleanup, tem_destroy_subTree_of_st_funList
mus_field_cleanup calls mus_source_cleanup, mus_fieldbc_cleanup, mus_fluid_cleanup
mus_perform_dynloadbal calls mus_scheme_cleanup
mus_solve calls mus_perform_dynloadbal
musubi calls mus_solve