mus_scheme_out – Musubi
mus_scheme_out Subroutine
12 statements
Source File
public subroutine mus_scheme_out(me, conf)
Dump single scheme info into restart solver specific conf to dump solver specific information in restart header file
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: me
schemes to dump to restart header file
type(aot_out_type), intent(inout), optional :: conf
aotus type handling the output to the file in lua format
Calls
Called by
Call graph
mus_scheme_out calls mus_fields_out, mus_interpolate_out, mus_mixture_out, mus_scheme_header_out
mus_fields_out calls mus_field_out_scal, mus_fields_out_vec
mus_interpolate_out calls aot_out_val
mus_mixture_out calls aot_out_close_table, aot_out_open_table, aot_out_val
mus_scheme_header_out calls aot_out_close_table, aot_out_open_table, aot_out_val
mus_field_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val, mus_field_prop_out
mus_fields_out_vec calls aot_out_close_table, aot_out_open_table, aot_out_val, mus_field_out_scal
mus_field_prop_out calls mus_fluid_save2lua, mus_species_out
mus_writesolverspecinfo calls mus_scheme_out