mus_assign_GradCalculation_ptr – Musubi
mus_assign_GradCalculation_ptr Function
26 statements
Source File
public function mus_assign_GradCalculation_ptr(label) result(Grad)
This function returns function pointer of nonEquilibrium scaling for interpolation according to scheme definition
Arguments
Type Intent Optional Attributes Name
character(len=labelLen), intent(in) :: label
Scheme header information
Return Value type(mus_Grad_type)
GradRhoU3 function
Calls
Called by
Call graph
mus_assign_gradcalculation_ptr calls tem_abort
mus_init_scheme calls mus_assign_gradcalculation_ptr
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve