mus_dump_moments – Musubi
mus_dump_moments Subroutine
9 statements
Source File
public subroutine mus_dump_moments(me, outUnit)
Dump moments matrix: toPDF and toMoment
Arguments
Type Intent Optional Attributes Name
type(mus_moment_type), intent(in) :: me
integer, intent(in) :: outUnit
Calls
Called by
Call graph
mus_dump_moments calls tem_matrix_dump
mus_init_moments calls mus_dump_moments
mus_init_scheme calls mus_init_moments
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme