mus_init_tracker – Musubi
mus_init_tracker Subroutine
23 statements
Source File
public subroutine mus_init_tracker(scheme, geometry, params)
This routine initialize tracking subTree to remove empty tracking objects. On active tracking objects: Homogenize time control, write solver speific info for harvester output format and initialize output using tem_init_tracker
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme type
type(mus_geom_type), intent(in) :: geometry
Treelmesh data
type(mus_param_type), intent(in) :: params
Global parameters
Calls
Called by
Call graph
mus_init_tracker calls config, instance, mus_timecontrol_homogenize, tem_init_tracker, tem_init_tracker_subTree
mus_timecontrol_homogenize calls tem_timeControl_dump
mus_hvs_init_aux calls mus_init_tracker
mus_init_aux calls mus_init_tracker
mus_reset_aux calls mus_init_tracker
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_hvs_init_aux
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve