mus_particles_initialize – Musubi
mus_particles_initialize Subroutine
141 statements
Source File
public subroutine mus_particles_initialize(particleGroup, scheme, geometry, params)
Initialization for particleGroup and all the particles in it Includes: * Assigning the required procedure pointers for particleGroup and particles * Initializing loggers * Initializing communication routines * Building the representation of the particles on the grid
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), target :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Called by
Call graph
mus_particles_initialize calls init_particle_interpolator, init_particle_logger, mus_particles_initialize_communication, mus_particles_updatefluidvolumefraction, tem_CoordOfReal, tem_abort
init_particle_interpolator calls getpathtovec
init_particle_logger calls newunit
mus_particles_initialize_communication calls init, find_particle_comm_procs4, init_mus_particles_comm_type, mus_particles_comm_init_buffers, mus_particles_initforcecontributionmpitype, mus_particles_initparticleinfompitype, mus_particles_initparticlestatempitype, mus_particles_initpositionupdatempitype, mus_particles_initwallposmpitype
mus_particles_updatefluidvolumefraction calls auxfield_varpos, distributeparticlevolume
mus_initialize calls mus_particles_initialize
musubi calls mus_initialize