mus_nNwtn_PL_dump – Musubi
mus_nNwtn_PL_dump Subroutine
6 statements
Source File
private subroutine mus_nNwtn_PL_dump(me, outUnit)
Dump nonNewtonian Power Law (PL) parameters to outUnit
Arguments
Type Intent Optional Attributes Name
type(mus_nNwtn_PL_type), intent(in) :: me
nonNewtonian parameters
integer, intent(in) :: outUnit
Called by
Call graph
mus_nnwtn_dump2outunit calls mus_nnwtn_pl_dump
mus_fluid_dump calls mus_nnwtn_dump2outunit
mus_init_fluid calls mus_fluid_dump
mus_hvs_init_aux calls mus_init_fluid
mus_init_aux calls mus_init_fluid
mus_reset_aux calls mus_init_fluid