mus_init_geomIncr – Musubi
mus_init_geomIncr Subroutine
15 statements
Source File
public subroutine mus_init_geomIncr(me, varSys, dt, reqInt)
This subroutine initializes the geometry increment.
Arguments
Type Intent Optional Attributes Name
type(mus_geomIncrHead_type), intent(inout) :: me(:)
geometry increment type
type(tem_varSys_type), intent(in) :: varSys
Global variable system
real(kind=rk), intent(in) :: dt
dt of maxlevel or smallest dt
integer, intent(in) :: reqInt
Required interval, in which the update MUST occur. This is required for the musubi multilevel, where the time step should only be determined active, when the end of the largest cycle is reached.
Calls
Called by
Call graph
mus_init_geomincr calls positionofval, mus_timecontrol_homogenize, tem_abort
mus_timecontrol_homogenize calls tem_timeControl_dump
mus_init_aux calls mus_init_geomincr
mus_initialize calls mus_init_aux
musubi calls mus_initialize