mus_update_relaxParamKine – Musubi
mus_update_relaxParamKine Subroutine
18 statements
Source File
public subroutine mus_update_relaxParamKine(viscKine, turb, nSolve, iLevel)
Update kinematic relaxation parameter from viscosity and check omega
Arguments
Type Intent Optional Attributes Name
type(mus_viscosity_type), intent(inout) :: viscKine
Kinematic viscosity
type(mus_turbulence_type), intent(in) :: turb
turbulence type
integer, intent(in) :: nSolve
Number of elements to solve in compute kernel
integer, intent(in) :: iLevel
current level
Calls
Called by
Call graph
mus_update_relaxparamkine calls val
mus_update_relaxparams calls mus_update_relaxparamkine
do_benchmark calls mus_update_relaxparams
do_fast_singlelevel calls mus_update_relaxparams
do_recursive_multilevel calls mus_update_relaxparams