mus_update_relaxParams – Musubi
mus_update_relaxParams Subroutine
24 statements
Source File
public subroutine mus_update_relaxParams(scheme, iLevel, tNow, physics, lattice, nBCs)
Set relaxation parameters for MRT
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme type
integer, intent(in) :: iLevel
level
type(tem_time_type), intent(in) :: tNow
global parameters
type(mus_physics_type), intent(in) :: physics
contains factors to convert physical to lattice unit and vice versa
type(mus_latticeUnit_type), intent(in) :: lattice
contains lattice dx and dt
integer, intent(in) :: nBCs
Number of boundaries
Calls
Called by
Call graph
mus_update_relaxparams calls nelems, mus_turb_updateviscofturbwall, mus_update_relaxparamkine, mus_update_visckine, setparameters_multispecies, tvisc
mus_update_relaxparamkine calls val
mus_update_visckine calls auxfield_varpos, calcvisc, mus_turb_calcvisc, tem_spacetime_for, val
setparameters_multispecies calls invert_matrix, tem_temporal_for
do_benchmark calls mus_update_relaxparams
do_fast_singlelevel calls mus_update_relaxparams
do_recursive_multilevel calls mus_update_relaxparams