mus_load_fluid – Musubi
mus_load_fluid Subroutine
120 statements
Source File
public subroutine mus_load_fluid(me, conf, parent, minLevel, physics, schemeHeader)
Read in the fluid property from the LUA parameter file
"Theory of the lattice Boltzmann method: Dispersion, dissipation, isotropy, Galilean invariance, and stability", Pierre Lallemand and Li-Shi Luo, Phys. Rev. E 61, 2000.
Arguments
Type Intent Optional Attributes Name
type(mus_fluid_type), intent(out) :: me
fluid type
type(flu_State) :: conf
lua state
integer, intent(in), optional :: parent
parent handle
integer, intent(in) :: minLevel
global pdf info
type(mus_physics_type), intent(in) :: physics
physics type to convert physics to lattice unit or vice versa
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
Calls
Called by
Call graph
mus_load_fluid calls aot_get_val, aot_table_close, aot_table_open, mus_load_turbulence, mus_nnwtn_load, tem_abort, tem_horizontalSpacer, tem_load_spacetime
mus_load_turbulence calls aot_get_val, aot_table_close, aot_table_open, tem_abort, tem_horizontalSpacer, upper_to_lower
mus_nnwtn_load calls aot_get_val, aot_table_close, aot_table_open, tem_abort, mus_nnwtn_cs_load, mus_nnwtn_cy_load, mus_nnwtn_pl_load, upper_to_lower
mus_nnwtn_cs_load calls aot_get_val
mus_nnwtn_cy_load calls aot_get_val
mus_nnwtn_pl_load calls aot_get_val
mus_load_field_prop calls mus_load_fluid
mus_load_field_single calls mus_load_field_prop
mus_load_fields calls mus_load_field_single
mus_load_scheme calls mus_load_fields