mus_load_particle_dps_data_chunk – Musubi
mus_load_particle_dps_data_chunk Subroutine
79 statements
Source File
public subroutine mus_load_particle_dps_data_chunk(conf, parent, particlebuffer, nchunkvals, key, istart)
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
integer, intent(in), optional :: parent
handle to parent table if position, velocity tables etc are inside another table
type(mus_particle_DPS_type), intent(inout), allocatable :: particlebuffer(:)
integer, intent(out) :: nchunkvals
character(len=*), intent(in) :: key
integer, intent(in) :: istart
Calls
Called by
Call graph
mus_load_particle_dps_data_chunk calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, tem_abort
load_particle_dps_creator_data calls mus_load_particle_dps_data_chunk
load_particle_dps_data calls mus_load_particle_dps_data_chunk
mus_load_particles calls load_particle_dps_creator_data
mus_initialize calls mus_load_particles
musubi calls mus_initialize