mus_append_sourceVar – Musubi
mus_append_sourceVar Subroutine
289 statements
Source File
private subroutine mus_append_sourceVar(me, solverData, schemeHeader, varSys, nFields, stencil, poss_srcVar, fldLabel)
Build a variable system of all possible source terms for the given schemeKind
Arguments
Type Intent Optional Attributes Name
type(mus_source_type), intent(inout) :: me
Contains source function pointer, source variable definition from lua and mapping of source variable in global varSys
type(mus_varSys_solverData_type), intent(in), target :: solverData
Contains pointer to solver data types
type(mus_scheme_header_type), intent(in) :: schemeHeader
Identifier of the scheme
type(tem_varSys_type), intent(inout) :: varSys
Global variable system
integer, intent(in) :: nFields
number of fields
type(tem_stencilHeader_type), intent(in) :: stencil
compute stencil defintion
type(tem_possible_variable_type), intent(in) :: poss_srcVar
possible source variables
character(len=*), intent(in), optional :: fldLabel
array of field label prefix required only for field source. If not present, it is assumed as global source
Calls
Called by
Call graph
mus_append_sourcevar calls input_varpos, positionofval, mus_get_new_solver_ptr, tem_abort, tem_varSys_append_derVar, tem_varSys_dump, val
mus_build_varsys calls mus_append_sourcevar
mus_init_scheme calls mus_build_varsys
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize