mus_calcBndForce_wall – Musubi
mus_calcBndForce_wall Subroutine
36 statements
Source File
private subroutine mus_calcBndForce_wall(me, bndForce, bndMoment, posInBndID, globBC, currState, levelDesc, nSize, iLevel, neigh, layout, nScalars, phyConvFac)
This routine computes bndForce on wall boundary elements
Arguments
Type Intent Optional Attributes Name
class(boundary_type), intent(in) :: me
field boundary type
real(kind=rk), intent(inout) :: bndForce(:,:)
bndForce to fill
real(kind=rk), intent(inout) :: bndMoment(:,:)
Boundary moment on wall boundary
integer, intent(in) :: posInBndID(:)
type(glob_boundary_type), intent(in) :: globBC
scheme global boundary type
real(kind=rk), intent(in) :: currState(:)
current state array to access post-collision values
type(tem_levelDesc_type), intent(in) :: levelDesc
iLevel descriptor
integer, intent(in) :: nSize
size of state array (in terms of elements)
integer, intent(in) :: iLevel
level which invokes boundary
integer, intent(in) :: neigh(:)
global parameters
type(mus_scheme_layout_type), intent(in) :: layout
scheme layout
integer, intent(in) :: nScalars
number of Scalars in the scheme var system
type(mus_convertFac_type), intent(in) :: phyConvFac
physics conversion factor
Calls
Call graph
mus_calcbndforce_wall calls cross_product3D, cxdirinv, cxdirrk, val