mus_finishIBM – Musubi
mus_finishIBM Subroutine
37 statements
Source File
public subroutine mus_finishIBM(me, params, useTime)
This routine dumps the timings%timedat to disc
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_globType), intent(inout) :: me
global IBM datatype incl. array of IBM datatypes
type(mus_param_type), intent(in) :: params
global parameters
logical, intent(in) :: useTime
use the timestamps when dumping the info?
Calls
Called by
Call graph
mus_finishibm calls newunit, tem_getMaxTimerVal, tem_resetTimer, tem_timeformatter_init, val
mus_finalize calls mus_finishibm
mus_solve calls mus_finishibm
musubi calls mus_finalize, mus_solve