mus_set_inletUbb – Musubi
mus_set_inletUbb Subroutine
50 statements
Source File
public subroutine mus_set_inletUbb(me, tree, stencil, nScalars, globBC, levelDesc, varPos, nLinks, minLevel, maxLevel)
Set necessary data for BC velocity_bounceback_qval
Bitmask is true for incoming direction
Arguments
Type Intent Optional Attributes Name
type(bc_inlet_bouzidi_type), intent(out), allocatable :: me(:)
setting type for bc
type(treelmesh_type), intent(in) :: tree
using mesh information
type(tem_stencilHeader_type), intent(in) :: stencil
for directions
integer, intent(in) :: nScalars
number of scalars
type(glob_boundary_type), intent(in) :: globBC
for number of elements in boundary and position in buffer
type(tem_levelDesc_type), intent(in) :: levelDesc(minLevel:maxLevel)
level descriptor
integer, intent(in) :: varPos(:)
for position of outgoing elements
integer, intent(in) :: nLinks(minLevel:maxLevel)
for linkwise treatment
integer, intent(in) :: minLevel
minimum and maximum level
integer, intent(in) :: maxLevel
minimum and maximum level
Calls
Called by
Call graph
mus_set_inletubb calls tem_BaryOfId, tem_ElemSizeLevel, val
init_boundary_single calls mus_set_inletubb
mus_init_boundary calls init_boundary_single
mus_initialize calls mus_init_boundary
mus_reset_aux calls mus_init_boundary
mus_perform_dynloadbal calls mus_reset_aux
musubi calls mus_initialize