mus_get_new_solver_ptr – Musubi
mus_get_new_solver_ptr Function
8 statements
Source File
public function mus_get_new_solver_ptr(solver) result(resPtr)
Routine to get a pointer to a new instance of mus_varSys_solverData_type to be used as method data for a variable in the variable system.
A new instance is allocated and a c_ptr to this type is returned. Be aware that local pointer are not automatically deallocated when leaving the routine
TODO init the point arrays
Arguments
Type Intent Optional Attributes Name
type(mus_varSys_solverData_type), intent(in), optional, target :: solver
The prototype is used to initialize the new instance.
Return Value type(c_ptr)
Pointer to the newly created instance.
Called by
Call graph
mus_append_auxfield calls mus_get_new_solver_ptr
mus_append_bcvar calls mus_get_new_solver_ptr
mus_append_derliquidmixvar calls mus_get_new_solver_ptr
mus_append_dermixvar_ms calls mus_get_new_solver_ptr
mus_append_dervar_fluid calls mus_get_new_solver_ptr
mus_append_dervar_fluidincomp calls mus_get_new_solver_ptr
mus_append_dervar_isotherm_aceq calls mus_get_new_solver_ptr
mus_append_dervar_lbmps calls mus_get_new_solver_ptr
mus_append_dervar_msgas calls mus_get_new_solver_ptr, mus_append_dermixvar_ms
mus_append_dervar_msliquid calls mus_get_new_solver_ptr, mus_append_derliquidmixvar, mus_append_dermixvar_ms
mus_append_dervar_physics calls mus_get_new_solver_ptr
mus_append_dervar_poisson calls mus_get_new_solver_ptr
mus_append_materialvar calls mus_get_new_solver_ptr
mus_append_readvarasstatevar calls mus_get_new_solver_ptr
mus_append_sourcevar calls mus_get_new_solver_ptr
mus_append_statevar calls mus_get_new_solver_ptr
mus_append_turbvar calls mus_get_new_solver_ptr
mus_set_opvar_getelement calls mus_get_new_solver_ptr
mus_set_stfun_getelement calls mus_get_new_solver_ptr
mus_build_varsys calls mus_append_auxfield, mus_append_bcvar, mus_append_dervar_fluid, mus_append_dervar_fluidincomp, mus_append_dervar_isotherm_aceq, mus_append_dervar_lbmps, mus_append_dervar_msgas, mus_append_dervar_msliquid, mus_append_dervar_physics, mus_append_dervar_poisson, mus_append_materialvar, mus_append_sourcevar, mus_append_turbvar
mus_load_scheme calls mus_append_readvarasstatevar, mus_append_statevar
mus_hvs_load_solverdata calls mus_load_scheme
mus_init_scheme calls mus_build_varsys
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme
musubi calls mus_load_config