mus_load_species – Musubi
mus_load_species Subroutine
97 statements
Source File
public subroutine mus_load_species(me, conf, parent, minLevel, nFields, physics, cs_lattice)
this routines load species table from config file
 species = { molweight = 1.0, diff_coeff = { 0.5,0.3,0.1 } }
if species handle is not defined convert physics to lattice unit \todo KM: Compute omega for each level
Arguments
Type Intent Optional Attributes Name
type(mus_species_type), intent(out) :: me
type(flu_State) :: conf
integer, intent(in), optional :: parent
integer, intent(in) :: minLevel
integer, intent(in) :: nFields
type(mus_physics_type), intent(in) :: physics
physics type to convert physics to lattice unit or vice versa
real(kind=rk), intent(in) :: cs_lattice
lattice speed of sound calculated for defined stencil layout required to compute omega from potential diffusivity
Calls
Called by
Call graph
mus_load_species calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, tem_abort, tem_horizontalSpacer
mus_load_field_prop calls mus_load_species
mus_load_field_single calls mus_load_field_prop
mus_load_fields calls mus_load_field_single
mus_load_scheme calls mus_load_fields