mus_init_turb_wallFunc – Musubi
mus_init_turb_wallFunc Subroutine
56 statements
Source File
private subroutine mus_init_turb_wallFunc(bc, globBC, auxField, viscKine, derVarPos, varSys, stencil, iLevel)
This routine allocates turbulent viscosity and friction velocity on boundary elements. It also initialize friction velocity from stream-wise velocity component on first neighbor in normal direction.
Arguments
Type Intent Optional Attributes Name
type(boundary_type), intent(inout) :: bc
Field bc which contains turbwallFunc type and neighbor info
type(glob_boundary_type), intent(inout) :: globBC
global bc of current boundary with elemPos and normal info
real(kind=rk), intent(in) :: auxField(:)
auxField array
type(mus_viscosity_type) :: viscKine
Kinematic viscosity
type(mus_derVarPos_type), intent(in) :: derVarPos
position of derived quantities in varsys
type(tem_varSys_type), intent(in) :: varSys
scheme variable system
type(tem_stencilHeader_type), intent(in) :: stencil
stencil info
integer, intent(in) :: iLevel
current level
Calls
Called by
Call graph
mus_init_turb_wallfunc calls auxfield_varpos, val
init_boundary_single calls mus_init_turb_wallfunc
mus_init_boundary calls init_boundary_single
mus_initialize calls mus_init_boundary
mus_reset_aux calls mus_init_boundary
mus_perform_dynloadbal calls mus_reset_aux
musubi calls mus_initialize