mus_create_poss_transVar – Musubi
mus_create_poss_transVar Subroutine
13 statements
Source File
public subroutine mus_create_poss_transVar(poss_transVar, schemeHeader)
Routine initialize possible transport variable depends on scheme kind
Arguments
Type Intent Optional Attributes Name
type(tem_possible_variable_type), intent(out) :: poss_transVar
possible transport variables
type(mus_scheme_header_type), intent(in) :: schemeHeader
Identifier of the scheme
Calls
Called by
Call graph
mus_create_poss_transvar calls append, init, truncate
mus_load_scheme calls mus_create_poss_transvar
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load