mus_calcOmegaFromVisc – Musubi
mus_calcOmegaFromVisc Function
5 statements
Source File
public elemental function mus_calcOmegaFromVisc(visc) result(omega)
This function compute relaxation paramter omega from viscosity
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: visc
scaled lattice viscosity i.e vL_c/dtL
Return Value real(kind=rk)
lattice time step size in current level real(kind=rk), intent(in) :: dtL output: relaxation parameter omega
Called by
Call graph
fillfinerghostsfromme_linear2d_feq_fneq calls mus_calcomegafromvisc
fillfinerghostsfromme_linear_feq_fneq calls mus_calcomegafromvisc
fillfinerghostsfromme_linearles_feq_fneq calls mus_calcomegafromvisc
fillfinerghostsfromme_quad2d_feq_fneq calls mus_calcomegafromvisc
fillfinerghostsfromme_quad_feq_fneq calls mus_calcomegafromvisc
fillfinerghostsfromme_quadles_feq_fneq calls mus_calcomegafromvisc
fillfinerghostsfromme_weighavg2d_feq_fneq calls mus_calcomegafromvisc
fillfinerghostsfromme_weighavg_feq_fneq calls mus_calcomegafromvisc
fillfinerghostsfromme_weighavgles_feq_fneq calls mus_calcomegafromvisc
fillmyghostsfromfiner_avg2d_feq_fneq calls mus_calcomegafromvisc
fillmyghostsfromfiner_avg_feq_fneq calls mus_calcomegafromvisc
fillmyghostsfromfiner_avgles_feq_fneq calls mus_calcomegafromvisc
mus_fluid_dump calls mus_calcomegafromvisc
mus_update_relaxparamfromviscstfun calls mus_calcomegafromvisc
mus_init_fluid calls mus_fluid_dump, mus_update_relaxparamfromviscstfun
mus_hvs_init_aux calls mus_init_fluid
mus_init_aux calls mus_init_fluid
mus_reset_aux calls mus_init_fluid
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_hvs_init_aux