mus_build_minBcID – Musubi
mus_build_minBcID Subroutine
12 statements
Source File
private subroutine mus_build_minBcID(minBcID, bc_prop, posInBndID)
This routine build minBcID for boundary elements, it is required if a element has more than one boundary in its directions. if a element has more than one boundary then use minBcID which depends on boundary order in seeder configuration
Arguments
Type Intent Optional Attributes Name
integer, intent(out), allocatable :: minBcID(:)
type(tem_BC_prop_type), intent(in) :: bc_prop
boundary information from mesh
integer, intent(in) :: posInBndID(:)
tree element position in boundaryID
Called by
Call graph
mus_build_posinprop calls mus_build_minbcid
exchange_tree_bc calls mus_build_posinprop
mus_load_bc_data calls mus_build_posinprop
mus_hvs_config_load calls mus_load_bc_data
mus_load_geom calls mus_load_bc_data
mus_perform_dynloadbal calls exchange_tree_bc
mus_load_config calls mus_load_geom
mus_harvesting calls mus_hvs_config_load