mus_build_posInProp – Musubi
mus_build_posInProp Subroutine
19 statements
Source File
public subroutine mus_build_posInProp(me)
This routine builds mapping between elements in tree to to propery list
Arguments
Type Intent Optional Attributes Name
type(mus_geom_type), intent(inout) :: me
Calls
Called by
Call graph
mus_build_posinprop calls mus_build_minbcid, property, tem_build_treeToProp_pointer
exchange_tree_bc calls mus_build_posinprop
mus_load_bc_data calls mus_build_posinprop
mus_hvs_config_load calls mus_load_bc_data
mus_load_geom calls mus_load_bc_data
mus_perform_dynloadbal calls exchange_tree_bc
mus_load_config calls mus_load_geom
mus_solve calls mus_perform_dynloadbal
mus_harvesting calls mus_hvs_config_load
musubi calls mus_load_config, mus_solve