mus_particles_move_DPS – Musubi
mus_particles_move_DPS Subroutine
7 statements
Source File
public subroutine mus_particles_move_DPS(particleGroup, scheme, geometry, params)
This routine moves all particles in particleArray.
Arguments
Type Intent Optional Attributes Name
class(mus_particle_group_type), intent(inout) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Call graph
mus_particles_move_dps calls demsubcycles_dps
demsubcycles_dps calls dem_swapfnowfnext, updatepositionverlet, updatevelocityverlet, dem_fillneighborlist, exchangemominc_dps, exchangepositions_dps, exchangevelocities_dps, incrementauxfield_dps, mapparticlestolattice_dps, recalculate_auxfield_dps, updateparticleforces, wrapperiodicpos, tem_startTimer, tem_stopTimer, val