mus_append_derMixVar_MS – Musubi
mus_append_derMixVar_MS Subroutine
86 statements
Source File
public subroutine mus_append_derMixVar_MS(varSys, solverData, nFields, fldLabel, derVarName)
Append mixture variables for multicomponent models
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
global variable system
type(mus_varSys_solverData_type), intent(in), target :: solverData
Contains pointer to solver data types
integer, intent(in) :: nFields
number of fields
character(len=*), intent(in) :: fldLabel(:)
array of field label prefix. Size=nFields
type(grw_labelarray_type), intent(in) :: derVarName
array of derive physical variable
Calls
Called by
Call graph
mus_append_dermixvar_ms calls positionofval, mus_get_new_solver_ptr, tem_abort, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
mus_append_dervar_msgas calls mus_append_dermixvar_ms
mus_append_dervar_msliquid calls mus_append_dermixvar_ms
mus_build_varsys calls mus_append_dervar_msgas, mus_append_dervar_msliquid
mus_init_scheme calls mus_build_varsys
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme