mus_particles_applyHydrodynamicForces_MEM – Musubi
mus_particles_applyHydrodynamicForces_MEM Subroutine
44 statements
Source File
public subroutine mus_particles_applyHydrodynamicForces_MEM(particleGroup, scheme, geometry, params)
Arguments
Type Intent Optional Attributes Name
class(mus_particle_group_type), intent(inout) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Call graph
mus_particles_applyhydrodynamicforces_mem calls allocateprocessmasks, applyhydrodynamicforces, destroyparticle_mem, initparticle_mem, remove_particle_from_da_particle_mem, swapfbuff
allocateprocessmasks calls allocateprocessmasks_dps
applyhydrodynamicforces calls baryoftotal, cxdirinv, nghelems, calcperiodicrsurface, cross_product, property, state_varpos, val
destroyparticle_mem calls append, baryoftotal, empty, computedisplacement, cross_product, settoequilibrium, updatenewfluidnodes, property, val
initparticle_mem calls init, make_pdf_tiny, updateexclusionlist, updatefluidneighbors, updatesolidnodes
remove_particle_from_da_particle_mem calls swap_da_particle_mem