mus_field_cleanup – Musubi
mus_field_cleanup Subroutine
22 statements
Source File
public subroutine mus_field_cleanup(me, schemeHeader, minLevel, maxLevel, nBCs, nFields)
This routines act as a destructor for field type. Only allocatable arrays which are allocated in mus_construct routine are deallocated. KM: DO NOT DESTROY FIELD ARRAY AS IT CONTAINS ALL CONFIG INFO
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(inout) :: me(:)
single field type
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
integer, intent(in) :: minLevel
minlevel
integer, intent(in) :: maxLevel
maxlevel
integer, intent(in) :: nBCs
Number of boundary conditions
integer, intent(in) :: nFields
Number of fields
Calls
Called by
Call graph
mus_field_cleanup calls mus_fieldbc_cleanup, mus_fluid_cleanup, mus_source_cleanup
mus_scheme_cleanup calls mus_field_cleanup
mus_perform_dynloadbal calls mus_scheme_cleanup
mus_solve calls mus_perform_dynloadbal
musubi calls mus_solve