mus_particles_initParticleInfoMPItype – Musubi
mus_particles_initParticleInfoMPItype Subroutine
17 statements
Source File
public subroutine mus_particles_initParticleInfoMPItype()
Routine to create and commit the MPI type used to communicate all continuous particle data
Arguments
None
Calls
Called by
Call graph
mus_particles_initparticleinfompitype calls mpi_aint_diff, mpi_get_address, mpi_type_commit, mpi_type_create_struct
mus_particles_initialize_communication calls mus_particles_initparticleinfompitype
mus_particles_initialize calls mus_particles_initialize_communication
mus_initialize calls mus_particles_initialize
musubi calls mus_initialize