mus_IBM_fillSendPos_X – Musubi
mus_IBM_fillSendPos_X Subroutine
37 statements
Source File
private subroutine mus_IBM_fillSendPos_X(IBMData, globSend, treeIDPos, startPos, parentID, globTree, added, match)
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_tmpData_type), intent(inout) :: IBMData
IBM temporary datatype incl. map2glob and communicator for send and recv
type(tem_communication_type), intent(in) :: globSend
global send communicator
integer, intent(in) :: treeIDPos
element position in the level desc total list
integer, intent(in) :: startPos
starting position of what to send as elemPos
integer(kind=long_k), intent(in) :: parentID
element position in the level desc total list
type(treelmesh_type), intent(in) :: globTree
global tree information
logical, intent(inout) :: added(:)
is this element added to the communication
logical :: match
Calls
Called by
Call graph
mus_ibm_fillsendpos_x calls append, tem_TreeIDComparison, val
mus_fillneigh_surfdata calls mus_ibm_fillsendpos_x
mus_buildbuffibm calls mus_fillneigh_surfdata
do_fast_singlelevel calls mus_buildbuffibm