mus_define_layout – Musubi
mus_define_layout Subroutine
37 statements
Source File
public subroutine mus_define_layout(layout, stencilName, nElems)
This routine defines layout for predefined stencils
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_layout_type), intent(inout) :: layout
scheme layout for pdf state
character(len=*), intent(in) :: stencilName
Name of the stencil to create
integer, intent(in) :: nElems
number of elements use this layout
Calls
Called by
Call graph
mus_define_layout calls mus_define_d1q3, mus_define_d2q5, mus_define_d2q9, mus_define_d3q13, mus_define_d3q19, mus_define_d3q27, mus_define_d3q6, mus_define_d3q7, tem_abort, tem_horizontalSpacer
mus_define_d1q3 calls mus_calculate_speed_of_sound, mus_set_weights_d1q3, tem_create_stencil, tem_identify_prevailDirections, tem_stencil_zeroPos
mus_define_d2q5 calls mus_calculate_speed_of_sound, mus_set_weights_d2q5, tem_create_stencil, tem_identify_prevailDirections, tem_stencil_zeroPos
mus_define_d2q9 calls mus_calculate_speed_of_sound, mus_set_weights_d2q9, tem_create_stencil, tem_identify_prevailDirections, tem_stencil_zeroPos
mus_define_d3q13 calls mus_calculate_speed_of_sound, mus_set_weights_d3q13, tem_create_stencil, tem_identify_prevailDirections, tem_stencil_zeroPos
mus_define_d3q19 calls mus_calculate_speed_of_sound, mus_set_weights_d3q19, tem_create_stencil, tem_identify_prevailDirections, tem_stencil_zeroPos
mus_define_d3q27 calls mus_calculate_speed_of_sound, mus_set_weights_d3q27, tem_create_stencil, tem_identify_prevailDirections, tem_stencil_zeroPos
mus_define_d3q6 calls mus_calculate_speed_of_sound, mus_set_weights_d3q6, tem_create_stencil, tem_identify_prevailDirections, tem_stencil_zeroPos
mus_define_d3q7 calls mus_calculate_speed_of_sound, mus_set_weights_d3q7, tem_create_stencil, tem_identify_prevailDirections, tem_stencil_zeroPos
mus_calculate_speed_of_sound calls cxcx
mus_load_scheme calls mus_define_layout
mus_perform_dynloadbal calls mus_define_layout
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_solve calls mus_perform_dynloadbal
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config, mus_solve
mus_harvesting calls mus_hvs_config_load