mus_load_mixture – Musubi
mus_load_mixture Subroutine
191 statements
Source File
public subroutine mus_load_mixture(me, conf, parent, minLevel, maxLevel, physics, schemeHeader, nFields)
This routine load mixture table from scheme table. Define either mass density or number density. If mass density is specified, number density can be computed at runtime or vice versa. @note Todo Currently, the simulation is initialized by density, extend it to initialize from mixture number density/volume fraction and mole fraction \verbatim mixture = { rho0 = 1.0, omega } \endverbatim
load paramters for forces
Arguments
Type Intent Optional Attributes Name
type(mus_mixture_type), intent(out) :: me
contains mixture information
type(flu_State) :: conf
integer, intent(in), optional :: parent
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(mus_physics_type), intent(in) :: physics
physics type to convert physics to lattice unit or vice versa
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
integer, intent(in) :: nFields
number of fields defined in lua file
Calls
Called by
Call graph
mus_load_mixture calls aot_get_val, aot_table_close, aot_table_open, mus_init_enrtl, set_omegaslvl, tem_abort, tem_horizontalSpacer, tem_load_ic, tem_load_spatial, tem_load_temporal
mus_init_enrtl calls init_enrtl_loc
set_omegaslvl calls tem_abort
mus_load_fields calls mus_load_mixture
mus_load_scheme calls mus_load_fields
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config