mus_perf_measure – Musubi
mus_perf_measure Subroutine
32 statements
Source File
public subroutine mus_perf_measure(totalDens, DomSize, minLevel, maxLevel, nElems, scaleFactor, general)
This routine measures performance imbalance, MLUPS and dumps timings to disk
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: totalDens
Total density from check_density
integer(kind=long_k), intent(in) :: DomSize
Total number of elements in tree
integer, intent(in) :: minLevel
level range
integer, intent(in) :: maxLevel
level range
integer, intent(in) :: nElems(minLevel:maxLevel)
array of nElems levelwise
integer, intent(in) :: scaleFactor
global parameter
type(tem_general_type), intent(in) :: general
Contains proc, simControl, solveHead
Calls
Call graph
mus_perf_measure calls get_computetime, mpi_allreduce, calc_mlups, dump_timing, get_communicatetime, get_mainlooptime, tem_calc_imbalance, tem_getMaxTimerVal
get_computetime calls get_computetime_atlevel, get_computetime_total
dump_timing calls get_auxtime, get_bcbufferratio, get_computeratio, get_relaxtime, newunit, get_boundaryratio, get_communicateratio, get_intpratio, tem_getTimerName, tem_getTimerVal
get_communicatetime calls tem_getTimerVal
get_mainlooptime calls tem_getTimerVal
get_auxtime calls get_auxtime_atlevel, get_auxtime_total
get_bcbufferratio calls get_bcbufferratio_atlevel, get_bcbufferratio_total
get_computeratio calls get_computeratio_atlevel, get_computeratio_total
get_relaxtime calls get_relaxtime_atlevel, get_relaxtime_total
get_boundaryratio calls get_mainlooptime, get_boundarytime
get_communicateratio calls get_communicatetime, get_mainlooptime
get_computetime_atlevel calls tem_getTimerVal
get_computetime_total calls get_computetime
get_intpratio calls get_mainlooptime, get_intptime