mus_load_turb_wallFunc – Musubi
mus_load_turb_wallFunc Subroutine
32 statements
Source File
public subroutine mus_load_turb_wallFunc(me, conf, parent)
This routine loads wall model and nonlinear solver type for nonlinear equation
Arguments
Type Intent Optional Attributes Name
type(mus_turb_wallFunc_type), intent(inout) :: me
Turbulent wall model type to fill assign wall model
type(flu_State) :: conf
lua flu state
integer, intent(in) :: parent
bc parent handle
Calls
Call graph
mus_load_turb_wallfunc calls aot_get_val, load_iterativemethod, load_wall_function, tem_abort
load_iterativemethod calls aot_get_val, tem_abort
load_wall_function calls aot_get_val, tem_abort