mus_particles_transferMomentumToFluid_MEM – Musubi
mus_particles_transferMomentumToFluid_MEM Subroutine
10 statements
Source File
public subroutine mus_particles_transferMomentumToFluid_MEM(particleGroup, scheme, geometry, params)
Arguments
Type Intent Optional Attributes Name
class(mus_particle_group_type), intent(inout) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Call graph
mus_particles_transfermomentumtofluid_mem calls applyvelocitybounceback
applyvelocitybounceback calls baryoftotal, cxdirinv, nghelems, calcperiodicrsurface, cross_product, property, state_varpos, val
calcperiodicrsurface calls calcperiodicdistancetosurface