mus_load_fieldBaseInfos – Musubi
mus_load_fieldBaseInfos Subroutine
45 statements
Source File
public subroutine mus_load_fieldBaseInfos(me, nFields, parent, conf)
This routine returns nFields and field labels from config file. It is required to initialize variable system. labels are loaded only if field table is present else default is set to empty string.
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(out), allocatable :: me(:)
array of field type
integer, intent(out) :: nFields
number of fields defined in lua file
integer, intent(in), optional :: parent
parent handle if scheme table is defined
type(flu_State), intent(inout) :: conf
flu state
Calls
Called by
Call graph
mus_load_fieldbaseinfos calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, tem_abort, tem_checkLabel, tem_horizontalSpacer
mus_load_scheme calls mus_load_fieldbaseinfos
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load