mus_init_boundary – Musubi
mus_init_boundary Subroutine
37 statements
Source File
public subroutine mus_init_boundary(field, pdf, tree, levelDesc, layout, schemeHeader, varSys, derVarPos, globBC, bc_prop, state, auxField)
Check prerequisite for multi-species boundary conditions
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(inout) :: field(:)
fluid parameters and properties
type(pdf_data_type), intent(inout) :: pdf(tree%global%minLevel:tree%global%maxLevel)
contains global state vector
type(treelmesh_type), intent(in) :: tree
global treelm mesh
type(tem_levelDesc_type), intent(in) :: levelDesc(tree%global%minLevel:tree%global%maxLevel)
Level Descriptor
type(mus_scheme_layout_type), intent(in) :: layout
scheme layout type
type(mus_scheme_header_type), intent(in) :: schemeHeader
scheme header info
type(tem_varSys_type), intent(in) :: varSys
scheme variable system
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
position of derived quantities in varsys
type(glob_boundary_type), intent(inout) :: globBC(:)
scheme global boundary type
type(tem_BC_prop_type) :: bc_prop
boundary property type
type(array2D_type), intent(inout) :: state(tree%global%minLevel:tree%global%maxLevel)
state array
type(mus_auxFieldVar_type), intent(in) :: auxField(tree%global%minLevel:tree%global%maxLevel)
AuxField array
Calls
Called by
Call graph
mus_init_boundary calls check_bcs_prerequisite_ms, init_boundary_single, mus_set_bclinks, val
check_bcs_prerequisite_ms calls tem_abort
init_boundary_single calls init_momentsbc, init_nrbc, init_qvals, mus_alloc_bouzidi, mus_init_turb_wallfunc, mus_set_bouzidi, mus_set_inletbfl, mus_set_inletubb, mus_set_noneqexpol, mus_set_outletexpol, mus_setupindices_forbc, tem_abort
mus_set_bclinks calls val
init_momentsbc calls val, tem_abort, a, invert_matrix
init_qvals calls val, cxdirinv, init
mus_init_turb_wallfunc calls val, auxfield_varpos
mus_set_bouzidi calls val, set_bouzidi_coeff
mus_set_inletbfl calls val, set_bouzidi_coeff, tem_BaryOfId, tem_ElemSizeLevel
mus_set_inletubb calls val, tem_BaryOfId, tem_ElemSizeLevel
mus_set_noneqexpol calls val
mus_set_outletexpol calls val
mus_setupindices_forbc calls val, tem_abort, append, indexlvl, init, mus_get_points_frombc, set_params, setup_indices
mus_get_points_frombc calls val, tem_BaryOfId, tem_ElemSizeLevel
mus_initialize calls mus_init_boundary
mus_reset_aux calls mus_init_boundary
mus_perform_dynloadbal calls mus_reset_aux
musubi calls mus_initialize, mus_solve
mus_solve calls mus_perform_dynloadbal