mus_getWeights – Musubi
mus_getWeights Subroutine
60 statements
Source File
public subroutine mus_getWeights(weights, tree, minLevel, maxLevel, levelDesc, nBCs, globBC)
Calculate weights using timing from compute kernel, interpolation and boundary routines
************ !
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(out) :: weights(:)
type(treelmesh_type), intent(in) :: tree
geometry infomation
integer, intent(in) :: minLevel
min level and max level
integer, intent(in) :: maxLevel
min level and max level
type(tem_levelDesc_type), intent(in) :: levelDesc(minLevel:maxLevel)
Level descriptor
integer, intent(in) :: nBCs
global IBM type Number of boundary conditions
type(glob_boundary_type), intent(in) :: globBC(nBCs)
BC elements information
Calls
Called by
Call graph
mus_getweights calls get_bcbuffertime, get_boundarytime, get_computetime, get_intpfromcoarsertime, get_intpfromfinertime, nelems, tem_LevelOf, val
get_bcbuffertime calls get_bcbuffertime_atlevel, get_bcbuffertime_total
get_boundarytime calls get_boundarytime_byid, get_boundarytime_total
get_computetime calls get_computetime_atlevel, get_computetime_total
get_intpfromcoarsertime calls get_intpfromcoarsertime_atlevel, get_intpfromcoarsertime_total
get_intpfromfinertime calls get_intpfromfinertime_atlevel, get_intpfromfinertime_total
get_bcbuffertime_atlevel calls tem_getTimerVal
get_bcbuffertime_total calls get_bcbuffertime
get_boundarytime_byid calls tem_getTimerVal
get_boundarytime_total calls get_boundarytime
get_computetime_atlevel calls tem_getTimerVal
get_computetime_total calls get_computetime
get_intpfromcoarsertime_atlevel calls tem_getTimerVal
get_intpfromcoarsertime_total calls get_intpfromcoarsertime
get_intpfromfinertime_atlevel calls tem_getTimerVal
get_intpfromfinertime_total calls tem_getTimerVal
mus_balance calls mus_getweights
mus_finalize calls mus_getweights
mus_perform_dynloadbal calls mus_balance
musubi calls mus_finalize, mus_solve
mus_solve calls mus_perform_dynloadbal