mus_geomIncr – Musubi
mus_geomIncr Subroutine
64 statements
Source File
public subroutine mus_geomIncr(geometry, scheme, commPattern, general)
This subroutine checks for various conditions defined in the geomIncr table within the lua file, calculates the requested macroscpoic variables and then compares them against the specified threshold. Accordingly then solidification or fluidification of elements is performed.
Arguments
Type Intent Optional Attributes Name
type(mus_geom_type) :: geometry
type(mus_scheme_type), intent(inout) :: scheme
type(tem_commPattern_type), intent(in) :: commPattern
type(tem_general_type), intent(in) :: general
global parameters
Calls
Called by
Call graph
mus_geomincr calls get_element, prepare_target_elem_list, proximity, update_connectivity, tem_timeControl_check, val
prepare_target_elem_list calls cxdirinv, nghelems, mus_setprop, property, tem_LevelOf
proximity calls elempropertybits, tem_LevelOf, treeid
update_connectivity calls val, cxdirinv, nghelems, property, state_varpos
check_flow_status calls mus_geomincr
mus_solve calls check_flow_status
musubi calls mus_solve