mus_load_geom – Musubi
mus_load_geom Subroutine
33 statements
Source File
public subroutine mus_load_geom(me, restart, solverHead, simControl, proc, scaleFactor, initial_balance)
This routine load all geometry related datas like mesh, boundary and immersed_boundary. Restart is also loaded here because mesh is loaded in tem_load_restart if restart read is defined.
Arguments
Type Intent Optional Attributes Name
type(mus_geom_type), intent(out) :: me
type(tem_restart_type), intent(out) :: restart
contains restart information
type(tem_solveHead_type), intent(inout) :: solverHead
contains general description of the solver including flu_state
type(tem_simControl_type), intent(inout) :: simControl
contains simulation time control information
type(tem_comm_env_type), intent(in) :: proc
contains MPI communication environment
integer, intent(in) :: scaleFactor
Temporal scaling factor for multilevel mesh
logical, intent(in) :: initial_balance
If true, do initial balancing using level_weights
Calls
Called by
Call graph
mus_load_geom calls load_tem, mus_geomincrhead_load, mus_load_bc_data, mus_load_ibm, tem_global_mesh_read, tem_horizontalSpacer, tem_load_restart, tem_timeControl_start_at_sim
mus_geomincrhead_load calls aot_table_close, aot_table_length, aot_table_open, mus_geomincrhead_load_single
mus_load_bc_data calls init_tem_bc_prop, load_tem_BC_qVal, mus_build_posinprop, property, qval
mus_load_ibm calls tem_horizontalSpacer, aot_table_close, aot_table_length, aot_table_open, mus_load_ibm_single, tem_connect_toNull, tem_logging_load
mus_build_posinprop calls property, mus_build_minbcid, tem_build_treeToProp_pointer
mus_geomincrhead_load_single calls tem_horizontalSpacer, aot_get_val, tem_timeControl_load
mus_load_ibm_single calls aot_get_val, tem_abort, tem_load_spacetime, tem_load_surfData
mus_load_config calls mus_load_geom
musubi calls mus_load_config