mus_particles_move – Musubi
mus_particles_move Subroutine
7 statements
Source File
public subroutine mus_particles_move(particleGroup, scheme, geometry, params)
This routine moves all particles in particleArray.
Arguments
Type Intent Optional Attributes Name
class(mus_particle_group_type), intent(inout) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Call graph
mus_particles_move calls demsubcycles_mem
demsubcycles_mem calls dem_swapfnowfnext, updatepositionverlet, updatevelocityverlet, dem_computeexternalforces, dem_computelocalcollisionforces, dem_computeremotecollisionforces, dem_computewallforces_mem, dem_exchangeforces, dem_resetfnext_mem, dem_storewallpositions_mem, exchangepositions, exchangevelocities, resetforcebuffers, updatecoordoforigin, wrapperiodicpos, val