mus_load_bc – Musubi
mus_load_bc Subroutine
326 statements
Source File
public subroutine mus_load_bc(me, bc_prop, conf, parent, varSys, stencil)
Read in the boundary conditions from the LUA parameter file.\n
Arguments
Type Intent Optional Attributes Name
type(boundary_type), allocatable :: me(:)
field boundary type
type(tem_BC_prop_type), intent(in) :: bc_prop
boundary data from mesh
type(flu_State) :: conf
lua flu state
integer, intent(in), optional :: parent
bc parent handle
type(tem_varSys_type), intent(inout) :: varSys
Global variable system required to append annoymous boundary variables
type(tem_stencilHeader_type) :: stencil
stencil information
Calls
Called by
Call graph
mus_load_bc calls aot_get_val, aot_table_close, aot_table_open, init, mus_load_turb_wallfunc, tem_abort, tem_horizontalSpacer, tem_load_bc_header, tem_load_bc_state, truncate
mus_load_turb_wallfunc calls aot_get_val, tem_abort, load_iterativemethod, load_wall_function
load_iterativemethod calls aot_get_val, tem_abort
load_wall_function calls aot_get_val, tem_abort
mus_load_field_single calls mus_load_bc
mus_load_fields calls mus_load_field_single
mus_load_scheme calls mus_load_fields
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme