mus_store_bcVarPos – Musubi
mus_store_bcVarPos Subroutine
67 statements
Source File
private subroutine mus_store_bcVarPos(field, nFields, varSys)
Store the position of each boundary variable in the global varSys in the field%bc%varPos%. This routine also checks if boundary variable defined in config file has same number of components as expected.
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(inout) :: field(:)
Field containing boundary infos
integer, intent(in) :: nFields
number of fields
type(tem_varSys_type), intent(in) :: varSys
global variable system
Calls
Called by
Call graph
mus_store_bcvarpos calls positionofval, tem_abort, val
mus_build_varsys calls mus_store_bcvarpos
mus_init_scheme calls mus_build_varsys
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme