mus_createSrcElemInTreeForGetPoint – Musubi
mus_createSrcElemInTreeForGetPoint Subroutine
32 statements
Source File
public subroutine mus_createSrcElemInTreeForGetPoint(pntDataMapToTree, posInPntData, point, nPnts, stencil, tree, levelPointer, levelDesc)
This routine creates srcElemInTree in pointData. It is called all in getPoint routine when first time the get point routine in called.
Arguments
Type Intent Optional Attributes Name
type(tem_pointData_type), intent(out) :: pntDataMapToTree
Contains position of source elements in Tree and weights for interpolation
integer, intent(out) :: posInPntData(:)
Contains position of a point in pntDataMapToTree
real(kind=rk), intent(in) :: point(:,:)
Three-dimensional coordinates at which the variable should be evaluated. Only useful for variables provided as space-time functions.
integer, intent(in) :: nPnts
Number of values to obtain for this variable (vectorized access).
type(tem_stencilHeader_type), intent(in) :: stencil
stencil definition
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: levelPointer(:)
Pointer from treeIDlist entry to level-wise fluid part of total list
type(tem_levelDesc_type), intent(in) :: levelDesc(tree%global%minLevel:)
level description of all levels
Calls
Call graph
mus_createsrcelemintreeforgetpoint calls append, mus_intp_getsrcelemposintree, truncate
mus_intp_getsrcelemposintree calls nghelems, tem_BaryOfId, tem_CoordOfReal, tem_FirstIdAtLevel, tem_IdOfCoord, tem_LevelOf, tem_ParentOf, tem_PosOfId, tem_eligibleChildren