mus_init_longBuffers – Musubi
mus_init_longBuffers Subroutine
10 statements
Source File
public subroutine mus_init_longBuffers(comm, pattern)
Wrapper around the actual communication, to avoid copy-in, copy-out by the Intel compiler. (At least the intel compiler on pigeon (v12.0) seems to do copying here, if a sub-array is passed to an assumed size dummy argument. Therefore we use this wrapping with an assumed shape dummy argument, so we can pass a complete field to the actual exchange which has an assumed size argument, without copying complete state field around, just for communication. Ugly, but it doesn't seem to have an impact on performance, and right it seems to be the most suitable solution.
Copy the element position in send and recv buffer to pos array in long type buffer
Arguments
Type Intent Optional Attributes Name
type(tem_communication_type), intent(inout) :: comm
type(tem_commPattern_type), intent(in) :: pattern
Called by
Call graph
communicate_property calls mus_init_longbuffers
mus_construct calls communicate_property
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize