mus_set_weights_d3q13 – Musubi
mus_set_weights_d3q13 Subroutine
5 statements
Source File
private subroutine mus_set_weights_d3q13(weights)
Arguments
Type Intent Optional Attributes Name
real(kind=rk) :: weights(13)
Called by
Call graph
mus_define_d3q13 calls mus_set_weights_d3q13
mus_define_layout calls mus_define_d3q13
mus_load_scheme calls mus_define_layout
mus_perform_dynloadbal calls mus_define_layout
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme