mus_finalize_particleGroup – Musubi
mus_finalize_particleGroup Subroutine
4 statements
Source File
public subroutine mus_finalize_particleGroup(particleGroup)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
Calls
Called by
Call graph
mus_finalize_particlegroup calls destroy_da_particle_mem
mus_finalize calls mus_finalize_particlegroup
musubi calls mus_finalize