mus_init_byIC – Musubi
mus_init_byIC Subroutine
47 statements
Source File
private subroutine mus_init_byIC(scheme, tree, fac, scaling)
Initialize flow field by calling corresponding routine according to scheme kind.
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
Scheme type
type(treelmesh_type), intent(in) :: tree
tree
type(mus_convertFac_type), intent(in) :: fac(tree%global%minLevel:tree%global%maxLevel)
Global parameters
character(len=*), intent(in) :: scaling
Calls
Called by
Call graph
mus_init_byic calls mus_init_isotherm_aceq, mus_init_msgas, mus_init_msliquid, mus_init_nernst_planck, mus_init_passivescalar, mus_init_pdf, mus_init_poisson, tem_abort, tem_horizontalSpacer
mus_init_isotherm_aceq calls ini_state, tem_BaryOfId, tem_spatial_for, total
mus_init_msgas calls ini_state, tem_BaryOfId, tem_spatial_for, total
mus_init_msliquid calls tem_abort, cxdir, ini_state, mus_calc_ms_diffmatrix, mus_calc_thermfactor, invert_matrix, tem_BaryOfId, tem_spatial_for, total
mus_init_nernst_planck calls cxdir, ini_state, tem_BaryOfId, tem_spatial_for, total
mus_init_passivescalar calls ini_state, tem_BaryOfId, tem_spatial_for, total
mus_init_pdf calls ini_state, getneq_acoustic, getneq_diffusive, tem_BaryOfId, tem_spatial_for, total
mus_init_poisson calls ini_state, tem_BaryOfId, tem_spatial_for, total
mus_calc_ms_diffmatrix calls mus_calc_ms_diffmatrix_single
mus_calc_thermfactor calls mus_calc_thermfactor_single
getneq_acoustic calls cxdirrk, convprepost
getneq_diffusive calls cxdirrk, convprepost
mus_calc_ms_diffmatrix_single calls calc_ms_diff_matrix_from_moledens
mus_calc_thermfactor_single calls calc_therm_factor_loc
mus_init_flow calls mus_init_byic
mus_initialize calls mus_init_flow
musubi calls mus_initialize