mus_iMomVector – Musubi
mus_iMomVector Function
35 statements
Source File
private pure function mus_iMomVector(cxDir, expX, QQ) result(iMom)
The integer moment vector for a given cxDir and order.
Assuming 0**0 = 1 here.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: cxDir(:,:)
discrete velocity
integer, intent(in) :: expX(3)
order in each direction
integer, intent(in) :: QQ
number of velocity channels (include rest)
Return Value integer, (QQ)
Called by
Call graph
get_momentvector calls mus_imomvector
get_moment calls get_momentvector
init_transformation_matrix_fluid calls get_momentvector
init_transformation_matrix_ms calls get_momentvector
mus_init_moments calls init_transformation_matrix_fluid, init_transformation_matrix_ms
mus_init_scheme calls mus_init_moments