mus_load_config – Musubi
mus_load_config Subroutine
43 statements
Source File
public subroutine mus_load_config(scheme, solverData, geometry, params, adapt, particleGroup)
Read in LUA parameter file See http://www.lua.org for a reference on how to use Lua is a scripting language in itself which allows more complex parameter files including comments And load / create the mesh depending on the configuration
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), target :: scheme
scheme type
type(mus_varSys_solverData_type), target :: solverData
contains pointer to scheme, physics types
type(mus_geom_type), intent(out), target :: geometry
Treelmesh data
type(mus_param_type), intent(inout), target :: params
Global parameters
type(tem_adapt_type), intent(inout) :: adapt
mesh adaptation
type(mus_particle_group_type), intent(inout) :: particleGroup
particleGroup object containing all particle data on this process
Calls
Called by
Call graph
mus_load_config calls conf, dump_linear_partition, mus_init_latticeunit, mus_load_geom, mus_load_param, mus_load_particlekind, mus_load_physics, mus_load_scheme, mus_open_config, tem_debug_load_main, tem_horizontalSpacer, tem_load_adapt, tem_load_general, tem_logging_load_primary, tem_startTimer, tem_stopTimer
musubi calls mus_load_config