mus_particles_updateFluidVolumeFraction – Musubi
mus_particles_updateFluidVolumeFraction Subroutine
19 statements
Source File
public subroutine mus_particles_updateFluidVolumeFraction(particleGroup, scheme, geometry, params, nElems)
Main routine to update the fluid volume fraction in the auxField
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(in) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
scheme for access to varSys
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
integer, intent(in) :: nElems
Number of elements including halos (multilevel not supported yet so no ghosts)
Calls
Called by
Call graph
mus_particles_updatefluidvolumefraction calls auxfield_varpos, distributeparticlevolume
distributeparticlevolume calls auxfield_varpos, neigh, followneighpath, getbaryofcoord, getposofcoord
getposofcoord calls tem_IdOfCoord, tem_PosOfId
check_particles_dps calls mus_particles_updatefluidvolumefraction
mus_particles_initialize calls mus_particles_updatefluidvolumefraction
mus_initialize calls mus_particles_initialize
musubi calls mus_initialize