mus_init_transport_var – Musubi
mus_init_transport_var Subroutine
50 statements
Source File
public subroutine mus_init_transport_var(me, varSys, tree, nElems_solve, levelDesc)
Initialize transport variable by calling setupIndices for every variable and store pntIndex
Arguments
Type Intent Optional Attributes Name
type(mus_transport_var_type), intent(inout) :: me
transport variable to fill in
type(tem_varSys_type), intent(in) :: varSys
global variable system
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: nElems_solve(tree%global%minLevel:)
Number of elements to solve in all levels nFluids + nGhosts
type(tem_levelDesc_type), intent(in) :: levelDesc(tree%global%minLevel:)
Level descriptors
Calls
Called by
Call graph
mus_init_transport_var calls append, indexlvl, positionofval, set_params, setup_indices, tem_BaryOfId, tem_abort, tem_horizontalSpacer, val
mus_init_aux calls mus_init_transport_var
mus_reset_aux calls mus_init_transport_var
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve