mus_writeSolverSpecInfo – Musubi
mus_writeSolverSpecInfo Subroutine
16 statements
Source File
public subroutine mus_writeSolverSpecInfo(scheme, params, rank, outUnit)
Write solver specific info to scratch file
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
scheme type
type(mus_param_type), intent(in) :: params
Contains physical convertion info and scaling type
integer, intent(in) :: rank
Rank of the process either from global communicator or tracking output communicator
integer, intent(inout) :: outUnit
unit to output solver info in lua format
Calls
Call graph
mus_writesolverspecinfo calls aot_out_close, aot_out_open, newunit, mus_param_out, mus_physics_out, mus_scheme_out
mus_param_out calls aot_out_val
mus_physics_out calls aot_out_close_table, aot_out_open_table, aot_out_val
mus_scheme_out calls mus_fields_out, mus_interpolate_out, mus_mixture_out, mus_scheme_header_out
mus_fields_out calls mus_field_out_scal, mus_fields_out_vec
mus_interpolate_out calls aot_out_val
mus_mixture_out calls aot_out_close_table, aot_out_open_table, aot_out_val
mus_scheme_header_out calls aot_out_close_table, aot_out_open_table, aot_out_val
mus_field_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val, mus_field_prop_out
mus_fields_out_vec calls aot_out_close_table, aot_out_open_table, aot_out_val, mus_field_out_scal