mus_set_weights_d2q5 – Musubi
mus_set_weights_d2q5 Subroutine
5 statements
Source File
private subroutine mus_set_weights_d2q5(weights)
Arguments
Type Intent Optional Attributes Name
real(kind=rk) :: weights(5)
Called by
Call graph
mus_define_d2q5 calls mus_set_weights_d2q5
mus_define_layout calls mus_define_d2q5
mus_load_scheme calls mus_define_layout
mus_perform_dynloadbal calls mus_define_layout
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_solve calls mus_perform_dynloadbal