mus_pdf_serialize – Musubi
mus_pdf_serialize Subroutine
28 statements
Source File
public subroutine mus_pdf_serialize(scheme, treeID, levelPointer, varMap, nElems, buffer, minLevel, maxLevel)
Preparation of the serialize PDF data
Serialize the information from the (level-wise) state vector (scheme%state) into chunks for writing it in original treeIDlist order to disk (which is not sorted by levels, but by the space-filling curve) The data is stored like follows (e.g. varSys, 2 elements):
   Elem = 1     Elem = 2
 ---------------------------
 | stateVars | stateVars
 ---------------------------
          varSys
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
scheme type containing the different state vectors
integer(kind=long_k), intent(in) :: treeID(nElems)
Partial treeID list
integer, intent(in) :: levelPointer(nElems)
Partial Level pointer
type(tem_varMap_type), intent(in) :: varMap
varaible map information
integer, intent(in) :: nElems
number of valid elements in this buffer
real(kind=rk), intent(inout) :: buffer(:)
Data buffer
integer :: minLevel
integer :: maxLevel
Calls
Called by
Call graph
mus_pdf_serialize calls tem_LevelOf, val
mus_perform_dynloadbal calls mus_pdf_serialize
mus_writerestart calls mus_pdf_serialize
mus_dumpdata calls mus_writerestart
mus_finalize calls mus_writerestart
mus_solve calls mus_perform_dynloadbal, check_flow_status
check_flow_status calls mus_dumpdata
musubi calls mus_finalize, mus_solve