mus_add_BcghostElem – Musubi
mus_add_BcghostElem Subroutine
53 statements
Source File
private subroutine mus_add_BcghostElem(levelDesc, stencil, bc_prop, globBC, nGhosts, offset, weight, iLevel)
Arguments
Type Intent Optional Attributes Name
type(tem_levelDesc_type), intent(inout) :: levelDesc
Level Descriptor for iLevel
type(tem_stencilHeader_type), intent(in) :: stencil
stencil
type(tem_BC_prop_type), intent(in) :: bc_prop
boundary information from mesh
type(glob_boundary_type), intent(inout) :: globBC(:)
boundaries for the elements with bnd property set
integer :: nGhosts
integer, intent(in) :: offset
integer, intent(in) :: weight(stencil%QQN)
integer, intent(in) :: iLevel
Calls
Called by
Call graph
mus_add_bcghostelem calls append, nghelems, val
mus_update_bcghostelem calls mus_add_bcghostelem
mus_construct calls mus_update_bcghostelem
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize