mus_field_getSymmetricBCs – Musubi
mus_field_getSymmetricBCs Subroutine
25 statements
Source File
public subroutine mus_field_getSymmetricBCs(symmetricBCs, nSymBCs, nBCs, nFields, field)
This routine checks for the existence of symmetric boundaries and returns the boundary IDs which are defined as symmetry
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: symmetricBCs(nBCs)
Symmetric boundary ids
integer, intent(out) :: nSymBCs
Number of symmetric boundary conditions
integer, intent(in) :: nBCs
number of boundary conditions
integer, intent(in) :: nFields
number of fields
type(mus_field_type), intent(in) :: field(nFields)
all fields to access their boundary definitions
Calls
Called by
Call graph
mus_field_getsymmetricbcs calls tem_abort
mus_construct calls mus_field_getsymmetricbcs
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve