mus_nNwtn_save2lua – Musubi
mus_nNwtn_save2lua Subroutine
15 statements
Source File
public subroutine mus_nNwtn_save2lua(me, conf)
write nonNewtonian fluid parameters into a lua file
Arguments
Type Intent Optional Attributes Name
type(mus_nNwtn_type), intent(in) :: me
nonNewtonian parameters
type(aot_out_type) :: conf
Calls
Called by
Call graph
mus_nnwtn_save2lua calls aot_out_close_table, aot_out_open_table, aot_out_val, mus_nnwtn_cs_save, mus_nnwtn_cy_save, mus_nnwtn_pl_save
mus_nnwtn_cs_save calls aot_out_val
mus_nnwtn_cy_save calls aot_out_val
mus_nnwtn_pl_save calls aot_out_val
mus_fluid_save2lua calls mus_nnwtn_save2lua
mus_field_prop_out calls mus_fluid_save2lua
mus_field_out_scal calls mus_field_prop_out
mus_fields_out calls mus_field_out_scal
mus_fields_out_vec calls mus_field_out_scal