mus_load_poissonBoltzmann – Musubi
mus_load_poissonBoltzmann Subroutine
37 statements
Source File
public subroutine mus_load_poissonBoltzmann(me, conf, parent, physics)
Load input to solve poisson boltzmann equation
Arguments
Type Intent Optional Attributes Name
type(mus_poisson_boltzmann_type), intent(out) :: me
poisson bolztmann type
type(flu_State) :: conf
flu state
integer, intent(in), optional :: parent
parent handle
type(mus_physics_type), intent(in) :: physics
physics type to convert physics to lattice unit or vice versa
Calls
Called by
Call graph
mus_load_poissonboltzmann calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, tem_abort
mus_load_poisson calls mus_load_poissonboltzmann
mus_load_field_prop calls mus_load_poisson
mus_load_field_single calls mus_load_field_prop
mus_load_fields calls mus_load_field_single