mus_setupIndices_forSrc – Musubi
mus_setupIndices_forSrc Subroutine
47 statements
Source File
private subroutine mus_setupIndices_forSrc(source, varSys, nSolve, bary, iLevel, tree, bc_prop, stencil)
This routines does setup indices for given source within a field or global. Index are stored for points which source term is active
Arguments
Type Intent Optional Attributes Name
type(mus_source_type), intent(inout) :: source
Source term to fill in
type(tem_varSys_type), intent(in) :: varSys
global variable system
integer, intent(in) :: nSolve
Number of elements to apply source term on this level
real(kind=rk), intent(in) :: bary(:,:)
Space coordinates to apply source terms
integer, intent(in) :: iLevel
Current level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
type(tem_BC_prop_type), intent(in) :: bc_prop
bc property which is used to identify elements belong to certain BCs
type(tem_stencilHeader_type), intent(in) :: stencil
stencil used to find bcID on certain links
Calls
Called by
Call graph
mus_setupindices_forsrc calls mus_init_absorblayer, mus_init_turbchanforce, set_params, setup_indices, val
mus_init_turbchanforce calls mpi_allreduce, tem_create_subTree_of
mus_init_sourceterms calls mus_setupindices_forsrc
mus_init_aux calls mus_init_sourceterms
mus_reset_aux calls mus_init_sourceterms
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize