mus_fillNeigh_surfData – Musubi
mus_fillNeigh_surfData Subroutine
162 statements
Source File
private subroutine mus_fillNeigh_surfData(me, IBMData, stencil, levelDesc, globTree, parentIDs, commPattern, params)
This routine builds the neighbor lists for Xk -> x (neigh_Xk) and x->Xk (neigh_x) as well as the send and receive buffers for the eulerian elements.
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_type), intent(inout) :: me
IBM data including the surface data
type(mus_IBM_tmpData_type), intent(inout) :: IBMData
tmp IBMData type to be filled
type(tem_stencilHeader_type), intent(in) :: stencil(:)
array of stencils (1 is the fluid stencil)
type(tem_levelDesc_type), intent(inout) :: levelDesc
the level descriptor incl. ghost and halo elements on the level iLevel
type(treelmesh_type), intent(in) :: globTree
global tree information
integer, intent(in) :: parentIDs(:)
array of parentID positions hosting the lagrangian points
type(tem_commPattern_type), intent(inout) :: commPattern
communication pattern to be used
type(mus_param_type), intent(inout) :: params
global parameters
Calls
Called by
Call graph
mus_fillneigh_surfdata calls append, buf_int, buf_long, elempos, nelems, nelemsproc, proc, mus_ibm_fillrecvpos_x, mus_ibm_fillsendpos_x, tem_CoordOfId, tem_IdOfCoord, tem_startTimer, tem_stopTimer, tem_treeIDinTotal, val
mus_ibm_fillrecvpos_x calls append, val
mus_ibm_fillsendpos_x calls append, val, tem_TreeIDComparison
mus_buildbuffibm calls mus_fillneigh_surfdata
do_fast_singlelevel calls mus_buildbuffibm