mus_load_scheme_header – Musubi
mus_load_scheme_header Subroutine
37 statements
Source File
public subroutine mus_load_scheme_header(me, conf, parent, scaling)
load scheme header info from lua file identify table or from scheme table or from config
Load scheme label, kind, layoutKind and relaxation
 identify = { kind = 'simType',
              layout = 'stencilLayout',
              relaxation = 'relaxationType' }
For a possible selection of the other parameters - simType: fluid, fluid_incompressible, multispecies_liquid - mus_scheme_layout_module: d2q9, d3q19, ... - relaxationType: bgk, mrt, ...
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_header_type), intent(out) :: me
returns scheme identify information
type(flu_State) :: conf
integer, intent(in), optional :: parent
parent handle if scheme table is defined
character(len=*), intent(in) :: scaling
Calls
Called by
Call graph
mus_load_scheme_header calls aot_get_val, aot_table_close, aot_table_open, load_relaxation_header, tem_horizontalSpacer
load_relaxation_header calls aot_get_val, tem_abort
mus_load_scheme calls mus_load_scheme_header
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load