mus_init_varSys_solverData – Musubi
mus_init_varSys_solverData Subroutine
9 statements
Source File
public subroutine mus_init_varSys_solverData(me, scheme, physics, geometry)
Arguments
Type Intent Optional Attributes Name
type(mus_varSys_solverData_type), intent(out) :: me
type(mus_scheme_type), intent(in), target :: scheme
type(mus_physics_type), intent(in), target :: physics
type(mus_geom_type), intent(in), target :: geometry
Called by
Call graph
mus_load_scheme calls mus_init_varsys_solverdata
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load