mus_append_bcVar – Musubi
mus_append_bcVar Subroutine
99 statements
Source File
public subroutine mus_append_bcVar(varSys, solverData, derVarName, nFields, field, stencil)
This routine adds boundary variables for tracking
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
global variable system
type(mus_varSys_solverData_type), intent(in), target :: solverData
Contains pointer to solver data types
type(grw_labelarray_type), intent(inout) :: derVarName
array of derive physical variables
integer, intent(in) :: nFields
number of fields
type(mus_field_type), intent(in) :: field(nFields)
Field contains sources and boundary infos
type(tem_stencilHeader_type), intent(in) :: stencil
Compute stencil header
Calls
Called by
Call graph
mus_append_bcvar calls append, init, mus_get_new_solver_ptr, tem_varSys_append_derVar
mus_build_varsys calls mus_append_bcvar
mus_init_scheme calls mus_build_varsys
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme