mus_init_turbChanForce – Musubi
mus_init_turbChanForce Subroutine
12 statements
Source File
private subroutine mus_init_turbChanForce(turbChanForce, tree, bc_prop, stencil)
Create subTree and store nElemsGlobal in all proc for turbulent channel force
Arguments
Type Intent Optional Attributes Name
type(mus_turbChannelForce_type), intent(inout) :: turbChanForce
Contains info for turbulent channel force
type(treelmesh_type), intent(in) :: tree
global treelm mesh
type(tem_BC_prop_type), intent(in) :: bc_prop
bc property which is used to identify elements belong to certain BCs
type(tem_stencilHeader_type), intent(in) :: stencil
stencil used to find bcID on certain links
Calls
Called by
Call graph
mus_init_turbchanforce calls mpi_allreduce, tem_create_subTree_of
mus_setupindices_forsrc calls mus_init_turbchanforce
mus_init_sourceterms calls mus_setupindices_forsrc
mus_init_aux calls mus_init_sourceterms
mus_reset_aux calls mus_init_sourceterms
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux