mus_load_bc_data – Musubi
mus_load_bc_data Subroutine
21 statements
Source File
public subroutine mus_load_bc_data(geometry, rank, comm)
This routine invokes the treelm routines to load the boundary conditions
Arguments
Type Intent Optional Attributes Name
type(mus_geom_type), intent(inout) :: geometry
integer, intent(in) :: rank
integer, intent(in) :: comm
Calls
Called by
Call graph
mus_load_bc_data calls init_tem_bc_prop, load_tem_BC_qVal, mus_build_posinprop, property, qval
mus_build_posinprop calls property, mus_build_minbcid, tem_build_treeToProp_pointer
mus_hvs_config_load calls mus_load_bc_data
mus_load_geom calls mus_load_bc_data
mus_load_config calls mus_load_geom
mus_harvesting calls mus_hvs_config_load
musubi calls mus_load_config