mus_append_turbVar – Musubi
mus_append_turbVar Subroutine
31 statements
Source File
public subroutine mus_append_turbVar(varSys, solverData, derVarName, turbConfig)
subroutine to add variables for turbulence model
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
global variable system
type(mus_varSys_solverData_type), intent(in), target :: solverData
Contains pointer to solver data types
type(grw_labelarray_type), intent(inout) :: derVarName
array of derive physical variables
type(mus_turbulence_config_type), intent(in) :: turbConfig
turbulence definition
Calls
Called by
Call graph
mus_append_turbvar calls append, mus_get_new_solver_ptr, tem_abort, tem_varSys_append_derVar
mus_build_varsys calls mus_append_turbvar
mus_init_scheme calls mus_build_varsys
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize