mus_fields_out_vec – Musubi
mus_fields_out_vec Subroutine
16 statements
Source File
private subroutine mus_fields_out_vec(me, conf, schemeHeader)
write array of fields into a lua file
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(in) :: me(:)
array of field type
type(aot_out_type), intent(inout) :: conf
aotus out type
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
Calls
Called by
Call graph
mus_fields_out_vec calls aot_out_close_table, aot_out_open_table, aot_out_val, mus_field_out_scal
mus_field_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val, mus_field_prop_out
mus_field_prop_out calls mus_fluid_save2lua, mus_species_out
mus_fluid_save2lua calls aot_out_close_table, aot_out_open_table, aot_out_val, const, mus_nnwtn_save2lua
mus_species_out calls aot_out_close_table, aot_out_open_table, aot_out_val
mus_fields_out calls mus_fields_out_vec
mus_scheme_out calls mus_fields_out
mus_writesolverspecinfo calls mus_scheme_out