mus_log_fluid_momentum – Musubi
mus_log_fluid_momentum Subroutine
32 statements
Source File
public subroutine mus_log_fluid_momentum(scheme, lev, params, comm)
perform_particle_checks computes the total momentum of the fluid and particle phases and logs this to a file
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme for access to auxfield
integer, intent(in) :: lev
level in the octree to compute total momentum on
type(mus_param_type), intent(in) :: params
params for access to dt, dx, etc.
integer :: comm
MPI communicator
Calls
Call graph
mus_log_fluid_momentum calls compute_fluid_momentum, openlogfile
compute_fluid_momentum calls auxfield_varpos, mpi_reduce, property
openlogfile calls newunit