mus_pdf_unserialize – Musubi
mus_pdf_unserialize Subroutine
29 statements
Source File
public subroutine mus_pdf_unserialize(scheme, treeID, levelPointer, varMap, nElems, buffer, minLevel, maxLevel)
This subroutine unserializes the read data and stores it in the state- vector to perform a restart.
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme type containing the different state vectors
integer(kind=long_k), intent(in) :: treeID(nElems)
global tree data type
integer, intent(in) :: levelPointer(nElems)
Level Pointer - from treelm to level descriptor
type(tem_varMap_type), intent(in) :: varMap
variable map
integer, intent(in) :: nElems
real(kind=rk), intent(in) :: buffer(:)
integer :: minLevel
integer :: maxLevel
Calls
Called by
Call graph
mus_pdf_unserialize calls tem_LevelOf, val
mus_perform_dynloadbal calls mus_pdf_unserialize
mus_readrestart calls mus_pdf_unserialize
mus_init_flow calls mus_readrestart
mus_solve calls mus_perform_dynloadbal
mus_harvesting calls mus_readrestart
mus_initialize calls mus_init_flow
musubi calls mus_solve, mus_initialize