mus_initialize – Musubi
mus_initialize Subroutine
34 statements
Source File
public subroutine mus_initialize(scheme, geometry, params, particleGroup, control, solverData)
This routine load musubi configuration file and initialize construction flow, auxilary and main control routines
Initialize flow field depends on read restart or initial condition
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme type
type(mus_geom_type), intent(inout) :: geometry
Treelmesh data
type(mus_param_type), intent(inout) :: params
Global parameters
type(mus_particle_group_type), intent(inout) :: particleGroup
Particle parameters
type(mus_control_type), intent(inout) :: control
control routine
type(mus_varSys_solverData_type), target :: solverData
contains pointer to scheme, physics types. passed to init_Scheme to build varSys
Calls
Called by
Call graph
mus_initialize calls conf, mus_construct, mus_init_aux, mus_init_boundary, mus_init_control, mus_init_flow, mus_init_ibm, mus_init_scheme, mus_load_particles, mus_particles_initfluidvolumefraction, mus_particles_initialize, tem_horizontalSpacer, tem_opVar_reduction_transient_init, tem_timeControl_dump
musubi calls mus_initialize