mus_update_BcghostElem – Musubi
mus_update_BcghostElem Subroutine
60 statements
Source File
private subroutine mus_update_BcghostElem(minLevel, maxLevel, levelDesc, layout, bc_prop, globBC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
Min and max level
integer, intent(in) :: maxLevel
Min and max level
type(tem_levelDesc_type), intent(inout) :: levelDesc(minLevel:maxLevel)
Level Descriptor
type(mus_scheme_layout_type), intent(in) :: layout
scheme layout
type(tem_BC_prop_type), intent(in) :: bc_prop
boundary information from mesh
type(glob_boundary_type), intent(inout) :: globBC(:)
boundaries for the elements with bnd property set
Calls
Called by
Call graph
mus_update_bcghostelem calls append, cxdir, mus_add_bcghostelem, tem_determine_discreteVector, truncate, val
mus_add_bcghostelem calls append, val, nghelems
mus_construct calls mus_update_bcghostelem
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve