mus_deriveElectricField – Musubi
mus_deriveElectricField Subroutine
37 statements
Source File
private recursive subroutine mus_deriveElectricField(fun, varsys, stencil, iLevel, posInState, pdf, res, nVals)
Calculate the electric_field of a given pre-collision pdfs i.e fetch_pdf_now
The interface has to comply to the abstract interface mus_derive_fromPDF.
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varsys
the variable system to obtain the variable from.
type(tem_stencilHeader_type), intent(in) :: stencil
fluid stencil defintion
integer, intent(in) :: iLevel
current Level
integer, intent(in) :: posInState(:)
Position of element in levelwise state array
real(kind=rk), intent(in) :: pdf(:)
pdf array contains pre-collision using FETCH and nNow
real(kind=rk), intent(out) :: res(:)
results
integer, intent(in) :: nVals
nVals to get
Calls
Call graph
mus_deriveelectricfield calls cxdirrk, convprepost, val