mus_perform_dynLoadBal – Musubi
mus_perform_dynLoadBal Subroutine
40 statements
Source File
public subroutine mus_perform_dynLoadBal(scheme, params, geometry, solverData)
Wrap up the routines required for dynamic load balancing
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme type
type(mus_param_type), intent(inout) :: params
Global parameters
type(mus_geom_type), intent(inout) :: geometry
Treelmesh data
type(mus_varSys_solverData_type), target :: solverData
contains pointer to scheme, physics types
Calls
Called by
Call graph
mus_perform_dynloadbal calls dump_linear_partition, exchange_tree_bc, mus_balance, mus_construct, mus_define_layout, mus_init_scheme, mus_pdf_serialize, mus_pdf_unserialize, mus_reload_ibm, mus_reset_aux, mus_scheme_cleanup, mus_unload_ibm, tem_destroy_sparta, tem_exchange_sparta, tem_init_sparta, treeid
mus_solve calls mus_perform_dynloadbal
musubi calls mus_solve