mus_mixture_out – Musubi
mus_mixture_out Subroutine
20 statements
Source File
public subroutine mus_mixture_out(me, conf, schemeHeader)
This routine write mixture properties into lua file
Arguments
Type Intent Optional Attributes Name
type(mus_mixture_type), intent(in) :: me
mixture info
type(aot_out_type) :: conf
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
Calls
Called by
Call graph
mus_mixture_out calls aot_out_close_table, aot_out_open_table, aot_out_val
mus_scheme_out calls mus_mixture_out
mus_writesolverspecinfo calls mus_scheme_out