mus_init_advRel_multispecies_liquid – Musubi
mus_init_advRel_multispecies_liquid Subroutine
46 statements
Source File
public subroutine mus_init_advRel_multispecies_liquid(relaxation, layout, nFields, compute)
Initialize the relaxation model for multispecies liquid model
Arguments
Type Intent Optional Attributes Name
character(len=labelLen), intent(in) :: relaxation
character(len=labelLen), intent(in) :: layout
integer, intent(in) :: nFields
procedure(kernel), intent(out), pointer :: compute
Calls
Called by
Call graph
mus_init_advrel_multispecies_liquid calls tem_abort
init_advrel calls mus_init_advrel_multispecies_liquid
mus_init_flow calls init_advrel
mus_initialize calls mus_init_flow
musubi calls mus_initialize