mus_derVar_intpOnPoint – Musubi
mus_derVar_intpOnPoint Subroutine
33 statements
Source File
public subroutine mus_derVar_intpOnPoint(varPos, varSys, tree, time, point, nPnts, stencil, levelPointer, levelDesc, res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: varPos
Position of variable in varSys
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
real(kind=rk), intent(in) :: point(:,:)
Three-dimensional coordinates at which the variable should be evaluated. Only useful for variables provided as space-time functions.
integer, intent(in) :: nPnts
Number of values to obtain for this variable (vectorized access).
type(tem_stencilHeader_type), intent(in) :: stencil
stencil definition
integer, intent(in) :: levelPointer(:)
Pointer from treeIDlist entry to level-wise fluid part of total list
type(tem_levelDesc_type), intent(in) :: levelDesc(tree%global%minLevel:)
level description of all levels
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Dimension: n requested entries x nComponents of this variable Access: (iElem-1)*fun%nComponents + iComp
Calls
Called by
Call graph
mus_dervar_intponpoint calls get_element, mus_intp_getsrcelemposintree, tem_abort, val
mus_intp_getsrcelemposintree calls nghelems, tem_BaryOfId, tem_CoordOfReal, tem_FirstIdAtLevel, tem_IdOfCoord, tem_LevelOf, tem_ParentOf, tem_PosOfId, tem_eligibleChildren
mus_derivevar_forpoint calls mus_dervar_intponpoint
mus_reductiontransient_forpoint calls mus_dervar_intponpoint