mus_init_latticeUnit – Musubi
mus_init_latticeUnit Subroutine
16 statements
Source File
public subroutine mus_init_latticeUnit(lattice, minLevel, maxLevel, scaleFactor)
This routine initialize lattice dx and dt
Arguments
Type Intent Optional Attributes Name
type(mus_latticeUnit_type), intent(out) :: lattice
Lattice unit
integer, intent(in) :: minLevel
minlevel and maxlevel
integer, intent(in) :: maxLevel
minlevel and maxlevel
integer, intent(in) :: scaleFactor
scaleFactor depending on acoustic or diffusive scaling
Calls
Called by
Call graph
mus_init_latticeunit calls set_values_by_levels, tem_horizontalSpacer
mus_load_config calls mus_init_latticeunit
musubi calls mus_load_config