mus_load_source_var – Musubi
mus_load_source_var Subroutine
42 statements
Source File
public subroutine mus_load_source_var(me, possVars, conf, parent, key, varSys)
Routine load musubi source terms for given key. key is glob_source or source
Arguments
Type Intent Optional Attributes Name
type(mus_source_type), intent(out) :: me
Source variable type to initialize
type(tem_possible_variable_type), intent(in) :: possVars
possible source variables
type(flu_State) :: conf
flu state
integer, intent(in), optional :: parent
parent handle if scheme table is defined
character(len=*), intent(in) :: key
key to load source term
type(tem_varSys_type), intent(inout) :: varSys
Global variable system
Calls
Called by
Call graph
mus_load_source_var calls aot_get_val, aot_table_open, init, load_turbchanforce, mus_load_absorblayer, tem_abort, tem_variable_loadMapping, truncate, val
load_turbchanforce calls aot_get_val, aot_table_open, tem_abort, canond, tem_load_shape
mus_load_absorblayer calls aot_get_val, aot_table_open, tem_abort, aot_table_close, upper_to_lower
mus_load_field_single calls mus_load_source_var
mus_load_scheme calls mus_load_source_var, mus_load_fields
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_load_fields calls mus_load_field_single
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load