mus_update_relaxParamFromViscSTfun – Musubi
mus_update_relaxParamFromViscSTfun Subroutine
21 statements
Source File
public subroutine mus_update_relaxParamFromViscSTfun(omega, visc, viscSTfun, nElems, baryOfTotal, tNow, viscRef)
This routine is used to initialize relaxation paramter and update bulk viscosity at every time step Bulk visocisty is defined as space-time function to apply ramping and spatial sponge in bulk viscosity
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout) :: omega(:)
relaxation parameter
real(kind=rk), intent(inout) :: visc(:)
Kinematic viscosity
type(tem_spacetime_fun_type), intent(in) :: viscSTfun
viscosity space-time function
integer, intent(in) :: nElems
Number of local elements including halos
real(kind=rk), intent(in) :: baryOfTotal(:,:)
baryID of total list
type(tem_time_type), intent(in) :: tNow
current simulation time
real(kind=rk), intent(in) :: viscRef
reference physical viscosity on current level i.e. (dxP_l)^2/dtP_l Dividing physical viscosity with the viscRef gives vL_l/dtL_l
Calls
Called by
Call graph
mus_update_relaxparamfromviscstfun calls mus_calcomegafromvisc, tem_spacetime_for
mus_init_fluid calls mus_update_relaxparamfromviscstfun
mus_hvs_init_aux calls mus_init_fluid
mus_init_aux calls mus_init_fluid
mus_reset_aux calls mus_init_fluid
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_hvs_init_aux