mus_inamuro_IBM – Musubi
mus_inamuro_IBM Subroutine
132 statements
Source File
public subroutine mus_inamuro_IBM(me, commPattern, globTree, general, pdf, layout, levelDesc, globSys, stateVarMap, convFac, iField, iLevel, state)
This subroutine modifies the state vector according to the method described in the paper \a Lift generation by a two-dimensional symmetric flapping wing: immersed boundary-lattice Boltzmann simulations \a by Inamuro et al. @cite Ota:2012bx .
!$omp single
!$omp end single
!$omp single
!$omp end single
!$omp single
!$omp end single
!$omp single
!$omp end single
!$omp single !$omp end single
!$omp single
!$omp end single
!$omp single
!$omp end single
!$omp single
!$omp end single !$omp single
!$omp end single
!$omp single
!$omp end single
!$omp single
!$omp end single
!$omp single
!$omp end single
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_type), intent(inout) :: me(:)
datatype to store the surface information
type(tem_commPattern_type), intent(inout) :: commPattern
communication pattern
type(treelmesh_type) :: globTree
global tree information
type(tem_general_type), intent(in) :: general
general data
type(pdf_data_type), intent(inout) :: pdf
pdf_data_type incl. connectivity array on all levels
type(mus_scheme_layout_type) :: layout
scheme layout of the current scheme incl. array of stencils
type(tem_levelDesc_type), intent(inout) :: levelDesc
the level descriptor incl. ghost and halo elements as well as the communicator information on the level iLevel
type(tem_varSys_type) :: globSys
global variable system of the current scheme
integer, intent(in) :: stateVarMap(:)
Position of state variables in globSys
type(mus_convertFac_type), intent(in) :: convFac
conversion factors
integer, intent(in) :: iField
the current field
integer, intent(in) :: iLevel
the current level
real(kind=rk), intent(inout) :: state(:,:)
state_data type
Calls
Called by
Call graph
mus_inamuro_ibm calls nelems, newunit, parentids, mus_applyforce_x, mus_calcforce_x, mus_corrforce_xk, mus_corrvel_x, mus_free_ibmdata, mus_ibmfinishbuff, mus_inamuroini, mus_intpvel_xk, tem_calcTriaAreas, tem_dump_stlb, tem_startTimer, tem_stopTimer, tem_timeControl_check, tem_time_sim_stamp, val
do_fast_singlelevel calls mus_inamuro_ibm