mus_assign_calcAuxField_ptr – Musubi
mus_assign_calcAuxField_ptr Subroutine
26 statements
Source File
public subroutine mus_assign_calcAuxField_ptr(schemeHeader, calcAuxField)
This routine assign function pointer to compute auxField var
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_header_type), intent(in) :: schemeHeader
scheme defnition
procedure(mus_proc_calcAuxField), intent(out), pointer :: calcAuxField
function pointer to assign
Called by
Call graph
mus_init_scheme calls mus_assign_calcauxfield_ptr
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve