mus_hvs_config_load – Musubi
mus_hvs_config_load Subroutine
46 statements
Source File
public subroutine mus_hvs_config_load(me, scheme, solverData, geometry, params)
Read in LUA parameter file See http://www.lua.org for a reference on how to use Lua is a scripting language in itself which allows more complex parameter files including comments And load / create the mesh depending on the configuration
Arguments
Type Intent Optional Attributes Name
type(mus_hvs_config_type), intent(out) :: me
Musubi harvesting configuration to load when no tracking table is defined
type(mus_scheme_type), target :: scheme
scheme type
type(mus_varSys_solverData_type), target :: solverData
contains pointer to scheme, physics types
type(mus_geom_type), intent(inout), target :: geometry
Treelmesh data
type(mus_param_type), intent(inout), target :: params
Global parameters
Calls
Called by
Call graph
mus_hvs_config_load calls aot_get_val, conf, hvs_output_load, mus_hvs_load_solverdata, mus_load_bc_data, mus_open_config, tem_abort, tem_debug_load_main, tem_horizontalSpacer, tem_load_general, tem_load_restart, tem_logging_load_primary, tem_startTimer, tem_stopTimer, tem_timeControl_start_at_sim
mus_hvs_load_solverdata calls conf, tem_horizontalSpacer, mus_load_param, mus_load_physics, mus_load_scheme
mus_load_bc_data calls init_tem_bc_prop, load_tem_BC_qVal, mus_build_posinprop, property, qval
mus_open_config calls open_config_chunk, mus_create_funcstr, tem_open_distconf_array
mus_harvesting calls mus_hvs_config_load