mus_append_auxField – Musubi
mus_append_auxField Subroutine
85 statements
Source File
public subroutine mus_append_auxField(varSys, solverData, schemeHeader, nFields, fldLabel, derVarName)
Append auxiliary variables which are computed from state and stored in auxField array using calcAuxField function
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
global variable system
type(mus_varSys_solverData_type), intent(in), target :: solverData
Contains pointer to solver data types
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
integer, intent(in) :: nFields
number of fields
character(len=*), intent(in) :: fldLabel(:)
array of field label prefix. Size=nFields
type(grw_labelarray_type), intent(inout) :: derVarName
array of derive physical variables
Calls
Called by
Call graph
mus_append_auxfield calls append, mus_get_new_solver_ptr, tem_abort, tem_varSys_append_auxFieldVar
mus_build_varsys calls mus_append_auxfield
mus_init_scheme calls mus_build_varsys
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize