mus_init_sourceTerms – Musubi
mus_init_sourceTerms Subroutine
59 statements
Source File
public subroutine mus_init_sourceTerms(field, nFields, globSrc, varSys, tree, bc_prop, stencil, nElems_solve, levelDesc)
This routine does set_params and setupIndices for all sources terms by gathering points to apply souce term before.
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(inout) :: field(:)
contains sources of all fields
integer, intent(in) :: nFields
Number of fields
type(mus_source_type), intent(inout) :: globSrc
global source
type(tem_varSys_type), intent(in) :: varSys
global variable system
type(treelmesh_type), intent(in) :: tree
global treelm mesh
type(tem_BC_prop_type), intent(in) :: bc_prop
bc property which is used to identify elements belong to certain BCs
type(tem_stencilHeader_type), intent(in) :: stencil
stencil header
integer, intent(in) :: nElems_solve(tree%global%minLevel:)
Number of elements to solve in all levels nFluids + nGhostFromCoarser
type(tem_levelDesc_type), intent(in) :: levelDesc(tree%global%minLevel:)
Level descriptors
Calls
Called by
Call graph
mus_init_sourceterms calls mus_init_internalsource, mus_setupindices_forsrc, tem_horizontalSpacer
mus_init_internalsource calls mus_init_hrrcorrection, val
mus_setupindices_forsrc calls mus_init_absorblayer, mus_init_turbchanforce, set_params, setup_indices, val
mus_init_turbchanforce calls mpi_allreduce, tem_create_subTree_of
mus_init_aux calls mus_init_sourceterms
mus_reset_aux calls mus_init_sourceterms
mus_perform_dynloadbal calls mus_reset_aux