mus_calc_thermFactor_single – Musubi
mus_calc_thermFactor_single Subroutine
12 statements
Source File
private subroutine mus_calc_thermFactor_single(nFields, temp, press, mole_frac, therm_factors)
Dummy routine which sets thermodynamic factor matrix to diagonal matrix
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nFields
number of fields in mixture
real(kind=rk), intent(in) :: temp
mixture temperature
real(kind=rk), intent(in) :: press
mixture pressure
real(kind=rk), intent(in) :: mole_frac(nFields)
mole fraction of all species of single element
real(kind=rk), intent(out) :: therm_factors(nFields,nFields)
thermodynamic factor matrix
Called by
Call graph
mus_calc_thermfactor calls mus_calc_thermfactor_single
applysrc_electricmsliquid_1stord_wtdf calls mus_calc_thermfactor
applysrc_electricmsliquid_2ndord_wtdf calls mus_calc_thermfactor
applysrc_forcemsliquid_1stord_wtdf calls mus_calc_thermfactor
applysrc_forcemsliquid_2ndord_wtdf calls mus_calc_thermfactor
bgk_advrel_d3q19f3_msliquid_wtdf calls mus_calc_thermfactor
bgk_advrel_msliquid_generic_wtdf calls mus_calc_thermfactor
deriveauxmsliquid_fromstate_wtdf calls mus_calc_thermfactor
deriveequilvelwtdf_msliquid calls mus_calc_thermfactor
deriveequilwtdf_msliquid calls mus_calc_thermfactor
mrt_advrel_d3q19f3_msliquid_wtdf calls mus_calc_thermfactor
mrt_advrel_msliquid_generic_wtdf calls mus_calc_thermfactor
mus_addelectrictoauxfield_msl_wtdf calls mus_calc_thermfactor
mus_addforcetoauxfield_msl_wtdf calls mus_calc_thermfactor
mus_init_msliquid calls mus_calc_thermfactor
spc_molefrac_wtdf calls mus_calc_thermfactor
mus_init_byic calls mus_init_msliquid
mus_init_flow calls mus_init_byic