mus_inamuroIni – Musubi
mus_inamuroIni Subroutine
77 statements
Source File
private subroutine mus_inamuroIni(me, IBMData, state, globTree, stencil, stencilPos, levelDesc, globSys, pdfPos, iLevel, convFac)
This subroutine fills the initial force, initial velocity, predef. velocity array for the surface points Xk as well as the velocity array for the neighbors.
!$omp single
!$omp end single
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_type), intent(in) :: me
datatype to store the surface information
type(mus_IBM_tmpData_type), intent(inout) :: IBMData
tmp IBMData type to be filled
real(kind=rk), intent(in) :: state(:)
the state array holding the pdfs
type(treelmesh_type), intent(in) :: globTree
global tree information
type(tem_stencilHeader_type), intent(in) :: stencil(:)
stencil used by the IBM
integer, intent(in) :: stencilPos
position of the IBM stencil
type(tem_levelDesc_type), intent(in) :: levelDesc
level descriptor incl. ghost and fluid elements
type(tem_varSys_type) :: globSys
global variable system of the current scheme
integer :: pdfPos
position of the velocity in the global variable system
integer :: iLevel
the current level
type(mus_convertFac_type), intent(in) :: convFac
conversion factors
Calls
Called by
Call graph
mus_inamuroini calls append, inamuroDelta3D, getvelocity, nelems, pointcoords, ptrs, tem_BaryOfId, val
getvelocity calls getvelocity_forelemfromstate_noforce, getvelocity_forpdfsubset
mus_inamuro_ibm calls mus_inamuroini
do_fast_singlelevel calls mus_inamuro_ibm