mus_load_particle_creator_timing – Musubi
mus_load_particle_creator_timing Subroutine
23 statements
Source File
public subroutine mus_load_particle_creator_timing(conf, p_thandle, particle_creator, Nparticles, chunkSize, scheme, geometry, myRank)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
configuration
integer, intent(in) :: p_thandle
Handle to particle table
type(mus_particle_creator_type), intent(inout) :: particle_creator
Particle creator object
integer, intent(in) :: Nparticles
Number of particles in lua table
integer, intent(in) :: chunkSize
Size of the chunks of particle data to read from the lua script
type(mus_scheme_type), intent(in) :: scheme
Scheme
type(mus_geom_type), intent(in) :: geometry
Geometry
integer, intent(in) :: myRank
This MPI process rank
Calls
Called by
Call graph
mus_load_particle_creator_timing calls aot_get_val, aot_table_open, init_particle_creator
init_particle_creator calls init
mus_load_particles calls mus_load_particle_creator_timing
mus_initialize calls mus_load_particles
musubi calls mus_initialize