mus_readRestart – Musubi
mus_readRestart Subroutine
27 statements
Source File
public subroutine mus_readRestart(levelPointer, restart, scheme, tree)
Read the serialized restart file into the state vectors
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: levelPointer(tree%nElems)
Level pointer, from tree mesh to level descriptor
type(tem_restart_type), intent(inout) :: restart
restart information
type(mus_scheme_type), intent(inout) :: scheme
array of schemes including the data to be serialized and dumped
type(treelmesh_type), intent(in) :: tree
mesh, provided in treelm format
Calls
Called by
Call graph
mus_readrestart calls mus_pdf_unserialize, tem_restart_closeRead, tem_restart_openRead, tem_restart_readData
mus_harvesting calls mus_readrestart