mus_define_d3q27 – Musubi
mus_define_d3q27 Subroutine
12 statements
Source File
public subroutine mus_define_d3q27(layout, nElems)
This subroutine sets the parameters for the predefined d3q27 stencil.
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_layout_type), intent(inout) :: layout
scheme layout for pdf state
integer, intent(in) :: nElems
number of elements use this layout
Calls
Called by
Call graph
mus_define_d3q27 calls mus_calculate_speed_of_sound, mus_set_weights_d3q27, tem_create_stencil, tem_identify_prevailDirections, tem_stencil_zeroPos
mus_calculate_speed_of_sound calls cxcx
mus_define_layout calls mus_define_d3q27
mus_load_scheme calls mus_define_layout
mus_perform_dynloadbal calls mus_define_layout
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config