mus_BC_timing – Musubi
mus_BC_timing Subroutine
20 statements
Source File
public subroutine mus_BC_timing(nBCs, bc_labels, comm)
Output the min and max time across all ranks, which are spent on each boundary condition.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nBCs
character(len=labelLen), intent(in) :: bc_labels(nBCs)
integer, intent(in) :: comm
Calls
Called by
Call graph
mus_bc_timing calls get_boundarytime, mpi_reduce, tem_horizontalSpacer
get_boundarytime calls get_boundarytime_byid, get_boundarytime_total
get_boundarytime_byid calls tem_getTimerVal
get_boundarytime_total calls get_boundarytime
mus_finalize calls mus_bc_timing
musubi calls mus_finalize