mus_writeRestart – Musubi
mus_writeRestart Subroutine
32 statements
Source File
public subroutine mus_writeRestart(levelPointer, restart, scheme, tree, timing, timerHandle, suffix)
Write the serialized buffer assembled in mus_serializeData to disk
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: levelPointer(:)
global pdf info
type(tem_restart_type), intent(inout) :: restart
restart information
type(mus_scheme_type), intent(inout) :: scheme
array of schemes including the data to be serialized and dumped
type(treelmesh_type), intent(in) :: tree
mesh, provided in treelm format
type(tem_time_type), intent(inout) :: timing
current simulation time information
integer, intent(in) :: timerHandle
Timer handle
character(len=*), intent(in), optional :: suffix
optional suffix (if present NO timestamp will be added!!!!)
Calls
Called by
Call graph
mus_writerestart calls mus_pdf_serialize, tem_restart_closeWrite, tem_restart_openWrite, tem_restart_writeData, tem_startTimer, tem_stopTimer
mus_pdf_serialize calls tem_LevelOf, val
mus_dumpdata calls mus_writerestart
mus_finalize calls mus_writerestart
check_flow_status calls mus_dumpdata
musubi calls mus_finalize, mus_solve
mus_solve calls check_flow_status