mus_init_interpolate – Musubi
mus_init_interpolate Subroutine
34 statements
Source File
public subroutine mus_init_interpolate(intp, levelDesc, schemeHeader, stencil, minLevel, maxLevel, fieldProp)
This subroutine initialzes the interpolation
setting the fillMineFromFiner and fillFinerFromMe function pointers to the interpolation function chosen by the user and
pre-calculating the weights based on the distances between source and target nodes
allocate buffers if required
Arguments
Type Intent Optional Attributes Name
type(mus_interpolation_type), intent(inout) :: intp
interpolation type
type(tem_levelDesc_type), intent(inout) :: levelDesc(minLevel:maxLevel)
level descriptor is actually used
type(mus_scheme_header_type), intent(in) :: schemeHeader
scheme header
type(tem_stencilHeader_type), intent(in) :: stencil
the stencil header
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(mus_field_prop_type), intent(in) :: fieldProp(:)
field properties
Calls
Called by
Call graph
mus_init_interpolate calls assign_intp_fluid, assign_intp_fluidles, tem_abort
assign_intp_fluid calls tem_abort
assign_intp_fluidles calls tem_abort
mus_hvs_init_aux calls mus_init_interpolate
mus_init_aux calls mus_init_interpolate
mus_reset_aux calls mus_init_interpolate
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_hvs_init_aux
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve