mus_timeControl_homogenize – Musubi
mus_timeControl_homogenize Subroutine
22 statements
Source File
public subroutine mus_timeControl_homogenize(me, dt, reqInt)
Converts sim time to iter and vice versa depends on which one is defined in the configuration file
Arguments
Type Intent Optional Attributes Name
type(tem_timeControl_type), intent(inout) :: me
simulation time control
real(kind=rk), intent(in) :: dt
dt of maxlevel or smallest dt
integer, intent(in) :: reqInt
Required interval, in which the update MUST occur. This is required for the musubi multilevel, where the time step should only be determined active, when the end of the largest cycle is reached.
Calls
Called by
Call graph
mus_timecontrol_homogenize calls tem_timeControl_dump
mus_init_aux calls mus_timecontrol_homogenize, mus_init_geomincr, mus_init_tracker
mus_init_geomincr calls mus_timecontrol_homogenize
mus_init_tracker calls mus_timecontrol_homogenize
mus_reset_aux calls mus_timecontrol_homogenize, mus_init_tracker
mus_hvs_init_aux calls mus_init_tracker
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_solve calls mus_perform_dynloadbal
mus_harvesting calls mus_hvs_init_aux
musubi calls mus_initialize, mus_solve