mus_load_particle_distribution – Musubi
mus_load_particle_distribution Subroutine
20 statements
Source File
public subroutine mus_load_particle_distribution(distribution, conf, parent)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_blob_prob_type), intent(inout) :: distribution
type(flu_State) :: conf
configuration
integer, intent(in) :: parent
Handle to parent table in which the "shape" table exists
Calls
Called by
Call graph
mus_load_particle_distribution calls aot_get_val, check_aot_error
mus_load_particleblob_cylinder calls mus_load_particle_distribution
mus_load_particleblob_prism calls mus_load_particle_distribution
mus_load_predefined_particleblob calls mus_load_particleblob_cylinder, mus_load_particleblob_prism
mus_load_particles calls mus_load_predefined_particleblob
mus_initialize calls mus_load_particles