mus_load_scheme – Musubi
mus_load_scheme Subroutine
62 statements
Source File
public subroutine mus_load_scheme(me, solverData, geometry, conf, params, parent, isMusHvs)
load single scheme defined in lua file with or without scheme handle
This routines checks whether schemes table
 boundary_conditions = {...},
is defined. If yes then it will load schemes table and set mus_scheme_type. If no special scheme table is defined, default tables are loaded from the root level of the lua file fluid, boundary conditions and initial condiitions
 fluid = { ... }
 boundary_conditions = {...}
 initial_conditions = {...}
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout), target :: me
scheme type
type(mus_varSys_solverData_type), target :: solverData
contains pointer to scheme, physics types
type(mus_geom_type), intent(in), target :: geometry
geometry information like tree and boundary
type(flu_State) :: conf
flu state
type(mus_param_type), intent(inout), target :: params
global parameter type
integer, intent(in), optional :: parent
parent handle if scheme table is defined
logical, intent(in), optional :: isMusHvs
Logic to not to load tracking and variable table if this routine is called from mus_hvs_config_load. Default is False
Calls
Called by
Call graph
mus_load_scheme calls mus_init_varsys_solverdata, mus_append_readvarasstatevar, mus_append_statevar, mus_create_poss_srcvar, mus_create_poss_transvar, mus_define_layout, mus_load_fieldbaseinfos, mus_load_fields, mus_load_interpolate, mus_load_newlayout, mus_load_scheme_header, mus_load_source_var, mus_load_transport_var, tem_abort, tem_horizontalSpacer, tem_load_tracking, tem_varSys_init, tem_variable_load
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load