mus_init_relaxParam – Musubi
mus_init_relaxParam Subroutine
11 statements
Source File
public subroutine mus_init_relaxParam(omLvl, minLevel, maxLevel, nElems)
This routine initialize relaxation parameter
Arguments
Type Intent Optional Attributes Name
type(mus_relaxationParam_type), intent(out), allocatable :: omLvl(:)
relaxation paramter
integer, intent(in) :: minLevel
minlevel and maxLevel
integer, intent(in) :: maxLevel
minlevel and maxLevel
integer, intent(in) :: nElems(minLevel:maxLevel)
number of local elements per level
Called by
Call graph
mus_init_fluid calls mus_init_relaxparam
mus_hvs_init_aux calls mus_init_fluid
mus_init_aux calls mus_init_fluid
mus_reset_aux calls mus_init_fluid
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_hvs_init_aux
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize