mus_nernstPlanck_advRel_generic – Musubi
mus_nernstPlanck_advRel_generic Subroutine
50 statements
Source File
public subroutine mus_nernstPlanck_advRel_generic(fieldProp, inState, outState, auxField, neigh, nElems, nSolve, level, layout, params, varSys, derVarPos)
Advection relaxation routine for the nernst planvk model with an explicit calculation of all equilibrium quantities. Slow and simple. This routine should only be used for testing purposes
This subroutine interface must match the abstract interface definition kernel in scheme/mus_scheme_type_module.f90 in order to be callable via compute function pointer.
Pre-calculate velocitiy terms relaxation parameter
Calculate equilibrium distribution functions fEq
Generic fetching step: Streaming for pull Local copy for push
Relaxation
Arguments
Type Intent Optional Attributes Name
type(mus_field_prop_type), intent(in) :: fieldProp(:)
Array of field properties (fluid or species)
real(kind=rk), intent(in) :: inState(nElems*varSys%nScalars)
input pdf vector
real(kind=rk), intent(out) :: outState(nElems*varSys%nScalars)
output pdf vector
real(kind=rk), intent(inout) :: auxField(nElems*varSys%nAuxScalars)
Auxiliary field computed from pre-collision state Is updated with correct velocity field for multicomponent models
integer, intent(in) :: neigh(nElems*layout%fStencil%QQ)
connectivity vector
integer, intent(in) :: nElems
number of elements in state Array
integer, intent(in) :: nSolve
number of elements solved in kernel
integer, intent(in) :: level
current level
type(mus_scheme_layout_type), intent(in) :: layout
current layout
type(mus_param_type), intent(in) :: params
global parameters
type(tem_varSys_type), intent(in) :: varSys
variable system definition
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
position of derived quantities in varsys for all fields
Calls
Call graph
mus_nernstplanck_advrel_generic calls cxdirrk, get_valofindex, val