mus_intp_update_depFromCoarser – Musubi
mus_intp_update_depFromCoarser Subroutine
114 statements
Source File
public subroutine mus_intp_update_depFromCoarser(intp, levelDesc, stencil, minLevel, maxLevel)
The required source elements for ghost from coarser elements are identified in this routine. Moreover, the weights for each sources based on distance are calculated. \n
The depdendencies for ghostFromCoarser elements initially only include its parent element. Additional dependencies Y for the element x are found which were not included in the construction routine before hand. However, they are defined to be inherently part of the stencil and hence exist locally and can simply be added to the dependencies. Two different ways are implemented. Full interpolation stencil the complete compute stencil is included into the dependency list
  Y       Y       Y
        x   o
  Y       O       Y
        o   o
  Y       Y       Y
Note: The view here is according to how the interpolation will be done. The coarse level does the interpolation for the finer level. Thus, we access the information from the levelDesc with the targetLevel and sourceLevel perspective.
Steps of finding sources: 1. loop over all neighbors: iNeigh = 1, QQ 2. get neighbor posInTotal: elemPos = neigh(1)%nghElems 3. if elemPos > 0, add this source into depFromCoarser%elem add this source into sourceFromCoarser save its position in sourceFromCoarser into depFromCoarser%elemBuffer calculate its weight based on relative coordinates in stencil weight is inverse proportional to the distance from source to target weight is normalized at last, so that sum of weights equals 1 4. save its offset on stencil
After finding sources, append target to low or high interpolation list based on if all required sources are found.
suppChild = 1
write(dbgUnit(5),"(A, I0)") ' suppChild: ', suppChild write(dbgUnit(5),"(A, I0)") ' childNum: ', childNum
Arguments
Type Intent Optional Attributes Name
type(mus_interpolation_type), intent(inout) :: intp
interpolation type
type(tem_levelDesc_type) :: levelDesc(minLevel:maxLevel)
Level Descriptor
type(tem_stencilHeader_type), intent(in) :: stencil
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
Calls
Called by
Call graph
mus_intp_update_depfromcoarser calls append, coord, depSource_append, nelems, nghelems, compute_weight, find_possintporderandupdatemysources, tem_abort, tem_horizontalSpacer, val
compute_weight calls tem_abort
mus_construct calls mus_intp_update_depfromcoarser
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve