mus_load_particles – Musubi
mus_load_particles Subroutine
95 statements
Source File
public subroutine mus_load_particles(particleGroup, particle_kind, conf, chunkSize, scheme, geometry, myRank)
Routine to load the particle data from the musubi.lua file meant to be called from within mus_load_config after the lua file has already been opened
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
particleGroup to add particles loaded from the lua script to
character(len=*), intent(in) :: particle_kind
Kind of particle modelling to use
type(flu_State) :: conf
configuration
integer, intent(in) :: chunkSize
Size of the number of particles to be read in one chunk from the lua table
type(mus_scheme_type), intent(in) :: scheme
Scheme to determine if particles belong on this process
type(mus_geom_type), intent(in) :: geometry
Geometry to determine if particles belong on this process
integer, intent(in) :: myRank
This process rank
Calls
Called by
Call graph
mus_load_particles calls aot_get_val, aot_table_close, aot_table_open, check_aot_error, check_particle_scheme_kind_compatibility, init_da_particle_dps, init_da_particle_mem, init_particle_creator_from_blob, init_particle_creator_from_blob_prism, load_particle_dps_creator_data, load_particle_mem_creator_data, mus_load_debugtracker, mus_load_particle_boundaries, mus_load_particle_collisions, mus_load_particle_creator_timing, mus_load_particle_interpolation, mus_load_predefined_particleblob, mus_particles_print_config, print_particleblob, print_particleblob_prism, printparticleinterpolator, tem_abort
mus_initialize calls mus_load_particles
musubi calls mus_initialize