mus_load_physics – Musubi
mus_load_physics Subroutine
159 statements
Source File
public subroutine mus_load_physics(me, conf, tree, scaleFactor, dtRef, dxRef)
This routine loads the physics table from musubi config file
If no physics table is provided, the conversion factors default to 1, resulting in the lattice units being directly used. dx_ref and dt_ref are set according to the provided arguments, or if not provided default to 1. See the [mus_physics_type] for a description of the various factors that can be set here.
Arguments
Type Intent Optional Attributes Name
type(mus_physics_type), intent(out) :: me
physics type
type(flu_State) :: conf
flu state
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: scaleFactor
scaling factor: diffusive -> 4; acoustic -> 2
real(kind=rk), intent(in), optional :: dtRef
reference time step if none
real(kind=rk), intent(in), optional :: dxRef
reference spacestep if none
Calls
Called by
Call graph
mus_load_physics calls aot_get_val, aot_table_close, aot_table_open, mus_physics_dump2outunit, mus_set_convfac, mus_set_scalefac, set_values_by_levels, tem_ElemSizeLevel, tem_abort, tem_horizontalSpacer
mus_physics_dump2outunit calls tem_toStr
mus_hvs_load_solverdata calls mus_load_physics
mus_load_config calls mus_load_physics
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load