mus_load_turbulence – Musubi
mus_load_turbulence Subroutine
67 statements
Source File
public subroutine mus_load_turbulence(me, conf, parent)
load turbulence table
Arguments
Type Intent Optional Attributes Name
type(mus_turbulence_type), intent(out) :: me
fluid type
type(flu_State) :: conf
lua state
integer, intent(in), optional :: parent
parent handle
Calls
Called by
Call graph
mus_load_turbulence calls aot_get_val, aot_table_close, aot_table_open, tem_abort, tem_horizontalSpacer, upper_to_lower
mus_load_fluid calls mus_load_turbulence
mus_load_field_prop calls mus_load_fluid
mus_load_field_single calls mus_load_field_prop
mus_load_fields calls mus_load_field_single