mus_source_cleanup – Musubi
mus_source_cleanup Subroutine
7 statements
Source File
public subroutine mus_source_cleanup(me)
This routine act as a destructor for source type. The arrays allocated in mus_init_sourceTerms are destroyed here
Arguments
Type Intent Optional Attributes Name
type(mus_source_type), intent(inout) :: me
Called by
Call graph
mus_field_cleanup calls mus_source_cleanup
mus_scheme_cleanup calls mus_source_cleanup, mus_field_cleanup
mus_perform_dynloadbal calls mus_scheme_cleanup
mus_solve calls mus_perform_dynloadbal
musubi calls mus_solve