mus_solve – Musubi
mus_solve Subroutine
53 statements
Source File
public subroutine mus_solve(scheme, geometry, params, control, solverData, adapt)
This routine does the main musubi computation loop
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme type
type(mus_geom_type), intent(inout) :: geometry
Treelmesh data
type(mus_param_type), intent(inout) :: params
Global parameters
type(mus_control_type), intent(inout) :: control
control routine
type(mus_varSys_solverData_type), target :: solverData
contains pointer to scheme, physics types
type(tem_adapt_type), intent(inout) :: adapt
mesh adaptation
Calls
Called by
Call graph
mus_solve calls check_density, check_flow_status, check_potential, dump_level_timing, mus_finishibm, mus_perf_measure, mus_perform_dynloadbal, mus_reset_maintimer, tem_simControl_clearStat, tem_startTimer, tem_status_run_end, tem_status_run_terminate, tem_stopTimer, tem_timeControl_check
musubi calls mus_solve