mus_dumpWeights – Musubi
mus_dumpWeights Subroutine
12 statements
Source File
public subroutine mus_dumpWeights(tree, weights, basename)
Dump weights to a file.
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
real(kind=rk), intent(in) :: weights(:)
character(len=pathLen), intent(in) :: basename
Calls
Called by
Call graph
mus_dumpweights calls tem_create_EndianSuffix, tem_dump_weights
mus_balance calls mus_dumpweights
mus_finalize calls mus_dumpweights
mus_perform_dynloadbal calls mus_balance
musubi calls mus_finalize, mus_solve
mus_solve calls mus_perform_dynloadbal