mus_open_config – Musubi
mus_open_config Subroutine
13 statements
Source File
public subroutine mus_open_config(conf, filename, proc)
This routine loads musubi specific lua function from string and musubi input configuration file
Arguments
Type Intent Optional Attributes Name
type(flu_State), allocatable :: conf(:)
lua state to be stored
character(len=*), intent(in) :: filename
name of the config file to be opened
type(tem_comm_env_type), intent(in) :: proc
process description to use
Calls
Called by
Call graph
mus_open_config calls open_config_chunk, mus_create_funcstr, tem_open_distconf_array
mus_hvs_config_load calls mus_open_config
mus_intp_error calls mus_open_config
mus_load_config calls mus_open_config
mus_testinterpolation calls mus_intp_error
mus_harvesting calls mus_hvs_config_load
musubi calls mus_load_config
mus_init_flow calls mus_testinterpolation
mus_initialize calls mus_init_flow