mus_load_fields – Musubi
mus_load_fields Subroutine
79 statements
Source File
public subroutine mus_load_fields(me, varSys, nFields, mixture, nernstPlanck, bc_prop, conf, parent, minLevel, maxLevel, schemeHeader, poss_srcVar, physics, scaling, layout, isMusHvs)
Subroutine to load the field table from the lua configuration file.
If field table is not defined than load bc, ic, fluid, species from scheme table. If scheme table is not defined than load field variables from config parent.
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(inout) :: me(:)
array of field type
type(tem_varSys_type), intent(inout) :: varSys
Global variable system required to append annoymous source and boundary variables
integer, intent(in) :: nFields
type(mus_mixture_type), intent(out) :: mixture
contains mixture information
type(mus_nernstPlanck_type), intent(out) :: nernstPlanck
contains solvent information
type(tem_BC_prop_type), intent(in) :: bc_prop
boundary data from mesh
type(flu_State), intent(inout) :: conf
flu state
integer, intent(in), optional :: parent
parent handle if scheme table is defined
integer, intent(in) :: minLevel
global pdf info
integer, intent(in) :: maxLevel
global pdf info
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
type(tem_possible_variable_type), intent(in) :: poss_srcVar
possible source variables
type(mus_physics_type), intent(in) :: physics
physics type to convert physics to lattice unit or vice versa
character(len=labelLen), intent(in) :: scaling
scaling type
type(mus_scheme_layout_type), intent(in) :: layout
fluid stencil info
logical, intent(in), optional :: isMusHvs
Logic to not to load tracking and variable table if this routine is called from mus_hvs_config_load. Default is False
Calls
Called by
Call graph
mus_load_fields calls aot_table_close, aot_table_open, compute_bulkviscomega, compute_molweightratio, mus_load_field_single, mus_load_mixture, mus_load_nernstplanck, tem_abort, tem_horizontalSpacer
compute_molweightratio calls tem_horizontalSpacer
mus_load_field_single calls tem_abort, tem_horizontalSpacer, mus_add_internal_source_var, mus_load_bc, mus_load_field_prop, mus_load_source_var, mus_set_ic_states, tem_load_ic
mus_load_mixture calls aot_table_close, aot_table_open, tem_abort, tem_horizontalSpacer, aot_get_val, mus_init_enrtl, set_omegaslvl, tem_load_ic, tem_load_spatial, tem_load_temporal
mus_load_nernstplanck calls aot_table_close, aot_table_open, tem_abort, aot_get_val, tem_toStr
mus_load_scheme calls mus_load_fields
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load