mus_set_ic_states – Musubi
mus_set_ic_states Subroutine
34 statements
Source File
private subroutine mus_set_ic_states(scheme_kind, ic_states, IC_nVars)
Set ic states labels by scheme kind
Arguments
Type Intent Optional Attributes Name
character(len=labelLen), intent(in) :: scheme_kind
character(len=labelLen), allocatable :: ic_states(:)
integer, intent(out) :: IC_nVars
Number of initial condition variables required to initialize state
Calls
Called by
Call graph
mus_set_ic_states calls tem_abort
mus_load_field_single calls mus_set_ic_states
mus_load_fields calls mus_load_field_single
mus_load_scheme calls mus_load_fields
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme