mus_updateSrcVar_turbChanForce – Musubi
mus_updateSrcVar_turbChanForce Subroutine
103 statements
Source File
public subroutine mus_updateSrcVar_turbChanForce(fun, auxField, iLevel, varSys, phyConvFac, derVarPos)
Compute dynamic force term using auxField for turbulent channel force.
If wall model BC is applied than compute the friction velocity If wall model BC is not used than compute the friction velocity from the single sided finite difference's and perform the spatial averaging. Friction velocity is computed only on elements intersected by shape_utau defined in musubi.lua. Bulk mean velocity part of forcing is independent whether a wall
Arguments
Type Intent Optional Attributes Name
class(mus_source_op_type), intent(inout) :: fun
Description of method to update source
real(kind=rk), intent(in) :: auxField(:)
input auxField array on current level
integer, intent(in) :: iLevel
current level
type(tem_varSys_type), intent(in) :: varSys
variable system definition
type(mus_convertFac_type), intent(in) :: phyConvFac
Physics conversion factor on current level
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
position of derived quantities in varsys
Calls
Call graph
mus_updatesrcvar_turbchanforce calls auxfield_varpos, bc, fac, field, globbc, graddata, levelpointer, map2global, mpi_allreduce, tem_LevelOf, treeid, u_ptr, val, veltau