mus_fluid_dump – Musubi
mus_fluid_dump Subroutine
50 statements
Source File
private subroutine mus_fluid_dump(me, minLevel, maxLevel, physics, nSolve, general, outUnit, schemeHeader)
Arguments
Type Intent Optional Attributes Name
type(mus_fluid_type), intent(inout) :: me
integer, intent(in) :: minLevel
minlevel and maxlevel
integer, intent(in) :: maxLevel
minlevel and maxlevel
type(mus_physics_type), intent(in) :: physics
physics type to convert physics to lattice unit or vice versa
integer, intent(in) :: nSolve(minLevel:maxLevel)
number of elements to solve per level (fluid+ghost)
type(tem_general_type), intent(in) :: general
general type
integer, intent(in) :: outUnit
type(mus_scheme_header_type), intent(in) :: schemeHeader
scheme header
Calls
Called by
Call graph
mus_fluid_dump calls mpi_reduce, cumulant_omega_check, mus_calcomegafromvisc, mus_nnwtn_dump2outunit, val
cumulant_omega_check calls tem_abort
mus_nnwtn_dump2outunit calls mus_nnwtn_cs_dump, mus_nnwtn_cy_dump, mus_nnwtn_pl_dump, tem_horizontalSpacer
mus_init_fluid calls mus_fluid_dump
mus_hvs_init_aux calls mus_init_fluid
mus_init_aux calls mus_init_fluid
mus_reset_aux calls mus_init_fluid
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_hvs_init_aux
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize