mus_load_transport_var – Musubi
mus_load_transport_var Subroutine
22 statements
Source File
public subroutine mus_load_transport_var(me, possVars, conf, parent, varSys, schemeHeader)
Routine load musubi transport variables
Arguments
Type Intent Optional Attributes Name
type(mus_transport_var_type), intent(out) :: me
transport variable type to initialize
type(tem_possible_variable_type), intent(in) :: possVars
possible transport variables
type(flu_State) :: conf
flu state
integer, intent(in), optional :: parent
parent handle if scheme table is defined
type(tem_varSys_type), intent(inout) :: varSys
Global variable system
type(mus_scheme_header_type), intent(in) :: schemeHeader
Identifier of the scheme
Calls
Called by
Call graph
mus_load_transport_var calls init, tem_abort, tem_variable_loadMapping, truncate, val
mus_load_scheme calls mus_load_transport_var
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load