mus_reset_aux – Musubi
mus_reset_aux Subroutine
64 statements
Source File
private subroutine mus_reset_aux(scheme, params, geometry)
This subroutine initializes musubi after a dynamic load balancing is performed.
initialize fluid type which contains relaxation parameter and function pointers to get mrt paramter and nonEqScaling factor for interpolation
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme type
type(mus_param_type), intent(inout) :: params
Global parameters
type(mus_geom_type), intent(inout) :: geometry
Treelmesh data
Calls
Called by
Call graph
mus_reset_aux calls convergence, fillhelperelementscoarsetofine, fillhelperelementsfinetocoarse, mus_init_bndforce, mus_init_boundary, mus_init_graddata, mus_init_interpolate, mus_calcauxfieldandexchange, mus_init_fluid, mus_init_sourceterms, mus_init_tracker, mus_init_transport_var, mus_intpauxfieldcoarserandexchange, mus_reset_bctimer, mus_reset_leveltimer, mus_timecontrol_homogenize, tem_abort, tem_create_subTree_of_st_funList, tem_init_convergence, tem_init_restart, tem_opVar_reduction_transient_init, tem_restart_finalize
mus_perform_dynloadbal calls mus_reset_aux