mus_load_predefined_particleblob – Musubi
mus_load_predefined_particleblob Subroutine
63 statements
Source File
public subroutine mus_load_predefined_particleblob(conf, parent, blob_type, flag)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
configuration
integer, intent(in) :: parent
Handle to parent table in which the "shape" table exists
character(len=LabelLen), intent(inout) :: blob_type
Output string containing the blob type
logical, intent(out) :: flag
Output flag set to TRUE when reading was successful, FALSE if not
Calls
Called by
Call graph
mus_load_predefined_particleblob calls aot_get_val, aot_table_close, aot_table_open, check_aot_error, mus_load_particleblob_cylinder, mus_load_particleblob_prism, tem_abort
mus_load_particleblob_cylinder calls aot_get_val, tem_abort, mus_load_particle_distribution
mus_load_particleblob_prism calls aot_get_val, tem_abort, mus_load_particle_distribution
mus_load_particle_distribution calls aot_get_val, check_aot_error
mus_load_particles calls mus_load_predefined_particleblob
mus_initialize calls mus_load_particles
musubi calls mus_initialize