mus_init_bc_elems – Musubi
mus_init_bc_elems Subroutine
24 statements
Source File
public subroutine mus_init_bc_elems(me, nElems, QQN, hasQval)
Arguments
Type Intent Optional Attributes Name
type(bc_elems_type), intent(inout) :: me
integer, intent(in) :: nElems
integer, intent(in) :: QQN
Number of direction excluding center since center is never treated for bc elems
logical, intent(in) :: hasQval
Calls
Called by
Call graph
mus_init_bc_elems calls destroy, init
allocatebclist calls mus_init_bc_elems
build_bclists calls allocatebclist
mus_construct calls build_bclists
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct