mus_intp_update_depFromFiner – Musubi
mus_intp_update_depFromFiner Subroutine
29 statements
Source File
public subroutine mus_intp_update_depFromFiner(intp, levelDesc, minLevel, maxLevel, stencil)
All sources (children) have been found in treelm, updated number of sources needed, based on nDims collect all source elements into sourceFromFiner assign ghost intp list. Currently only average interpolation is implemented for fillMineFromFiner
Arguments
Type Intent Optional Attributes Name
type(mus_interpolation_type), intent(inout) :: intp
interpolation type
type(tem_levelDesc_type) :: levelDesc(minLevel:maxLevel)
Level Descriptor
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(tem_stencilHeader_type), intent(in) :: stencil
Stencil
Calls
Called by
Call graph
mus_intp_update_depfromfiner calls append, depSource_append, nelems, tem_horizontalSpacer, val
mus_construct calls mus_intp_update_depfromfiner
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve