mus_init_aux – Musubi
mus_init_aux Subroutine
61 statements
Source File
public subroutine mus_init_aux(scheme, geometry, params)
Init auxiliary features such as interpolation boundaries, restart and the tracker
initialize fluid type which contains relaxation parameter and function pointers to get mrt paramter and nonEqScaling factor for interpolation
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout), target :: scheme
containers for the different schemes
type(mus_geom_type), intent(inout) :: geometry
geometry information
type(mus_param_type), intent(inout) :: params
global parameters
Calls
Called by
Call graph
mus_init_aux calls convergence, check_streaming_layout, debug_dependencies, dump_intplists, mus_ibm_setparentids, mus_init_bndforce, mus_init_fluid, mus_init_geomincr, mus_init_graddata, mus_init_interpolate, mus_init_sourceterms, mus_init_tracker, mus_init_transport_var, mus_time_homogenize, mus_timecontrol_homogenize, tem_abort, tem_create_subTree_of_st_funList, tem_horizontalSpacer, tem_init_convergence, tem_init_restart
mus_initialize calls mus_init_aux
musubi calls mus_initialize