mus_hvs_construct – Musubi
mus_hvs_construct Subroutine
67 statements
Source File
public subroutine mus_hvs_construct(scheme, geometry, params)
Initialize Musubi data strucutres based on data provided by Treelm
Load the mesh and boundary conditions for this process from disk. Get the level-wise treeID lists and create the required ghost and halo elements.
This is achieved by a two-folded identification of elements.
-# the theoretically required elements are collected based on mus_scheme_layout_type "stencil information" The tem_construction_module "find neighbor routine" performs this task for compute fluid elements. For boundaries which require information from neighbor elements, these required tem_topology_module "treeIDs" are collected into the mus_bc_header_module "boundary element type" -# All required elements are created in the tem_construction_module "Level Descriptor creation routine"
Additional Tasks
receive tem_construction_module "horizontal" (within a level for the element updates)
and tem_construction "vertical" dependencies (between levels for ghost-interpolations).
The main state vector and the neighbor lists on which the kernel then acts is created
The MPI buffers are created.
For each mus_scheme_module "Scheme", the tem_levelDesc_type "Level Descriptor" is created
Result
After this routine, all data structures for starting the main loop of the solver are allocated and ready.
Only difference between this routine and mus_construct is then creating of boundary elements and its stencil are omitted for harvesting
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme information including fluid, boundary and flow information
type(mus_geom_type), intent(inout) :: geometry
geometric information
type(mus_param_type), intent(inout) :: params
run-time Parameters
Calls
Called by
Call graph
mus_hvs_construct calls calculate_nelems, destroy, my_status_int, nelems, mus_calc_nelems, mus_finalize_layout, mus_pdf_allocate, tem_build_horizontalDependencies, tem_debug_HorizontalDependencies, tem_dumpTreeIDlists, tem_find_allElements, tem_getTimerVal, tem_horizontalSpacer, tem_init_elemLevels, tem_startTimer, tem_stopTimer
mus_finalize_layout calls destroy, append, elemlvl, mpi_gather, mpi_gatherv, mpi_type_commit, mpi_type_contiguous, truncate, val
mus_harvesting calls mus_hvs_construct