mus_testInterpolation – Musubi
mus_testInterpolation Subroutine
28 statements
Source File
public subroutine mus_testInterpolation(scheme, tree, general, fac, iLevel, minLevel, maxLevel, pdf)
Call tests to determine the actual error from the interpolation routines on the ghost elements. Compare against the analytical solution, which is given in terms of the initial conditions. Call this routine after the initial values are set and the ghost elements have been filled once, but no computation was started -> after fillHelperElements in the mus_aux_module
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
type(treelmesh_type), intent(in) :: tree
treelm tree
type(tem_general_type), intent(in) :: general
type(mus_convertFac_type), intent(in) :: fac
integer, intent(in) :: iLevel
Level counter variable
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(pdf_data_type), intent(inout) :: pdf(tree%global%minlevel:tree%global%maxlevel)
Calls
Called by
Call graph
mus_testinterpolation calls append, destroy, init, intpfromcoarser, mus_intp_error
mus_intp_error calls ini_state, mpi_reduce, newunit, offset, mus_open_config, set_momentindices, tem_BaryOfId, tem_spatial_for, total
mus_open_config calls open_config_chunk, mus_create_funcstr, tem_open_distconf_array
mus_init_flow calls mus_testinterpolation
mus_initialize calls mus_init_flow
musubi calls mus_initialize