mus_init_fluid – Musubi
mus_init_fluid Subroutine
45 statements
Source File
public subroutine mus_init_fluid(me, physics, schemeHeader, minLevel, maxLevel, levelDesc, pdf, stencil, general, tNow)
This routine initilizes fluid visocity and relaxation paramters for each level
Arguments
Type Intent Optional Attributes Name
type(mus_fluid_type), intent(inout) :: me
fluid type
type(mus_physics_type), intent(in) :: physics
physics type to convert physics to lattice unit or vice versa
type(mus_scheme_header_type), intent(in) :: schemeHeader
scheme header
integer, intent(in) :: minLevel
min and max level
integer, intent(in) :: maxLevel
min and max level
type(tem_levelDesc_type), intent(in) :: levelDesc(minLevel:maxLevel)
level descriptor
type(pdf_data_type), intent(in) :: pdf(minLevel:maxLevel)
pdf info with neigh array for all levels
type(tem_stencilHeader_type), intent(in) :: stencil
stencil header
type(tem_general_type), intent(in) :: general
general type contains communication pattern and proc info
type(tem_time_type), intent(in) :: tNow
current simulation time
Calls
Called by
Call graph
mus_init_fluid calls init, mus_assign_mrt_ptr, mus_assign_nnwtnvisc_ptr, mus_assign_turbvisc_ptr, mus_fluid_dump, mus_init_relaxparam, mus_init_turbulencedata, mus_update_relaxparamfromviscstfun
mus_assign_mrt_ptr calls tem_abort
mus_assign_nnwtnvisc_ptr calls tem_abort
mus_assign_turbvisc_ptr calls tem_abort
mus_fluid_dump calls mpi_reduce, cumulant_omega_check, mus_calcomegafromvisc, mus_nnwtn_dump2outunit, val
mus_init_turbulencedata calls tem_comm_init
mus_update_relaxparamfromviscstfun calls mus_calcomegafromvisc, tem_spacetime_for
cumulant_omega_check calls tem_abort
mus_nnwtn_dump2outunit calls mus_nnwtn_cs_dump, mus_nnwtn_cy_dump, mus_nnwtn_pl_dump, tem_horizontalSpacer
mus_hvs_init_aux calls mus_init_fluid
mus_init_aux calls mus_init_fluid
mus_reset_aux calls mus_init_fluid
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_hvs_init_aux
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve