mus_create_funcStr – Musubi
mus_create_funcStr Subroutine
12 statements
Source File
public subroutine mus_create_funcStr(fun_str)
This routine creates musubi specific lua function to compute dx and dt.
Arguments
Type Intent Optional Attributes Name
character(len=*) :: fun_str
This string contains lua functions to compute dt from visocosity or velocity
Called by
Call graph
mus_open_config calls mus_create_funcstr
mus_hvs_config_load calls mus_open_config
mus_intp_error calls mus_open_config
mus_load_config calls mus_open_config
mus_testinterpolation calls mus_intp_error
mus_harvesting calls mus_hvs_config_load
musubi calls mus_load_config
mus_init_flow calls mus_testinterpolation