mus_init_turbulenceData – Musubi
mus_init_turbulenceData Subroutine
26 statements
Source File
public subroutine mus_init_turbulenceData(me, levelDesc, pattern, nSize)
This initialize turbulence data type which includes velocity array and communication buffer
Arguments
Type Intent Optional Attributes Name
type(mus_turbulence_data_type), intent(out) :: me
turbulence data
tubulence configuration
type(tem_levelDesc_type), intent(in) :: levelDesc
levelDesc to access communication buffers of state array
type(tem_commPattern_type), intent(in) :: pattern
communication pattern
integer, intent(in) :: nSize
Number of elements in state array
Calls
Called by
Call graph
mus_init_turbulencedata calls tem_comm_init
mus_init_fluid calls mus_init_turbulencedata
mus_hvs_init_aux calls mus_init_fluid
mus_init_aux calls mus_init_fluid
mus_reset_aux calls mus_init_fluid
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_hvs_init_aux
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize