mus_turbVisc_Smagorinsky_fromPreColPDF_3D – Musubi
mus_turbVisc_Smagorinsky_fromPreColPDF_3D Subroutine
42 statements
Source File
public subroutine mus_turbVisc_Smagorinsky_fromPreColPDF_3D(turbVisc, turbConfig, state, neigh, auxField, densPos, velPos, nSize, nSolve, nScalars, nAuxScalars, layout, dxL, dtL, viscKine)
Calculate eddy viscosity with smagorinsky model for compressible model using pre-collision PDF. Schneider, A. (2015). A Consistent Large Eddy Approach for Lattice Boltzmann Methods and its Application to Complex Flows. Technical University Kaiserslautern.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(out) :: turbVisc(:)
output: turbulent viscosity
type(mus_turbulence_config_type), intent(in) :: turbConfig
Contains turbulenct coefficients
real(kind=rk), intent(in) :: state(:)
state array
integer, intent(in) :: neigh(:)
neigh array to obtain precollision pdf
real(kind=rk), intent(in) :: auxField(:)
Auxiliary field variable array
integer, intent(in) :: densPos
position of density in auxField
integer, intent(in) :: velPos(3)
position of velocity components in auxField
integer, intent(in) :: nSize
number of elements in state array
integer, intent(in) :: nSolve
Number of element to solve in this level
integer, intent(in) :: nScalars
number of scalars in state array
integer, intent(in) :: nAuxScalars
number of scalars in auxField array
type(mus_scheme_layout_type), intent(in) :: layout
scheme layout
real(kind=rk), intent(in) :: dxL
current level lattice element size
real(kind=rk), intent(in) :: dtL
current level lattice time step size
real(kind=rk), intent(in) :: viscKine(:)
Background kinematic viscosity in lattice divided by dtL
Calls
Call graph
mus_turbvisc_smagorinsky_fromprecolpdf_3d calls getequilibrium, secondmom_minus_cs2_3d
getequilibrium calls geteqbydensvel, getequilibrium_forelemfromstate, getequilibrium_forpdfsubset
geteqbydensvel calls cxdirrk
getequilibrium_forelemfromstate calls cxdirrk, getdensity, getvelocity
getequilibrium_forpdfsubset calls cxdirrk, getdensity_forpdfsubset, getvelocity_forpdfsubset
getdensity calls getdensity_forpdfsubset, getdensity_forelemfromstate
getvelocity calls getvelocity_forpdfsubset, getvelocity_forelemfromstate_noforce