mus_calculate_speed_of_sound – Musubi
mus_calculate_speed_of_sound Function
5 statements
Source File
private function mus_calculate_speed_of_sound(layout) result(c_sound)
Calculate lattice speed of sound for given stencil
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_layout_type), intent(inout) :: layout
scheme layout for pdf state
Return Value real(kind=rk)
Calls
Called by
Call graph
mus_calculate_speed_of_sound calls cxcx
mus_define_d1q3 calls mus_calculate_speed_of_sound
mus_define_d2q5 calls mus_calculate_speed_of_sound
mus_define_d2q9 calls mus_calculate_speed_of_sound
mus_define_d3q13 calls mus_calculate_speed_of_sound
mus_define_d3q19 calls mus_calculate_speed_of_sound
mus_define_d3q27 calls mus_calculate_speed_of_sound
mus_define_d3q6 calls mus_calculate_speed_of_sound
mus_define_d3q7 calls mus_calculate_speed_of_sound
mus_define_layout calls mus_define_d1q3, mus_define_d2q5, mus_define_d2q9, mus_define_d3q13, mus_define_d3q19, mus_define_d3q27, mus_define_d3q6, mus_define_d3q7
mus_load_scheme calls mus_define_layout
mus_perform_dynloadbal calls mus_define_layout
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme