mus_append_stateVar – Musubi
mus_append_stateVar Subroutine
47 statements
Source File
public subroutine mus_append_stateVar(varSys, stateVarMap, solverData, schemeHeader, stencil, nFields, fldLabel)
Append state variable depends on the scheme kind
allocate function pointers, and append pdf to scheme%varSys
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
global variable system
type(tem_varMap_type), intent(out) :: stateVarMap
Store position of state variable in global varSys
type(mus_varSys_solverData_type), intent(in), target :: solverData
Contains pointer to solver data types
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
type(tem_stencilHeader_type), intent(in) :: stencil
compute stencil defintion
integer, intent(in) :: nFields
number of fields
character(len=*), intent(in) :: fldLabel(:)
array of field label prefix. Size=nFields
Calls
Called by
Call graph
mus_append_statevar calls append, init, mus_get_new_solver_ptr, tem_abort, tem_varSys_append_stateVar, truncate
mus_load_scheme calls mus_append_statevar
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load