mus_initAuxField – Musubi
mus_initAuxField Subroutine
15 statements
Source File
public subroutine mus_initAuxField(scheme, general, minLevel, maxLevel)
This routine initialize auxField variable from PDF values initialized by initial condition. AuxField is computed from state using SAVE access for fluid elements and interpolated for ghost elements
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
containers for the scheme contains interpolation type
type(tem_general_type), intent(in) :: general
contains commPattern, MPI communicator and simControl
integer, intent(in) :: minLevel
level range
integer, intent(in) :: maxLevel
level range
Calls
Called by
Call graph
mus_initauxfield calls mus_initauxfieldfluidandexchange, mus_intpauxfieldcoarserandexchange, mus_intpauxfieldfinerandexchange
mus_initauxfieldfluidandexchange calls exchange_real
mus_intpauxfieldcoarserandexchange calls exchange_real
mus_intpauxfieldfinerandexchange calls exchange_real
mus_init_flow calls mus_initauxfield
mus_harvesting calls mus_initauxfield
mus_initialize calls mus_init_flow
musubi calls mus_initialize