mus_particles_DPS_interpolateFluidProperties_onewaycoupled – Musubi
mus_particles_DPS_interpolateFluidProperties_onewaycoupled Subroutine
28 statements
Source File
public subroutine mus_particles_DPS_interpolateFluidProperties_onewaycoupled(particle, interpolator, scheme, geometry, params)
Interpolates fluid properties from neighboring lattice sites to determine the fluid density and velocity at the location of the particle
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: particle
Particle to interpolate fluid properties to
type(mus_particle_interpolator_type), intent(in) :: interpolator
Interpolation object containing interpolation bounds and weigth function info
type(mus_scheme_type), intent(inout) :: scheme
Scheme
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Called by
Call graph
mus_particles_dps_interpolatefluidproperties_onewaycoupled calls calcvelocityandpressuregradient_onewaycoupled_old, interpolatefluidprops_onewaycoupled_old, tem_abort
calcvelocityandpressuregradient_onewaycoupled_old calls tem_abort, auxfield_varpos, cxdir, cxdirinv, grabvalueatcoord, cross_product, getindexofcoordintotal, getneighborcoord
interpolatefluidprops_onewaycoupled_old calls tem_abort, auxfield_varpos, grabvalueatcoord, getbaryofcoord, getneighborcoord
grabvalueatcoord calls grabvalueatcoord_onewaycoupled, grabvalueatcoord_twowaycoupled
getindexofcoordintotal calls tem_IdOfCoord, tem_PosOfId
grabvalueatcoord_onewaycoupled calls tem_IdOfCoord, tem_PosOfId
grabvalueatcoord_twowaycoupled calls tem_IdOfCoord, tem_PosOfId
mus_particles_applyhydrodynamicforces_dps_onewaycoupled calls mus_particles_dps_interpolatefluidproperties_onewaycoupled