mus_set_nSources – Musubi
mus_set_nSources Subroutine
92 statements
Source File
public subroutine mus_set_nSources(me, nDims, QQ, layout)
Arguments
Type Intent Optional Attributes Name
type(mus_interpolation_type), intent(inout) :: me
integer, intent(in) :: nDims
integer, intent(in) :: QQ
character(len=*), intent(in) :: layout
Calls
Called by
Call graph
mus_set_nsources calls init, init_cxdirweightedavg, tem_abort
init_cxdirweightedavg calls tem_abort
mus_init_scheme calls mus_set_nsources
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve