mus_calcAuxFieldAndExchange – Musubi
mus_calcAuxFieldAndExchange Subroutine
36 statements
Source File
public subroutine mus_calcAuxFieldAndExchange(auxField, calcAuxField, state, pdfData, nFields, field, globSrc, stencil, varSys, derVarPos, phyConvFac, general, iLevel, minLevel, schemeHeader, quantities)
This routine compute auxField variable from pre-collision pdf and exchange halos
Arguments
Type Intent Optional Attributes Name
type(mus_auxFieldVar_type), intent(inout) :: auxField
auxilary field array
procedure(mus_proc_calcAuxField), intent(in), pointer :: calcAuxField
function pointer to calculate auxField
real(kind=rk), intent(in) :: state(:)
state array
type(pdf_data_type), intent(in) :: pdfData
contains neigh array and nElems on current level
integer, intent(in) :: nFields
Number of fields
type(mus_field_type), intent(inout) :: field(nFields)
contains sources of all fields
type(mus_source_type), intent(inout) :: globSrc
global source
type(tem_stencilHeader_type), intent(in) :: stencil
stencil header
type(tem_varSys_type), intent(in) :: varSys
variable system
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
contains auxField position of all fields in varSys
type(mus_convertFac_type), intent(in) :: phyConvFac
physics conversion factors for this level
type(tem_general_type), intent(in) :: general
contains commPattern, MPI communicator and simControl
integer, intent(in) :: iLevel
current level
integer, intent(in) :: minLevel
minlevel
type(mus_scheme_header_type), intent(in) :: schemeHeader
scheme header
type(mus_scheme_derived_quantities_type), intent(in) :: quantities
Class that contains pointers to the proper derived quantities functions
Calls
Called by
Call graph
mus_calcauxfieldandexchange calls exchange_real
do_benchmark calls mus_calcauxfieldandexchange
do_fast_singlelevel calls mus_calcauxfieldandexchange
do_recursive_multilevel calls mus_calcauxfieldandexchange
mus_reset_aux calls mus_calcauxfieldandexchange
mus_perform_dynloadbal calls mus_reset_aux
mus_solve calls mus_perform_dynloadbal
musubi calls mus_solve