mus_load_newLayout – Musubi
mus_load_newLayout Subroutine
74 statements
Source File
public subroutine mus_load_newLayout(me, parent_handle, conf)
load a new stencil definition from the lua file
a label
the stencil (predefined or new)
for a new defined stencil (weights, inverse directions, prevailing directions)
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_layout_type) :: me
integer, intent(in), optional :: parent_handle
type(flu_State) :: conf
Calls
Called by
Call graph
mus_load_newlayout calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, cxdirinv, tem_abort, tem_identify_inverseDirections, tem_identify_prevailDirections, tem_loadStencil, tem_stencil_zeroPos
mus_load_scheme calls mus_load_newlayout
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load