mus_init_flow – Musubi
mus_init_flow Subroutine
25 statements
Source File
public subroutine mus_init_flow(scheme, tree, general, physics, scaling, levelPointer)
Initialize flow field depends on read restart or initial condition
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
Scheme type
type(treelmesh_type), intent(in) :: tree
tree
type(tem_general_type), intent(inout) :: general
type(mus_physics_type), intent(in) :: physics
character(len=*), intent(in) :: scaling
integer, intent(in) :: levelPointer(:)
global info type
Calls
Called by
Call graph
mus_init_flow calls fillhelperelementscoarsetofine, fillhelperelementsfinetocoarse, init_advrel, mus_init_byic, mus_initauxfield, mus_readrestart, mus_testinterpolation
mus_initialize calls mus_init_flow
musubi calls mus_initialize