mus_build_varSys – Musubi
mus_build_varSys Subroutine
146 statements
Source File
public subroutine mus_build_varSys(varSys, solverData, schemeHeader, stencil, nFields, derVarPos, luaVar, field, globSrc, poss_srcVar, st_funList)
Build global variable system for Musubi
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
global variable system
type(mus_varSys_solverData_type), intent(in), target :: solverData
Contains pointer to solver data types
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
type(tem_stencilHeader_type), intent(in) :: stencil
Compute stencil header
integer, intent(in) :: nFields
number of fields
type(mus_derVarPos_type), intent(out), allocatable :: derVarPos(:)
store position of each variable for each field and mixture size: nFields+1
type(tem_variable_type), intent(in), allocatable :: luaVar(:)
additional variable defined in the lua file. Function pointer for this variables depends on its varType.
type(mus_field_type), intent(inout) :: field(:)
Field contains sources and boundary infos
type(mus_source_type), intent(inout) :: globSrc
global source
type(tem_possible_variable_type), intent(in) :: poss_srcVar
possible source variables
type(tem_st_fun_linkedList_type), intent(out) :: st_funList
contains spacetime functions of all variables
Calls
Called by
Call graph
mus_build_varsys calls init, mus_append_auxfield, mus_append_bcvar, mus_append_dervar_fluid, mus_append_dervar_fluidincomp, mus_append_dervar_isotherm_aceq, mus_append_dervar_lbmps, mus_append_dervar_msgas, mus_append_dervar_msliquid, mus_append_dervar_physics, mus_append_dervar_poisson, mus_append_materialvar, mus_append_sourcevar, mus_append_turbvar, mus_store_bcvarpos, mus_store_dervarpos, tem_abort, tem_varSys_append_luaVar, tem_varSys_append_meshInfoVar, tem_varSys_dump
mus_append_auxfield calls tem_abort, append, mus_get_new_solver_ptr, tem_varSys_append_auxFieldVar
mus_append_bcvar calls init, append, mus_get_new_solver_ptr, tem_varSys_append_derVar
mus_append_dervar_fluid calls append, mus_get_new_solver_ptr, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
mus_append_dervar_fluidincomp calls append, mus_get_new_solver_ptr, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
mus_append_dervar_isotherm_aceq calls append, mus_get_new_solver_ptr, tem_varSys_append_derVar
mus_append_dervar_lbmps calls tem_abort, append, mus_get_new_solver_ptr, tem_varSys_append_derVar
mus_append_dervar_msgas calls append, mus_append_dermixvar_ms, mus_get_new_solver_ptr, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
mus_append_dervar_msliquid calls append, mus_append_derliquidmixvar, mus_append_dermixvar_ms, mus_get_new_solver_ptr, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
mus_append_dervar_physics calls tem_abort, positionofval, mus_get_new_solver_ptr, tem_varSys_append_derVar
mus_append_dervar_poisson calls append, mus_get_new_solver_ptr, tem_varSys_append_derVar
mus_append_materialvar calls tem_abort, append, mus_get_new_solver_ptr, tem_varSys_append_derVar
mus_append_sourcevar calls tem_abort, tem_varSys_dump, input_varpos, positionofval, mus_get_new_solver_ptr, tem_varSys_append_derVar, val
mus_append_turbvar calls tem_abort, append, mus_get_new_solver_ptr, tem_varSys_append_derVar
mus_store_bcvarpos calls tem_abort, positionofval, val
mus_store_dervarpos calls positionofval
mus_append_derliquidmixvar calls append, positionofval, mus_get_new_solver_ptr, tem_varSys_append_derVar
mus_append_dermixvar_ms calls tem_abort, positionofval, mus_get_new_solver_ptr, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
mus_init_scheme calls mus_build_varsys
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve