mus_init_MSGas – Musubi
mus_init_MSGas Subroutine
77 statements
Source File
private subroutine mus_init_MSGas(me, tree, fac, state, neigh, field, nElems, nSize, iLevel)
Initialize the flow from calculated quantitites like density, velocity etc. for multispecies lbm
dens_1 | dens_2 | .. | dens_nElems | | ux_1 | uy_1 | uz_1 | .. .. | ux_nelems| uy_nelems| uz_nelems|
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: me
type(treelmesh_type), intent(in) :: tree
type(mus_convertFac_type), intent(in) :: fac
real(kind=rk), intent(inout) :: state(:)
PDF
integer, intent(in) :: neigh(:)
Connectivity array
type(mus_field_type), intent(inout) :: field(:)
integer, intent(in) :: nElems
integer, intent(in) :: nSize
integer, intent(in) :: iLevel
Calls
Called by
Call graph
mus_init_msgas calls ini_state, tem_BaryOfId, tem_spatial_for, total
mus_init_byic calls mus_init_msgas
mus_init_flow calls mus_init_byic
mus_initialize calls mus_init_flow
musubi calls mus_initialize