mus_load_IBM – Musubi
mus_load_IBM Subroutine
52 statements
Source File
public subroutine mus_load_IBM(me, conf, rank)
Load the IBM information from the lua config file.
The information has to be provided in the \a immersed_boundary \a table as a single table
  immersed_boundary = {
                        logging = {
                          level = 20,   -- level of logging
                          filename = 'IBMdeb/test', -- file to write the log
                          root_only = false -- should only root write msgs?
                        },
                        label = 'surface',
                        kind = 'IBM',
                        stlfiles = {'stl/surface1.stl', 'stl/surface2.stl'},
                        dump_stl = {
                          time_control = {
                            min = {iter=0},
                            max = {iter=tmax},
                            interval = {iter=interval}
                          },
                          outprefix = 'test_',
                        },
                        inaIters = 4,
                        movement = mov_pulse,
                        velocity = vel_pulse
  }
or as multiple tables
  immersed_boundary = {
                        logging = {
                          level = 20,   -- level of logging
                          filename = 'IBMdeb/test', -- file to write the log
                          root_only = false -- should only root write msgs?
                        },
                       {
                        label = 'surface',
                        kind = 'IBM',
                        stlfiles = {'stl/surface1.stl', 'stl/surface2.stl'},
                        dump_stl = {
                          time_control = {
                            min = {iter=0},
                            max = {iter=tmax},
                            interval = {iter=interval}
                          },
                          outprefix = 'test_',
                        },
                        inaIters = 4,
                        movement = mov_pulse,
                        velocity = vel_pulse
                       }
  }
in the mus_field table.
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_globType), intent(inout) :: me
datatype to store the surface information
type(flu_State), intent(in) :: conf
handle of the lua config file
integer, intent(in) :: rank
the current rank
Calls
Called by
Call graph
mus_load_ibm calls aot_table_close, aot_table_length, aot_table_open, mus_load_ibm_single, tem_connect_toNull, tem_horizontalSpacer, tem_logging_load
mus_load_ibm_single calls aot_get_val, tem_abort, tem_load_spacetime, tem_load_surfData
mus_load_geom calls mus_load_ibm
mus_load_config calls mus_load_geom
musubi calls mus_load_config