mus_hvs_load_solverData – Musubi
mus_hvs_load_solverData Subroutine
11 statements
Source File
private subroutine mus_hvs_load_solverData(scheme, solverData, geometry, params)
This routines load solver data from config file except tracking
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), target :: scheme
scheme type
type(mus_varSys_solverData_type), target :: solverData
contains pointer to scheme, physics types
type(mus_geom_type), intent(inout), target :: geometry
Treelmesh data
type(mus_param_type), intent(inout), target :: params
Global parameters
Calls
Called by
Call graph
mus_hvs_load_solverdata calls conf, mus_load_param, mus_load_physics, mus_load_scheme, tem_horizontalSpacer
mus_load_param calls tem_horizontalSpacer, aot_get_val
mus_load_physics calls tem_horizontalSpacer, aot_get_val, aot_table_close, aot_table_open, mus_physics_dump2outunit, mus_set_convfac, mus_set_scalefac, set_values_by_levels, tem_ElemSizeLevel, tem_abort, tem_toStr
mus_load_scheme calls tem_horizontalSpacer, mus_append_readvarasstatevar, mus_append_statevar, mus_create_poss_srcvar, mus_create_poss_transvar, mus_define_layout, mus_init_varsys_solverdata, mus_load_fieldbaseinfos, mus_load_fields, mus_load_interpolate, mus_load_newlayout, mus_load_scheme_header, mus_load_source_var, mus_load_transport_var, tem_abort, tem_load_tracking, tem_varSys_init, tem_variable_load
mus_hvs_config_load calls mus_hvs_load_solverdata
mus_harvesting calls mus_hvs_config_load