mus_add_internal_source_var – Musubi
mus_add_internal_source_var Subroutine
28 statements
Source File
public subroutine mus_add_internal_source_var(me, possVars, varSys, schemeHeader)
Routine load musubi source terms for given key. key is glob_source or source
Arguments
Type Intent Optional Attributes Name
type(mus_source_type), intent(out) :: me
Source variable type to initialize
type(tem_possible_variable_type), intent(in) :: possVars
possible source variables
type(tem_varSys_type), intent(inout) :: varSys
Global variable system
type(mus_scheme_header_type), intent(in) :: schemeHeader
Identifier of the scheme
Calls
Called by
Call graph
mus_add_internal_source_var calls append, init, positionofval, tem_varSys_append_stfun, truncate, val
mus_load_field_single calls mus_add_internal_source_var
mus_load_fields calls mus_load_field_single
mus_load_scheme calls mus_load_fields
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme