mus_hvs_init_aux – Musubi
mus_hvs_init_aux Subroutine
40 statements
Source File
public subroutine mus_hvs_init_aux(scheme, geometry, params)
Init auxiliary features such as interpolation boundaries, restart and the tracker
initialize fluid type which contains relaxation parameter and function pointers to get mrt paramter and nonEqScaling factor for interpolation
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout), target :: scheme
container for the scheme
type(mus_geom_type), intent(inout) :: geometry
geometry infomation
type(mus_param_type), intent(inout) :: params
global parameters
Calls
Called by
Call graph
mus_hvs_init_aux calls debug_dependencies, dump_intplists, mus_init_bndforce, mus_init_graddata, mus_init_interpolate, check_streaming_layout, mus_init_fluid, mus_init_tracker, mus_time_homogenize, tem_abort, tem_create_subTree_of_st_funList, tem_horizontalSpacer, tem_init_restart
mus_init_fluid calls init, mus_assign_mrt_ptr, mus_assign_nnwtnvisc_ptr, mus_assign_turbvisc_ptr, mus_fluid_dump, mus_init_relaxparam, mus_init_turbulencedata, mus_update_relaxparamfromviscstfun
mus_init_tracker calls config, instance, mus_timecontrol_homogenize, tem_init_tracker, tem_init_tracker_subTree
mus_time_homogenize calls tem_time_dump
mus_harvesting calls mus_hvs_init_aux