mus_load_field_single – Musubi
mus_load_field_single Subroutine
41 statements
Source File
private subroutine mus_load_field_single(me, varSys, nFields, bc_prop, conf, parent, minLevel, maxLevel, poss_srcVar, physics, schemeHeader, scaling, layout, isMusHvs)
load a single field table In includes: load field property load source variables load boundary defination load immersed boundary method load initial condition defination and its property
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(inout) :: me
field type
type(tem_varSys_type), intent(inout) :: varSys
Global variable system required to append annoymous source and boundary variables
integer, intent(in) :: nFields
number of fields defined in lua file
type(tem_BC_prop_type), intent(in) :: bc_prop
boundary data from mesh
type(flu_State), intent(inout) :: conf
flu state
integer, intent(in), optional :: parent
parent handle if scheme table is defined
integer, intent(in) :: minLevel
global pdf info
integer, intent(in) :: maxLevel
global pdf info
type(tem_possible_variable_type), intent(in) :: poss_srcVar
possible source variables
type(mus_physics_type), intent(in) :: physics
physics type to convert physics to lattice unit or vice versa
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
character(len=labelLen), intent(in) :: scaling
scaling type
type(mus_scheme_layout_type), intent(in) :: layout
fluid stencil info
logical, intent(in), optional :: isMusHvs
Logic to not to load tracking and variable table if this routine is called from mus_hvs_config_load. Default is False
Calls
Called by
Call graph
mus_load_field_single calls mus_add_internal_source_var, mus_load_bc, mus_load_field_prop, mus_load_source_var, mus_set_ic_states, tem_abort, tem_horizontalSpacer, tem_load_ic
mus_add_internal_source_var calls append, init, positionofval, tem_varSys_append_stfun, truncate, val
mus_load_bc calls tem_abort, tem_horizontalSpacer, aot_get_val, aot_table_close, aot_table_open, init, mus_load_turb_wallfunc, tem_load_bc_header, tem_load_bc_state, truncate
mus_load_field_prop calls tem_abort, mus_load_fluid, mus_load_poisson, mus_load_species
mus_load_source_var calls tem_abort, aot_get_val, aot_table_open, init, load_turbchanforce, mus_load_absorblayer, tem_variable_loadMapping, truncate, val
mus_set_ic_states calls tem_abort
mus_load_fields calls mus_load_field_single
mus_load_scheme calls mus_load_fields
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config