mus_load_particle_boundaries – Musubi
mus_load_particle_boundaries Subroutine
73 statements
Source File
public subroutine mus_load_particle_boundaries(conf, p_thandle, bndData)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
configuration
integer, intent(in) :: p_thandle
Handle to parent table
type(mus_particle_boundarydata_type), intent(inout) :: bndData
Particle boundary data
Calls
Called by
Call graph
mus_load_particle_boundaries calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, tem_abort
mus_load_particles calls mus_load_particle_boundaries
mus_initialize calls mus_load_particles
musubi calls mus_initialize