mus_generic_varFromPDF_fromIndex – Musubi
mus_generic_varFromPDF_fromIndex Subroutine
36 statements
Source File
public subroutine mus_generic_varFromPDF_fromIndex(fun, varSys, time, iLevel, idx, idxLen, nVals, fnCalcPtr, res)
Routine to get the actual value for a given array of indices for musubi derive variables The indices belong to the grwarray of points storing levelwise in Pointdata%pntLvl(iLevel). Hence this routines takes the indeices as input, can refer to the pointData and evaluate the variable and returns the values
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables,
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
integer, intent(in) :: iLevel
Level on which values are requested
integer, intent(in) :: idx(:)
Index of points in the growing array and variable val array to return. Size: n
integer, intent(in), optional :: idxLen(:)
With idx as start index in contiguous memory, idxLength defines length of each contiguous memory Size: dependes on number of first index for contiguous array, but the sum of all idxLen is equal to nVals
integer, intent(in) :: nVals
Number of values to obtain for this variable (vectorized access).
procedure(mus_derive_fromPDF), pointer :: fnCalcPtr
Function pointer to perform specific operation.
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Dimension: n requested entries x nComponents of this variable Access: (iElem-1)*fun%nComponents + iComp
Calls
Called by
Call graph
mus_generic_varfrompdf_fromindex calls get_valofindex, tem_abort, val
derequilisothermaceq_fromindex calls mus_generic_varfrompdf_fromindex
derivedensity_fromindex calls mus_generic_varfrompdf_fromindex
deriveelectricfield_fromindex calls mus_generic_varfrompdf_fromindex
deriveequil_fromindex calls mus_generic_varfrompdf_fromindex
derivemoledensity_fromindex calls mus_generic_varfrompdf_fromindex
derivenonequil_fromindex calls mus_generic_varfrompdf_fromindex
derivestrainrate_fromindex calls mus_generic_varfrompdf_fromindex