mus_finalize – Musubi
mus_finalize Subroutine
71 statements
Source File
public subroutine mus_finalize(scheme, params, particleGroup, tree, levelPointer, nBCs, globIBM)
Do final check on check on total density, Close auxiliary stuff such as restart and the tracker, finalize treelm, dump timing and finialize mpi with fin_env
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme type
type(mus_param_type), intent(inout) :: params
Global parameters
type(mus_particle_group_type), intent(inout) :: particleGroup
Particle data
type(treelmesh_type), intent(inout) :: tree
geometry infomation
integer, intent(in) :: levelPointer(:)
global information
integer, intent(in) :: nBCs
Number of BC
type(mus_IBM_globType), intent(inout) :: globIBM
global IBM datatype incl. array of IBM datatypes
Calls
Called by
Call graph
mus_finalize calls close_config, conf, check_density, check_potential, dump_level_timing, mus_bc_timing, mus_dumpweights, mus_finalize_particlegroup, mus_finishibm, mus_getweights, mus_perf_measure, mus_writerestart, tem_comm_destroy, tem_global_mesh_free, tem_restart_finalize, tem_status_dump, tem_status_run_terminate, tem_time_dump, tem_tracking_finalize
musubi calls mus_finalize