mus_dumpData – Musubi
mus_dumpData Subroutine
23 statements
Source File
public subroutine mus_dumpData(scheme, tree, levelPointer, general, restart_triggered)
This routine dumps tracking and restart when timeControl is active
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme type
type(treelmesh_type), intent(in) :: tree
Treelmesh data
integer, intent(in) :: levelPointer(:)
Level Pointer
type(tem_general_type), intent(inout) :: general
Global parameters
logical, intent(inout) :: restart_triggered
Calls
Called by
Call graph
mus_dumpdata calls mus_writerestart, tem_timeControl_check, tem_time_dump, tem_tracker
mus_writerestart calls mus_pdf_serialize, tem_restart_closeWrite, tem_restart_openWrite, tem_restart_writeData, tem_startTimer, tem_stopTimer
check_flow_status calls mus_dumpdata