mus_init_bndForce – Musubi
mus_init_bndForce Subroutine
35 statements
Source File
public subroutine mus_init_bndForce(bndForce, bndMoment, bc_prop, schemeHeader, bc)
This routine initialize bndForce array assign function pointer to calculate bndForce
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(out), allocatable :: bndForce(:,:)
Bnd force to allocate
real(kind=rk), intent(out), allocatable :: bndMoment(:,:)
Bnd moment to allocate
type(tem_BC_prop_type), intent(in) :: bc_prop
Boundary property
type(mus_scheme_header_type), intent(in) :: schemeHeader
scheme header info
type(boundary_type), intent(inout) :: bc(:)
global array boundary type
Called by
Call graph
mus_hvs_init_aux calls mus_init_bndforce
mus_init_aux calls mus_init_bndforce
mus_reset_aux calls mus_init_bndforce
mus_initialize calls mus_init_aux
mus_perform_dynloadbal calls mus_reset_aux
mus_harvesting calls mus_hvs_init_aux
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve