mus_IBM_getSurfVel – Musubi
mus_IBM_getSurfVel Subroutine
35 statements
Source File
private subroutine mus_IBM_getSurfVel(me, IBMData, levelDesc, general, iLevel)
This routine calculates the surface velocity for all local xk.
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_type), intent(in) :: me
datatype to store the surface information
type(mus_IBM_tmpData_type), intent(inout) :: IBMData
tmp IBMData type to be filled
type(tem_levelDesc_type), intent(in) :: levelDesc
level descriptor incl. ghost and fluid elements
type(tem_general_type), intent(in) :: general
general info
integer :: iLevel
the current level
Calls
Called by
Call graph
mus_ibm_getsurfvel calls backpointcoords, nelems, pointcoords, ptrs, tem_spacetime_for
mus_buildbuffibm calls mus_ibm_getsurfvel
do_fast_singlelevel calls mus_buildbuffibm