mus_particles_transferMomentumToFluid_DPS – Musubi
mus_particles_transferMomentumToFluid_DPS Subroutine
14 statements
Source File
public subroutine mus_particles_transferMomentumToFluid_DPS(particleGroup, scheme, geometry, params)
Arguments
Type Intent Optional Attributes Name
class(mus_particle_group_type), intent(inout) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Call graph
mus_particles_transfermomentumtofluid_dps calls exchangehydroforces_dps
exchangehydroforces_dps calls mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, sortposofval_particle_dps, tem_abort, tem_startTimer, tem_stopTimer