mus_particles_initForceContributionMPItype – Musubi
mus_particles_initForceContributionMPItype Subroutine
17 statements
Source File
public subroutine mus_particles_initForceContributionMPItype()
Arguments
None
Calls
Called by
Call graph
mus_particles_initforcecontributionmpitype calls mpi_aint_diff, mpi_get_address, mpi_type_commit, mpi_type_create_struct
mus_particles_initialize_communication calls mus_particles_initforcecontributionmpitype
mus_particles_initialize calls mus_particles_initialize_communication
mus_initialize calls mus_particles_initialize
musubi calls mus_initialize