mus_init_advRel_fluid_trt – Musubi
mus_init_advRel_fluid_trt Subroutine
18 statements
Source File
private subroutine mus_init_advRel_fluid_trt(variant, layout, compute)
This routine assigns compute routine for trt relaxation
Supported variants are: * standard - Optimized routines for specifc layouts.
Arguments
Type Intent Optional Attributes Name
character(len=labelLen), intent(in) :: variant
character(len=labelLen), intent(in) :: layout
procedure(kernel), intent(out), pointer :: compute
Calls
Called by
Call graph
mus_init_advrel_fluid_trt calls tem_abort
mus_init_advrel_fluid calls mus_init_advrel_fluid_trt
init_advrel calls mus_init_advrel_fluid
mus_init_flow calls init_advrel
mus_initialize calls mus_init_flow