mus_intp_getSrcElemPosinTree – Musubi
mus_intp_getSrcElemPosinTree Subroutine
90 statements
Source File
public subroutine mus_intp_getSrcElemPosinTree(srcElemPos, weights, nSrcElems, point, stencil, tree, levelPointer, levelDesc)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: srcElemPos(:)
position of source element in the level independent list
real(kind=rk), intent(out) :: weights(:)
weights for interpolation
integer, intent(out) :: nSrcElems
number of source elements found
real(kind=rk), intent(in) :: point(3)
target point
type(tem_stencilHeader_type), intent(in) :: stencil
stencil definition
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: levelPointer(:)
Pointer from treeIDlist entry to level-wise fluid part of total list
type(tem_levelDesc_type), intent(in) :: levelDesc(tree%global%minLevel:)
level description of all levels
Calls
Called by
Call graph
mus_intp_getsrcelemposintree calls nghelems, tem_BaryOfId, tem_CoordOfReal, tem_FirstIdAtLevel, tem_IdOfCoord, tem_LevelOf, tem_ParentOf, tem_PosOfId, tem_eligibleChildren
mus_auxfieldvar_forpoint calls mus_intp_getsrcelemposintree
mus_createsrcelemintreeforgetpoint calls mus_intp_getsrcelemposintree
mus_dervar_intponpoint calls mus_intp_getsrcelemposintree
mus_statevar_forpoint calls mus_intp_getsrcelemposintree
mus_derivevar_forpoint calls mus_dervar_intponpoint
mus_reductiontransient_forpoint calls mus_dervar_intponpoint