mus_particles_initialize_communication – Musubi
mus_particles_initialize_communication Subroutine
66 statements
Source File
public subroutine mus_particles_initialize_communication(particleGroup, scheme, geometry, params)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), target :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Called by
Call graph
mus_particles_initialize_communication calls init, find_particle_comm_procs4, init_mus_particles_comm_type, mus_particles_comm_init_buffers, mus_particles_initforcecontributionmpitype, mus_particles_initparticleinfompitype, mus_particles_initparticlestatempitype, mus_particles_initpositionupdatempitype, mus_particles_initwallposmpitype
find_particle_comm_procs4 calls append, findpartitionoftreeid, getbaryofcoord, getcartesianstencilindices, getneighborcoord, getsearchboxlimits, pruneparticlecommprocs, property, tem_CoordOfId, tem_FirstIdAtLevel, tem_IdOfCoord, total
mus_particles_comm_init_buffers calls mus_particles_comm_init_idbuffer, mus_particles_comm_init_particlebuffer, mus_particles_comm_init_posbuffer, mus_particles_comm_init_statebuffer, mus_particles_comm_init_vectorbuffer, mus_particles_comm_init_wallbuffer
mus_particles_initforcecontributionmpitype calls mpi_aint_diff, mpi_get_address, mpi_type_commit, mpi_type_create_struct
mus_particles_initparticleinfompitype calls mpi_aint_diff, mpi_get_address, mpi_type_commit, mpi_type_create_struct
mus_particles_initparticlestatempitype calls mpi_aint_diff, mpi_get_address, mpi_type_commit, mpi_type_create_struct
mus_particles_initpositionupdatempitype calls mpi_aint_diff, mpi_get_address, mpi_type_commit, mpi_type_create_struct
mus_particles_initwallposmpitype calls mpi_aint_diff, mpi_get_address, mpi_type_commit, mpi_type_create_struct
mus_particles_initialize calls mus_particles_initialize_communication
mus_initialize calls mus_particles_initialize
musubi calls mus_initialize