mus_set_bouzidi – Musubi
mus_set_bouzidi Subroutine
24 statements
Source File
public subroutine mus_set_bouzidi(iLevel, QQ, QQN, nScalars, globBC, cxDirInv, varPos, bouzidi)
Set necessary data for Wall Bouzidi BC bouzidi should be allocated beforehand
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iLevel
integer, intent(in) :: QQ
integer, intent(in) :: QQN
integer, intent(in) :: nScalars
type(glob_boundary_type), intent(in) :: globBC
integer, intent(in) :: cxDirInv(QQ)
integer, intent(in) :: varPos(:)
type(bc_wall_bouzidi_type), intent(inout) :: bouzidi
cIn, cOut, cNgh should have size of nLinks
Calls
Called by
Call graph
mus_set_bouzidi calls set_bouzidi_coeff, val
init_boundary_single calls mus_set_bouzidi
mus_init_boundary calls init_boundary_single
mus_initialize calls mus_init_boundary
mus_reset_aux calls mus_init_boundary
mus_perform_dynloadbal calls mus_reset_aux
musubi calls mus_initialize