mus_append_derVar_MSGas – Musubi
mus_append_derVar_MSGas Subroutine
109 statements
Source File
public subroutine mus_append_derVar_MSGas(varSys, solverData, stencil, nFields, fldLabel, derVarName)
subroutine to add derive variables for multispecies-liquid (schemekind = 'multispecies_gas') to the varsys.
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
global variable system
type(mus_varSys_solverData_type), intent(in), target :: solverData
Contains pointer to solver data types
type(tem_stencilHeader_type), intent(in) :: stencil
compute stencil defintion
integer, intent(in) :: nFields
number of fields
character(len=*), intent(in) :: fldLabel(:)
array of field label prefix. Size=nFields
type(grw_labelarray_type), intent(inout) :: derVarName
array of derive physical variables
Calls
Called by
Call graph
mus_append_dervar_msgas calls append, mus_append_dermixvar_ms, mus_get_new_solver_ptr, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
mus_append_dermixvar_ms calls mus_get_new_solver_ptr, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar, positionofval, tem_abort
mus_build_varsys calls mus_append_dervar_msgas
mus_init_scheme calls mus_build_varsys
mus_initialize calls mus_init_scheme
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize