mus_nNwtn_load – Musubi
mus_nNwtn_load Subroutine
32 statements
Source File
public subroutine mus_nNwtn_load(me, conf, parent)
Read in the nonNewtonian table from Lua file and dump parameters to logUnit Specificly, this routine calls each model parameter loader.
Arguments
Type Intent Optional Attributes Name
type(mus_nNwtn_type), intent(out) :: me
nonNewtonian type
type(flu_State), intent(inout) :: conf
lua state
integer, intent(in), optional :: parent
parent handle
Calls
Called by
Call graph
mus_nnwtn_load calls aot_get_val, aot_table_close, aot_table_open, mus_nnwtn_cs_load, mus_nnwtn_cy_load, mus_nnwtn_pl_load, tem_abort, upper_to_lower
mus_nnwtn_cs_load calls aot_get_val
mus_nnwtn_cy_load calls aot_get_val
mus_nnwtn_pl_load calls aot_get_val
mus_load_fluid calls mus_nnwtn_load
mus_load_field_prop calls mus_load_fluid
mus_load_field_single calls mus_load_field_prop
mus_load_fields calls mus_load_field_single