mus_load_field_prop – Musubi
mus_load_field_prop Subroutine
27 statements
Source File
public subroutine mus_load_field_prop(me, conf, parent, minLevel, schemeHeader, nFields, physics, cs_lattice)
load fluid properties like fluid and species table from lua file based on the scheme kind
Arguments
Type Intent Optional Attributes Name
type(mus_field_prop_type), intent(out) :: me
field property type
type(flu_State), intent(inout) :: conf
flu state
integer, intent(in), optional :: parent
parent lua handle
integer, intent(in) :: minLevel
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
integer, intent(in) :: nFields
number of fields defined in lua file
type(mus_physics_type), intent(in) :: physics
physics type to convert physics to lattice unit or vice versa
real(kind=rk), intent(in) :: cs_lattice
lattice speed of sound calculated for defined stencil layout
Calls
Called by
Call graph
mus_load_field_prop calls mus_load_fluid, mus_load_poisson, mus_load_species, tem_abort
mus_load_fluid calls tem_abort, aot_get_val, aot_table_close, aot_table_open, mus_load_turbulence, mus_nnwtn_load, tem_horizontalSpacer, tem_load_spacetime
mus_load_poisson calls tem_abort, aot_get_val, aot_table_close, aot_table_open, mus_load_poissonboltzmann, tem_toStr
mus_load_species calls tem_abort, aot_get_val, aot_table_close, aot_table_length, aot_table_open, tem_horizontalSpacer
mus_load_poissonboltzmann calls tem_abort, aot_get_val, aot_table_close, aot_table_length, aot_table_open
mus_load_turbulence calls tem_abort, aot_get_val, aot_table_close, aot_table_open, tem_horizontalSpacer, upper_to_lower
mus_nnwtn_load calls tem_abort, aot_get_val, aot_table_close, aot_table_open, mus_nnwtn_cs_load, mus_nnwtn_cy_load, mus_nnwtn_pl_load, upper_to_lower
mus_nnwtn_cs_load calls aot_get_val
mus_nnwtn_cy_load calls aot_get_val
mus_nnwtn_pl_load calls aot_get_val
mus_load_field_single calls mus_load_field_prop
mus_load_fields calls mus_load_field_single
mus_load_scheme calls mus_load_fields
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme