mus_fluid_cleanup – Musubi
mus_fluid_cleanup Subroutine
20 statements
Source File
public subroutine mus_fluid_cleanup(me)
This routines act as a destructor for fluid type
Arguments
Type Intent Optional Attributes Name
type(mus_fluid_type), intent(inout) :: me
single fluid type
Called by
Call graph
mus_field_cleanup calls mus_fluid_cleanup
mus_scheme_cleanup calls mus_field_cleanup
mus_perform_dynloadbal calls mus_scheme_cleanup
mus_solve calls mus_perform_dynloadbal