mus_build_BCStencils – Musubi
mus_build_BCStencils Subroutine
66 statements
Source File
private subroutine mus_build_BCStencils(globBC, bc, prevailDir, prefix, minLevel, maxLevel, stencil_labels, grwStencil)
subroutine to find neighbours of element with individual (for each element) stencil definitions. Unique stencil label for boundary stencils are created with boundary label and stencil%cxDir therefore each stencil is limited to one boundary type
Arguments
Type Intent Optional Attributes Name
type(glob_boundary_type), intent(in) :: globBC
boundaries for the elements with bnd property set
type(boundary_type), intent(inout) :: bc
field boundary with boundary neighbor info
real(kind=rk), intent(in) :: prevailDir(:,:)
scheme layout
character(len=*), intent(in) :: prefix
field label
integer, intent(in) :: minLevel
min and max level
integer, intent(in) :: maxLevel
min and max level
type(dyn_labelarray_type), intent(inout) :: stencil_labels
dynamic array of stencil labels
type(grw_stencilheaderarray_type), intent(inout) :: grwStencil
growing array of stencils
Calls
Called by
Call graph
mus_build_bcstencils calls append, init, tem_stencil_getLabelForcxDir, val
mus_construct calls mus_build_bcstencils
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve