mus_IBM_prepareSendRecv_X – Musubi
mus_IBM_prepareSendRecv_X Subroutine
22 statements
Source File
private subroutine mus_IBM_prepareSendRecv_X(IBMData)
This subroutine prepares the send and receive buffers for the eulerian elements by copying information from the send and receive buffers for the lagrangian elements.
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_tmpData_type), intent(inout) :: IBMData
tmp IBMData type to be filled
Calls
Called by
Call graph
mus_ibm_preparesendrecv_x calls buf_int, elempos, init, nelemsproc, proc
mus_buildbuffibm calls mus_ibm_preparesendrecv_x
do_fast_singlelevel calls mus_buildbuffibm