mus_load_nernstPlanck – Musubi
mus_load_nernstPlanck Subroutine
37 statements
Source File
public subroutine mus_load_nernstPlanck(me, conf, parent, physics)
load input to solve nernst_planck equation
Arguments
Type Intent Optional Attributes Name
type(mus_nernstPlanck_type), intent(out) :: me
nernst_planck type
type(flu_State) :: conf
flu state
integer, intent(in), optional :: parent
parent handle
type(mus_physics_type), intent(in) :: physics
physics type to convert physics to lattice unit or vice versa
Calls
Called by
Call graph
mus_load_nernstplanck calls aot_get_val, aot_table_close, aot_table_open, tem_abort, tem_toStr
mus_load_fields calls mus_load_nernstplanck
mus_load_scheme calls mus_load_fields
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config