mus_particles_applyHydrodynamicForces_DPS_onewaycoupled – Musubi
mus_particles_applyHydrodynamicForces_DPS_onewaycoupled Subroutine
12 statements
Source File
public subroutine mus_particles_applyHydrodynamicForces_DPS_onewaycoupled(particleGroup, scheme, geometry, params)
Arguments
Type Intent Optional Attributes Name
class(mus_particle_group_type), intent(inout) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Call graph
mus_particles_applyhydrodynamicforces_dps_onewaycoupled calls mus_particles_dps_interpolatefluidproperties_onewaycoupled
mus_particles_dps_interpolatefluidproperties_onewaycoupled calls calcvelocityandpressuregradient_onewaycoupled_old, interpolatefluidprops_onewaycoupled_old, tem_abort
calcvelocityandpressuregradient_onewaycoupled_old calls tem_abort, auxfield_varpos, cxdir, cxdirinv, grabvalueatcoord, cross_product, getindexofcoordintotal, getneighborcoord
interpolatefluidprops_onewaycoupled_old calls tem_abort, auxfield_varpos, grabvalueatcoord, getbaryofcoord, getneighborcoord
grabvalueatcoord calls grabvalueatcoord_onewaycoupled, grabvalueatcoord_twowaycoupled
getindexofcoordintotal calls tem_IdOfCoord, tem_PosOfId