mus_load_absorbLayer – Musubi
mus_load_absorbLayer Subroutine
72 statements
Source File
public subroutine mus_load_absorbLayer(me, conf, key, parent, loadPres, loadVel)
This routine load additional information for absorblayer
Arguments
Type Intent Optional Attributes Name
type(absorbLayer_config_type), intent(out) :: me
Absorb layer
type(flu_State) :: conf
flu state
character(len=*), intent(in) :: key
Table name to load target states
integer, intent(in) :: parent
parent source handle
logical, intent(in) :: loadPres
Load pressure if true else set to dynamic
logical, intent(in) :: loadVel
Load velocity if true else set to dynamic
Calls
Called by
Call graph
mus_load_absorblayer calls aot_get_val, aot_table_close, aot_table_open, tem_abort, upper_to_lower
mus_load_source_var calls mus_load_absorblayer
mus_load_field_single calls mus_load_source_var
mus_load_scheme calls mus_load_source_var, mus_load_fields
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_load_fields calls mus_load_field_single
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config