mus_IBM_fillRecvPos_X – Musubi
mus_IBM_fillRecvPos_X Subroutine
27 statements
Source File
private subroutine mus_IBM_fillRecvPos_X(IBMData, globRecv, treeIDPos, startPos, added, match)
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_tmpData_type), intent(inout) :: IBMData
IBM temporary datatype incl. map2glob and communicator for send and recv
type(tem_communication_type), intent(in) :: globRecv
global recv communicator
integer, intent(in) :: treeIDPos
element position in the level desc total list
integer, intent(in) :: startPos
starting position of what to recv as elemPos
logical, intent(inout) :: added(:)
is this element added to the communication
logical :: match
Calls
Called by
Call graph
mus_ibm_fillrecvpos_x calls append, val
mus_fillneigh_surfdata calls mus_ibm_fillrecvpos_x
mus_buildbuffibm calls mus_fillneigh_surfdata
do_fast_singlelevel calls mus_buildbuffibm