mus_init_scheme – Musubi
mus_init_scheme Subroutine
22 statements
Source File
public subroutine mus_init_scheme(me, tree, solverData)
Initialize single scheme stencil and variable system
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: me
single scheme to initialize
type(treelmesh_type), intent(in) :: tree
global treelm mesh
type(mus_varSys_solverData_type), intent(in), target :: solverData
contains pointer to scheme, physics types
Calls
Called by
Call graph
mus_init_scheme calls append, mus_assign_calcauxfield_ptr, mus_assign_gradcalculation_ptr, mus_assign_derived_functions_ptr, mus_build_varsys, mus_init_moments, mus_set_nsources, tem_horizontalSpacer, tem_stencil_map_toTreelmDef, tem_treelmDef_map_toStencil
mus_perform_dynloadbal calls mus_init_scheme
mus_harvesting calls mus_init_scheme