mus_load_poisson – Musubi
mus_load_poisson Subroutine
71 statements
Source File
public subroutine mus_load_poisson(me, conf, parent, minLevel, cs_lattice, physics, schemeKind)
load input to solve poisson equation
Arguments
Type Intent Optional Attributes Name
type(mus_poisson_type), intent(out) :: me
poisson type
type(flu_State) :: conf
flu state
integer, intent(in), optional :: parent
parent handle
integer, intent(in) :: minLevel
minlevel
real(kind=rk), intent(in) :: cs_lattice
lattice speed of sound calculated for defined stencil layout required to compute omega from potential diffusivity
type(mus_physics_type), intent(in) :: physics
physics type to convert physics to lattice unit or vice versa
character(len=*), intent(in) :: schemeKind
scheme kind
Calls
Called by
Call graph
mus_load_poisson calls aot_get_val, aot_table_close, aot_table_open, mus_load_poissonboltzmann, tem_abort, tem_toStr
mus_load_poissonboltzmann calls aot_get_val, aot_table_close, aot_table_open, tem_abort, aot_table_length
mus_load_field_prop calls mus_load_poisson
mus_load_field_single calls mus_load_field_prop
mus_load_fields calls mus_load_field_single
mus_load_scheme calls mus_load_fields