mus_append_readVarAsStateVar – Musubi
mus_append_readVarAsStateVar Subroutine
46 statements
Source File
public subroutine mus_append_readVarAsStateVar(varSys, readVarIsPdf, read_varSys, stateVarMap, solverData, nFields, fldLabel)
Append variable read from restart file as state variables
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
global variable system
logical, intent(out) :: readVarIsPdf
Is true if read_varSys has pdf variable
type(tem_varSys_type), intent(in) :: read_varSys
Variable system loaded from restart header file
type(tem_varMap_type), intent(out) :: stateVarMap
Store position of state variable in global varSys
type(mus_varSys_solverData_type), intent(in), target :: solverData
Contains pointer to solver data types
integer, intent(in) :: nFields
number of fields
character(len=*), intent(in) :: fldLabel(:)
array of field label prefix. Size=nFields
Calls
Called by
Call graph
mus_append_readvarasstatevar calls append, init, mus_get_new_solver_ptr, check_varsys_forpdfvar, tem_abort, tem_varSys_append_stateVar, truncate, val
check_varsys_forpdfvar calls val
mus_load_scheme calls mus_append_readvarasstatevar
mus_hvs_load_solverdata calls mus_load_scheme
mus_load_config calls mus_load_scheme
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load