mus_intp_error – Musubi
mus_intp_error Subroutine
204 statements
Source File
private subroutine mus_intp_error(pdf, level, tree, general, fac, scheme, layout, intp, ind, varSys, derVarPos, eType)
Determine the numerical error of the interpolated quantities to the given initial conditions
Arguments
Type Intent Optional Attributes Name
type(pdf_data_type), intent(in) :: pdf
global fluid parameters
integer, intent(in) :: level
level
type(treelmesh_type), intent(in) :: tree
treelm tree
type(tem_general_type), intent(in) :: general
type(mus_convertFac_type), intent(in) :: fac
type(mus_scheme_type), intent(in) :: scheme
the current scheme
type(mus_scheme_layout_type), intent(in) :: layout
the layout used
type(mus_interpolation_type), intent(in) :: intp
interpolation method info
type(grw_intarray_type), intent(in) :: ind
indirection list
type(tem_varSys_type), intent(in) :: varSys
global variable system
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
required variable system which maps to global varsys
integer, intent(in) :: eType
element type, eT_ghostFromFiner, eT_ghostFromCoarser
Calls
Called by
Call graph
mus_intp_error calls ini_state, mpi_reduce, newunit, offset, mus_open_config, set_momentindices, tem_BaryOfId, tem_spatial_for, total
mus_open_config calls open_config_chunk, mus_create_funcstr, tem_open_distconf_array
mus_testinterpolation calls mus_intp_error
mus_init_flow calls mus_testinterpolation
mus_initialize calls mus_init_flow
musubi calls mus_initialize