mus_buildBuffIBM – Musubi
mus_buildBuffIBM Subroutine
41 statements
Source File
public subroutine mus_buildBuffIBM(me, commPattern, globTree, params, layout, levelDesc, iLevel)
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_type), intent(inout) :: me(:)
datatype to store the surface information
type(tem_commPattern_type), intent(inout) :: commPattern
communication pattern
type(treelmesh_type) :: globTree
global tree information
type(mus_param_type) :: params
global parameters
type(mus_scheme_layout_type) :: layout
scheme layout of the current scheme incl. array of stencils
type(tem_levelDesc_type), intent(inout) :: levelDesc
the level descriptor incl. ghost and halo elements as well as the communicator information on the level iLevel
integer, intent(in) :: iLevel
the current level
Calls
Called by
Call graph
mus_buildbuffibm calls destroy, nelems, parentids, mus_fillneigh_surfdata, mus_ibm_buildsendrecv_xk, mus_ibm_getsurfvel, mus_ibm_preparesendrecv_x, mus_init_ibmdata, tem_startTimer, tem_stopTimer, tem_time_advance, tem_time_sim_stamp, tem_update_surfPos
mus_fillneigh_surfdata calls nelems, tem_startTimer, tem_stopTimer, append, buf_int, buf_long, elempos, nelemsproc, proc, mus_ibm_fillrecvpos_x, mus_ibm_fillsendpos_x, tem_CoordOfId, tem_IdOfCoord, tem_treeIDinTotal, val
mus_ibm_buildsendrecv_xk calls nelems, tem_startTimer, tem_stopTimer, append, buf_int, elempos, nelemsproc, proc, mus_ibm_commnewpos, ptrs, val
mus_ibm_getsurfvel calls nelems, backpointcoords, pointcoords, ptrs, tem_spacetime_for
mus_ibm_preparesendrecv_x calls buf_int, elempos, init, nelemsproc, proc
mus_init_ibmdata calls init
do_fast_singlelevel calls mus_buildbuffibm