mus_IBM_commNewPos – Musubi
mus_IBM_commNewPos Subroutine
184 statements
Source File
private subroutine mus_IBM_commNewPos(IBMData, levelDesc, commPattern, globTree, surfData, iLevel, comm)
This subroutine communicates all elements which just moved from the fluids to the halo elements.
Arguments
Type Intent Optional Attributes Name
type(mus_IBM_tmpData_type), intent(inout) :: IBMData
tmp IBMData type to be filled
type(tem_levelDesc_type), intent(inout) :: levelDesc
the level descriptor incl. the global send and receive buffers
type(tem_commPattern_type), intent(inout) :: commPattern
communication pattern to be used
type(treelmesh_type), intent(inout) :: globTree
global tree information
type(tem_surfData_type), intent(inout) :: surfData
the surface data incl. the coordinates for the Xk
integer, intent(in) :: iLevel
current level
integer, intent(in) :: comm
process description to use
Calls
Called by
Call graph
mus_ibm_commnewpos calls append, buf_int, buf_real, elempos, empty, init, nelems, nelemsproc, proc, ptrs, tem_init_surfData, val
mus_ibm_buildsendrecv_xk calls mus_ibm_commnewpos
mus_buildbuffibm calls mus_ibm_buildsendrecv_xk
do_fast_singlelevel calls mus_buildbuffibm