normcdf – Musubi
normcdf Subroutine
10 statements
Source File
public subroutine normcdf(x, mu, sigma, cum, ccum)
This function evaluates the normal distribution function:
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: x
Input: argument x to compute P(X <= x)
real(kind=rk), intent(in) :: mu
Input: mean of the gaussian
real(kind=rk), intent(in) :: sigma
Input: standard deviation (sqrt of variance)
real(kind=rk), intent(out) :: cum
Output: P(X <= x)
real(kind=rk), intent(out) :: ccum
Calls
Called by
Call graph
normcdf calls cumnor
cumnor calls r8_swap
init_particle_blob_prob_circle calls normcdf
init_particle_blob_prob_square calls normcdf
init_particle_blob_prob calls init_particle_blob_prob_circle, init_particle_blob_prob_square
fill_blob_positions_gauss calls init_particle_blob_prob
fill_blob_positions_gauss_prism calls init_particle_blob_prob
init_particle_creator_from_blob calls fill_blob_positions_gauss
init_particle_creator_from_blob_prism calls fill_blob_positions_gauss_prism