openLogFile – Musubi
openLogFile Subroutine
20 statements
Source File
public subroutine openLogFile(filename, plogUnit, isNewFile)
openLogFile opens a file with name fileName and returns the unit attached to it. It checks whether the file exists and if not
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: filename
integer, intent(out) :: plogUnit
logical, intent(out), optional :: isNewFile
Calls
Called by
Call graph
openlogfile calls newunit
dumpdata calls openlogfile
mus_log_fluid_momentum calls openlogfile
mus_particles_log_total_momentum calls openlogfile
mus_particles_runtests calls openlogfile