perform_checks – Musubi
perform_checks Subroutine
29 statements
Source File
public subroutine perform_checks(scheme, minLevel, maxLevel, general, mus_aborts, initCheck)
Perform run-time checks if interval is active
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(tem_general_type), intent(inout) :: general
type(mus_abortCriteria_type), intent(in) :: mus_aborts
logical, intent(in) :: initCheck
True for initial check before main time toop
Calls
Called by
Call graph
perform_checks calls check_density, check_potential, check_velocityfluid, check_velocityms, mus_check_omegakine, tem_abort, tem_timeControl_globalTriggered
check_density calls auxfield_varpos, bits, mpi_reduce, tem_isNaN, tem_time_dump, total
check_potential calls bits, mpi_reduce, tem_isNaN, tem_time_dump
check_velocityfluid calls auxfield_varpos, bits, mpi_reduce, tem_isNaN
check_velocityms calls auxfield_varpos, bits, mpi_reduce, tem_isNaN
mus_check_omegakine calls tem_abort, bits, mpi_reduce
check_flow_status calls perform_checks
mus_solve calls check_flow_status
musubi calls mus_solve