printTotalElemList – Musubi
printTotalElemList Subroutine
49 statements
Source File
public subroutine printTotalElemList(scheme, geometry, lev, proc, plogUnit)
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
type(mus_geom_type), intent(in) :: geometry
integer, intent(in) :: lev
integer, intent(in) :: proc
integer, intent(in) :: plogUnit
Calls
Call graph
printtotalelemlist calls boundary_id, property, total