printParticleGroup – Musubi
printParticleGroup Subroutine
46 statements
Source File
public subroutine printParticleGroup(particleGroup, logUnit)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(in) :: particleGroup
integer, intent(in) :: logUnit
Called by
Call graph
dem_exchangeforces calls printparticlegroup
dem_exchangewallpositions calls printparticlegroup
exchangeforces calls printparticlegroup
exchangeparticlestates calls printparticlegroup
exchangepositions calls printparticlegroup
exchangevelocities calls printparticlegroup
test_append_da_particle calls printparticlegroup
dem_storewallpositions_mem calls dem_exchangewallpositions
demsubcycles_mem calls dem_exchangeforces, exchangepositions, exchangevelocities, dem_storewallpositions_mem
mus_particles_move calls demsubcycles_mem