proximity – Musubi
proximity Subroutine
49 statements
Source File
public subroutine proximity(scheme, geometry, iGInc, pot_nElems, pot_lp, pot_lp_tree)
A subroutine which checks the proximity condition and generates a new treeID list of potential target elements which can then be checked against various thresholds as defined in the lua configuration file.
Proximity condition means that an element can be solidified only if it has at least one wall as a neighboring element. In biological clotting models it ensures that no isolated clot is produced in the fluid domain. Furthermore the noSolidification property is checked for every element. It is used to define spaces where solidification is not allowed.
Acc the proximity condition, as soon as its found that any of the neighbors of current element is solid, that element is stored in the new list of potential elements. Loop is terminated for this element and check is performed for other element.
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme information
type(mus_geom_type), intent(in) :: geometry
scheme information
integer, intent(in) :: iGInc
Geomtry icrement
integer, intent(inout) :: pot_nElems
number of potential elements found
integer, intent(inout) :: pot_lp(:)
level pointer of potential elements
integer, intent(inout) :: pot_lp_tree(:)
position of potential elements in the treeID list
Calls
Called by
Call graph
proximity calls elempropertybits, tem_LevelOf, treeid
mus_geomincr calls proximity
check_flow_status calls mus_geomincr
mus_solve calls check_flow_status
musubi calls mus_solve