pruneParticleCommProcs – Musubi
pruneParticleCommProcs Subroutine
47 statements
Source File
public subroutine pruneParticleCommProcs(procs, prunedProcs, nParts, myRank)
pruneParticleCommProcs takes the initial list of processes we think we need to communicate particle data with (determined using only local data) and checks whether those processes also think they need to communicate with us. The prunedProcs array contains the final list of processes for which we know we will send and also receive messages.
Arguments
Type Intent Optional Attributes Name
type(dyn_intarray_type) :: procs
Initial list of particle comm procs to be pruned
type(dyn_intarray_type) :: prunedProcs
Final (pruned) list of procs
integer, intent(in) :: nParts
number of processes
integer, intent(in) :: myRank
This procs rank
Calls
Called by
Call graph
pruneparticlecommprocs calls append, mpi_irecv, mpi_isend, mpi_waitall
find_particle_comm_procs4 calls pruneparticlecommprocs
mus_particles_initialize_communication calls find_particle_comm_procs4
mus_particles_initialize calls mus_particles_initialize_communication
mus_initialize calls mus_particles_initialize