recalculate_auxField_DPS – Musubi
recalculate_auxField_DPS Subroutine
31 statements
Source File
public subroutine recalculate_auxField_DPS(particle, interpolator, scheme, geometry, params)
Remove the momentum increments added during subcycles to prevent double-adding the momentum of particles to the fluid.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: particle
Particle to interpolate fluid properties to
type(mus_particle_interpolator_type), intent(in) :: interpolator
interpolator object containing stencil and weight function info
type(mus_scheme_type), intent(inout) :: scheme
Scheme
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
Calls
Called by
Call graph
recalculate_auxfield_dps calls neigh, add_momentum_increment_to_auxfield, followneighpath, getbaryofcoord, getposofcoord
add_momentum_increment_to_auxfield calls auxfield_varpos
getposofcoord calls tem_IdOfCoord, tem_PosOfId
demsubcycles_dps calls recalculate_auxfield_dps
mus_particles_move_dps calls demsubcycles_dps