remove_particle_from_da_particle_mem – Musubi
remove_particle_from_da_particle_mem Subroutine
17 statements
Source File
public subroutine remove_particle_from_da_particle_mem(particles, ielem)
Arguments
Type Intent Optional Attributes Name
type(dyn_particle_mem_array_type), intent(inout) :: particles
particle group to operate on
integer, intent(in) :: ielem
current index of element to remove
Calls
Called by
Call graph
remove_particle_from_da_particle_mem calls swap_da_particle_mem
check_and_create_new_particles_mem calls remove_particle_from_da_particle_mem, create_particles_mem
createnewparticle_mem calls remove_particle_from_da_particle_mem
mus_particles_applyhydrodynamicforces_mem calls remove_particle_from_da_particle_mem
mus_particles_mapping_mem calls remove_particle_from_da_particle_mem
test_append_da_particle calls remove_particle_from_da_particle_mem
check_particles_mem calls check_and_create_new_particles_mem
create_particles_mem calls createnewparticle_mem