remove_particle_from_da_particle_dps – Musubi
remove_particle_from_da_particle_dps Subroutine
17 statements
Source File
public subroutine remove_particle_from_da_particle_dps(particles, ielem)
Arguments
Type Intent Optional Attributes Name
type(dyn_particle_dps_array_type), intent(inout) :: particles
particle group to operate on
integer, intent(in) :: ielem
current index of element to remove
Calls
Called by
Call graph
remove_particle_from_da_particle_dps calls swap_da_particle_dps
createnewparticle_dps calls remove_particle_from_da_particle_dps
mapparticlestolattice_dps calls remove_particle_from_da_particle_dps
mus_particles_mapping_dps calls remove_particle_from_da_particle_dps
create_particles_dps calls createnewparticle_dps
demsubcycles_dps calls mapparticlestolattice_dps
demsubcycles_dps_onewaycoupled calls mapparticlestolattice_dps
check_and_create_new_particles_dps calls create_particles_dps
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled
check_particles_dps calls check_and_create_new_particles_dps