remove_solid_in_bc – Musubi
remove_solid_in_bc Subroutine
41 statements
Source File
public subroutine remove_solid_in_bc(minLevel, maxLevel, nBCs, nFields, levelPointer, levelDesc, globBC, fields)
First check count number of valid elements (non-solid) in each BC. Then rearrange BC elements list so it contains only valid elements. Update fields%bc%elemLvl%stencilPos fields%bc%elemLvl%posInNghElems accordingly.
\todo: do this for both SBB and LIBB?
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
integer, intent(in) :: nBCs
integer, intent(in) :: nFields
integer, intent(in) :: levelPointer(:)
Level pointer
type(tem_levelDesc_type), intent(in) :: levelDesc(minLevel:maxLevel)
Level Descriptor
type(glob_boundary_type) :: globBC(nBCs)
type(mus_field_type) :: fields(nFields)
Calls
Call graph
remove_solid_in_bc calls bc_kind, check_solid_in_bc, nelems, posinnghelems, rearrange_bc_elems, stencilpos