remove_elem_grw_real2darray – Musubi
remove_elem_grw_real2darray Subroutine
9 statements
Source File
public subroutine remove_elem_grw_real2darray(me, i, array_width)
Arguments
Type Intent Optional Attributes Name
type(grw_real2darray_type), intent(inout) :: me
integer, intent(in) :: i
integer, intent(in) :: array_width
Calls
Called by
Call graph
remove_elem_grw_real2darray calls swap_grw_real2darray
pick_random_position calls remove_elem_grw_real2darray
fill_blob_positions_gauss calls pick_random_position
fill_blob_positions_gauss_prism calls pick_random_position
init_particle_creator_from_blob calls fill_blob_positions_gauss
init_particle_creator_from_blob_prism calls fill_blob_positions_gauss_prism
mus_load_particles calls init_particle_creator_from_blob, init_particle_creator_from_blob_prism