secondMom_3D – Musubi
secondMom_3D Function
12 statements
Source File
public pure function secondMom_3D(cxcx, f, QQ) result(m)
Calculate second moments of some quantity where Q is number of discrete velocity.\n The output is 1 dimentional array which has 6 componenents.\n Specifically, This function is used by shear stress and strain rate. 1=xx, 2=yy, 3=zz, 4=xy, 5=yz, 6=xz in 2D: 1=xx, 2=yy, 3=xy
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: cxcx(6,QQ)
real(kind=rk), intent(in) :: f(QQ)
quantity to which second moment is applied
integer, intent(in) :: QQ
Return Value real(kind=rk), (6)
Called by
Call graph
bgk_dualrelaxationtime_rr_d3q19 calls secondmom_3d
bgk_dualrelaxationtime_rr_d3q27 calls secondmom_3d
bgk_hybridrecursiveregularized_d3q19 calls secondmom_3d
bgk_hybridrecursiveregularized_d3q27 calls secondmom_3d
bgk_hybridrecursiveregularizedcorr_d3q19 calls secondmom_3d
bgk_hybridrecursiveregularizedcorr_d3q27 calls secondmom_3d
bgk_recursiveregularized_d3q19 calls secondmom_3d
bgk_recursiveregularized_d3q27 calls secondmom_3d
bgk_regularized_d3q19 calls secondmom_3d
bgk_regularized_d3q27 calls secondmom_3d
deriveshearstress calls secondmom_3d
mus_derivestrainrate calls secondmom_3d
mus_turbvisc_smagorinsky_fromprecolpdf_incomp_3d calls secondmom_3d