secondMom_2D – Musubi
secondMom_2D Function
9 statements
Source File
public pure function secondMom_2D(cxcx, f, QQ) result(m)
Calculate second moments of some quantity where Q is number of discrete velocity.\n The output is 1 dimentional array which has 6 componenents.\n Specifically, This function is used by shear stress and strain rate. 1=xx, 2=yy, 3=xy
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: cxcx(6,QQ)
real(kind=rk), intent(in) :: f(QQ)
quantity to which second moment is applied
integer, intent(in) :: QQ
Return Value real(kind=rk), (3)
Called by
Call graph
bgk_dualrelaxationtime_rr_d2q9 calls secondmom_2d
bgk_hybridrecursiveregularized_d2q9 calls secondmom_2d
bgk_hybridrecursiveregularizedcorr_d2q9 calls secondmom_2d
bgk_recursiveregularized_d2q9 calls secondmom_2d
bgk_regularized_d2q9 calls secondmom_2d
mus_turbvisc_smagorinsky_fromprecolpdf_incomp_2d calls secondmom_2d