set_values_by_levels – Musubi
set_values_by_levels Function
9 statements
Source File
public pure function set_values_by_levels(valMinLevel, minLevel, maxLevel, scaleFac) result(values)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: valMinLevel
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
integer, intent(in) :: scaleFac
Return Value real(kind=rk), (minLevel:maxLevel)
Called by
Call graph
mus_init_latticeunit calls set_values_by_levels
mus_load_physics calls set_values_by_levels
mus_hvs_load_solverdata calls mus_load_physics
mus_load_config calls mus_init_latticeunit, mus_load_physics
mus_hvs_config_load calls mus_hvs_load_solverdata
musubi calls mus_load_config
mus_harvesting calls mus_hvs_config_load