set_bouzidi_coeff – Musubi
set_bouzidi_coeff Subroutine
15 statements
Source File
private subroutine set_bouzidi_coeff(qVal, cIn, cOut, cNgh, cVel)
Set the coefficients of bouzidi linear interpolation boundary condition.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: qVal
real(kind=rk), intent(out) :: cIn
real(kind=rk), intent(out) :: cOut
real(kind=rk), intent(out) :: cNgh
real(kind=rk), intent(out) :: cVel
Called by
Call graph
mus_set_bouzidi calls set_bouzidi_coeff
mus_set_inletbfl calls set_bouzidi_coeff
init_boundary_single calls mus_set_bouzidi, mus_set_inletbfl
mus_init_boundary calls init_boundary_single
mus_initialize calls mus_init_boundary
mus_reset_aux calls mus_init_boundary