set_halo_commLinks – Musubi
set_halo_commLinks Subroutine
92 statements
Source File
private subroutine set_halo_commLinks(scheme, minLevel, maxLevel, nBCs, comm_reduced, haloRequired)
Select the halo elements which require all links
Determine which pdfs to communicate
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(in) :: scheme
scheme information including fluid, boundary and flow information
integer, intent(in) :: minLevel
Global information
integer, intent(in) :: maxLevel
Global information
integer, intent(in) :: nBCs
Global information
logical, intent(in) :: comm_reduced
reduced communication
type(logical_array_type), intent(inout), allocatable :: haloRequired(:)
Calls
Called by
Call graph
set_halo_commlinks calls cxdirinv, depfromcoarser, depfromfiner, nelemsproc, nghelems, offset
mus_construct calls set_halo_commlinks
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve