set_boundary – Musubi
set_boundary Subroutine
31 statements
Source File
public subroutine set_boundary(field, pdf, levelDesc, tree, iLevel, nBCs, params, layout, varSys, derVarPos, globBC, mixture, physics, state)
Call the functions associated with each boundary condition
Loop over each field and Run over all the boundary conditions for current iLevel and call the function pointer. The function pointer was before assigned in init_boundary This routine is being called from the do_recursive_multiLevel "main control routine" before the compute (advection_relaxation) kernel call
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(inout) :: field(:)
fluid parameters and properties
type(pdf_data_type), intent(inout) :: pdf
contains global state vector
type(tem_levelDesc_type), intent(in) :: levelDesc
global type contains iLevel descriptor
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: iLevel
the iLevel on which this boundary was invoked
integer, intent(in) :: nBCs
number of BC
type(mus_param_type), intent(in) :: params
global parameters
type(mus_scheme_layout_type), intent(in) :: layout
stencil layout information
type(tem_varSys_type), intent(in) :: varSys
scheme variable system
type(mus_derVarPos_type), intent(in) :: derVarPos(:)
position of derived quantities in varsys
type(glob_boundary_type), intent(in) :: globBC(:)
scheme global boundary type
type(mus_mixture_type), intent(in) :: mixture
mixture info
type(mus_physics_type), intent(in) :: physics
scheme global boundary type
real(kind=rk), intent(inout) :: state(:,:)
state arrays fo current iLevel both now and next
Calls
Called by
Call graph
set_boundary calls fill_bcbuffer, fill_neighbuffer, tem_startTimer, tem_stopTimer, val
fill_bcbuffer calls state_varpos
fill_neighbuffer calls tem_startTimer, tem_stopTimer, val, state_varpos
do_benchmark calls set_boundary
do_fast_singlelevel calls set_boundary
do_recursive_multilevel calls set_boundary