setFieldBCNeigh – Musubi
setFieldBCNeigh Subroutine
60 statements
Source File
private subroutine setFieldBCNeigh(fieldBC, globBC, levelDesc, minLevel, maxLevel)
This routine sets field BC neigh array with position of neighbor element in the inward normal direction of boundary in the levelwise list. if valid 1st neighbor does not exist return current element position. if valid higher order neighbor does not exist return last valid neighbor
Arguments
Type Intent Optional Attributes Name
type(boundary_type), intent(inout) :: fieldBC
field boundary with boundary neighbor info
type(glob_boundary_type), intent(in) :: globBC
boundaries for the elements with bnd property set
type(tem_levelDesc_type), intent(in) :: levelDesc(minLevel:maxLevel)
Level descriptor
integer, intent(in) :: minLevel
Level range
integer, intent(in) :: maxLevel
Calls
Called by
Call graph
setfieldbcneigh calls nghelems, tem_CoordOfId, tem_FirstIdAtLevel, tem_IdOfCoord, tem_treeIDinTotal, val
finalize_bclist calls setfieldbcneigh
mus_construct calls finalize_bclist
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize