setParameters_multispecies – Musubi
setParameters_multispecies Subroutine
74 statements
Source File
public subroutine setParameters_multispecies(field, nFields, mixture, header, layout, iLevel, tNow)
Set parameters for multispecies
Relaxation parameter for each level kine_viscosity = dtc^2(1/omega - 0.5) => omega = dt / (viscosity/c^2 + dt/2) omega for each level is stored at fluid%omLvl
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(inout) :: field(nFields)
integer, intent(in) :: nFields
type(mus_mixture_type), intent(inout) :: mixture
type(mus_scheme_header_type), intent(in) :: header
type(mus_scheme_layout_type), intent(in) :: layout
integer, intent(in) :: iLevel
type(tem_time_type), intent(in) :: tNow
solver general info
Calls
Called by
Call graph
setparameters_multispecies calls invert_matrix, tem_temporal_for
mus_update_relaxparams calls setparameters_multispecies
do_benchmark calls mus_update_relaxparams
do_fast_singlelevel calls mus_update_relaxparams
do_recursive_multilevel calls mus_update_relaxparams