setToEquilibrium – Musubi
setToEquilibrium Subroutine
33 statements
Source File
public subroutine setToEquilibrium(elemList, N, lev, scheme, rho, vel)
setToEquilibrium sets elements to equilibrium distribution
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: elemList(:)
list containing positions in state vector of elements to set to equilibrium distribution
integer, intent(in) :: N
number of values in elemList
integer, intent(in) :: lev
level
type(mus_scheme_type), intent(inout) :: scheme
scheme for access to levelDesc and pdf
real(kind=rk), intent(in) :: rho(:)
density value for computing fEq
real(kind=rk), intent(in) :: vel(:,:)
velocity vector
Calls
Called by
Call graph
settoequilibrium calls state_varpos, val
destroyparticle_mem calls settoequilibrium
maptolattice calls settoequilibrium
mus_particles_applyhydrodynamicforces_mem calls destroyparticle_mem
mus_particles_mapping_mem calls maptolattice