sortposofval_particle_mem – Musubi
sortposofval_particle_mem Function
44 statements
Source File
public function sortposofval_particle_mem(me, pid, nextifnotfound, lower, upper) result(pos)
return the sorted position of a value in the given dynamic array
if the value was not found, - return 0 if nextifnotfound = .false. - return position at the end if nextifnotfound = .true.
binary search on sorted list
Arguments
Type Intent Optional Attributes Name
type(dyn_particle_mem_array_type), intent(in) :: me
integer, intent(in) :: pid
logical, intent(in), optional :: nextifnotfound
flag to indicate, if the next entry in the list should be returned, if the searched one is not found.
integer, intent(in), optional :: lower
integer, intent(in), optional :: upper
Return Value integer
Called by
Call graph
append_da_particle_mem calls sortposofval_particle_mem
dem_exchangeforces calls sortposofval_particle_mem
dem_exchangewallpositions calls sortposofval_particle_mem
exchangeforces calls sortposofval_particle_mem
exchangeparticlestates calls sortposofval_particle_mem
exchangeparticlestoremove calls sortposofval_particle_mem
exchangepositions calls sortposofval_particle_mem
exchangevelocities calls sortposofval_particle_mem
createnewparticle_mem calls append_da_particle_mem
dem_storewallpositions_mem calls dem_exchangewallpositions
demsubcycles_mem calls dem_exchangeforces, exchangepositions, exchangevelocities, dem_storewallpositions_mem
exchangenewparticles_mem calls append_da_particle_mem
load_particle_mem_data calls append_da_particle_mem
test_append_da_particle calls append_da_particle_mem
check_and_create_new_particles_mem calls exchangenewparticles_mem, create_particles_mem
create_particles_mem calls createnewparticle_mem
mus_particles_move calls demsubcycles_mem
check_particles_mem calls check_and_create_new_particles_mem