sortposofval_particle_dps – Musubi
sortposofval_particle_dps Function
44 statements
Source File
public function sortposofval_particle_dps(me, pid, nextifnotfound, lower, upper) result(pos)
return the sorted position of a value in the given dynamic array
if the value was not found, - return 0 if nextifnotfound = .false. - return position at the end if nextifnotfound = .true.
binary search on sorted list
Arguments
Type Intent Optional Attributes Name
type(dyn_particle_dps_array_type), intent(in) :: me
integer, intent(in) :: pid
logical, intent(in), optional :: nextifnotfound
flag to indicate, if the next entry in the list should be returned, if the searched one is not found.
integer, intent(in), optional :: lower
integer, intent(in), optional :: upper
Return Value integer
Called by
Call graph
append_da_particle_dps calls sortposofval_particle_dps
dem_exchangeforces_dps calls sortposofval_particle_dps
dem_exchangewallpositions_dps calls sortposofval_particle_dps
exchangehydroforces_dps calls sortposofval_particle_dps
exchangemominc_dps calls sortposofval_particle_dps
exchangeparticlestoremove_dps calls sortposofval_particle_dps
exchangepositions_dps calls sortposofval_particle_dps
exchangevelocities_dps calls sortposofval_particle_dps
createnewparticle_dps calls append_da_particle_dps
demsubcycles_dps calls exchangemominc_dps, exchangepositions_dps, exchangevelocities_dps, mapparticlestolattice_dps, updateparticleforces
demsubcycles_dps_onewaycoupled calls exchangepositions_dps, exchangevelocities_dps, mapparticlestolattice_dps, updateparticleforces
exchangenewparticles_dps calls append_da_particle_dps
load_particle_dps_data calls append_da_particle_dps
mapparticlestolattice_dps calls exchangeparticlestoremove_dps, exchangenewparticles_dps
mus_particles_mapping_dps calls exchangeparticlestoremove_dps, exchangenewparticles_dps
mus_particles_transfermomentumtofluid_dps calls exchangehydroforces_dps
test_compute_particle_momentum calls append_da_particle_dps
test_dem_fillneighborlist calls append_da_particle_dps
updateparticleforces calls dem_exchangeforces_dps, exchangehydroforces_dps
check_and_create_new_particles_dps calls exchangenewparticles_dps, create_particles_dps
create_particles_dps calls createnewparticle_dps
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled
check_particles_dps calls check_and_create_new_particles_dps