test_interpolation_delta_DPS_d3q19 – Musubi
test_interpolation_delta_DPS_d3q19 Subroutine
49 statements
Source File
public subroutine test_interpolation_delta_DPS_d3q19(xp, interpolator, scheme, geometry, params, plogunit)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: xp(3)
Query point (x,y,z) to interpolate fluid properties to
type(mus_particle_interpolator_type) :: interpolator
Object containing interpolation information
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to fluid data
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
integer, intent(in) :: plogunit
Unit to write output to
Calls
Call graph
test_interpolation_delta_dps_d3q19 calls auxfield_varpos, interpolatefluidprops, tem_BaryOfId, tem_CoordOfReal, total
interpolatefluidprops calls auxfield_varpos, neigh, followneighpath, getbaryofcoord, getposofcoord
getposofcoord calls tem_IdOfCoord, tem_PosOfId