test_generateElemListLine – Musubi
test_generateElemListLine Subroutine
25 statements
Source File
public subroutine test_generateElemListLine(scheme, geometry, params)
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to fluid data
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params
Calls
Call graph
test_generateelemlistline calls generateelemlistline, getbaryofcoord, tem_CoordOfId, tem_FirstIdAtLevel, total
generateelemlistline calls append, empty, tem_CoordOfReal, tem_IdOfCoord, tem_PosOfId