testParticleConnectivity – Musubi
testParticleConnectivity Subroutine
35 statements
Source File
public subroutine testParticleConnectivity(scheme, particle, lev)
Routine for manually checking connectivity of particle elements, to be removed later
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type) :: scheme
type(mus_particle_MEM_type) :: particle
integer :: lev
Calls
Call graph
testparticleconnectivity calls cxdirinv, nghelems, state_varpos, val