test_compute_particle_momentum – Musubi
test_compute_particle_momentum Subroutine
42 statements
Source File
public subroutine test_compute_particle_momentum(lev, params, comm, myRank, nProcs, plogunit, flag)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: lev
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
integer, intent(in) :: comm
MPI communicator
integer, intent(in) :: myRank
My MPI rank
integer, intent(in) :: nProcs
Number of MPI processes in communicator
integer, intent(in) :: plogunit
Unit to log test result to
logical, intent(out) :: flag
flag gets set to TRUE if test succeeded, FALSE if it failed
Calls
Call graph
test_compute_particle_momentum calls append_da_particle_dps, compute_particle_momentum, init_da_particle_dps
append_da_particle_dps calls expand_da_particle_dps, sortposofval_particle_dps
compute_particle_momentum calls mpi_reduce