test_append_da_particle – Musubi
test_append_da_particle Subroutine
23 statements
Source File
public subroutine test_append_da_particle(particleGroup)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
Calls
Call graph
test_append_da_particle calls append_da_particle_mem, init_da_particle_mem, printparticlegroup, printpidlist, remove_particle_from_da_particle_mem
append_da_particle_mem calls expand_da_particle_mem, sortposofval_particle_mem
remove_particle_from_da_particle_mem calls swap_da_particle_mem