translate_positions – Musubi
translate_positions Subroutine
8 statements
Source File
public subroutine translate_positions(positions, translation_vec)
Arguments
Type Intent Optional Attributes Name
type(grw_real2darray_type), intent(inout) :: positions
Output: coordinates of the particles
real(kind=rk), intent(in) :: translation_vec(3)
Vector with which to translate positions by
Called by
Call graph
fill_blob_positions_gauss calls translate_positions
fill_blob_positions_gauss_prism calls translate_positions
init_particle_creator_from_blob calls translate_positions, fill_blob_positions_gauss
init_particle_creator_from_blob_prism calls fill_blob_positions_gauss_prism
mus_load_particles calls init_particle_creator_from_blob, init_particle_creator_from_blob_prism
mus_initialize calls mus_load_particles
musubi calls mus_initialize