transferMomentumToFluid_DPS – Musubi
transferMomentumToFluid_DPS Subroutine
35 statements
Source File
public subroutine transferMomentumToFluid_DPS(particle, interpolator, scheme, geometry, params, Ftot)
Routine that applies forces from particles to the fluid for unresolved DPS particles based on the VANS equations
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: particle
Particle to interpolate fluid properties to
type(mus_particle_interpolator_type), intent(in) :: interpolator
interpolator object containing stencil and weight function info
type(mus_scheme_type), intent(inout) :: scheme
Scheme
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
real(kind=rk), intent(out) :: Ftot(3)
Output, total force exerted on fluid by particle
Calls
Call graph
transfermomentumtofluid_dps calls neigh, applysrc_toelem_eps, followneighpath, getbaryofcoord, getposofcoord
applysrc_toelem_eps calls auxfield_varpos, cxdirrk
getposofcoord calls tem_IdOfCoord, tem_PosOfId