update_BClists – Musubi
update_BClists Subroutine
42 statements
Source File
private subroutine update_BClists(scheme, minLevel, maxLevel, nBCs, LP, remove_solid)
Update the neighbor stencil positions for the Boundaries
Before, positions in the original treeIDs were assigned to the boundary element lists. Update these now with level-wise positions in the tem_levelDesc_type "total list". When no element is found, the value in nghElems is 0. This has to be treated in this routine. If an empty neighbor relation is encountered, the last valid neighbor is used for all other neighbors Assertion: Before this routine, we should have: scheme%globBC(iBnd)%nElems(iLevel) scheme%globBC(iBnd)%elemLvl(iLevel)%elem%val(iElem))
Arguments
Type Intent Optional Attributes Name
type(mus_scheme_type), intent(inout) :: scheme
scheme information including fluid, boundary and flow information
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
integer, intent(in) :: nBCs
integer, intent(in) :: LP(:)
Level Pointer
logical, intent(in) :: remove_solid
Calls
Called by
Call graph
update_bclists calls append, init, positionofval, mus_set_posinnghelems, remove_solid_in_bc, val
remove_solid_in_bc calls check_solid_in_bc, rearrange_bc_elems
check_solid_in_bc calls val
rearrange_bc_elems calls val
mus_construct calls update_bclists
mus_initialize calls mus_construct
mus_perform_dynloadbal calls mus_construct
mus_harvesting calls mus_construct
mus_solve calls mus_perform_dynloadbal
musubi calls mus_initialize, mus_solve