updateParticleOwner – Musubi
updateParticleOwner Subroutine
43 statements
Source File
public subroutine updateParticleOwner(this, scheme, geometry, myRank, procs, nProcs)
UpdateParticleOwner updates the "owner process" of each particle, which is the process responsible for performing operations (e.g. modifying velocity and position) on the particle and sending updates to other processes.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: this
Particle to update owner of
type(mus_scheme_type), intent(in) :: scheme
Scheme for access to level descriptor
type(mus_geom_type), intent(in) :: geometry
Geometry to determine TreeIDs of elements 'covered' by particle
integer, intent(in) :: myRank
This process's rank
integer, intent(in) :: procs(:)
Array of neighbor procs on which particle could possibly exist
integer, intent(in) :: nProcs
Number of procs in array procs
Calls
Called by
Call graph
updateparticleowner calls part_first, part_last, findpartitionoftreeid, tem_IdOfCoord, tem_PosOfId
findpartitionoftreeid calls part_first, part_last
initparticle_dps calls updateparticleowner
maptolattice_dps calls updateparticleowner
check_and_create_new_particles_dps calls initparticle_dps, create_particles_dps
createnewparticle_dps calls initparticle_dps
mapparticlestolattice_dps calls initparticle_dps, maptolattice_dps
mus_particles_mapping_dps calls initparticle_dps, maptolattice_dps
check_particles_dps calls check_and_create_new_particles_dps
create_particles_dps calls createnewparticle_dps
demsubcycles_dps calls mapparticlestolattice_dps
demsubcycles_dps_onewaycoupled calls mapparticlestolattice_dps
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled