updateExistsOnProc_DPS – Musubi
updateExistsOnProc_DPS Subroutine
57 statements
Source File
public subroutine updateExistsOnProc_DPS(this, interpolator, scheme, geometry, procs, nProcs, myRank)
updateExistsOnProc updates the boolean values of the array of neighbor procs that tell us whether the particle exists on that process or not.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: this
Particle to update owner of
type(mus_particle_interpolator_type), intent(in) :: interpolator
Interpolation data type. We don't interpolate stuff here but we use it to determine the directions we need to search for local elements in (only x, y for d2q9, x, y, z for d3q19)
type(mus_scheme_type), intent(in) :: scheme
Scheme for access to level descriptor
type(mus_geom_type), intent(in) :: geometry
Geometry to determine TreeIDs of elements 'covered' by particle
integer, intent(in) :: procs(:)
Array of neighbor procs on which particle could possibly exist
integer, intent(in) :: nProcs
Number of procs in array procs
integer, intent(in) :: myRank
This process's rank
Calls
Called by
Call graph
updateexistsonproc_dps calls neigh, part_first, part_last, findpartitionoftreeid, followneighpath, wrapperiodiccoord, tem_IdOfCoord, tem_PosOfId, total
findpartitionoftreeid calls part_first, part_last
initparticle_dps calls updateexistsonproc_dps
maptolattice_dps calls updateexistsonproc_dps
check_and_create_new_particles_dps calls initparticle_dps, create_particles_dps
createnewparticle_dps calls initparticle_dps
mapparticlestolattice_dps calls initparticle_dps, maptolattice_dps
mus_particles_mapping_dps calls initparticle_dps, maptolattice_dps
check_particles_dps calls check_and_create_new_particles_dps
create_particles_dps calls createnewparticle_dps
demsubcycles_dps calls mapparticlestolattice_dps
demsubcycles_dps_onewaycoupled calls mapparticlestolattice_dps
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled