updateNewFluidNodes – Musubi
updateNewFluidNodes Subroutine
34 statements
Source File
public subroutine updateNewFluidNodes(this, scheme, stencil)
updateNewFluidNodes restores the correct connectivity for new fluid elements which were particle elements in the previous time step.
Arguments
Type Intent Optional Attributes Name
type(mus_particle_MEM_type), intent(inout) :: this
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to level descriptor
type(tem_stencilHeader_type), intent(in) :: stencil
fluid stencil
Calls
Called by
Call graph
updatenewfluidnodes calls cxdirinv, nghelems, property, state_varpos, val
destroyparticle_mem calls updatenewfluidnodes
maptolattice calls updatenewfluidnodes
mus_particles_applyhydrodynamicforces_mem calls destroyparticle_mem
mus_particles_mapping_mem calls maptolattice