updateCoordOfOrigin_DPS – Musubi
updateCoordOfOrigin_DPS Subroutine
17 statements
Source File
public subroutine updateCoordOfOrigin_DPS(this, scheme, geometry, myRank)
updateCoordOfOrigin updates the integer coordinate of the origin of a particle
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: this
Particle to update coordOfOrigin of
type(mus_scheme_type), intent(in) :: scheme
Scheme to look up posOfOrigin
type(mus_geom_type), intent(in) :: geometry
Geometry information to determine new coord of origin
integer, intent(in) :: myRank
This process's rank
Calls
Called by
Call graph
updatecoordoforigin_dps calls getposofcoord, tem_CoordOfReal
getposofcoord calls tem_IdOfCoord, tem_PosOfId
initparticle_dps calls updatecoordoforigin_dps
maptolattice_dps calls updatecoordoforigin_dps
check_and_create_new_particles_dps calls initparticle_dps, create_particles_dps
createnewparticle_dps calls initparticle_dps
mapparticlestolattice_dps calls initparticle_dps, maptolattice_dps
mus_particles_mapping_dps calls initparticle_dps, maptolattice_dps
check_particles_dps calls check_and_create_new_particles_dps
create_particles_dps calls createnewparticle_dps
demsubcycles_dps calls mapparticlestolattice_dps
demsubcycles_dps_onewaycoupled calls mapparticlestolattice_dps
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled