updateSolidNodes – Musubi
updateSolidNodes Subroutine
32 statements
Source File
public subroutine updateSolidNodes(this, scheme, stencil)
updateSolidNodes modifies connectivity of scheme%pdf%neigh such that the particle cells do not participate in the streaming process. Specifically it: * runs over the elements in this%exclusionList * sets kernel neighbor list values to the particle elements themselves. * This way they are effectively excluded from the streaming process. * Sets the property bit prp_solid to 1 to indicate elements belonging to a particle
Arguments
Type Intent Optional Attributes Name
type(mus_particle_MEM_type), intent(inout) :: this
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to pdf%neigh
type(tem_stencilHeader_type), intent(in) :: stencil
fluid stencil
Calls
Called by
Call graph
updatesolidnodes calls property, state_varpos, val
initparticle_mem calls updatesolidnodes
maptolattice calls updatesolidnodes
check_and_create_new_particles_mem calls initparticle_mem, create_particles_mem
createnewparticle_mem calls initparticle_mem
mus_particles_applyhydrodynamicforces_mem calls initparticle_mem
mus_particles_mapping_mem calls maptolattice
check_particles_mem calls check_and_create_new_particles_mem
create_particles_mem calls createnewparticle_mem