updateParticleForces – Musubi
updateParticleForces Subroutine
40 statements
Source File
public subroutine updateParticleForces(particleGroup, scheme, geometry, params, boundaryData)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_group_type), intent(inout) :: particleGroup
Array of particles
type(mus_scheme_type), intent(inout) :: scheme
Scheme for access to leveldescriptor
type(mus_geom_type), intent(in) :: geometry
Geometry for access to tree
type(mus_param_type), intent(in) :: params
Params for access to dt, dx, etc.
type(mus_particle_boundarydata_type) :: boundaryData
Domain boundary information for particle-wall collisions
Calls
Called by
Call graph
updateparticleforces calls computehydroforces_dps, dem_computelocalcollisionforces_dps, dem_computeremotecollisionforces_dps, dem_computewallforces_dps, dem_exchangeforces_dps, dem_resetfnext_dps, exchangehydroforces_dps, interpolatefluidproperties_dps, resetforcebuffers, tem_startTimer, tem_stopTimer, val
dem_computelocalcollisionforces_dps calls checkandcollidedem, islocalcollision
dem_computeremotecollisionforces_dps calls checkandcollidedem, dem_isremotecollision, addcollisionforcetobuffer, tem_abort
dem_computewallforces_dps calls computewallforce_dps
dem_exchangeforces_dps calls tem_startTimer, tem_stopTimer, mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, sortposofval_particle_dps
exchangehydroforces_dps calls tem_startTimer, tem_stopTimer, mpi_get_count, mpi_irecv, mpi_isend, mpi_waitall, sortposofval_particle_dps, tem_abort
interpolatefluidproperties_dps calls mus_particles_dps_interpolatefluidproperties
checkandcollidedem calls checkandcollidedem_dps, checkandcollidedem_mem
dem_isremotecollision calls dem_isremotecollision_dps, dem_isremotecollision_mem
islocalcollision calls islocalcollision_dps, islocalcollision_mem
addcollisionforcetobuffer calls tem_abort
computewallforce_dps calls computewallforce_1d
mus_particles_dps_interpolatefluidproperties calls tem_abort
demsubcycles_dps calls updateparticleforces
demsubcycles_dps_onewaycoupled calls updateparticleforces
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled