wrapPeriodicPos – Musubi
wrapPeriodicPos Subroutine
39 statements
Source File
public subroutine wrapPeriodicPos(pos, boundaryData)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout) :: pos(3)
type(mus_particle_boundarydata_type) :: boundaryData
Called by
Call graph
demsubcycles_dps calls wrapperiodicpos
demsubcycles_dps_onewaycoupled calls wrapperiodicpos
demsubcycles_mem calls wrapperiodicpos
mus_particles_move calls demsubcycles_mem
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled