allocateProcessMasks – Musubi
allocateProcessMasks Interface
3 statements
Source File
public interface allocateProcessMasks
Calls
Called by
Module Procedures
private subroutine allocateProcessMasks_DPS(particle, nProcs)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: particle
Particle to initialize
integer :: nProcs
Number of processes to communicate particle data with
Call graph
allocateprocessmasks calls allocateprocessmasks_dps
check_and_create_new_particles_dps calls allocateprocessmasks, create_particles_dps
check_and_create_new_particles_mem calls allocateprocessmasks, create_particles_mem
createnewparticle_dps calls allocateprocessmasks
createnewparticle_mem calls allocateprocessmasks
mapparticlestolattice_dps calls allocateprocessmasks
mus_particles_applyhydrodynamicforces_mem calls allocateprocessmasks
mus_particles_mapping_dps calls allocateprocessmasks
check_particles_dps calls check_and_create_new_particles_dps
check_particles_mem calls check_and_create_new_particles_mem
create_particles_dps calls createnewparticle_dps
create_particles_mem calls createnewparticle_mem
demsubcycles_dps calls mapparticlestolattice_dps
demsubcycles_dps_onewaycoupled calls mapparticlestolattice_dps
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled