calc_therm_factor_loc – Musubi
calc_therm_factor_loc Interface
10 statements
Source File
interface
This routine calculates thermodynamic factor for given mole_frac of all species
Called by
private subroutine calc_therm_factor_loc(nSpc, Temp, Press, Mole_frac, Therm_factors) bind(c, name='calc_therm_factor_C')
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in), value :: nSpc
real(kind=c_double), intent(in), value :: Temp
real(kind=c_double), intent(in), value :: Press
real(kind=c_double), intent(in), dimension(*) :: Mole_frac
real(kind=c_double), intent(out), dimension(*) :: Therm_factors
Call graph
mus_calc_thermfactor_single calls calc_therm_factor_loc
mus_calc_thermfactor calls mus_calc_thermfactor_single
applysrc_electricmsliquid_1stord_wtdf calls mus_calc_thermfactor
applysrc_electricmsliquid_2ndord_wtdf calls mus_calc_thermfactor
applysrc_forcemsliquid_1stord_wtdf calls mus_calc_thermfactor
applysrc_forcemsliquid_2ndord_wtdf calls mus_calc_thermfactor
bgk_advrel_d3q19f3_msliquid_wtdf calls mus_calc_thermfactor
bgk_advrel_msliquid_generic_wtdf calls mus_calc_thermfactor
deriveauxmsliquid_fromstate_wtdf calls mus_calc_thermfactor
deriveequilvelwtdf_msliquid calls mus_calc_thermfactor
deriveequilwtdf_msliquid calls mus_calc_thermfactor
mrt_advrel_d3q19f3_msliquid_wtdf calls mus_calc_thermfactor
mrt_advrel_msliquid_generic_wtdf calls mus_calc_thermfactor
mus_addelectrictoauxfield_msl_wtdf calls mus_calc_thermfactor
mus_addforcetoauxfield_msl_wtdf calls mus_calc_thermfactor
mus_init_msliquid calls mus_calc_thermfactor
spc_molefrac_wtdf calls mus_calc_thermfactor
mus_init_byic calls mus_init_msliquid