calc_ms_diff_matrix_from_moledens – Musubi
calc_ms_diff_matrix_from_moledens Interface
10 statements
Source File
interface
This routine calculates Maxwell-Stefan diffusivity coeffcient Matrix for given mole_frac of all species
Called by
private subroutine calc_ms_diff_matrix_from_moledens(nSpc, Temp, Press, Mole_dens, D_ij_out) bind(c, name='calc_ms_diff_matrix_from_moledens_C')
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in), value :: nSpc
real(kind=c_double), intent(in), value :: Temp
real(kind=c_double), intent(in), value :: Press
real(kind=c_double), intent(in), dimension(*) :: Mole_dens
real(kind=c_double), intent(out), dimension(*) :: D_ij_out
Call graph
mus_calc_ms_diffmatrix_single calls calc_ms_diff_matrix_from_moledens
mus_calc_ms_diffmatrix calls mus_calc_ms_diffmatrix_single
bgk_advrel_d3q19f3_msliquid_wtdf calls mus_calc_ms_diffmatrix
bgk_advrel_msliquid_generic_wtdf calls mus_calc_ms_diffmatrix
deriveauxmsliquid_fromstate_wtdf calls mus_calc_ms_diffmatrix
deriveequilvelwtdf_msliquid calls mus_calc_ms_diffmatrix
deriveequilwtdf_msliquid calls mus_calc_ms_diffmatrix
mrt_advrel_d3q19f3_msliquid_wtdf calls mus_calc_ms_diffmatrix
mrt_advrel_msliquid_generic_wtdf calls mus_calc_ms_diffmatrix
mus_init_msliquid calls mus_calc_ms_diffmatrix
spc_molefrac_wtdf calls mus_calc_ms_diffmatrix
mus_init_byic calls mus_init_msliquid