fill_prism – Musubi
fill_prism Interface
3 statements
Source File
public interface fill_prism
Calls
Called by
Module Procedures
public subroutine fill_prism_by_distance(lx, ly, lz, d, positions)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: lx
Vector spanning the prism in x-direction
real(kind=rk), intent(in) :: ly
Vector spanning the prism in y-direction
real(kind=rk), intent(in) :: lz
Vector spanning the prism in z-direction
real(kind=rk), intent(in) :: d
Distance between particles
type(grw_real2darray_type), intent(inout) :: positions
public subroutine fill_prism_by_number(lx, ly, lz, Nx, Ny, Nz, positions)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: lx
Vector spanning the prism in x-direction
real(kind=rk), intent(in) :: ly
Vector spanning the prism in y-direction
real(kind=rk), intent(in) :: lz
Vector spanning the prism in z-direction
integer, intent(in) :: Nx
Number of particles in x-direction
integer, intent(in) :: Ny
Number of particles in y-direction
integer, intent(in) :: Nz
Number of particles in z-direction
type(grw_real2darray_type), intent(inout) :: positions
Call graph
fill_prism calls fill_prism_by_distance, fill_prism_by_number
fill_prism_by_distance calls append, init
fill_prism_by_number calls append, init
init_particle_creator_from_blob_prism calls fill_prism
mus_load_particles calls init_particle_creator_from_blob_prism
mus_initialize calls mus_load_particles
musubi calls mus_initialize