get_intpFromCoarserTime – Musubi
get_intpFromCoarserTime Interface
4 statements
Source File
public interface get_intpFromCoarserTime
Calls
Called by
Module Procedures
private function get_intpFromCoarserTime_total() result(time)
Arguments
None
Return Value real(kind=rk)
private function get_intpFromCoarserTime_atLevel(level) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Call graph
get_intpfromcoarsertime calls get_intpfromcoarsertime_atlevel, get_intpfromcoarsertime_total
get_intpfromcoarsertime_atlevel calls tem_getTimerVal
get_intpfromcoarsertime_total calls get_intpfromcoarsertime
get_intpfromcoarserratio_atlevel calls get_intpfromcoarsertime
get_intpfromcoarserratio_total calls get_intpfromcoarsertime
get_intptime calls get_intpfromcoarsertime
mus_getweights calls get_intpfromcoarsertime
get_intpfromcoarserratio calls get_intpfromcoarserratio_atlevel, get_intpfromcoarserratio_total
get_intpratio calls get_intptime
mus_balance calls mus_getweights
mus_finalize calls mus_getweights
dump_timing calls get_intpratio
mus_perform_dynloadbal calls mus_balance
musubi calls mus_finalize
mus_perf_measure calls dump_timing
mus_solve calls mus_perform_dynloadbal