get_bcBufferRatio – Musubi
get_bcBufferRatio Interface
4 statements
Source File
public interface get_bcBufferRatio
Calls
Called by
Module Procedures
private function get_bcBufferRatio_total() result(ratio)
Arguments
None
Return Value real(kind=rk)
private function get_bcBufferRatio_atLevel(level) result(ratio)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Call graph
get_bcbufferratio calls get_bcbufferratio_atlevel, get_bcbufferratio_total
get_bcbufferratio_atlevel calls get_bcbuffertime, get_mainlooptime
get_bcbufferratio_total calls get_bcbuffertime, get_mainlooptime
get_bcbuffertime calls get_bcbuffertime_atlevel, get_bcbuffertime_total
get_mainlooptime calls tem_getTimerVal
get_bcbuffertime_atlevel calls tem_getTimerVal
get_bcbuffertime_total calls get_bcbuffertime
dump_timing calls get_bcbufferratio
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure
musubi calls mus_finalize, mus_solve