get_intpFromFinerRatio – Musubi
get_intpFromFinerRatio Interface
4 statements
Source File
public interface get_intpFromFinerRatio
Calls
Module Procedures
private function get_intpFromFinerRatio_total() result(ratio)
Arguments
None
Return Value real(kind=rk)
private function get_intpFromFinerRatio_atLevel(level) result(ratio)
Arguments
Type Intent Optional Attributes Name
integer :: level
Return Value real(kind=rk)
Call graph
get_intpfromfinerratio calls get_intpfromfinerratio_atlevel, get_intpfromfinerratio_total
get_intpfromfinerratio_atlevel calls get_intpfromfinertime, get_mainlooptime
get_intpfromfinerratio_total calls get_intpfromfinertime, get_mainlooptime
get_intpfromfinertime calls get_intpfromfinertime_atlevel, get_intpfromfinertime_total
get_mainlooptime calls tem_getTimerVal
get_intpfromfinertime_atlevel calls tem_getTimerVal
get_intpfromfinertime_total calls tem_getTimerVal