get_intpFromFinerTime – Musubi
get_intpFromFinerTime Interface
4 statements
Source File
public interface get_intpFromFinerTime
Calls
Called by
Module Procedures
private function get_intpFromFinerTime_total() result(time)
Arguments
None
Return Value real(kind=rk)
private function get_intpFromFinerTime_atLevel(level) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Call graph
get_intpfromfinertime calls get_intpfromfinertime_atlevel, get_intpfromfinertime_total
get_intpfromfinertime_atlevel calls tem_getTimerVal
get_intpfromfinertime_total calls tem_getTimerVal
get_intpfromfinerratio_atlevel calls get_intpfromfinertime
get_intpfromfinerratio_total calls get_intpfromfinertime
get_intptime calls get_intpfromfinertime
mus_getweights calls get_intpfromfinertime
get_intpfromfinerratio calls get_intpfromfinerratio_atlevel, get_intpfromfinerratio_total
get_intpratio calls get_intptime
mus_balance calls mus_getweights
mus_finalize calls mus_getweights
dump_timing calls get_intpratio
mus_perform_dynloadbal calls mus_balance
musubi calls mus_finalize
mus_perf_measure calls dump_timing
mus_solve calls mus_perform_dynloadbal