get_bcBufferTime – Musubi
get_bcBufferTime Interface
4 statements
Source File
public interface get_bcBufferTime
Calls
Called by
Module Procedures
private function get_bcBufferTime_total() result(time)
Arguments
None
Return Value real(kind=rk)
private function get_bcBufferTime_atLevel(level) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Call graph
get_bcbuffertime calls get_bcbuffertime_atlevel, get_bcbuffertime_total
get_bcbuffertime_atlevel calls tem_getTimerVal
get_bcbuffertime_total calls get_bcbuffertime
dump_bc_timing calls get_bcbuffertime
get_bcbufferratio_atlevel calls get_bcbuffertime
get_bcbufferratio_total calls get_bcbuffertime
mus_getweights calls get_bcbuffertime
get_bcbufferratio calls get_bcbufferratio_atlevel, get_bcbufferratio_total
mus_balance calls mus_getweights
mus_finalize calls mus_getweights
dump_timing calls get_bcbufferratio
mus_perform_dynloadbal calls mus_balance
musubi calls mus_finalize
mus_perf_measure calls dump_timing
mus_solve calls mus_perform_dynloadbal