get_intpFromCoarserRatio – Musubi
get_intpFromCoarserRatio Interface
4 statements
Source File
public interface get_intpFromCoarserRatio
Calls
Module Procedures
private function get_intpFromCoarserRatio_total() result(ratio)
Arguments
None
Return Value real(kind=rk)
private function get_intpFromCoarserRatio_atLevel(level) result(ratio)
Arguments
Type Intent Optional Attributes Name
integer :: level
Return Value real(kind=rk)
Call graph
get_intpfromcoarserratio calls get_intpfromcoarserratio_atlevel, get_intpfromcoarserratio_total
get_intpfromcoarserratio_atlevel calls get_intpfromcoarsertime, get_mainlooptime
get_intpfromcoarserratio_total calls get_intpfromcoarsertime, get_mainlooptime
get_intpfromcoarsertime calls get_intpfromcoarsertime_atlevel, get_intpfromcoarsertime_total
get_mainlooptime calls tem_getTimerVal
get_intpfromcoarsertime_atlevel calls tem_getTimerVal
get_intpfromcoarsertime_total calls get_intpfromcoarsertime