get_auxTime – Musubi
get_auxTime Interface
4 statements
Source File
public interface get_auxTime
Calls
Called by
Module Procedures
private function get_auxTime_total() result(time)
Arguments
None
Return Value real(kind=rk)
private function get_auxTime_atLevel(level) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Call graph
get_auxtime calls get_auxtime_atlevel, get_auxtime_total
get_auxtime_atlevel calls tem_getTimerVal
get_auxtime_total calls get_auxtime
dump_timing calls get_auxtime
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure
musubi calls mus_finalize, mus_solve