get_computeRatio – Musubi
get_computeRatio Interface
4 statements
Source File
public interface get_computeRatio
Calls
Called by
Module Procedures
private function get_computeRatio_total() result(ratio)
Arguments
None
Return Value real(kind=rk)
private function get_computeRatio_atLevel(level) result(ratio)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Call graph
get_computeratio calls get_computeratio_atlevel, get_computeratio_total
get_computeratio_atlevel calls get_computetime, get_mainlooptime
get_computeratio_total calls get_computetime, get_mainlooptime
get_computetime calls get_computetime_atlevel, get_computetime_total
get_mainlooptime calls tem_getTimerVal
get_computetime_atlevel calls tem_getTimerVal
get_computetime_total calls get_computetime
dump_timing calls get_computeratio
mus_perf_measure calls dump_timing
mus_finalize calls mus_perf_measure
mus_solve calls mus_perf_measure
musubi calls mus_finalize, mus_solve