get_boundaryTime – Musubi
get_boundaryTime Interface
4 statements
Source File
public interface get_boundaryTime
Calls
Called by
Module Procedures
private function get_boundaryTime_total() result(time)
Arguments
None
Return Value real(kind=rk)
private function get_boundaryTime_byID(bcID) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: bcID
Return Value real(kind=rk)
Call graph
get_boundarytime calls get_boundarytime_byid, get_boundarytime_total
get_boundarytime_byid calls tem_getTimerVal
get_boundarytime_total calls get_boundarytime
dump_bc_timing calls get_boundarytime
get_boundaryratio calls get_boundarytime
mus_bc_timing calls get_boundarytime
mus_getweights calls get_boundarytime
dump_timing calls get_boundaryratio
mus_balance calls mus_getweights
mus_finalize calls mus_bc_timing, mus_getweights, mus_perf_measure
mus_perf_measure calls dump_timing
mus_perform_dynloadbal calls mus_balance
musubi calls mus_finalize
mus_solve calls mus_perf_measure, mus_perform_dynloadbal