get_computeTime – Musubi
get_computeTime Interface
4 statements
Source File
public interface get_computeTime
Calls
Called by
Module Procedures
private function get_computeTime_total() result(time)
Arguments
None
Return Value real(kind=rk)
private function get_computeTime_atLevel(level) result(time)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
Return Value real(kind=rk)
Call graph
get_computetime calls get_computetime_atlevel, get_computetime_total
get_computetime_atlevel calls tem_getTimerVal
get_computetime_total calls get_computetime
dump_bc_timing calls get_computetime
get_computeratio_atlevel calls get_computetime
get_computeratio_total calls get_computetime
mus_getweights calls get_computetime
mus_perf_measure calls get_computetime, dump_timing
get_computeratio calls get_computeratio_atlevel, get_computeratio_total
mus_balance calls mus_getweights
mus_finalize calls mus_getweights, mus_perf_measure
mus_solve calls mus_perf_measure, mus_perform_dynloadbal
dump_timing calls get_computeratio
mus_perform_dynloadbal calls mus_balance
musubi calls mus_finalize, mus_solve