getDensity – Musubi
getDensity Interface
4 statements
Source File
public interface getDensity
Calls
Called by
Module Procedures
private pure function getDensity_forElemFromState(state, elem, stencil, varPos, nScalars) result(res)
Calculate the density of a given element number with the given state vector (sum up all values)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:)
integer, intent(in) :: elem
type(tem_stencilHeader_type), intent(in) :: stencil
integer, intent(in) :: varPos(:)
integer, intent(in) :: nScalars
Return Value real(kind=rk)
private pure function getDensity_forPdfSubset(subset, stencil, varPos) result(res)
Calculate the density of a given subset of pdfs vector (sum up all values)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: subset(:)
type(tem_stencilHeader_type), intent(in) :: stencil
integer, intent(in) :: varPos(:)
Return Value real(kind=rk)
Call graph
getdensity calls getdensity_forelemfromstate, getdensity_forpdfsubset
getequilibrium_forelemfromstate calls getdensity
mus_applyforce_x calls getdensity
getequilibrium calls getequilibrium_forelemfromstate
mus_inamuro_ibm calls mus_applyforce_x
do_fast_singlelevel calls mus_inamuro_ibm
mus_turbvisc_smagorinsky_fromprecolpdf_2d calls getequilibrium
mus_turbvisc_smagorinsky_fromprecolpdf_3d calls getequilibrium