getEquilibrium – Musubi
getEquilibrium Interface
5 statements
Source File
public interface getEquilibrium
Calls
Called by
Module Procedures
private pure function getEquilibrium_forElemfromState(state, elem, layout, varPos, nScalars, neigh) result(equil)
Calculate the equilibrium distribution function in all directions
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:)
integer, intent(in) :: elem
type(mus_scheme_layout_type), intent(in) :: layout
integer, intent(in) :: varPos(:)
integer, intent(in) :: nScalars
integer, intent(in) :: neigh(:)
Return Value real(kind=rk), (layout%fStencil%QQ)
public pure function getEqByDensVel(dens, vel, layout) result(equil)
Calculate the equilibrium distribution function in all directions
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: dens
real(kind=rk), intent(in) :: vel(3)
type(mus_scheme_layout_type), intent(in) :: layout
Return Value real(kind=rk), (layout%fStencil%QQ)
private pure function getEquilibrium_forPdfSubset(subset, layout, varPos) result(equil)
Calculate the equilibrium distribution function in all directions
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: subset(:)
type(mus_scheme_layout_type), intent(in) :: layout
integer, intent(in) :: varPos(:)
Return Value real(kind=rk), (layout%fStencil%QQ)
Call graph
getequilibrium calls geteqbydensvel, getequilibrium_forelemfromstate, getequilibrium_forpdfsubset
geteqbydensvel calls cxdirrk
getequilibrium_forelemfromstate calls cxdirrk, getdensity, getvelocity
getequilibrium_forpdfsubset calls cxdirrk, getdensity_forpdfsubset, getvelocity_forpdfsubset
getdensity calls getdensity_forpdfsubset, getdensity_forelemfromstate
getvelocity calls getvelocity_forpdfsubset, getvelocity_forelemfromstate_noforce
mus_turbvisc_smagorinsky_fromprecolpdf_2d calls getequilibrium
mus_turbvisc_smagorinsky_fromprecolpdf_3d calls getequilibrium