getFieldVariable – Musubi
getFieldVariable Interface
4 statements
Source File
public interface getFieldVariable
Calls
Module Procedures
private function getFieldVariable_scalar(conf, varLabel, varName, fieldVar, fieldProp) result(val)
Get the field variable name for given field type from a given solver specific character handle.
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
handle of the solver specific character
character(len=*), intent(in) :: varLabel
complete variable label (prefix + pure variable name)
character(len=*), intent(in) :: varName
pure variable name (e.g. density)
character(len=*), intent(in) :: fieldVar
required name of the field variable
character(len=*), intent(in) :: fieldProp
Which field type does the field variable belong to. Example: 'fluid'/'species'
Return Value real(kind=rk)
val to be returned
private function getFieldVariable_array(conf, varLabel, varName, fieldVar, fieldProp, nVals) result(val)
Get the field variable name for given field type from a given solver specific character handle.
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
handle of the solver specific character
character(len=*), intent(in) :: varLabel
complete variable label (prefix + pure variable name)
character(len=*), intent(in) :: varName
pure variable name (e.g. density)
character(len=*), intent(in) :: fieldVar
required name of the field variable
character(len=*), intent(in) :: fieldProp
Which field type does the field variable belong to. Example: 'fluid'/'species'
integer, intent(in) :: nVals
number of entries in the array to read out
Return Value real(kind=rk), (nVals)
val to be returned
Call graph
getfieldvariable calls getfieldvariable_array, getfieldvariable_scalar
getfieldvariable_array calls aot_get_val, aot_table_close, aot_table_open
getfieldvariable_scalar calls aot_get_val, aot_table_close, aot_table_open