grabValueAtCoord – Musubi
grabValueAtCoord Interface
4 statements
Source File
public interface grabValueAtCoord
Interface for routine to get the value of the velocity and pressure field at a specified integer coordinate
Calls
Called by
Module Procedures
public subroutine grabValueAtCoord_twowaycoupled(coord, scheme, vel_pos, dens_pos, vol_frac_pos, rho, u, eps_f, err)
Get the value of the density and velocity at a certain integer coordinate
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: coord(4)
type(mus_scheme_type), intent(inout) :: scheme
integer, intent(in) :: vel_pos(3)
integer, intent(in) :: dens_pos
integer, intent(in) :: vol_frac_pos
real(kind=rk), intent(out) :: rho
real(kind=rk), intent(out) :: u(3)
real(kind=rk), intent(out) :: eps_f
logical, intent(out) :: err
Error code: set to TRUE if we could not find ldPos of coord we are trying to grab value at (for example because it is outside domain and not a halo.
public subroutine grabValueAtCoord_onewaycoupled(coord, scheme, vel_pos, dens_pos, rho, u, err)
Get the value of the density and velocity at a certain integer coordinate
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: coord(4)
type(mus_scheme_type), intent(inout) :: scheme
integer, intent(in) :: vel_pos(3)
integer, intent(in) :: dens_pos
real(kind=rk), intent(out) :: rho
real(kind=rk), intent(out) :: u(3)
logical, intent(out) :: err
Error code: set to TRUE if we could not find ldPos of coord we are trying to grab value at (for example because it is outside domain and not a halo.
Call graph
grabvalueatcoord calls grabvalueatcoord_onewaycoupled, grabvalueatcoord_twowaycoupled
grabvalueatcoord_onewaycoupled calls tem_IdOfCoord, tem_PosOfId
grabvalueatcoord_twowaycoupled calls tem_IdOfCoord, tem_PosOfId
calcvelocityandpressuregradient_onewaycoupled_old calls grabvalueatcoord
interpolatefluidprops_onewaycoupled_old calls grabvalueatcoord
mus_particles_dps_interpolatefluidproperties_onewaycoupled calls calcvelocityandpressuregradient_onewaycoupled_old, interpolatefluidprops_onewaycoupled_old
mus_particles_applyhydrodynamicforces_dps_onewaycoupled calls mus_particles_dps_interpolatefluidproperties_onewaycoupled