init_particle_blob_prob – Musubi
init_particle_blob_prob Interface
4 statements
Source File
public interface init_particle_blob_prob
Calls
Called by
Module Procedures
public subroutine init_particle_blob_prob_circle(blob, d, R, mu, sigma, Nchosen)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_blob_prob_type), intent(inout) :: blob
real(kind=rk), intent(in) :: d
Distance between particle positions. This should be chosen larger than one particle diameter to prevent overlap.
real(kind=rk) :: R
Radius within which all positions must be located
real(kind=rk) :: mu(2)
Mean value of the probability distributions in x and y directions (mu_x, mu_y)
real(kind=rk) :: sigma(2)
Standard deviation of the probability distributions in x and y directions (sig_x, sig_y)
integer, intent(in) :: Nchosen
Number of particles we plan to choose. This determines the size to which the chosen_positions array will be allocated
public subroutine init_particle_blob_prob_square(blob, d, xlim, ylim, mu, sigma, Nchosen)
Arguments
Type Intent Optional Attributes Name
type(mus_particle_blob_prob_type), intent(inout) :: blob
real(kind=rk), intent(in) :: d
Distance between particle positions. This should be chosen larger than one particle diameter to prevent overlap.
real(kind=rk) :: xlim(2)
Range of x-positions particles can have [xmin, xmax]
real(kind=rk) :: ylim(2)
Range of y-positions particles can have [ymin, ymax]
real(kind=rk) :: mu(2)
Mean value of the probability distributions in x and y directions (mu_x, mu_y)
real(kind=rk) :: sigma(2)
Standard deviation of the probability distributions in x and y directions (sig_x, sig_y)
integer, intent(in) :: Nchosen
Number of particles we plan to choose. This determines the size to which the chosen_positions array will be allocated
Call graph
init_particle_blob_prob calls init_particle_blob_prob_circle, init_particle_blob_prob_square
init_particle_blob_prob_circle calls append, init, fill_bins, normalize_probabilities, normcdf
init_particle_blob_prob_square calls append, init, fill_bins, normalize_probabilities, normcdf
fill_bins calls append, val
normalize_probabilities calls val
normcdf calls cumnor
cumnor calls r8_swap
fill_blob_positions_gauss calls init_particle_blob_prob
fill_blob_positions_gauss_prism calls init_particle_blob_prob
init_particle_creator_from_blob calls fill_blob_positions_gauss
init_particle_creator_from_blob_prism calls fill_blob_positions_gauss_prism
mus_load_particles calls init_particle_creator_from_blob, init_particle_creator_from_blob_prism
mus_initialize calls mus_load_particles