mus_calc_MS_DiffMatrix – Musubi
mus_calc_MS_DiffMatrix Interface
3 statements
Source File
public interface mus_calc_MS_DiffMatrix
Calls
Called by
Module Procedures
private subroutine mus_calc_MS_DiffMatrix_single(nFields, temp, press, mole_dens, D_ij_out)
Dummy routine which sets diffusivity coeff matrix to diagonal matrix
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nFields
number of fields in mixture
real(kind=rk), intent(in) :: temp
mixture temperature
real(kind=rk), intent(in) :: press
mixture pressure
real(kind=rk), intent(in) :: mole_dens(nFields)
mole density of all species of single element
real(kind=rk), intent(out) :: D_ij_out(nFields,nFields)
thermodynamic factor matrix
Call graph
mus_calc_ms_diffmatrix calls mus_calc_ms_diffmatrix_single
bgk_advrel_d3q19f3_msliquid_wtdf calls mus_calc_ms_diffmatrix
bgk_advrel_msliquid_generic_wtdf calls mus_calc_ms_diffmatrix
deriveauxmsliquid_fromstate_wtdf calls mus_calc_ms_diffmatrix
deriveequilvelwtdf_msliquid calls mus_calc_ms_diffmatrix
deriveequilwtdf_msliquid calls mus_calc_ms_diffmatrix
mrt_advrel_d3q19f3_msliquid_wtdf calls mus_calc_ms_diffmatrix
mrt_advrel_msliquid_generic_wtdf calls mus_calc_ms_diffmatrix
mus_init_msliquid calls mus_calc_ms_diffmatrix
spc_molefrac_wtdf calls mus_calc_ms_diffmatrix
mus_init_byic calls mus_init_msliquid
mus_init_flow calls mus_init_byic
mus_initialize calls mus_init_flow