mus_fields_out – Musubi
mus_fields_out Interface
4 statements
Source File
public interface mus_fields_out
Interface for dumping a single field or a set of fields in a file in lua format.
Calls
Called by
Module Procedures
private subroutine mus_fields_out_vec(me, conf, schemeHeader)
write array of fields into a lua file
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(in) :: me(:)
array of field type
type(aot_out_type), intent(inout) :: conf
aotus out type
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
private subroutine mus_field_out_scal(me, conf, schemeHeader, level)
write single field into a lua file
Arguments
Type Intent Optional Attributes Name
type(mus_field_type), intent(in) :: me
single field type
type(aot_out_type), intent(inout) :: conf
aotus out type
type(mus_scheme_header_type), intent(in) :: schemeHeader
identifier of the scheme
integer, intent(in), optional :: level
To dump field with or without key
Call graph
mus_fields_out calls mus_field_out_scal, mus_fields_out_vec
mus_field_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val, mus_field_prop_out
mus_fields_out_vec calls mus_field_out_scal, aot_out_close_table, aot_out_open_table, aot_out_val
mus_field_prop_out calls mus_fluid_save2lua, mus_species_out
mus_fluid_save2lua calls aot_out_close_table, aot_out_open_table, aot_out_val, const, mus_nnwtn_save2lua
mus_species_out calls aot_out_close_table, aot_out_open_table, aot_out_val
mus_scheme_out calls mus_fields_out
mus_writesolverspecinfo calls mus_scheme_out