updateVelocityVerlet – Musubi
updateVelocityVerlet Interface
4 statements
Source File
public interface updateVelocityVerlet
Calls
Called by
Module Procedures
public subroutine updateVelocityVerlet_MEM(this, dt)
Update particle velocity using Verlet integration
Arguments
Type Intent Optional Attributes Name
type(mus_particle_MEM_type), intent(inout) :: this
real(kind=rk), intent(in) :: dt
public subroutine updateVelocityVerlet_DPS(this, dt)
Update particle velocity using Verlet integration
Arguments
Type Intent Optional Attributes Name
type(mus_particle_DPS_type), intent(inout) :: this
real(kind=rk), intent(in) :: dt
Call graph
updatevelocityverlet calls updatevelocityverlet_dps, updatevelocityverlet_mem
updatevelocityverlet_dps calls tem_abort
demsubcycles_dps calls updatevelocityverlet
demsubcycles_dps_onewaycoupled calls updatevelocityverlet
demsubcycles_mem calls updatevelocityverlet
mus_particles_move calls demsubcycles_mem
mus_particles_move_dps calls demsubcycles_dps
mus_particles_move_dps_onewaycoupled calls demsubcycles_dps_onewaycoupled