mus_harvesting – Musubi
mus_harvesting Program
96 statements
Source File
Uses
tem_tracking_module
hvs_output_module
mus_bndForce_module
mpi
mus_param_module
tem_logging_module
aotus_module
iso_c_binding
mus_hvs_config_module
mus_timer_module
mus_hvs_aux_module
mus_scheme_type_module
env_module
mus_geom_module
tem_general_module
hvs_aux_module
mus_hvs_construction_module
mus_scheme_module
mus_flow_module
tem_aux_module
mus_restart_module
mus_varSys_module
tem_timeControl_module
mus_construction_module
Musubi Harvesting Tool Visualization of restart file or tracking harvester formar, generated by musubi (c) 2015 University of Siegen
For a documentation, run ./waf gendoxy and find the documentation at ./Documentation/html/index.html If restart read variable is not pdf then set interpolation method to none to deactivate interpolation for derived variable
Calls
Variables
Type Attributes Name Initial
type(mus_scheme_type), target :: scheme
type(mus_geom_type), target :: geometry
type(mus_param_type), target :: params
type(mus_varSys_solverData_type), target :: solverData
type(mus_hvs_config_type) :: config
type(hvs_output_file_type) :: out_file
integer :: ierr
integer :: iTrack
integer :: iConfig
integer :: nVars
integer :: minLevel
integer :: maxLevel
character(len=pathLen) :: basename
Call graph
mus_harvesting calls config, fillhelperelementscoarsetofine, fillhelperelementsfinetocoarse, hvs_banner, hvs_output_close, hvs_output_finalize, hvs_output_init, hvs_output_open, hvs_output_write, instance, mpi_barrier, mus_calcbndforce, mus_construct, mus_initauxfield, mus_hvs_config_load, mus_hvs_construct, mus_hvs_init_aux, mus_init_leveltimer, mus_init_maintimer, mus_init_scheme, mus_readrestart, tem_finalize, tem_start, tem_tracking_finalize, val