musubi – Musubi
musubi Program
35 statements
Source File
Uses
mus_program_module
mpi
tem_adaptation_config_module
mus_config_module
tem_general_module
mus_timer_module
mus_scheme_type_module
mus_param_module
mus_aux_module
mus_geom_module
mus_varSys_module
mus_control_module
M U S U B I The lattice Boltzmann solver within the APES suite (c) 2012 German Research School for Simulation Sciences GmbH (c) 2013 University of Siegen.
For a documentation, run ./waf gendoxy and find the documentation at ./Documentation/html/index.html
Calls
Variables
Type Attributes Name Initial
type(mus_scheme_type), target :: scheme
scheme types
type(mus_geom_type), target :: geometry
type(mus_param_type), target :: params
type(mus_varSys_solverData_type), target :: solverData
type(mus_control_type) :: control
type(tem_adapt_type) :: adapt
integer :: ierr
Call graph
musubi calls mpi_barrier, mus_finalize, mus_initialize, mus_solve, mus_banner, mus_init_bctimer, mus_init_leveltimer, mus_init_maintimer, mus_load_config, tem_finalize, tem_start
mus_banner calls mus_print_ppinfo, tem_print_execInfo, utc_date_string
mus_init_bctimer calls tem_addTimer
mus_init_leveltimer calls tem_addTimer
mus_init_maintimer calls tem_addTimer, tem_getNTimers
mus_load_config calls conf, dump_linear_partition, mus_init_latticeunit, mus_load_geom, mus_load_param, mus_load_physics, mus_load_scheme, mus_open_config, tem_debug_load_main, tem_horizontalSpacer, tem_load_adapt, tem_load_general, tem_logging_load_primary, tem_startTimer, tem_stopTimer