name: ForDoc

on:
  push:
    branches:
      - 'main'

jobs:
  documentation:
    permissions:
      contents: write
    uses: apes-suite/reus/.github/workflows/ford.yml@v1.3.4
    with:
      name: Musubi
      docdir: 'build/ford/mus'

